### ISSUE TITLE
New pod initialised on helm upgrade even without any changes

### ISSUE THREAD

**Issue by Fuuzetsu** [grafana/helm-charts#10]
Any time I run `helm upgrade` even without touching the config, the grafana pod is torn down and new one is started in its place. If I run `helm upgrade` 5 times back-to-back, it goes through 5 pods. This seems strange.

I'm not sure what kind of information would help, please let me know.

I have a very basic setup. In Chart.yaml `dependencies` I have

```yaml
  - name: grafana
    version: 5.6.2
    repository: https://grafana.github.io/helm-charts
  - name: prometheus
    version: 11.15.0
    repository: https://prometheus-community.github.io/helm-charts
```

and in values.yaml I have
```
grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: …
        access: proxy
        isDefault: true
  dashboardProviders:
   dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: default
       orgId: 1
       folder: ""
       type: file
       disableDeletion: false
       editable: true
       options:
         path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
     kubernetes-cluster-monitoring-prometheus:
       gnetId: 315
       datasource: Prometheus
```
