### ISSUE TITLE
[loki-distributed] storage_config index_gateway_client setting put in incorrect spot

### ISSUE THREAD

**Issue by js8080** [grafana/helm-charts#1003]
## Issue Summary
The [loki-distributed](https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed) chart has a bug where it places the storage_config index_gateway_client settings in the wrong place.

Here is the resulting `storage_config` from my Helm install -- notice the `index_gateway_client` setting is not under `boltdb_shipper` like it is supposed to be:
```yaml
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 168h
        shared_store: filesystem
      filesystem:
        directory: /var/loki/chunks
      index_gateway_client:
        server_address: dns:///obs-loki-index-gateway:9095
```

This is what it _should_ look like:
```yaml
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 168h
        shared_store: filesystem
        index_gateway_client:
          server_address: dns:///obs-loki-index-gateway:9095
      filesystem:
        directory: /var/loki/chunks
```

## Cause
In the `values.yaml`, the following templated loki/config section we have this templating:
```yaml
    storage_config:
    {{- toYaml .Values.loki.storageConfig | nindent 2}}
    {{- if .Values.indexGateway.enabled}}
      index_gateway_client:
        server_address: dns:///{{ include "loki.indexGatewayFullname" . }}:9095
    {{- end}}
    {{- end}}
```

But then if we look at the `loki.storageConfig` section a little further down in the `values.yaml`, we see this:
```yaml
  storageConfig:
    boltdb_shipper:
      shared_store: filesystem
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      cache_ttl: 168h
    filesystem:
      directory: /var/loki/chunks
```

The presence of `filesystem` throws off the templating above which ends up creating this invalid yaml:
```yaml
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 168h
        shared_store: filesystem
      filesystem:
        directory: /var/loki/chunks
      index_gateway_client:
        server_address: dns:///obs-loki-index-gateway:9095
```

## Proposed Solution
I'm not quite sure on the best way to address this. Reading the entire config as a string like the chart does right now seems like a major contributor to this problem in general but I am sure there is a more targeted change that could be made to address it in a less disruptive manner.

## Further References
I also made a post on the Grafana community forum about this:
[Loki-distributed helm install: field index_gateway_client not found in type storage.Config ](https://community.grafana.com/t/loki-distributed-helm-install-field-index-gateway-client-not-found-in-type-storage-config/59745/2)
