### ISSUE TITLE
[loki] aws insecure parameter is not effective

### ISSUE THREAD

**Issue by scybZhangliang** [grafana/helm-charts#1025]
I've set the `insecure` parameter was `true` , but there is still output the `"https://minio.default.svc.cluster.local/loki-data/fake/85a8507d6831e392%3A17ede5a9024%3A17ede5f2fae%3A4684e217\": x509: certificate signed by unknown authority` error messge in the log.
below is my aws config snippet:
```
  storage_config:
    boltdb_shipper:
      active_index_directory: /data/loki/boltdb-shipper-active
      cache_location: /data/loki/boltdb-shipper-cache
      cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
      shared_store: s3
    filesystem:
      directory: /data/loki/chunks
    aws:
      endpoint: https://minio.default.svc.cluster.local
      insecure: true
      bucketnames: loki-data
      access_key_id: minioadmin
      secret_access_key: minioadmin
      s3forcepathstyle: true
```
need your help, thks!

**Comment by gerardjp** [comment]
I'm seeing the same issue, except I'm on a local minio S3 install and have the url configured as `aws:s3` instead of `aws:endpoint`. Using a valid wildcard certificate. This setup works with self-signed certs behind the minio install, but loki doesn't seem handle (or validate) the CA chain somehow.

**Comment by tman5** [comment]
I have this same issue where `insecure: true` does nothing. I do not have the issue with my cert chain though. The chain has all the certs and no errors using openssl

**Comment by Forestsoft-de** [comment]
Did you tried:

`
storage_config:
    boltdb_shipper:
      active_index_directory: /data/loki/boltdb-shipper-active
      cache_location: /data/loki/boltdb-shipper-cache
      cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
      shared_store: s3
    filesystem:
      directory: /data/loki/chunks
    aws:
      endpoint: https://minio.default.svc.cluster.local
      insecure: true
      bucketnames: loki-data
      access_key_id: minioadmin
      secret_access_key: minioadmin
      s3forcepathstyle: true
      http_config:
            insecure_skip_verify: true
`

br
Sebastian

**Comment by tman5** [comment]
Thanks. That seems to have cleared the error. Still getting a failure in Grafana when adding the data source and I haven't found any errors in the stack yet.

**Comment by ivomarino** [comment]
Not a chart bug - traced it into Loki itself. `insecure: true` under `storage_config.aws` only switches the endpoint from https:// to http://; it does not skip TLS certificate verification. What you actually want is `http_config.insecure_skip_verify` (or `http_config.ca_file` to trust your CA properly instead of skipping verification):

```yaml
storage_config:
  aws:
    endpoint: https://minio.default.svc.cluster.local
    bucketnames: loki-data
    http_config:
      insecure_skip_verify: true
    # insecure: true  <- not needed if you keep the https:// endpoint
```

Filed grafana/loki#24549 to clarify the insecure flag's help text and docs so this is less of a trap going forward.
