### ISSUE TITLE
Grafana helm chart broken by latest kubernetes ingress version 1.19

### ISSUE THREAD

**Issue by crawforde** [grafana/helm-charts#1035]
I saw some similar issues raised for Loki, but the Grafana helm chart (even the latest version, 6.21.3) cannot be deployed to a kubernetes cluster with the latest ingress version. See this issue:

https://stackoverflow.com/questions/64125048/get-error-unknown-field-servicename-in-io-k8s-api-networking-v1-ingressbacken

Here is the error generated when trying to apply the helm chart:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]
```

This `backend.servicePort` field is currently a setting in `ingress.extraPaths`. Any chance there will be a fix for this? Back-porting a fix to Grafana v7 would also be helpful.

**Comment by crawforde** [comment]
As it turns out, the `backend` piece in this helm chart is a pass-through to the ingress controller and can be corrected without changes to the Grafana chart.

New syntax looks like this:
```
extraPaths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: foo
            port:
              number: 8080
```

or this:
```
extraPaths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
```

I'd like to thank this Stack Overflow wizard who saved me a lot of headache due to Kubernetes docs being woefully incomplete:
https://stackoverflow.com/a/68300871/10023749
