### ISSUE TITLE
[Promtail] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+ 

### ISSUE THREAD

**Issue by CherryJia** [grafana/helm-charts#1039]
When I trying to install the promtail agent on my openshift cluster with pspEnabled:true , it throwed out the error :

% helm upgrade --install promtail grafana/promtail  --install -f values.yaml -n promtail-agent

W0214 20:20:59.545974   64766 warnings.go:67] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+

**Comment by stefanjay** [comment]
Bumping this, but please see hivemq docu https://www.hivemq.com/docs/operator/4.11/kubernetes-operator/configuration.html,

tl;dr

set value `pspEnabled: false` to false
```
global:
  rbac:
    create: true
    # Create a PodSecurityPolicy, cluster role, role binding and service account for the HiveMQ pods and assign the service account to them.
    pspEnabled: false
```
