### ISSUE TITLE
Tempo: Global overrides do not work

### ISSUE THREAD

**Issue by joe-alford** [grafana/helm-charts#1077]
If using the `overrides` section to add a global override (https://grafana.com/docs/tempo/latest/configuration/#overrides), they are not imported into the running Tempo config. They appear on the filesystem on the pod, but are not parsed.

# Steps to recreate

Create a deployment of Tempo, with overrides set:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-tempo
  namespace: grafana-tempo
spec:
  chart:
    spec:
      chart: tempo 
      version: 0.14.2
  values:
    tempo:
      tag: 1.3.2
      overrides: 
        max_bytes_per_trace: 350000 
        ingestion_rate_limit_bytes: 400000 

```

Verify they are set:

```
 kubectl describe helmreleases.helm.toolkit.fluxcd.io -n grafana-tempo grafana-tempo | grep Overrides -A 3
      Overrides:
        ingestion_rate_limit_bytes:  400000
        max_bytes_per_trace:         350000
      Pull Policy:                   IfNotPresent
```

Check they're in the pod:

```
/ # cat /conf/overrides.yaml
overrides:
  ingestion_rate_limit_bytes: 400000
  max_bytes_per_trace: 350000
```

And notice that they're not in the running config:

```
/ # curl -s localhost:3100/status/config | grep ingestion_rate_limit_bytes
    ingestion_rate_limit_bytes: 15000000
/ # curl -s localhost:3100/status/config | grep max_bytes_per_trace
    max_bytes_per_trace: 5000000
/ #
```

# Work around

_Note: I don't know if this has larger repercussions, but we have a simple deployment without `multitenancy`, so this works for us_

Change `configmap-tempo.yaml` from:

```
data:
  overrides.yaml: |
    overrides:
      {{- toYaml .Values.tempo.overrides | nindent 6 }}
  tempo.yaml: |
    multitenancy_enabled: {{ .Values.tempo.multitenancyEnabled }}
    search_enabled: {{ .Values.tempo.searchEnabled }}
    compactor:
      compaction:
        compacted_block_retention: {{ .Values.tempo.retention }}
    distributor:
      receivers:
        {{- toYaml .Values.tempo.receivers | nindent 8 }}
    ingester:
      {{- toYaml .Values.tempo.ingester | nindent 6 }}
    server:
      {{- toYaml .Values.tempo.server | nindent 6 }}
    storage:
      {{- toYaml .Values.tempo.storage | nindent 6 }}
```

to 

```
data:
  tempo.yaml: |
    multitenancy_enabled: {{ .Values.tempo.multitenancyEnabled }}
    search_enabled: {{ .Values.tempo.searchEnabled }}
    compactor:
      compaction:
        compacted_block_retention: {{ .Values.tempo.retention }}
    distributor:
      receivers:
        {{- toYaml .Values.tempo.receivers | nindent 8 }}
    ingester:
      {{- toYaml .Values.tempo.ingester | nindent 6 }}
    server:
      {{- toYaml .Values.tempo.server | nindent 6 }}
    storage:
      {{- toYaml .Values.tempo.storage | nindent 6 }}
    overrides:  ############## moved from `overrides.yaml: |`
      {{- toYaml .Values.tempo.overrides | nindent 6 }}  ##############
```

by combining the overrides into the main `tempo.yaml` file, they will be read at application startup, as expected:

```
cat: can't open '/conf/overrides.yaml': No such file or directory
/ # cat /conf/tempo.yaml | grep overrides -A 3
overrides:
  ingestion_rate_limit_bytes: 400000
  max_bytes_per_trace: 350000
/ # curl -s localhost:3100/status/config | grep ingestion_rate_limit_bytes
    ingestion_rate_limit_bytes: 400000
/ # curl -s localhost:3100/status/config | grep max_bytes_per_trace
    max_bytes_per_trace: 350000
/ #
```

**Comment by svennjegac** [comment]
Hey, I am using [official tempo distributed chart](https://github.com/grafana/helm-charts/tree/main/charts/tempo-distributed) and I _had a similar issue_.

The issue is, we both made mistakes.

If you take a closer look at [values.yaml](https://github.com/grafana/helm-charts/blob/dc39d0eb823cd7ca239064b7a87823b5cd1643cf/charts/tempo-distributed/values.yaml#L463), you will see that overrides are actually populated by `.Values.global_overrides`, and not by `.Values.overrides`.

So in your case, I think you just need to use the following snippet:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-tempo
  namespace: grafana-tempo
spec:
  chart:
    spec:
      chart: tempo 
      version: 0.14.2
  values:
    tempo:
      tag: 1.3.2
      global_overrides: 
        max_bytes_per_trace: 350000 
        ingestion_rate_limit_bytes: 400000 
```

I'd say that there [is an issue in official docs](https://grafana.com/docs/tempo/latest/configuration/#overrides). They should use `global_overrides` in their docs instead of `overrides`.

**Comment by joe-alford** [comment]
Hi @svennjegac ,

Thanks for taking the time to respond. Sadly, I don't think this approach is going to work for the `tempo` (rather than `tempo-distributed`) Chart, as there is no option for `overrides_global` in [values.yaml for charts/tempo](https://github.com/grafana/helm-charts/blob/dc39d0eb823cd7ca239064b7a87823b5cd1643cf/charts/tempo/values.yaml).

The only option offered in `overrides`, and that experiences the problem in this bug/issue.

**Comment by ognjenVlad** [comment]
I have the same issue, there is no way to use overrides in a single-tenant deployment.

**Comment by ognjenVlad** [comment]
@joe-alford This issue is fixed with tempo 0.15.2 Helm chart, use global_overrides to achieve this.

**Comment by joe-alford** [comment]
Thanks! :) I'll update it soon.

**Comment by joe-alford** [comment]
Just to add, for completeness, the outcome of this: I updated to 0.15.3, and had to change the config as followed (to get away from the work around I posted above: `overrides` became `global_overrides`), but then it works. Thanks @ognjenVlad 

```
    tempo:
      repository: our-repo/tempo
      tag: 1.4.1
      pullPolicy: IfNotPresent
      overrides: 
        max_bytes_per_trace: 10000000
        ingestion_rate_limit_bytes: 40000000 
```

to

```
    tempo:
      repository: our-repo/tempo
      tag: 1.4.1
      pullPolicy: IfNotPresent
      global_overrides: 
        max_bytes_per_trace: 10000000
        ingestion_rate_limit_bytes: 40000000 
```
