### ISSUE TITLE
[Loki-Simple-Scalable] Memberlist port name protocol breaks with istio

### ISSUE THREAD

**Issue by pastjean** [grafana/helm-charts#1099]
in: `charts/loki-simple-scalable/templates/service-memberlist.yaml`

The port name is "http", since the protocol is not really tcp this conflicts when istio is enabled and the istio port selection (https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/) breaks the memberlist protocol (500: empty ring). 

We're not the first ones to get this: https://community.grafana.com/t/empty-ring-error-with-memberlist/51857

Our fix was to rename the port name to `tcp` like this:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.fullname" . }}-memberlist
  labels:
    {{- include "loki.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    # This is a fork of the https://github.com/grafana/helm-charts
    # Where we change the "version-name" & the memberlist service port name from http to tcp
    # due to istio port selection
    - name: tcp
      port: 7946
      targetPort: http-memberlist
      protocol: TCP
  selector:
    {{- include "loki.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/part-of: memberlist
```
