### ISSUE TITLE
[tempo-distributed] configmap should allow values for ingester's ring

### ISSUE THREAD

**Issue by AlexDHoffer** [grafana/helm-charts#1110]
The chart's default value for ingester shows:

````
ingester:
    lifecycler:
      ring:
        replication_factor: 1
        kvstore:
          store: memberlist
````

It would be nice to have some of these configurable, e.g.:

````
ingester:
    lifecycler:
      ring:
        replication_factor: {{ .Values.ingester.config.replication_factor }}
        kvstore:
          store: {{ .Values.ingester.config.kvstore }}
````

As it stands I'm overriding the entire configmap so I can increase the replication factor for a highly available ingester.
