### ISSUE TITLE
[Loki-distributed]

### ISSUE THREAD

**Issue by danielserrao** [grafana/helm-charts#1111]
I have Grafana with the Loki datasource pointing to the loki querier-frontend but I get the following error:

```
Query error
open /var/loki/chunks/ZmFrZS9kOGU4OGYwOTg3ZTM0NWUyOjE3ZjllMTk0NmE4OjE3ZjllMTk1NmVkOmMwMWFiYmNm: no such file or directory
```

Sometimes it is working and then it gets the same error for some reason that is not clear to me.

On the logs of the querier-frontend pod I can see:

`caller=logging.go:72 traceID=5c8361c04594c7a2 orgID=fake msg="GET /loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bjob%3D%22fbit_k8s%22%7D&start=1647619419284000000&end=1647630219285000000&step=5 (500) 53.767877ms Response: \"open /var/loki/chunks/ZmFrZS9kOGU4OGYwOTg3ZTM0NWUyOjE3ZjllMTk0NmE4OjE3ZjllMTk1NmVkOmMwMWFiYmNm: no such file or directory\\n\" ws: false; Accept: application/json, text/plain, */*; Accept-Encoding: gzip, deflate, br; Accept-Language: en-GB,en;q=0.9,en-US;q=0.8; Sec-Ch-Ua: \" Not A;Brand\";v=\"99\", \"Chromium\";v=\"99\", \"Microsoft Edge\";v=\"99\"; Sec-Ch-Ua-Mobile: ?0; Sec-Ch-Ua-Platform: \"Windows\"; Sec-Fetch-Dest: empty; Sec-Fetch-Mode: cors; Sec-Fetch-Site: same-origin; User-Agent: Grafana/8.3.5; X-Forwarded-For: 127.0.0.1, 127.0.0.1; X-Grafana-Org-Id: 1; "`

When doing "helm template", the K8s manifest (which is applied) is the following:

[test.txt](https://github.com/grafana/helm-charts/files/8307041/test.txt)

I already tried multiple types of configurations, but I always get this annoying error. 

Some help would be very appreciated.

**Comment by rafaribe** [comment]
I'm experiencing the same thing with a very similar config to yours but using azure blob storage.
If I query anything over 1h i get this annoying message.

**Comment by aberenshtein** [comment]
Thanks @danielserrao 
```compactor:
      shared_store: s3
```
worked for me

**Comment by kumarganesh2814** [comment]
Hi 

I am getting same error, may I know config which you mentioned where needs to be updated. I have installed Loki as 

![image](https://user-images.githubusercontent.com/22414186/167345617-d1b71976-fbcd-40c5-ac9d-0eaf20ca6664.png)
 Is there any configmap we can update?

Best Regards
Ganesh

**Comment by aberenshtein** [comment]
These are all the places I changed
https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/values.yaml#L144
https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/values.yaml#L163
https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/values.yaml#L172

**Comment by kfkawalec** [comment]
I have the same problem after restarting some components. Anyone have a solution on how to fix it?

```
error: open /grafana-loki/chunks/ZmFrZS8yMDU1NjdiNzY5ZWVhZmJkOjE4MGU0ZTE3ZDJkOjE4MGU1NGZhYjg2OmRkMDQ4NWQy: no such file or directory 
```
But the file exists and all perminision is OK
```
$ more /grafana-loki/chunks/ZmFrZS8yMDU1NjdiNzY5ZWVhZmJkOjE4MGU0ZTE3ZDJkOjE4MGU1NGZhYjg2OmRkMDQ4NWQy
rke2-ingress-nginx-controller","filename":"/var/log/pods/kube-system_rk
--More--(1%)
```

**Comment by liuxuzxx** [comment]
When I use loki-simple-scalabel, and I use nfs of storageClass, 
When I select the time range is 5 minutes ,It is ok, but when I select 15 minutes or 1hour time range,the error occured!
```bash
open /var/loki/chunks/fake/755005aa5e414340/MTgxMTNjOGM5MGI6MTgxMTQzNmE2NTI6M2RkYjQzYmQ=: no such file or directory
```
when I enter the write pod ,the file is exists!

This error occurs sometimes and sometimes not

**Comment by tobifroe** [comment]
This is mentioned in the chart [README](https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed#configuration) I think: 

> NOTE: In its default configuration, the chart uses boltdb-shipper and filesystem as storage. The reason for this is that the chart can be validated and installed in a CI pipeline. However, this setup is not fully functional. Querying will not be possible (or limited to the ingesters' in-memory caches) because that would otherwise require shared storage between ingesters and queriers which the chart does not support and would require a volume that supports ReadWriteMany access mode anyways. The recommendation is to use object storage, such as S3, GCS, MinIO, etc., or one of the other options documented at https://grafana.com/docs/loki/latest/storage/.

I got around this issue by installing the [single binary Loki chart](https://github.com/grafana/helm-charts/tree/main/charts/loki)

**Comment by andretadeu** [comment]
I could get the things working by configuring the volumes:

```
loki-distributed:
  ingester:
    extraVolumes:
      - name: loki-chunks
        hostPath:
          path: "/var/loki/chunks"
          type: Directory
    extraVolumeMounts:
      - name: loki-chunks
        mountPath: "/var/loki/chunks"
  querier:
    extraVolumes:
      - name: loki-chunks
        hostPath:
          path: "/var/loki/chunks"
          type: Directory
    extraVolumeMounts:
      - name: loki-chunks
        mountPath: "/var/loki/chunks"
```
and I created this folder with permissions to the pods to write on them.

**Comment by aberenshtein** [comment]
yes, but I see that the references I put for the value files are outdated. 
I guess they were updated in later versions

**Comment by ak2766** [comment]
I'm getting this error when there's high traffic in the cluster.  I managed to duplicate by running the benchmark tool - [wrk](https://github.com/wg/wrk).  It seems that when `promtail` is unable to send logs to `loki` due to high network traffic in my cluster, then querying loki datasource in `grafana` results in this error if the query range includes the time period of high traffic.

Any solution for this?

**Comment by jdgomeza** [comment]
For me, the problem was solved by removing the default configuration `storage_config/filesystem` that the helm template generates after applying my `values.yaml` file. I am using the helm chart `loki-distributed` v0.63.1.

here is the snippet that removes the extra `filesystem` config property

```yaml
# values.yaml
loki:
  annotations: {}

  ...  

  storageConfig:
    boltdb_shipper:
      shared_store: s3
    aws:
      s3: s3://${cluster_region}
      bucketnames: ${bucket_name}
    filesystem: null
```

Notice the latest `filesystem: null`. That line removes the reference to `directory: /var/loki/chunks` that was confusing the querier

```diff
# generated configMap
apiVersion: v1
data:
  config.yaml: |
    auth_enabled: false

...

    storage_config:
      aws:
        bucketnames: bucket-for-logs
        s3: s3://${region}
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 168h
        shared_store: s3
-      filesystem:
-       directory: /var/loki/chunks

```

**Comment by adapasuresh** [comment]
I have distributed micro services working in one cluster, but in production facing issues after couple of weeks. I added pvc to grafana and restarted the same and now I am not able to get labels in grafana UI with "failed to call resource "

**Comment by saitama-24** [comment]
> I could get the things working by configuring the volumes:
> 
> ```
> loki-distributed:
>   ingester:
>     extraVolumes:
>       - name: loki-chunks
>         hostPath:
>           path: "/var/loki/chunks"
>           type: Directory
>     extraVolumeMounts:
>       - name: loki-chunks
>         mountPath: "/var/loki/chunks"
>   querier:
>     extraVolumes:
>       - name: loki-chunks
>         hostPath:
>           path: "/var/loki/chunks"
>           type: Directory
>     extraVolumeMounts:
>       - name: loki-chunks
>         mountPath: "/var/loki/chunks"
> ```
> 
> and I created this folder with permissions to the pods to write on them. Of course, this settings are for local directories, not for volumes on GCS or S3, for example.

I tried it and it seems to be feasible. Thank you for providing the idea. I will keep an eye on it.

**Comment by shengjiangfeng** [comment]
i still have problem when use distributed to query log

**Comment by Hamza-Aziz** [comment]
As pointed in a previous comment, the querier and the ingester needs to have access to the same dir  `/var/loki/chunks`

I got working and this is by creating a pvc out of the helm chart because the helm chart is hard coding the access mode of the data pvc, and therefore I had to create a  RWX pvc  `loki-chunks` and attach it to both components 

```
    querier:
      extraVolumes:
        - name: loki-chunks
          persistentVolumeClaim:
            claimName: loki-chunks
      extraVolumeMounts:
        - name: loki-chunks
          mountPath: "/var/loki/chunks"
```

```
    ingester:
      extraVolumes:
        - name: loki-chunks
          persistentVolumeClaim:
            claimName: loki-chunks
      extraVolumeMounts:
        - name: loki-chunks
          mountPath: "/var/loki/chunks"
```
