### ISSUE TITLE
Loki-simple-scalable object storage values ambiguous

### ISSUE THREAD

**Issue by samox73** [grafana/helm-charts#1126]
When deploying `loki-simple-scalable`, the S3 configuration does not provide enough error handling and the doc is not clear about what values to set. Using
```yaml
common:
  ....
  storage:
    s3:
      bucketnames: mybucketname
      s3: s3://ACCESS_KEY:URI_ENCODED_SECRET_KEY@eu-central-1
```
results in `loki-write` pods which report:
```
level=info ts=2022-03-25T12:50:39.699229502Z caller=table_manager.go:171 msg="uploading tables"
level=info ts=2022-03-25T12:51:39.699329652Z caller=table_manager.go:171 msg="uploading tables"
level=info ts=2022-03-25T12:51:39.703260241Z caller=checkpoint.go:617 msg="starting checkpoint"
level=info ts=2022-03-25T12:51:39.703491468Z caller=checkpoint.go:342 msg="attempting checkpoint for" dir=/var/loki/wal/checkpoint.000001
level=info ts=2022-03-25T12:51:39.706892492Z caller=checkpoint.go:504 msg="atomic checkpoint finished" old=/var/loki/wal/checkpoint.000001.tmp new=/var/loki/wal/checkpoint.000001
level=info ts=2022-03-25T12:52:39.698819226Z caller=table_manager.go:171 msg="uploading tables"
```
when in fact no objects are stored in the corresponding bucket.
