### ISSUE TITLE
Authorization errors when starting a Loki pod

### ISSUE THREAD

**Issue by AndriiKhodyriev** [grafana/helm-charts#1192]
This morning I discovered that Loki stopped working in the EKS cluster

In the loki pod logs I see the following:

`level=error ts=2022-04-07T10:44:43.298418416Z caller=table_manager.go:233 msg="error syncing tables" err="WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.us-east-2.amazonaws.com/\": dial tcp XXX.XXX.XXX.XXX:443: i/o timeout"
`

- ServiceAccount exists and has not changed
- IAM Role exists and has not changed
- Dashboards related to Loki and prometheus stopped working (prometheus works with thanos)
 
Example values ​​file - deployment happens via flux:
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  values:
    extraArgs:
      target: all,table-manager
    serviceAccount: 
      create: true
      name: lokiaccess
      annotations: 
        eks.amazonaws.com/role-arn: arn:aws:iam::<PRIVATE_ID>:role/LokiAccess
        eks.amazonaws.com/sts-regional-endpoints: "true"
    config: 
      storage_config: 
        boltdb_shipper:
          shared_store: s3
        aws: 
          s3: s3://us-east-2/<PRIVATE_STORAGE>
          dynamodb: 
            dynamodb_url: dynamodb://us-east-2
      schema_config:
        configs:
          - from: "2022-04-04"
            store: aws
            object_store: s3
            schema: v11
            index:
              prefix: loki_
              period: 24h

```

**Comment by sarasensible** [comment]
It's really strange that it just stopped working out of the blue - that sounds frustrating!

If you are trying to use regional endpoints I found this issue while searching for solutions to a similar error - https://github.com/grafana/loki/issues/5436 .  In this case they were trying to use a regional endpoint and also needed to set AWS_STS_REGIONAL_ENDPOINTS=regional in the Loki pods environments.

So you would need to add it on every service:

```
querier:
  extraEnv:
    - name: AWS_STS_REGIONAL_ENDPOINTS
      value: regional
distributor:
  extraEnv:
    - name: AWS_STS_REGIONAL_ENDPOINTS
      value: regional
queryFrontend:
  extraEnv:
    - name: AWS_STS_REGIONAL_ENDPOINTS
      value: regional
gateway:
  extraEnv:
    - name: AWS_STS_REGIONAL_ENDPOINTS
      value: regional
compactor:
  extraEnv:
    - name: AWS_STS_REGIONAL_ENDPOINTS
      value: regional
indexGateway:
  extraEnv:
    - name: AWS_STS_REGIONAL_ENDPOINTS
      value: regional
```

In my case I am fine with the global endpoints and just removing `loki.storageConfig.aws.insecure=true` was enough to get past the connection refused error (it was trying to connect to port 80).  In your case though it looks like the configuration does not have `insecure=true` since it is correctly trying to invoke the 443 port.

Hope it helps!
