### ISSUE TITLE
[grafana] Unified Alerting not working

### ISSUE THREAD

**Issue by marlongehringer** [grafana/helm-charts#1202]
Hello,
I followed the instructions in README.md 
https://github.com/grafana/helm-charts/tree/main/charts/grafana#high-availability-for-unified-alerting

I received following error:
`No private IP address found, and explicit IP not provided`

I'm not sure if it's related to my setup that the Grafana Pods could not automatically detect the Pod IP, but I could fix it with:

```yaml
env:
  GF_UNIFIED_ALERTING_HA_ADVERTISE_ADDRESS: $(POD_IP):9094

envValueFrom:
  POD_IP:
    fieldRef:
      fieldPath: status.podIP
```

Maybe this should be added to the README.md.
