### ISSUE TITLE
Cant define dashboard name 

### ISSUE THREAD

**Issue by slev-dev** [grafana/helm-charts#1204]
I cant figure out how to define a dashboard name.
I tried name, title, label - nothing seems to works. The documentation doesnt state how to do it.

```
dashboards:
  default:
    rproxy-traefik:
      name: rproxy-traefik  # label, title... nothing works..  
      gnetId: 12250
      revision: 1
      datasource: Prometheus
```

Any ideas?
