### ISSUE TITLE
[Promtail] extraClientConfigs breaking change

### ISSUE THREAD

**Issue by dungdm93** [grafana/helm-charts#1214]
Before, I have one `lokiAddress` and I use `extraClientConfigs` to add extra config/labels before send logs to Loki server.
![image](https://user-images.githubusercontent.com/6848311/162719115-0384c82f-0782-4341-8908-73ae16bcc1f8.png)
![image](https://user-images.githubusercontent.com/6848311/162720008-a375bb3c-ce88-4809-a919-e76d652bbf47.png)

After #1119, `extraClientConfigs` seem used to add extra clients, instead of extra config of existing client. So that will breaking my use-case:
![image](https://user-images.githubusercontent.com/6848311/162720464-98468a91-c81c-4953-8c26-6747ed387c23.png)

**Comment by dungdm93** [comment]
I can make a PR for this, but I don't known which one you prefer:
1. Rollback #1119 and add another key for this like `extraClients`
2. make `lokiAddress` become a map, instead of string
```
lokiAddress:
   url: http://loki-gateway/loki/api/v1/push
   // more config can be added here
```
then:
```
    clients:
      - {{ toYaml .Values.config.lokiAddress }}
```

**Comment by tobygale** [comment]
We've hit the same issue.
We use `extraClientConfigs` to set the `tenant_id` in places where we cannot inject the `X-Scope-OrgID` header.
Just had to rollback to the previous version.

**Comment by jimgus** [comment]
Hit this issue as well when trying to add `tls_config` in `extraClientConfigs `

**Comment by secustor** [comment]
We have ran into this today too. We use it to set the external labels and authentication methods .

I suggest the introduction of a new variable instead of replacing `lokiAddress` with a map. 
```
lokiClientConfig:
  external_labels:
     aLabel: aValue
```

```
    clients:
      - url: {{ .Values.config.lokiAddress }}
        {{ toYaml .Values.config.lokiClientConfig | nindent 4 }}
      {{- with .Values.config.snippets.extraClientConfigs }}
      {{- toYaml . | nindent 2 }}
      {{- end }}
```

**Comment by fabienpelletier** [comment]
same, I'm using the `extraClientConfigs` to set `basic_auth` and this change breaks it.

**Comment by ambis** [comment]
> same, I'm using the `extraClientConfigs` to set `basic_auth` and this change breaks it.

Same here. I have to re-write the whole file, which is not update proof.

```yaml
    extraEnv:
      - name: PROMTAIL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: some-pw
            key: some-key
    extraArgs:
      - -config.expand-env=true
    config:
      lokiAddress: http://loki-loki-distributed-gateway/loki/api/v1/push
      file: |
        server:
          log_level: {{ .Values.config.logLevel }}
          http_listen_port: {{ .Values.config.serverPort }}

        clients:
          - url: {{ tpl .Values.config.lokiAddress . }}
            basic_auth:
              username: promtail
              password: ${PROMTAIL_PASSWORD}
          {{- with .Values.config.snippets.extraClientConfigs }}
          {{- toYaml . | nindent 2 }}
          {{- end }}

        positions:
          filename: /run/promtail/positions.yaml

        scrape_configs:
          {{- tpl .Values.config.snippets.scrapeConfigs . | nindent 2 }}
          {{- tpl .Values.config.snippets.extraScrapeConfigs . | nindent 2 }}
```
