### ISSUE TITLE
[mimir] query-frontend results cache: no memcached addresses configured

### ISSUE THREAD

**Issue by aaronstutzer** [grafana/helm-charts#1218]
`error validating config: invalid query-frontend middleware config: invalid ResultsCache config: query-frontend results cache: no memcached addresses configured`
that is the error I get when trying to deploy mimir-distributed with helm. not sure where in the config I should define the addresses. I tried some stuff but failed.

this is (part) of my values file:
``` yaml

  mimir:
    # -- Config file for Grafana Mimir, enables templates. Needs to be copied in full for modifications.
    config: |
      multitenancy_enabled: true

      limits:
        max_label_names_per_series: 50
        ingestion_rate: 50000
        max_global_series_per_user: 0

      alertmanager:
        data_dir: '/data'
        enable_api: true
        external_url: '/alertmanager'

      alertmanager_storage:
        backend: gcs
        gcs:
          bucket_name: mimir-alerts
          service_account: ${GCS_SERVICE_ACCOUNT}

      distributor:
        pool:
            health_check_ingesters: true
        
      frontend_worker:
        frontend_address: {{ template "mimir.fullname" . }}-query-frontend-headless.{{ .Release.Namespace }}.svc:{{ include "mimir.serverGrpcListenPort" . }}

      ruler:
        enable_api: true
        rule_path: '/data'
        alertmanager_url: dnssrvnoa+http://_http-metrics._tcp.{{ template "mimir.fullname" . }}-alertmanager-headless.{{ .Release.Namespace }}.svc.cluster.local/alertmanager

      server:
        http_listen_port: 80
        grpc_server_max_recv_msg_size: 104857600
        grpc_server_max_send_msg_size: 104857600
        grpc_server_max_concurrent_streams: 1000

      frontend:
        align_queries_with_step: true
        cache_results: true
        log_queries_longer_than: 10s
        results_cache:
            backend: memcached
            memcached:
                timeout: 1s
        split_queries_by_interval: 24h0m0s

      compactor:
        data_dir: "/data"

      ingester:
        ring:
          final_sleep: 0s
          num_tokens: 512
          kvstore:
            store: memberlist
          replication_factor: 3

      ingester_client:
        grpc_client_config:
          grpc_compression: snappy
          max_recv_msg_size: 104857600
          max_send_msg_size: 104857600

      querier:
        query_ingesters_within: 12h5m0s
        query_store_after: 12h0m0s

      runtime_config:
        file: /var/mimir/runtime.yaml

      memberlist:
        abort_if_cluster_join_fails: false
        compression_enabled: false
        join_members:
        - {{ include "mimir.fullname" . }}-gossip-ring
        bind_port: 7946

      blocks_storage:
        backend: gcs
        bucket_store:
          bucket_index:
            enabled: true
          sync_dir: /data/tsdb-sync
          {{- if .Values.memcached.enabled }}
          chunks_cache:
            backend: "memcached"
            memcached:
              addresses: "dns+{{ .Release.Name }}-memcached.{{ .Release.Namespace }}.svc:11211"
              max_item_size: {{ .Values.memcached.maxItemMemory }}
          {{- end }}
          {{- if index .Values "memcached-metadata" "enabled" }}
          metadata_cache:
            backend: "memcached"
            memcached:
              addresses: "dns+{{ .Release.Name }}-memcached-metadata.{{ .Release.Namespace }}.svc:11211"
              max_item_size: {{ (index .Values "memcached-metadata").maxItemMemory }}
          {{- end }}
          {{- if index .Values "memcached-queries" "enabled" }}
          index_cache:
            backend: "memcached"
            memcached:
              addresses: "dns+{{ .Release.Name }}-memcached-queries.{{ .Release.Namespace }}.svc:11211"
              max_item_size: {{ (index .Values "memcached-queries").maxItemMemory }}
          {{- end }}
        gcs:
            bucket_name: mimir-data
            service_account: ${GCS_SERVICE_ACCOUNT}
        tsdb:
            retention_period: 24h0m0s

      ruler_storage:
        backend: gcs
        gcs:
            bucket_name: mimir-alerts
            service_account: ${GCS_SERVICE_ACCOUNT}

  query_frontend:
    replicas: 1

    resources:
      requests:
        cpu: 1
        memory: 4Gi
      limits:
        memory: 4Gi

    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: target
                    operator: In
                    values:
                      - query-frontend
              topologyKey: 'kubernetes.io/hostname'
```
