### ISSUE TITLE
Is there an example somewhere of using external storage such as S3 in mimir?

### ISSUE THREAD

**Issue by WilliamCassanova** [grafana/helm-charts#1222]
I'm a bit confused about where I should actually be creating things such as is mentioned in:
- https://github.com/grafana/helm-charts/blob/main/charts/mimir-distributed/small.yaml#L12-L13.

I'd love to not have to add this to `mimir.config` and if at all possible set in somewhere around ( Not Yet in the Values.yaml file, but someplace it could possible live ) here.:
- https://github.com/grafana/helm-charts/blob/main/charts/mimir-distributed/values.yaml#L46

Instead of in the `mimir.config` as shown below as an example.
```
mimir:
  # -- Config file for Grafana Mimir, enables templates. Needs to be copied in full for modifications.
  config: |
    multitenancy_enabled: true

    storage:
      engine: blocks
    blocks_storage:
      backend: s3 # s3, gcs, azure or filesystem are valid options
      s3:
        endpoint: s3.private.us-south.cloud-object-storage.appdomain.cloud
        bucket_name: prometheus-icm-mimir-server-south
      tsdb:
        dir: "/data/tsdb"
      bucket_store:
        sync_dir: "/data/tsdb-sync"

   #####  Do I Also need to set it in each section under mimir.config ? ####
    alertmanager:
      data_dir: '/data'
      enable_api: true
      external_url: '/alertmanager'
      alertmanager_storage:
         backend: s3 # s3, gcs, azure or filesystem are valid options
         s3:
           endpoint: s3.private.us-south.cloud-object-storage.appdomain.cloud
           bucket_name: prometheus-icm-mimir-server-south
        tsdb:
          dir: "/data/tsdb"
        bucket_store:
          sync_dir: "/data/tsdb-sync"
```

**Comment by krajorama** [comment]
Hi, currently only `mimir.config` is supported as a way to provide configuration to mimir - some users have indicated that there were too many ways to influence the configuration in other charts so it was obvious what the end result was. We are happy to receive feedback on this issue.

There is an example of s3 usage as we provide `minio` s3 compatible storage for trying out the chart. So to set up s3, you need to copy `mimir.config` into your own custom-values.yaml and add/modify the parts where minio is also set (i.e. alertmanager_storage, ruler_storage, blocks_storage.

**Comment by WilliamCassanova** [comment]
Thank you very much...That help!

**Comment by WilliamCassanova** [comment]
Let me ask a few clarifying questions:

1. If my values.yaml file I have something like the below is the external `storage` section even needed?
2. If I did provide both does the one in `mimir.config` take precedence over anything I have separately?  Using this example I named the `storage.blocks_storage.s3.bucket_name` to `foo`.  In the `mirmir.config.storage.blocks_storage.s3.bucket_name` to `bar`.  In this case which one would actually be used?

```
storage:
  engine: blocks
blocks_storage:
  backend: s3 # s3, gcs, azure or filesystem are valid options
  s3:
    endpoint: s3.private.us-south.cloud-object-storage.appdomain.cloud
    bucket_name: foo
  tsdb:
    dir: "/data/tsdb"
  bucket_store:
    sync_dir: "/data/tsdb-sync"

mimir:
  # -- Config file for Grafana Mimir, enables templates. Needs to be copied in full for modifications.
  config: |
    #### I removed the rest for clarity of the question ###
    
    blocks_storage:
      backend: s3 # s3, gcs, azure or filesystem are valid options
      s3:
        endpoint: s3.private.us-south.cloud-object-storage.appdomain.cloud
        bucket_name: bar
      tsdb:
        dir: "/data/tsdb"
      bucket_store:
        sync_dir: "/data/tsdb-sync"
```

**Comment by WilliamCassanova** [comment]
I think I was able to get this resolved.  The method I used was to pre-create the buckets needed:
- `mimir-tsdb`
- `mimir-ruler`
- `enterprise-metrics-tsdb` # NOTE This may not be needed for a DIY Deployment
- `enterprise-metrics-admin` # NOTE This may not be needed for a DIY Deployment
- `enterprise-metrics-ruler` # NOTE This may not be needed for a DIY Deployment

Then in `mimir.config`, for example, I locally modified to remove the `minio.enabled` and have something like:
```
alertmanager_storage:
   backend: s3
    s3:
      endpoint: < Your-EndPoint-Here >
      bucket_name: mimir-ruler
```

Grep through the default`values.yaml` file for the word `bucket_name` and associate the correct bucket with the correct section.
