### ISSUE TITLE
[Grafana] Sidecar dashboard

### ISSUE THREAD

**Issue by Dante3004** [grafana/helm-charts#1239]
Hello,

I already use the sidecar to inject the datasources dynamically. The question I have is, is it possible to load the dashboard other than in json format, with a 'gnetId' for example?
As an example, I have tested in vain with the following configmap to deploy the provider and the dashboard associated with the victoriametrics chart helm:
```
      sidecar:
        datasources:
          enabled: true
          label: grafana_datasource
          searchNamespace: "test"
        dashboards:
          enabled: true
          label: grafana_dashboard
          folder: /tmp/dashboards
          searchNamespace: "test"
        notifiers:
          enabled: true
          label: grafana_notifier
          searchNamespace: "test"
```

Provider Configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: victoria-grafana-dashboardprovider-config
  namespace: "{{ namespace_name }}"
data:
  dashboardproviders.yaml: |
    apiVersion: 1
    providers:
    - name: 'victoria'
      orgId: 2
      folder: 'victoria'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /tmp/dashboards/victoria
```

Dashboard import:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: victoria-grafana-dashboard-config
  namespace: "{{ namespace_name }}"
  labels:
    grafana_dashboard: "2"
data:
  dashboard.yaml: |
    dashboards:
      victoria:
        victoriametrics:
          gnetId: 11176
          revision: 18
          datasource: victoriametrics
        vmagent:
          gnetId: 12683
          revision: 7
          datasource: victoriametrics
        kubernetes:
          gnetId: 14205
          revision: 1
          datasource: victoriametrics
```

Thx in advance for your helping :)
