### ISSUE TITLE
[mimir-distributed] Add prometheus rule and alert specifications for mimir dashboards

### ISSUE THREAD

**Issue by krajorama** [grafana/helm-charts#1240]
Continues #1190 .

Enable the user to turn on creating [Prometheus operator](https://github.com/prometheus-operator/prometheus-operator) rules and alerts based on our mixins:
https://github.com/grafana/mimir/blob/main/operations/mimir-mixin-compiled/rules.yaml
https://github.com/grafana/mimir/blob/main/operations/mimir-mixin-compiled/alerts.yaml

Proposed solution (by @dimitarvdimitrov , to test):
Continue in PR https://github.com/grafana/mimir/pull/2609 
Add symlink to the rules and alert yaml in the compiled mixins:
operations/helm/charts/mimir-distributed/mixins/rules.yaml -> ../../../../mimir-mixin-compiled/rules.yaml  (and for alerts)

Add boolean flags to enable/disable loading them via the PrometheusRule

Out of scope:  Mimir itself will not pick these up, only Prometheus operator or Grafana agent

**Comment by dimitarvdimitrov** [comment]
proposal for config format:

```yaml
metamonitoring:
  prometheus:
    recording_rules:
      # controls whether to create a PrometheusRulesList CRD with the recording rules from the mixin (default: false)
      enabled: false

    alerting_rules:
      # controls whether to create a PrometheusRulesList CRD with the alerting rules from the mixin (default: false)
      enabled: false
```
