### ISSUE TITLE
sidecar.dashboards.enabled and persistence.enabled exclude each other

### ISSUE THREAD

**Issue by yurinek** [grafana/helm-charts#125]
Following config doesnt make sence.

```
sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
persistence:
    type: pvc
    enabled: true
    existingClaim: pvc-grafana-data
```
The first manages dashboards in configmaps. it discovers cm where dashboards are defined and loads them in pod to /tmp/dashboards

```
/dev/sda1               123.9G     22.0G    101.8G  18% /tmp/dashboards
```
this prevents following mount points from being mounted:

/var/lib/grafana
/etc/grafana/grafana.ini

When persistence is enabled it writes to /var/lib/grafana but it doesnt work if "sidecar.dashboards.enabled: true" because the pv is not mounted

however all the default k8s dashboards are created only when "sidecar.dashboards.enabled: true"

1. It would be nice to have both: all the default k8s dashboards and persistence with mounted pv.

For now I need to create pv because persistence.existingClaim is mandatory if persistence enabled, though its not used because not mounted in  /var/lib/grafana.

If 1. is not possible it would be good to make persistence.existingClaim not mandatory so we dont need to create pv which is not used anyway.

Thank you
