### ISSUE TITLE
[loki-stack] chart update 2.6.2 - 2.6.4 causes change to immutable field in loki-stack-promtail daemonset 

### ISSUE THREAD

**Issue by gclawes** [grafana/helm-charts#1256]
Updaing the `loki-stack` chart from `2.6.2` to `2.6.4`  causes the following immutable field change error:
```
Error: UPGRADE FAILED: cannot patch "loki-stack-promtail" with kind DaemonSet: DaemonSet.apps "loki-stack-promtail" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"loki-stack", "app.kubernetes.io/name":"promtail"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
Associated `values.yaml`:
```
loki:
  persistence:
    enabled: true
  podAnnotations:
    sidecar.istio.io/inject: "true"

promtail:
  podAnnotations:
    sidecar.istio.io/inject: "true"
```

Reproduction steps:
1. Install `loki-stack` `2.6.2` with above values (istio annotations can be ignored on non-istio clusters).
2. Upgrade to `loki-stack` `2.6.4`
