### ISSUE TITLE
Import Dashboard features

### ISSUE THREAD

**Issue by Yalafeg** [grafana/helm-charts#127]
Hello,

I am trying to import different dashboards to Grafana interface using the different features provided, but I am not able to find the best way that replies to my request.

I want to be able to import the dashboards during the Grafana helm chart installation, and be able to modify the content of the Dashboards, update, delete, etc... without redeploying the configuration and recreating the pod.

I tried to add the dashboards under a specific volume on the pod, it worked properly, the dashboards appear in the Grafana interface, BUT, I am unable to do the proper modification without recreation of the pod.

I tried to use the sidecar, I created the dashboard as configmap with the appropriate labeling and attributes, but the dashboards were not appearing at all on Grafana GUI interface. And I was wondering if I am missing a specific configuration that was not clear enough for me.

In addition, I tried to use also the local-dashboard option; I added as value a Gitlab URL redirected to the dashboard JSON file. But the dashboard was not appearing on Grafana interface.

I am wondering if I am missing a specific information or detail, can you please advise what can I do to be able to get my Grafana working as requested.

Thank you

**Comment by caleb15** [comment]
The readme doesn't mention it but for me I had to specify a dashboardProvider to get my dashboards to work

For example:
```yml
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        folder: ''
        options:
          path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    aws-billing:
      # Ref: https://grafana.com/dashboards/139
      gnetId: 139
      revision: 15
      datasource: CloudWatch
    redis:
      # Ref: https://grafana.com/dashboards/969
      gnetId: 969
      revision: 3
      datasource: CloudWatch
```
