### ISSUE TITLE
Change default listening Port.

### ISSUE THREAD

**Issue by WilliamCassanova** [grafana/helm-charts#1276]
In `mimir` there does not seem to be a place we can change the `server.http_listen_port` 
https://github.com/grafana/helm-charts/blob/main/charts/mimir-distributed/values.yaml#L83-L86

As there was in Cortex:
https://github.com/cortexproject/cortex-helm-chart/blob/master/values.yaml#L73-L78

I tried adding this to `mirmir.config` in the following way:
```
      server:
        http_listen_port: 9009
        grpc_server_max_recv_msg_size: 104857600
        grpc_server_max_send_msg_size: 104857600
        grpc_server_max_concurrent_streams: 1000
```

But some pods are failing to spin-up.  The ones that are working I eliminated from this issue to avoid confusion:
```
mimir-alertmanager-0                        0/1     Running   0               53m
mimir-compactor-0                           0/1     Running   0               53m
mimir-store-gateway-0                       0/1     Running   0               53m
```

Is there some additional place I need to change it?
