### ISSUE TITLE
Unable to install loki stack when grafana is disabled

### ISSUE THREAD

**Issue by adnan-kamili** [grafana/helm-charts#131]
I have loki stack insatalled in my k8s cluster and it works fine. Here is the config and install command:

```
helm repo add loki https://grafana.github.io/loki/charts
helm repo update
helm upgrade --install loki loki/loki-stack --atomic --create-namespace --namespace cluster-management --values ./loki/loki.yaml
```

And loki.yaml

```
loki:
  persistence:
    enabled: true
    size: 20Gi
  config:
    table_manager:
      retention_deletes_enabled: true
      # retain logs for two weeks
      retention_period: 336h

promtail:
  enabled: false

fluent-bit:
  enabled: true

grafana:
  enabled: false

prometheus:
  enabled: false
```

This worked fine with 1.x but fails with 2.x for the fluentbit with following error:

```
2020-12-11T07:09:02.805142608Z Fluent Bit v1.4.6
2020-12-11T07:09:02.805165872Z * Copyright (C) 2019-2020 The Fluent Bit Authors
2020-12-11T07:09:02.805172280Z * Copyright (C) 2015-2018 Treasure Data
2020-12-11T07:09:02.805175930Z * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
2020-12-11T07:09:02.805179296Z * https://fluentbit.io
2020-12-11T07:09:02.805182583Z 
2020-12-11T07:09:02.805185697Z Output plugin 'grafana-loki' cannot be loaded
2020-12-11T07:09:02.805189030Z Error: You must specify an output target. Aborting
```

We already have grafana installed so we don't want to re-install in the loki-stack

**Comment by utkudarilmaz** [comment]
Same issue occurred when installing loki/fluent-bit v2.0.1 chart.

**Comment by knfoo** [comment]
I just tried to install it via the loki-stack

`helm upgrade --install loki grafana/loki-stack --set fluent-bit.enabled=true,promtail.enabled=false,grafana.enabled=true,prometheus.enabled=true,prometheus.alertmanager.persistentVolume.enabled=false,prometheus.server.persistentVolume.enabled=false --namespace loki`

I get the same error

**Comment by utkudarilmaz** [comment]
If change the output plugin name to `loki` error is resolving.

**Comment by ohdearaugustin** [comment]
Same issue here with loki-stack version 2.2.0.

**Comment by unguiculus** [comment]
With Loki 2.1.0 and updated chart versions, the issue should be fixed. Unfortunately, the Grafana folks had updated the charts when the change made it into master but was not released yet. See https://github.com/grafana/loki/releases/tag/v2.1.0.

**Comment by ohdearaugustin** [comment]
@unguiculus That problem remains with loki-stack version 2.3.0 too. The helm chart installs the version 2.0.0 of the fluent-bit chart, which includes the old image with grafana/fluent-bit-plugin-loki:1.6.0-amd64.

We need to upgrade the requirements file.

```- name: "fluent-bit"
  condition: fluent-bit.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "^2.0.0"
  ```
  
  Workaround for now. Just set the container image to the new version:
```
fluent-bit:
  enabled: true
  image:
      tag: 2.1.0-amd64
```

BTW: Should fix is not being tested. Please test the charts next time.
