### ISSUE TITLE
Deploy Promtail without Cluster Wide Permissions

### ISSUE THREAD

**Issue by benediktwetzel** [grafana/helm-charts#1310]
I want to use Promtail without cluster-wide permissions. 
To do this, I copied the rbac files from the helm template folder and changed the `ClusterRole` to a `Role` and the `ClusterRoleBinding` to a `RoleBinding`. However, in the logs it seems that Promtail is trying to list pods at the cluser level. 

Is there a way to configure Promtail to only look at its own namespace?

Thanks a lot!

**Comment by beneiltis** [comment]
Awesome question from my name-cousin! I would be interessted in this matter too :-)

**Comment by dominik003** [comment]
I just ran into the same problem and solved it by adding the namespaces to the `kubernetes_sd_configs` inside the `scrapeConfigs`. So it should look like this:
```
kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
        - namespace1
        - namespace2
```
Since there is no configuration option for the namespaces, I think the only solution is to replace the entire scrape configuration with the customized one.
