### ISSUE TITLE
[mimir-distributed] extraEnvFrom Options for s3 secrets in mimir config file. 

### ISSUE THREAD

**Issue by brandonrjacobs** [grafana/helm-charts#1314]
Currently the only supported option is located in the Nginx values path:

```yaml

# Configuration for nginx gateway
nginx:
  # -- Environment variables to add to the nginx pods
  extraEnv: []
  # -- Environment variables from secrets or configmaps to add to the nginx pods
  extraEnvFrom: []
```

Given I am using `s3` as the `blocks_storage` I would like to set the S3 credentials as environment variables as such in the config:

```yaml
ingester:
  extraEnvFrom:
    - secretRef:
        name: s3-auth
mimir:
  config: |
    blocks_storage:
          backend: s3
          tsdb:
            dir: /data/tsdb
          bucket_store:
            sync_dir: /data/tsdb-sync
          s3:
            endpoint: <endpoint>
            bucket_name: <bucket>
            access_key_id: ${S3_ACCESS_KEY}
            secret_access_key: ${S3_ACCESS_SECRET}
            insecure: true
```
Given this configuration is needed by the `ingester` and I believe other services, is there a way for this to work with the chart? I know loki-distributed has this capability and we currently do that there. Or am I missing something with the current implementation?
