### ISSUE TITLE
per-user series limit of 150000 exceeded error

### ISSUE THREAD

**Issue by WilliamCassanova** [grafana/helm-charts#1320]
This is more of a question than an actual issue:

In my first deployment of this guy using the default settings for all components I am seeing an error:
```
level=warn ts=2022-04-28T17:50:27.996176708Z caller=grpc_logging.go:38 method=/cortex.Ingester/Push duration=2.216469ms err="rpc error: code = Code(400) desc = user=wdc-01: per-user series limit of 150000 exceeded, please contact administrator to raise it (per-ingester local limit: 150000)" msg=gRPC
```

In my second attempt I increased the number of replicas and resources for the ingester, compactor, distributor, and store_gatway such that each had a minimum of 1 cpu and 1Gi of memory.  The replicas are:
- ingester --> 6
- querier --> 2
- store_gateway --> 2
- distributor --> 2

The error I am now seeing show a reduction in the number of `per-ingester` local limits but not sure I am actually attacking the problem correctly.
```
evel=warn ts=2022-04-28T18:53:27.370191335Z caller=grpc_logging.go:38 duration=1.658678ms method=/cortex.Ingester/Push err="rpc error: code = Code(400) desc = user=wdc-01: per-user series limit of 150000 exceeded, please contact administrator to raise it (per-ingester local limit: 75000)" msg=gRPC
```

Questions:
- Will increasing the ingester even further fix this problem or essentially have no effect?
- Is the problem being caused by the sending client which in this case is `wdc-01` remote-writing too many metrics or is this a problem that is internal to my mimir-cluster which is the recipient of these remote-writes?

**Comment by WilliamCassanova** [comment]
It may be related to: https://grafana.com/docs/grafana-cloud/metrics-prometheus/errors-monitoring/#per-user-series-limit

**Comment by WilliamCassanova** [comment]
Closing.  I worked around with relabeling in the mimir clients.

**Comment by nxf5025** [comment]
> Closing. I worked around with relabeling in the mimir clients.

@WilliamCassanova - Can you elaborate a bit? I just hit this same issue.

**Comment by sarasensible** [comment]
@nxf5025  I don't know if this is the correct solution but I was able to get this to work by raising the global series per user limit:

```
mimir:
  # -- Config file for Grafana Mimir, enables templates. Needs to be copied in full for modifications.
  config: |
    limits:
      max_global_series_per_user: 1000000
```

In my case we are only using the one user `anonymous` so allowing it to post all series data works for us.  I would welcome feedback though on the "right" way to do this.

**Comment by WilliamCassanova** [comment]
Let me see if I can elaborate.  First some assumptions:
- We have a cluster named `foo`.
- `foo` would deployed to multiple data centers within a given region, for example, us-east-01 and us-east-02. 
- `foo` might also be deployed to multiple regions, for example, us-east, us-west, London, Singapore, etc.
- In each of those there are multiple namespaces.  Some are standard kubernetes and some are namespaces we create specifically for an application or multiple dependent applications.

In some way shape or form we needed to have something that is globally aggregated for total traffic estimates for these applications.  We also needed to be able to individually look at each cluster to determine if there was a regional outage or perhaps a problem with a given data-center.  To make it such that all metrics showed up under a given tenant I assigned all of them the same `tenant-id` in `kube-prometheus-stack` in the  `prometheus.prometheusSpec.remoteWrite.headers.X-Scope-OrgID` key as `foo`.

The main issue was that all of these clusters are quite large and sending lots of metrics from all namespaces....To attempt to fix the problem I limited to a few of the more important namespaces in the regex below:

```
  prometheus:
    prometheusSpec:
      externalLabels: < FOR EACH CLUSTER BUT DEPLOYED to EACH INDEPENDENTLY >
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      remoteWrite:
      - url: <YOUR-MIMIR-CLUSTER-HERE>
        writeRelabelConfigs:
        # Create new label with values of namespace
        - sourceLabels: [namespace]
          targetLabel: export_namespace
        - sourceLabels: [export_namespace]
          regex: APP-1-NS|APP-2-NS|APP-3-NS # EACH NAMESPACE NEEDED HERE
          action: keep 
        headers:
          X-Scope-OrgID: foo # SAME FOR ALL CLUSTERS
```



A few open questions I have:

1. Let's assume I was originally storing my metrics within prometheus itself with either block storage, file storage or perhaps in empty-dir.  In that storage medium let's assume I have 7 days of metrics.  When you deploy the prometheus-operator with remote_writes does it replay the last 7 days? or replay just the things that are currently arriving when it first comes alive?
2. Same question as above...But let's add Thanos into the equation.  Let's assume I have been storing long-term metrics in Thanos for 10 months?  Hopefully all of this does not get replayed back across remote_write.
3. Let's assume that I am also running `Loki` and it is set up as part of the prometheus-operator.  Is it safe the assume that the potentially large set of files being `promtailed` do NOT get sent or does it based on my regex expression?  As an example, let assume that something in the `APP-1` namespace is spewing lots of `INFO` or `DEBUG` messages.  Do all of those get sent?  If so, I will potentially have to refine my regex further if possible.

**Comment by WilliamCassanova** [comment]
There hasn't been any responses to the questions above.  Closing

**Comment by luvpreetsingh** [comment]
So, still confused on this. I know what to do but not sure where. I am using mimr helm chart and added the below config

```
runtimeConfig:
  overrides:
    anonymous:
      max_global_series_per_user: 0
```

As far as I know, this will remove all the limits. Am I doing it right? If not, what am I doing wrong?

**Comment by Otterpohl** [comment]
I fixed this by adding the following to my `values.yaml` file, note that the ingestors need to be restarted manually for this to take effect.

```
mimir:
  structuredConfig:
    limits:
      max_global_series_per_user: 1000000
```

@luvpreetsingh if its not too late try the above  😆

**Comment by shanmugara** [comment]
@Otterpohl I know this is an old thread. can you tell me how much memory resource you allocated for the ingesters for 100000 ? did you get any OOM kills after increasing the limit?

**Comment by Otterpohl** [comment]
@shanmugara I actually haven't set any memory limits (although this very much depends on your metrics) and haven't had any issues with OOM. 

One thing I would suggest is upping the pvc size of the ingester, store_gateway and compactor.

```
ingester:
  persistentVolume:
    size: 25Gi
compactor:
  persistentVolume:
    size: 25Gi
store_gateway:
  persistentVolume:
    size: 25Gi
```
