### ISSUE TITLE
metrics-generator in tempo-distributed charts

### ISSUE THREAD

**Issue by mvkrishna86** [grafana/helm-charts#1321]
May I know if metrics-generator part of the tempo helm charts? I cant find it in the latest charts

**Comment by Samuron** [comment]
@mvkrishna86 hello! Were you able to resolve the issue? I would like to try metrics-generator as well but not able to find any metions of it in helm values

**Comment by mvkrishna86** [comment]
No @Samuron , I have not tried it. I am planning to upgrade my tempo to latest version, then look into this metrics-generator.

**Comment by mvkrishna86** [comment]
Here is my statefulset of metrics-generator:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: tempo-distributed
    meta.helm.sh/release-namespace: observability
  labels:
    app.kubernetes.io/component: metrics-generator
    app.kubernetes.io/instance: tempo-distributed
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/version: 1.3.1
    helm.sh/chart: tempo-distributed-0.15.2
    helm.toolkit.fluxcd.io/name: tempo
    helm.toolkit.fluxcd.io/namespace: observability
  name: tempo-metrics-generator
  namespace: observability
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics-generator
      app.kubernetes.io/instance: tempo-distributed
      app.kubernetes.io/name: tempo-distributed
  serviceName: metrics-generator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: metrics-generator
        app.kubernetes.io/instance: tempo-distributed
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: tempo-distributed
        app.kubernetes.io/version: 1.3.1
        helm.sh/chart: tempo-distributed-0.15.2
        tempo-gossip-member: "true"
    spec:
      containers:
        - args:
            - -target=metrics-generator
            - -config.file=/conf/tempo.yaml
          image: public.ecr.aws/nslhub/tempo:1.4.1
          imagePullPolicy: Always
          name: metrics-generator
          ports:
            - containerPort: 9095
              name: grpc
              protocol: TCP
            - containerPort: 7946
              name: http-memberlist
              protocol: TCP
            - containerPort: 3100
              name: http
              protocol: TCP
            - containerPort: 3200
              name: svcport
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
            requests:
              cpu: "2"
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /conf
              name: tempo-conf
            - mountPath: /var/tempo
              name: data
      dnsPolicy: ClusterFirst
      nodeSelector:
        workload: tempo
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: tempo
      serviceAccountName: tempo
      terminationGracePeriodSeconds: 30
      tolerations:
        - key: tempo
          operator: Exists
      volumes:
        - configMap:
            defaultMode: 420
            name: tempo
          name: tempo-conf
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: ebs-sc
        volumeMode: Filesystem
```


```
      metrics_generator_enabled: true

      metrics_generator:
        ring:
          kvstore:
            store: memberlist
        processor:
          service_graphs:
            max_items: 20000
            dimensions: ['cluster']
          span_metrics:
            dimensions: ['cluster']
        storage:
          path: /var/tempo/wal
          remote_write:
            - url: http://cortex/api/v1/push
              headers:
                x-scope-orgid: operations
```
