### ISSUE TITLE
Loki in Kubernetes cluster processes logs slowly

### ISSUE THREAD

**Issue by vetalfw** [grafana/helm-charts#1322]
I have an Azure Kubernetes cluster. I use Loki to collect logs. I install Loki with the command below:

`helm upgrade --install loki grafana/loki-stack --namespace tms-monitor --set grafana.enabled=true,prometheus.enabled=true,prometheus.alertmanager.persistentVolume.enabled=false,prometheus.server.persistentVolume.enabled=false,loki.persistence.enabled=true,loki.persistence.storageClassName=default,loki.persistence.size=100Gi`

On Dev, the configuration works fine. But in production, the logs began to appear with a delay of 10 - 20 minutes.
I did testing. And for example when launching 40 thousand requests to the service, I see that the processing of about 15 thousand requests goes well and then problems begin. As if not enough handlers.

I see only one error in Loki's logs

`Code(429) desc = Maximum active stream limit exceeded, reduce the number of active streams, or contact your Loki administrator to see if the limit can be increased`
Could you please write me what to change in the settings to improve the output of the logs. Thanks

**Comment by alexandre1984rj** [comment]
I had the same problem and solved increasing those parameters:
ingestion_rate_mb
per_stream_rate_limit
ingestion_burst_size_mb
https://grafana.com/docs/loki/latest/configuration/#limits_config

**Comment by vetalfw** [comment]
@alexandre1984rj thanks for your answer. I have set the following values but I see that there is a delay.
`
limits_config:
  enforce_metric_name: false
  ingestion_burst_size_mb: 20
  ingestion_rate_mb: 100
  per_stream_rate_limit: 100
  reject_old_samples: true
  reject_old_samples_max_age: 168h
`
Could you please send an example of your settings or perhaps correct mine?
Thanks and have a nice day.

**Comment by alexandre1984rj** [comment]
Hi @vetalfw my config is like that:
```
limits_config:
      ingestion_rate_strategy: "local"
      enforce_metric_name: false
      split_queries_by_interval: 1h
      retention_period: 168h
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      ingestion_rate_mb: 100
      per_stream_rate_limit: 100MB
      ingestion_burst_size_mb: 100
```
