### ISSUE TITLE
Importing dashboard

### ISSUE THREAD

**Issue by mlorenzo92** [grafana/helm-charts#1330]
Hello team
I can't understand how the dashboard import works. Today I am using the "main" branch. I currently have a legacy grafana which imports all the dashboards and now I simply want to upload it to my grafana deployed in k8s with helm configuring my values.yaml where necessary without deleting the dashboards that are automatically displayed. Someone could help me?

**Comment by Atom7k-4** [comment]
Do you want to deploy the with helm or do you want to import them via your browser?

**Comment by kaykhancheckpoint** [comment]
@Atom7k-4 I think i have a related question https://github.com/grafana/helm-charts/issues/1385

I want to be able to deploy grafana with dashboards pre-installed via configuring helm. I have a specific grafana dashboard id i have taken from the grafana website. Is there some way to plugin that dashboard id?

**Comment by mlorenzo92** [comment]
Hello good afternoon, thank you for your answers. I will tell you the solution:
The first thing I did was clone the repository and build my own helm to be able to import my dashboards through yaml inside the dashboard. The problem I had is that I had so many dashboards that it exceeded 1mb and the secret was so heavy that the configuration was not applied to me.
For which inside the values file add the following:
 ```
 enabled: true
  namespaceOverride: ""
  
  persistence:
    type: pvc
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection
```

This allowed me to import my manual dashboards and save it to persistent data within my own cluster.
I hope this solution can help someone. I don't know if it's the best solution but it worked for me.
