### ISSUE TITLE
Converter for dashboards

### ISSUE THREAD

**Issue by WilliamCassanova** [grafana/helm-charts#1336]
Many folks have dashboards that are either `home-grown` or publicly available in https://grafana.com/grafana/dashboards/.

Is there some tool allowing someone to easily take a given dashboard and convert it to something that adds necessary fields such as  `cluster` to the `templating` section and then modifies each of the dependent `targets.expr` section(s) for each panel?  The `cluster` field is something that would have arrived in the Prometheus running in our `mimir` cluster via the remote_write header such as the below code section.  For one or 2 dashboards this could be done manually...But for a team that could potentially have many ( 10's, 100's, or more ) this would be a herculean effort.

```
prometheus:
  externalLabels:
    cluster: blah-blah-blah-my-cluster
  volumeClaimTemplate:
    storageClassName: < Your-Storage-Class >
  prometheusSpec:
    remoteWrite:
      url: "https://mimir.mimir-server-balh-blah-blah/api/v1/push"
      mimirHeader: "my-cluster-header"
```
