### ISSUE TITLE
[tempo-distributed] Set max_recv_msg_size_mib for the OTLP gRPC receiver 

### ISSUE THREAD

**Issue by ben-natan** [grafana/helm-charts#1348]
The chart does not allow to set `max_recv_msg_size_mib` for the OTLP gRPC receiver, which would allow to fix this issue that I have: https://github.com/grafana/tempo/issues/860. 
I was thinking about adding the value `traces.otlp.grpc.config` that would contain this [server configuration](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configgrpc/README.md) and be injected under `distributor.receivers.otlp.protocols.grpc` in the configmap.

Is this the way to go? If so I can create a PR.

**Comment by pavleec** [comment]
@ben-natan did you manage to solve it somehow?

**Comment by harshrai654** [comment]
For someone still trying to figure this out, `tempo-distributed` helm chart has a root level config `traces` where we can configure OTEL receivers.
To configure distributor like below:
```
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
          max_recv_msg_size_mib: 50
        http:
          endpoint: 0.0.0.0:4318
          max_request_body_size: 52428800
```

we need to configure the chart like this:
```
traces:
  otlp:
    grpc:
      enabled: true
      receiverConfig:
        max_recv_msg_size_mib: 50
    http:
      enabled: true
      receiverConfig:
        max_request_body_size: 52428800
```

Just overriding the global config `max_bytes_per_trace` will not help since if not configured gRPC will use [default 4MB message size limit ](https://pkg.go.dev/google.golang.org/grpc#MaxRecvMsgSize) causing traces to drop resulting in errors like:
```
level=error msg="Exporting failed. Dropping data." component_path=/ component_id=otelcol.exporter.otlp.tempo error="not retryable error: Permanent error: rpc error: code = ResourceExhausted desc = grpc: received message after decompression larger than max 4194304" dropped_items=577

```

We need to increase the default gRPC message size limit as well for trace to be accepted by distributor, the same needs to be done with other components of tempo as well.
Refer: https://grafana.com/docs/tempo/latest/troubleshooting/querying/response-too-large/#ingestion

Reference of the `traces` field's syntax: https://artifacthub.io/packages/helm/grafana/tempo-distributed/1.44.1?modal=values&path=traces

OTEL configuration docs:
- For HTTP: https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/confighttp/README.md
- For gRPC: https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configgrpc/README.md
