### ISSUE TITLE
[tempo] Allow configure the `query_frontend`

### ISSUE THREAD

**Issue by fullonic** [grafana/helm-charts#1354]
Hi!
Currently is not possible to change the `query_frontend` default values directly from the chart. And because the default value for `query_frontend.search.max_duration` is `1h1m0s`, searching for traces older than this value results in a query error:

```
Query error
range specified by start and end exceeds 1h1m0s. received start=1651828767 end=1651839567
```

The current solution is to edit the generated config map and deploy it again. However, being able to configure it directly in the chart would be nicer. Maybe, could we extend the [confimap-map template](https://github.com/grafana/helm-charts/blob/b4565658eb7f414a52b276e025213354ca0814f7/charts/tempo/templates/configmap-tempo.yaml#L25) to load the `Values.tempo.query_frontend`? 

Thanks

**Comment by nosalan** [comment]
I can see it is possible to configure `query_frontend` via values file. Here's how I set it.
```
tempo:
  enabled: true
  tempo:
    resources:
      limits:
        cpu: 2000m
        memory: 6Gi
      requests:
        cpu: 1000m
        memory: 4Gi
    searchEnabled: true
    retention: 72h
    queryFrontend:
      search:
        default_result_limit: 500
        max_result_limit: 500
        max_duration: 72h
```
