### ISSUE TITLE
missing pod labels in grafana

### ISSUE THREAD

**Issue by fragolinux** [grafana/helm-charts#1371]
hi
deployed loki-stack with a very basic helm release, i've some issues with loki not getting some of the labels... i've grafana deployed as a separate helmrelease

with this helmrelease, i just get a few labels, and never get new ones:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ${release}
  namespace: ${namespace}
spec:
  interval: 1m
  timeout: 10m
  releaseName: ${release}
  targetNamespace: ${namespace}
  test:
    enable: false # disable tests for now
    timeout: 10m
  chart:
    spec:
      # see https://artifacthub.io/packages/helm/grafana/loki-stack
      chart: loki-stack
      version: "2.6.4"
      sourceRef:
        kind: HelmRepository
        name: loki
      interval: 24h
  install:
    remediation:
      retries: 3
      remediateLastFailure: false
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: false
  values:
    loki:
      enabled: true
      image:
        tag: 2.5.0
      # podLabels:
        # k8s.twr.io/imageswap: enabled
      persistence:
        enabled: true
        storageClassName: azuredisk-retain
        size: 128Gi
      table_manager:
        retention_deletes_enabled: true
        retention_period: 168h # one week log retention
      config:
        ingester:
          wal:
            dir: /data/loki/wal

    grafana:
      enabled: false

    promtail:
      enabled: true
      image:
        tag: 2.5.0
      config:
        lokiAddress: http://loki:3100/loki/api/v1/push
```

the only way i could get actual existent labels is by adding all of this (found [online](https://community.grafana.com/t/information-is-missing-when-collecting-logs/54232/5)) just after the "lokiAddress" line in previuos helmrelease...

```
        snippets:
          pipelineStages:
            - docker: {}
          common:
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_node_name
              target_label: node_name
            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              replacement: $1
              separator: /
              source_labels:
                - namespace
                - app
              target_label: job
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - action: replace
              replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
              target_label: __path__
            - action: replace
              replacement: /var/log/pods/*$1/*.log
              regex: true/(.*)
              separator: /
              source_labels:
                - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
                - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
                - __meta_kubernetes_pod_container_name
              target_label: __path__

          # If set to true, adds an additional label for the scrape job.
          # This helps debug the Promtail config.
          addScrapeJobLabel: false

          # -- You can put here any keys that will be directly added to the config file's 'client' block.
          # @default -- empty
          extraClientConfigs: |
            basic_auth:
              username: x
              password: x
            backoff_config:
              max_period: 5m
              max_retries: 10
              min_period: 500ms
            batchsize: 1048576
            batchwait: 1s
            external_labels: {}
            timeout: 10s

          scrapeConfigs: |
            # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet for reference
            - job_name: kubernetes-pods-name
              pipeline_stages:
                - docker: {}
              kubernetes_sd_configs:
              - role: pod
              relabel_configs:
              - source_labels:
                - __meta_kubernetes_pod_label_name
                target_label: __service__
              - source_labels:
                - __meta_kubernetes_pod_node_name
                target_label: __host__
              #- action: drop
              #  regex: ""
              #  source_labels:
              #  - __service__
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - action: replace
                replacement: $1
                separator: /
                source_labels:
                - __meta_kubernetes_namespace
                - __service__
                target_label: job
              - action: replace
                source_labels:
                - __meta_kubernetes_namespace
                target_label: namespace
              - action: replace
                source_labels:
                - __meta_kubernetes_pod_name
                target_label: pod
              - action: replace
                source_labels:
                - __meta_kubernetes_pod_container_name
                target_label: container
              - replacement: /var/log/pods/*$1/*.log
                separator: /
                source_labels:
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
                target_label: __path__
            - job_name: kubernetes-pods-app
              pipeline_stages:
                - docker: {}
              kubernetes_sd_configs:
              - role: pod
              relabel_configs:
              - action: drop
                regex: .+
                source_labels:
                - __meta_kubernetes_pod_label_name
              - source_labels:
                - __meta_kubernetes_pod_label_app
                target_label: __service__
              - source_labels:
                - __meta_kubernetes_pod_node_name
                target_label: __host__
              #- action: drop
              #  regex: ""
              #  source_labels:
              #  - __service__
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - action: replace
                replacement: $1
                separator: /
                source_labels:
                - __meta_kubernetes_namespace
                - __service__
                target_label: job
              - action: replace
                source_labels:
                - __meta_kubernetes_namespace
                target_label: namespace
              - action: replace
                source_labels:
                - __meta_kubernetes_pod_name
                target_label: pod
              - action: replace
                source_labels:
                - __meta_kubernetes_pod_container_name
                target_label: container
              - replacement: /var/log/pods/*$1/*.log
                separator: /
                source_labels:
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
                target_label: __path__
            - job_name: kubernetes-pods-direct-controllers
              pipeline_stages:
                - docker: {}
              kubernetes_sd_configs:
              - role: pod
              relabel_configs:
              - action: drop
                regex: .+
                separator: ''
                source_labels:
                - __meta_kubernetes_pod_label_name
                - __meta_kubernetes_pod_label_app
              - action: drop
                regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
                source_labels:
                - __meta_kubernetes_pod_controller_name
              - source_labels:
                - __meta_kubernetes_pod_controller_name
                target_label: __service__
              - source_labels:
                - __meta_kubernetes_pod_node_name
                target_label: __host__
              #- action: drop
              #  regex: ""
              #  source_labels:
              #  - __service__
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - action: replace
                replacement: $1
                separator: /
                source_labels:
                - __meta_kubernetes_namespace
                - __service__
                target_label: job
              - action: replace
                source_labels:
                - __meta_kubernetes_namespace
                target_label: namespace
              - action: replace
                source_labels:
                - __meta_kubernetes_pod_name
                target_label: pod
              - action: replace
                source_labels:
                - __meta_kubernetes_pod_container_name
                target_label: container
              - replacement: /var/log/pods/*$1/*.log
                separator: /
                source_labels:
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
                target_label: __path__
            - job_name: kubernetes-pods-indirect-controller
              pipeline_stages:
                - docker: {}
              kubernetes_sd_configs:
              - role: pod
              relabel_configs:
              - action: drop
                regex: .+
                separator: ''
                source_labels:
                - __meta_kubernetes_pod_label_name
                - __meta_kubernetes_pod_label_app
              - action: keep
                regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
                source_labels:
                - __meta_kubernetes_pod_controller_name
              - action: replace
                regex: '([0-9a-z-.]+)-[0-9a-f]{8,10}'
                source_labels:
                - __meta_kubernetes_pod_controller_name
                target_label: __service__
              - source_labels:
                - __meta_kubernetes_pod_node_name
                target_label: __host__
              #- action: drop
              #  regex: ""
              #  source_labels:
              #  - __service__
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - action: replace
                replacement: $1
                separator: /
                source_labels:
                - __meta_kubernetes_namespace
                - __service__
                target_label: job
              - action: replace
                source_labels:
                - __meta_kubernetes_namespace
                target_label: namespace
              - action: replace
                source_labels:
                - __meta_kubernetes_pod_name
                target_label: pod
              - action: replace
                source_labels:
                - __meta_kubernetes_pod_container_name
                target_label: container
              - replacement: /var/log/pods/*$1/*.log
                separator: /
                source_labels:
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
                target_label: __path__
            - job_name: kubernetes-pods-static
              pipeline_stages:
                - docker: {}
              kubernetes_sd_configs:
              - role: pod
              relabel_configs:
              - action: drop
                regex: ''
                source_labels:
                - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
              - action: replace
                source_labels:
                - __meta_kubernetes_pod_label_component
                target_label: __service__
              - source_labels:
                - __meta_kubernetes_pod_node_name
                target_label: __host__
              #- action: drop
              #  regex: ""
              #  source_labels:
              #  - __service__
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - action: replace
                replacement: $1
                separator: /
                source_labels:
                - __meta_kubernetes_namespace
                - __service__
                target_label: job
              - action: replace
                source_labels:
                - __meta_kubernetes_namespace
                target_label: namespace
              - action: replace
                source_labels:
                - __meta_kubernetes_pod_name
                target_label: pod
              - action: replace
                source_labels:
                - __meta_kubernetes_pod_container_name
                target_label: container
              - replacement: /var/log/pods/*$1/*.log
                separator: /
                source_labels:
                - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
                - __meta_kubernetes_pod_container_name
                target_label: __path__

```

BUT, i'm not getting new labels, i just added a test pod and labeled it, i saw in promtail log:

```
level=info ts=2022-05-11T15:32:49.112327161Z caller=filetargetmanager.go:328 msg="Adding target" key="/var/log/pods/*1ac065cf-f8c7-4949-a752-ed23f5c68ce0/alpine/*.log:{container=\"alpine\", eco_mind_eu_target_node_system=\"enabled\", eco_mind_eu_target_node_user_spot=\"enab
led\", job=\"loki/\", namespace=\"loki\", paperino=\"topolino\", pippo=\"pluto\", pluto=\"pippo\", pod=\"alpine\", run=\"alpine\", topolino=\"paperino\"}"
level=info ts=2022-05-11T15:32:49.120649621Z caller=filetargetmanager.go:351 msg="Removing target" key="/var/log/pods/*1ac065cf-f8c7-4949-a752-ed23f5c68ce0/alpine/*.log:{container=\"alpine\", eco_mind_eu_target_node_system=\"enabled\", eco_mind_eu_target_node_user_spot=\"en
abled\", job=\"loki/\", namespace=\"loki\", pippo=\"pluto\", pluto=\"pippo\", pod=\"alpine\", run=\"alpine\", topolino=\"paperino\"}"
level=info ts=2022-05-11T15:32:49.129019281Z caller=filetargetmanager.go:328 msg="Adding target" key="/var/log/pods/*1ac065cf-f8c7-4949-a752-ed23f5c68ce0/alpine/*.log:{container=\"alpine\", eco_mind_eu_target_node_system=\"enabled\", eco_mind_eu_target_node_user_spot=\"enab
led\", job=\"loki/\", namespace=\"loki\", paperino=\"topolino\", pippo=\"pluto\", pluto=\"pippo\", pod=\"alpine\", run=\"alpine\", topolino=\"paperino\"}"
level=info ts=2022-05-11T15:32:49.135220726Z caller=filetargetmanager.go:351 msg="Removing target" key="/var/log/pods/*1ac065cf-f8c7-4949-a752-ed23f5c68ce0/alpine/*.log:{container=\"alpine\", eco_mind_eu_target_node_system=\"enabled\", eco_mind_eu_target_node_user_spot=\"en
abled\", job=\"loki/\", namespace=\"loki\", pippo=\"pluto\", pluto=\"pippo\", pod=\"alpine\", run=\"alpine\", topolino=\"paperino\"}"
level=info ts=2022-05-11T15:32:49.150083033Z caller=filetargetmanager.go:328 msg="Adding target" key="/var/log/pods/*1ac065cf-f8c7-4949-a752-ed23f5c68ce0/alpine/*.log:{container=\"alpine\", eco_mind_eu_target_node_system=\"enabled\", eco_mind_eu_target_node_user_spot=\"enab
led\", job=\"loki/\", namespace=\"loki\", paperino=\"topolino\", pippo=\"pluto\", pluto=\"pippo\", pod=\"alpine\", run=\"alpine\", topolino=\"paperino\"}"
level=info ts=2022-05-11T15:32:49.150913839Z caller=filetargetmanager.go:351 msg="Removing target" key="/var/log/pods/*1ac065cf-f8c7-4949-a752-ed23f5c68ce0/alpine/*.log:{container=\"alpine\", eco_mind_eu_target_node_system=\"enabled\", eco_mind_eu_target_node_user_spot=\"en
abled\", job=\"loki/\", namespace=\"loki\", pippo=\"pluto\", pluto=\"pippo\", pod=\"alpine\", run=\"alpine\", topolino=\"paperino\"}"

```

BUT they never reach loki (and so, grafana, too, which as loki as datasource):

```
curl http://loki.loki.svc.cluster.local:3100/loki/api/v1/labels
{"status":"success","data":["__name__","aadpodidbinding","acme_cert_manager_io_http01_solver","acme_cert_manager_io_http_domain","acme_cert_manager_io_http_token","alertmanager","app","app_kubernetes_io_component","app_kubernetes_io_instance","app_kubernetes_io_managed_by","app_kubernetes_io_name","app_kubernetes_io_part_of","app_kubernetes_io_version","chart","component","configAuditReport_scanner","container","control_plane","controller_revision_hash","controller_uid","eco_mind_eu_distribution","eco_mind_eu_module_role","eco_mind_eu_target_node_system","eco_mind_eu_target_node_user_spot","filename","gatekeeper_sh_operation","gatekeeper_sh_system","helm_sh_chart","heritage","job","jobLabel","job_name","k8s_app","kubernetes_azure_com_managedby","kubernetes_io_cluster_service","name","namespace","node_name","operator_prometheus_io_name","operator_prometheus_io_shard","ov_k8s_actuator_io_image","pippo","plugin_config_hash","pod","pod_template_generation","pod_template_hash","prometheus","release","resource_spec_hash","run","sidecar_istio_io_inject","starboard_resource_kind","starboard_resource_name","starboard_resource_namespace","statefulset_kubernetes_io_pod_name","stream","tier","version","vulnerabilityReport_scanner"]}

```
