### ISSUE TITLE
notifiers does not show in contact points

### ISSUE THREAD

**Issue by Atom7k-4** [grafana/helm-charts#1379]
I'm currently setting up a new Grafana with the latest version and helm chart.
I added a notifier so alerts are send to a microsoft teams channel.
The notifiers.yaml can be found in the running container in 'etc/grafana/provisioning/notifiers'

Unfortunately it does not appear in 'contact points'.

The part of the helm chart regarding notfiers looks like this

```
notifiers: 
 notifiers.yaml:
   notifiers:
   - name: sa-roemoe-notifier
     type: teams
     uid: lnc31CJGz
     org_id: 1
     is_default: true
     settings:
       url: <<myTeamsUrl>>
```
Is there something wrong with it? 
Since it already is in the running container I assume I made a mistake but I can't figure it out.

Best regards.

**Comment by Atom7k-4** [comment]
@balalopilav did you figured it out yet? I have not found a solution yet.

**Comment by EinAeffchen** [comment]
It looks like you're missing some parameters. If you deploy your grafana like this, it should end up in a crashloop, telling you that frequency is missing.

**Comment by tim-felix-lange** [comment]
@Atom7k-4, @balalopilav  & @EinAeffchen : 
The issue you and me face is related to Grafana's advent of unified/NG alerting in Grafana v8.0. Provisioning has not yet been implemented for alerts/notification points unfortunately and has been postponed for some version >9.0 (https://github.com/grafana/grafana/issues/36153#issuecomment-1087597922). 
The entire discussion about provisioning notifiers can be found at https://github.com/grafana/grafana/issues/36153.

**Comment by alexweav** [comment]
@tim-felix-lange is correct - this is the legacy alerting provisioning system, in unified alerting contact points are quite different. This should be done very soon, [the PR for .yaml alert rules is already open ](https://github.com/grafana/grafana/pull/51635/files)and the other types like contact points are following very closely behind.

**Comment by maxime-menard** [comment]
@alexweav above PR is merged, but issue is still there. Any news on this ? Thanks !

**Comment by alexweav** [comment]
@maxime-menard We have full .yaml file support for provisioning Unified Alerting resources now. (FYI @JohnnyQQQQ)

Unified Alerting won't know to understand the resources from Legacy alerting. You'll need to provision a contact point, there is an example here:
https://grafana.com/docs/grafana/latest/administration/provisioning/#contact-points

And, it will need to go under the `provisioning/alerting` directory:
https://grafana.com/docs/grafana/latest/administration/provisioning/#alerting

**Comment by maxime-menard** [comment]
@alexweav is that also configurable through the helm chart ?

**Comment by yuliyantsvetkov** [comment]
Asking the same question. Notifiers won't work. I don't see sidecar for that, but there is a `grafana-sc-notifier` one which does nothing.

**Comment by alexweav** [comment]
Unified Alerting is a fully different subsystem - legacy notifiers are deprecated, in favor of Contact Points. These can still be provisioned through the .yaml file, but your file will need to be updated to create contact points. See here: https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/#provision-contact-points

**Comment by hpl002** [comment]
Had success with the following

```yaml
alerting:
  contactpoints.yaml:
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: mycp
        receivers:
          - uid: opsgen01
            type: opsgenie
            settings:
              apiKey: redacted
              apiUrl: https://api.opsgenie.com/v2/alerts
              autoClose: true
              overridePriority: false
              sendTagsAs: both
```
Ref https://github.com/grafana/helm-charts/blob/878071f78f10b733d29b876b1bbfaf444fad5815/charts/grafana/values.yaml#L593-L608
