### ISSUE TITLE
[loki-stack] Promtail fails to push logs to loki after upgrade

### ISSUE THREAD

**Issue by hatzlj** [grafana/helm-charts#1383]
After upgrading loki-stack from 2.4.1 to 2.6.4 the promtail daemonsets start to fail pushing logs to loki with the following error
```
level=warn ts=2022-05-18T03:37:09.360423983Z caller=client.go:349 component=client host=myloki:3100 msg="error sending batch, will retry" status=-1 error="Post \"http://myloki:3100/loki/api/v1/push\": dial tcp: lookup myloki on 10.100.0.10:53: no such host"
```

This seems to be related to the [following line](https://github.com/grafana/helm-charts/blob/9de374802e38d88c119f2d61bfa6c87856b84f51/charts/loki-stack/values.yaml#L8), which specifies
```yaml
promtail
  config:
    lokiAddress: http://{{ .Release.Name }}:3100/loki/api/v1/push
```
as the default value for `lokiAddress` whereas it should be rather (mind the `-loki`)
```yaml
promtail:
  config:
    lokiAddress: http://{{ .Release.Name }}-loki:3100/loki/api/v1/push
```
to reference the k8s service for loki that gets created by the loki helm chart, see https://github.com/grafana/helm-charts/blob/9bce229569edc2035c39249ae818f1003331b821/charts/loki/templates/_helpers.tpl#L22

Current workaround is to specify the latter config in an override.yml when installing/upgrading via helm.
