### ISSUE TITLE
[loki-distributed] Memcached is not used even if enabled in helm

### ISSUE THREAD

**Issue by kovaxur** [grafana/helm-charts#1386]
Hi,
If I enabled the memcached caches in the Loki-distributed helm's values.yml, it only creates the memcached pods, however Loki will not start to use it.

If I manually set the host in the configuration of the memcached_client, it works as expected, for example:

```        
storage_config:
  index_queries_cache_config:
    memcached_client:
      consistent_hash: true
      host: loki-loki-distributed-memcached-index-queries.XXX.svc.cluster.local
      service: http
```
