### ISSUE TITLE
Setting preferences via chart values in Grafana chart

### ISSUE THREAD

**Issue by SoerenHenning** [grafana/helm-charts#139]
Is it possible to set preferences such as UI theme or organisation name in the values.yaml file the Grafana chart?

If not, would it make sense or is possible to add it as a feature?

**Comment by SoerenHenning** [comment]
I would a solution to set at least the UI theme:

```yaml
  grafana.ini:
    users:
      default_theme: light
```
