### ISSUE TITLE
Problem in promtail helm installation

### ISSUE THREAD

**Issue by sam75m** [grafana/helm-charts#1392]
I edited values.yaml and added basic auth to reach my remote loki server in this format:
```
  extraScrapeConfigs: |
      basic_auth:
         username: lokiuser
         password: secret
```
but pods are crashing with this error:
```
Unable to parse config: /etc/promtail/promtail.yaml: yaml: line 77: did not find expected '-' indicator
```
list of pods:
```
NAME             READY   STATUS              RESTARTS   AGE
promtail-nqpxn   0/1     CrashLoopBackOff   3          98s
promtail-qnh5x   0/1     CrashLoopBackOff   3          99s
```

**Comment by kucerakk** [comment]
I experience the same issue. The problem is, that in the following update the extra client config part became an array/list (it used to be a string):
https://github.com/grafana/helm-charts/commit/5a990ab9883bf2c001204cf9bc867b6a286f4363

If I understand it correctly according to the config from https://grafana.com/docs/loki/latest/clients/promtail/configuration/ the clients part can now contain multiple loki instances as list elements.  However in the ```values.yaml``` the url part is already one element of the list + It adds the ```extraClientConfigs``` as additional elements to the ```clients``` list.

```
 clients:
      - url: {{ tpl .Values.config.lokiAddress . }}
      {{- with .Values.config.snippets.extraClientConfigs }}
      {{- toYaml . | nindent 2 }}
      {{- end }}
```

resulting to:
``` 
clients:
  - url: https://loki
  - basic_auth:
       username: lokiuser
       password: secret
```

If you keep passing the values to the chart as dictionary, then the resulting config looks like:
```
clients:
  - url: https://loki
  basic_auth:
       username: lokiuser
       password: secret
```

CORRECT config should look like:
```
clients:
  - url: https://loki
    basic_auth:
       username: lokiuser
       password: secret
  - url: https://loki2
    basic_auth:
       username: lokiuser
       password: secret
```

pls correct me If I am wrong.
