### ISSUE TITLE
[mimir-distributed] I don't see a way to configure results cache used by query-frontend

### ISSUE THREAD

**Issue by pstibrany** [grafana/helm-charts#1403]
I've found that I can enable chunks, metadata and index caches by:

```
memcached:
  enabled: true

memcached-metadata:
  enabled: true

memcached-queries:
  enabled: true
```

But I don't see a way to enable results-cache, which is used by query-frontend.
