### ISSUE TITLE
[loki-simple-scalable-1.0.0] Cannot start 'loki-read'

### ISSUE THREAD

**Issue by aaron0609** [grafana/helm-charts#1408]
Hi,

I found some strange errors while deploying loki-simple-scalable version 1.0.0
loki-gateway & loki-write all seems good, but loki-read keeps failing with following logs:
```
root# kubectl logs loki-read-0 -n blueprint
level=info ts=2022-05-24T06:28:41.865051511Z caller=main.go:106 msg="Starting Loki" version="(version=2.5.0, branch=HEAD, revision=2d9d0ee23)"
level=warn ts=2022-05-24T06:28:41.865143812Z caller=experimental.go:20 msg="experimental feature in use" feature="Azure Blob Storage"
level=info ts=2022-05-24T06:28:41.865588415Z caller=server.go:260 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=warn ts=2022-05-24T06:28:41.865808916Z caller=experimental.go:20 msg="experimental feature in use" feature="Azure Blob Storage"
level=info ts=2022-05-24T06:28:41.866484921Z caller=memberlist_client.go:394 msg="Using memberlist cluster node name" name=loki-read-0-9bbcc6ef
level=warn ts=2022-05-24T06:28:41.866644722Z caller=experimental.go:20 msg="experimental feature in use" feature="Azure Blob Storage"
level=error ts=2022-05-24T06:28:41.866774523Z caller=log.go:100 msg="error running loki" err="mkdir : no such file or directory\nerror initialising module: compactor\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:339\nmain.main\n\t/src/loki/cmd/loki/main.go:108\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"
```
And here is my settings I passed to values.yaml:
```
loki:
  containerSecurityContext:
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - ALL
    allowPrivilegeEscalation: true

  podSecurityContext:
    fsGroup: 0
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0

  config: |
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    memberlist:
      join_members:
      - {{ include "loki.fullname" . }}-memberlist

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 15m

    schema_config:
      configs:
      - from: "2020-12-11"
        store: boltdb-shipper
        object_store: azure
        schema: v11
        index:
          prefix: index_
          period: 24h
        chunks:
          prefix: chunks_
          period: 24h

    ruler:
      storage:
        type: local
        local:
          directory: /var/rules
      rule_path: /var/scratch
      alertmanager_url: http://prometheus-alertmanager.monitoring:9093
      ring:
        kvstore:
          store: inmemory

    storage_config:
      azure:
        account_name: STORAGE_ACCOUNT_NAME
        account_key: STORAGE_ACCOUNT_KEY
        container_name: loki-logs
        environment: AzureChinaCloud
        request_timeout: 0
      boltdb_shipper:
        active_index_directory: /var/loki/index
        shared_store: azure
        cache_ttl: 24h
        cache_location: /var/loki/boltdb-cache
      filesystem:
        directory: /var/loki/chunks
```
