### ISSUE TITLE
[grafana] PersistentVolumeClaim is not bound

### ISSUE THREAD

**Issue by Mirdrack** [grafana/helm-charts#1413]
# PersistentVolumeClaim is not bound

## Description of the issue:
I'm installing grafana through the `prometheus-community/kube-prometheus-stack` enabling grafana on the values file on a GKE cluster.

## Configuration: 
Values files for the chart has these values related to grafana configuration:
```
grafana:
  enabled: true
  namespaceOverride: ""
  deploymentStrategy:
    type: Recreate

  persistence:
    enabled: true
    type: pvc
    storageClassName: default
    accessModes:
    - ReadWriteOnce
    size: 4Gi
    finalizers:
    - kubernetes.io/pvc-protection
```

## Expected behaviour: 
Get a successful install

## Actual behaviour:
Timeout due to this error:
```
ready.go:268: [debug] PersistentVolumeClaim is not bound: prometheus/prometheus-grafana
``` 

## Notes and observations
* It seems like there is missing the `pv` to bind the `pvc` but the documentation doesn't provide any information about this or gives a warning about create the `pv` previous to the installation of the chart.
* I'm using the default  for the `storageClassName` but not sure if this change based on the cloud provider, documentation doesn't have any info about this.

Thanks!
