### ISSUE TITLE
chunksDirectory and rulesDirectory variable name is error!

### ISSUE THREAD

**Issue by liuxuzxx** [grafana/helm-charts#1415]
when I use create loki-simle-scalable use loki.storage.type:local then loki ConfigMap chunks_directory and rules_directory is null!

values.yaml:
```yaml
loki:
    storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    type: s3
    //......
    local:
      chunks_directory: /var/loki/chunks  
      rules_directory: /var/loki/rules
```

_helpers.tpl:
```yaml
{{- with .Values.loki.storage.local }}
filesystem:
  chunks_directory: {{ .chunksDirectory }}  //the values.yaml loki.storage.local.chunksDirectory and loki.storage.local.rulesDirectory is not exists!
  rules_directory: {{ .rulesDirectory }}
{{- end -}}
```

**Comment by Artemigos** [comment]
I ran into this as well when I just override the storage type:

```yaml
loki:
  storage:
    type: local
```

The resulting config is this:

```yaml
auth_enabled: false
common:
  path_prefix: /var/loki
  replication_factor: 3
  storage:
    filesystem:
      chunks_directory: null
      rules_directory: null
limits_config:
  enforce_metric_name: false
  max_cache_freshness_per_query: 10m
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  split_queries_by_interval: 15m
memberlist:
  join_members:
  - loki-memberlist
schema_config:
  configs:
  - from: "2020-09-07"
    index:
      period: 24h
      prefix: loki_index_
    object_store: filesystem
    schema: v11
    store: boltdb-shipper
server:
  grpc_listen_port: 9095
  http_listen_port: 3100
```

Specifically this part is a problem:

```yaml
      chunks_directory: null
      rules_directory: null
```

It also can't be overridden, because it's not a value (unless I'm misunderstanding Helm, TBF I'm fairly new to this).

**Comment by liuxuzxx** [comment]
@Artemigos I use this is ok!

rewrite-values.yaml
```yaml
loki:
  authEnabled: false
  storage:
    type: local
    local:
      chunksDirectory: /var/loki/chunks
      rulesDirectory: /var/loki/rules
```

the bash command is:
```bash
helm install loki-simple-scalabel -f rewrite-values.yaml   grafana/loki-simple-scalable -n logs
```

**Comment by Artemigos** [comment]
Ah, I see, I didn't realize that the `{{- with .Values.loki.storage.local }}` section in the template effectively `cd`s into that part of the tree. Thank you for the workaround :smile:

**Comment by liuxuzxx** [comment]
应该是作者这个地方的变量名字写错了，很多人可能使用的是s3这种服务，所以local这种形式的问题很少发现

**Comment by trevorwhitney** [comment]
yikes, sorry for the typo. looks like it will be fixed soon!

**Comment by liuxuzxx** [comment]
OK!
Now we use huawei cloud ,and the pvc accessModes must be ReadWriteMany,but:the loki statefulset's accessModes is: ReadWriteOnce, no template variable can replace it!

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "loki.writeFullname" . }}
  labels:
    {{- include "loki.writeLabels" . | nindent 4 }}
    app.kubernetes.io/part-of: memberlist
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce   //here
```
