### ISSUE TITLE
[loki-stack][loki] Allow storage_config to be imported from secret

### ISSUE THREAD

**Issue by everspader** [grafana/helm-charts#1439]
At the moment in `loki` helm chart the [storage_config](https://github.com/grafana/helm-charts/blob/main/charts/loki/values.yaml#L95) is loaded from the values. This means that if I want to have an external storage configuration, such as Azure Blob Storage, which requires an Access Key, I would need to have this key in plain text in the values file and committed to git. Needless to say this is not a good idea.

There is also the option to use [existingSecret](https://github.com/grafana/helm-charts/blob/main/charts/loki/values.yaml#L50) in the values file to pass the name of a secret that contains the entire configuration of Loki. Despite this being a safe way to pass the key, it is not practical for configuration changes because a change in configuration means a change in the secret and consequently a restart of the Loki pod. And because the configuration is in a secret it can't also be committed to git, not very GitOpsy.

I wonder if there is a way to use a secret just for the external storage configuration, something similar as it's done in [Thanos helm chart](https://github.com/bitnami/charts/blob/master/bitnami/thanos/values.yaml#L84) where only the object storage configuration is loaded from a a secret and not the entire configuration?

**Comment by JWilson45** [comment]
There is! It's not very well documented but by default if values for the Access Key and Secret are blank Loki will use environment variables.

For AWS those environment variables are:
```
AWS_ACCESS_KEY
AWS_SECRET_KEY
```

I didn't use Azure but I'm sure its the same.... but that's the fancy way to do it. There's another way which allows you to use environment variables anywhere you want in the values files.

Under each service there should be a heading called **extraArgs** (I'm coming from loki-distributed)

This allows environment variables to be used in values files:
```
extraArgs:
    - -config.expand-env=true
```

To import a secret:
```
extraEnv:
  # -- Environment variables from secrets or configmaps to add to the ingester pods
    - name: ENV_VARIABLE_NAME
      valueFrom:
        secretKeyRef:
          key: secretKey
          name: secretName
    - name: ENV_VARIABLE_NAME
      valueFrom:
        secretKeyRef:
          key: secretKey
          name: secretName
    ...
```

To reference the variable in the config:

```
${ENV_VARIABLE_NAME}
```

Hope this helps!

**Comment by trevorwhitney** [comment]
Glad you found the workaround! This is how we provide these credentials on our own deployments as well, via env vars that are populated from secrets. I do think it might be nice to expose `-config.expand-env` through a toggle in the `values.yaml`, but otherwise I would agree with the way you solved this, and wouldn't want to add any more complication to the `values.yaml` which already has so many options. Please re-open if you disagree or think any other improvements might be necessary. Thanks!

**Comment by everspader** [comment]
@JWilson45 oh this is great. I couldn't find a default value for the Azure keys but using it as environment variable with the extra arg solves the problem. I did find it documented in Grafana's Loki oficial documentation [here](https://grafana.com/docs/loki/latest/configuration/#use-environment-variables-in-the-configuration) but it would be nice to have it more explicit on the charts docs I guess.
Anyway, thank you for this!

**Comment by everspader** [comment]
@JWilson45 I followed your steps with `loki-distributed` and after restarting the pod I inspected the config file with
```
cat /etc/loki/config/config.yaml
```
And I don't see the env variables replaced but I think they should right?
```
storage_config:
  azure:
    account_key: ${AZURE_ACCOUNT_KEY}
    account_name: ${AZURE_ACCOUNT_NAME}
```
The `extraArg` is also added in querier and ingester:
```
containers:
    - args:
        - '-config.file=/etc/loki/config/config.yaml'
        - '-target=querier'
        - '-config.expand-env=true'
```
I `echo`ed both variables and they are correct. Any ideas?
