### ISSUE TITLE
Default value not working for extraConfigmapMounts subPath

### ISSUE THREAD

**Issue by itsjusth** [grafana/helm-charts#1446]
Issue exists in this file:
https://github.com/grafana/helm-charts/blob/84f7fc974fbf2e5a097e4af4fa92735b0dc3d0d4/charts/grafana/templates/_pod.tpl#L423-L428

My extra configmaps looked like a collection of these dashboard templates (no subPath):
``` yaml
- name: templateDashboard1
  mountPath: /var/lib/grafana/dashboards/dashboard-templates/templateDashboard1
  configMap: templateDashboard1
```

My last chart version was 6.28.0 and this default value "" was working fine.  After [this change](https://github.com/grafana/helm-charts/commit/b818e2686c909b7f676adb31aa464197c4181c82), the default value is no longer working as expected.  I had to specify the blank subPath in each of my extra configmaps in order to work around this issue.
