### ISSUE TITLE
Grafana pod crashes after upgrade or restart

### ISSUE THREAD

**Issue by Subetov** [grafana/helm-charts#1451]
grafana chart version: 6.29.6
k8s vesrion: 1.21.4

Grafana pod crashes after upgrade or restart and never become online.
Everything is fine with fresh install.
But if I trigger restart or try to upgrade helm release - getting this error:

```
│ grafana panic: New alert rules created while using unified alerting will be deleted, set force_migration=true in your grafana.ini and try again if this is okay.                                         │
│ grafana                                                                                                                                                                                                  │
│ grafana goroutine 1 [running]:                                                                                                                                                                           │
│ grafana github.com/grafana/grafana/pkg/services/sqlstore/migrations/ualert.AddDashAlertMigration(0xc000c974f0)                                                                                           │
│ grafana     /drone/src/pkg/services/sqlstore/migrations/ualert/ualert.go:78 +0x797                                                                                                                       │
│ grafana github.com/grafana/grafana/pkg/services/sqlstore/migrations.(*OSSMigrations).AddMigration(0xc00028a620, 0xc000c974f0)                                                                            │
│ grafana     /drone/src/pkg/services/sqlstore/migrations/migrations.go:58 +0x205                                                                                                                          │
│ grafana github.com/grafana/grafana/pkg/services/sqlstore.(*SQLStore).Migrate(0xc000232300, 0x0)                                                                                                          │
│ grafana     /drone/src/pkg/services/sqlstore/sqlstore.go:135 +0x6f                                                                                                                                       │
│ grafana github.com/grafana/grafana/pkg/services/sqlstore.ProvideService(0xc000d00000, 0x18, {0x36e67e0, 0x5752738}, {0x370c300, 0xc000c970e0})                                                           │
│ grafana     /drone/src/pkg/services/sqlstore/sqlstore.go:67 +0xdc                                                                                                                                        │
│ grafana github.com/grafana/grafana/pkg/server.Initialize({{0x7ffc83eb2c4d, 0x18}, {0x7ffc83eb2c31, 0x12}, {0xc0001a8040, 0x5, 0x5}}, {{0x0, 0x0}, {0x0, ...}, ...}, ...)                                 │
│ grafana     /drone/src/pkg/server/wire_gen.go:147 +0x1b6                                                                                                                                                 │
│ grafana github.com/grafana/grafana/pkg/cmd/grafana-server/commands.executeServer({0x7ffc83eb2c4d, 0x18}, {0x7ffc83eb2c31, 0x12}, {0x0, 0x0}, {0x7ffc83eb2c72, 0x6}, 0x0, {{0x3667e20, ...}, ...})        │
│ grafana     /drone/src/pkg/cmd/grafana-server/commands/cli.go:170 +0x625                                                                                                                                 │
│ grafana github.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer({{0x3667e20, 0x5}, {0x3669770, 0xa}, {0x3667e18, 0x4}, {0x3669760, 0xa}})                                                   │
│ grafana     /drone/src/pkg/cmd/grafana-server/commands/cli.go:107 +0x785                                                                                                                                 │
│ grafana main.main()                                                                                                                                                                                      │
│ grafana     /drone/src/pkg/cmd/grafana-server/main.go:16 +0xc5
```

**Comment by Subetov** [comment]
I have noticed behavior described above in all versions since 6.29.3
What is very strange - if you update sequentially from version 6.29.2 - everything is fine.
And one more strange thing - version 6.29.2, installation from scratch. There are Prometheus alerts:
![image](https://user-images.githubusercontent.com/5689355/172385412-f933d664-96cd-4a47-998f-76c03d5a2ca2.png)

But after I reboot the pod, the prometheus alerts disappear:
![image](https://user-images.githubusercontent.com/5689355/172385696-30d958cc-2157-4fb1-a8af-7c3ffb2d5f5d.png)

Chart values:
```
  enabled: true
  plugins: []
  grafana.ini:
    server:
      domain: ""
      root_url: "%(protocol)s://%(domain)s/grafana"
      serve_from_sub_path: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: qqq
          orgId: 1
          type: file
          options:
            path: /var/lib/grafana/dashboards/qqq
  dashboardsConfigMaps:
    ice: "qqq-dashboards"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: prometheus
          type: prometheus
          url: "http://{{ .Release.Name }}-prometheus-server"
        - name: loki
          type: loki
          url: "http://{{ .Release.Name }}-loki:3100"
          jsonData:
            manageAlerts: false
```
