### ISSUE TITLE
Volume Multi-Attach error on helm upgrade

### ISSUE THREAD

**Issue by bensta** [grafana/helm-charts#146]
Hi all!

I am deploying Grafana on a Managed K8S instance on OVH cloud. 
When I enable persistence in the helm chart, a helm upgrade command always fails with
```
Multi-Attach error for volume "<long-volume-id>" Volume is already used by pod(s) grafana-6dbfbb76c7-zjkc2
```
Because of this error, then rolling update never progresses, as the new pod never becomes healthy. 

I (mostly) run default values for the helm chart but I am happy to provide additional info should that help. 
I use the following setup: 
Helm Chart Version: grafana-6.1.16
Grafana Version: 7.3.5
My persistence config:
``` yaml
persistence:
  type: pvc
  enabled: true
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  # annotations: {}
  finalizers:
    - kubernetes.io/pvc-protection
```
