### ISSUE TITLE
Substituting datasource for some dashboards doesn't work.

### ISSUE THREAD

**Issue by takeda** [grafana/helm-charts#1461]
When trying to import dashboards via helm chart it appears to be a hit and miss.

For example with this configuration:
```yaml
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: consul
          orgId: 1
          folder: Consul
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/consul
    dashboards:
      consul:
        consul-mesh:
          gnetId: 15859
          revision: 2
          datasource: prometheus
        consul-server:
          gnetId: 10642
          revision: 1
          datasource: prometheus
        consul-server-chinese:
          gnetId: 8919
          revision: 25
          datasource: prometheus
```
`consul-server` appears to be working correctly, while `consul-mesh` and `consul-server-chinese` have sources that are not working.

I managed to trace the issue to this `sed` command on line 83:

https://github.com/grafana/helm-charts/blob/b5c866cc612ae86bf1fb3c4bbc5b890679e5e91c/charts/grafana/templates/configmap.yaml#L83

It seems like `datasource` field can be a dictionary and the `sed` is still expecting the old format.

Is there a workaround for this issue?
