### ISSUE TITLE
[loki-simple-scalable] Bad render for custom priorityClassName on gateway deployment

### ISSUE THREAD

**Issue by parera10** [grafana/helm-charts#1467]
Try to set a custom priorityClassName for gateway (via gateway value or global value):
```
global:
  priorityClassName: cluster-logging
...
```
or
```
gateway:
  enabled: true
  ...
  priorityClassName: cluster-logging
...
```

Rendered result:
```
...
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-gateway
  labels:
    helm.sh/chart: loki-simple-scalable-1.3.0
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: "2.5.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gateway
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: loki
      app.kubernetes.io/component: gateway
  template:
    metadata:
      annotations:
        checksum/config: 2fd95a0ef9e58927035504e580dbcf900ddd46131eb9318cc63e5f0c4f5ee020
      labels:
        app.kubernetes.io/name: loki
        app.kubernetes.io/instance: loki
        app.kubernetes.io/component: gateway
    spec:
      serviceAccountName: loki
     ### HERE
      priorityClassName: cluster-loggingsecurityContext:
                           fsGroup: 101
                           runAsGroup: 101
                           runAsNonRoot: true
                           runAsUser: 101**
      terminationGracePeriodSeconds: 30
...
```
