### ISSUE TITLE
[loki-simple-scalable] Providing basic authentications causes gateway to timeout.

### ISSUE THREAD

**Issue by quentinbadoud** [grafana/helm-charts#1471]
Hi,

When I provide Basic authentication settings for the gateway, I am unable to connect le loki datastore in grafana (504 timeout). If i remove basic authentication settings I have instantly an authentication error (which is normal, i guess). See the value parameters below.

```
...
gateway:
  # -- Specifies whether the gateway should be enabled
  enabled: true
  # Gateway ingress configuration
  ingress:
    # -- Specifies whether an ingress for the gateway should be created
    enabled: true
    # -- Ingress Class Name. MAY be required for Kubernetes versions >= 1.18
    ingressClassName: nginx

    # -- Hosts configuration for the gateway ingress
    hosts:
      - host: loki-gateway.example.com
        paths:
          - path: /
            # -- pathType (e.g. ImplementationSpecific, Prefix, .. etc.) might also be required by some Ingress Controllers
            pathType: Prefix
    # -- TLS configuration for the gateway ingress
    tls:
      - secretName: loki-gateway-tls
        hosts:
          - loki-gateway.example.com
  basicAuth:
    # -- Enables basic authentication for the gateway
    enabled: true
    # -- The basic auth username for the gateway
    username: username
    # -- The basic auth password for the gateway
    password: password
```
Also here are logs of the gateway, I don't see any errors:
```
10.253.3.1 - - [09/Jun/2022:09:25:37 +0000]  200 "GET / HTTP/1.1" 2 "-" "kube-probe/1.19" "-" 
10.253.3.1 - - [09/Jun/2022:09:25:47 +0000]  200 "GET / HTTP/1.1" 2 "-" "kube-probe/1.19" "-"
10.253.3.1 - - [09/Jun/2022:09:25:57 +0000]  200 "GET / HTTP/1.1" 2 "-" "kube-probe/1.19" "-" 
```
