### ISSUE TITLE
How to update dependency helm chart value

### ISSUE THREAD

**Issue by elbek** [grafana/helm-charts#1477]
I am trying to install `loki-stack` with updated promtail values (promtail enabled), but I don't see values being applied. Here is my values file to override: 
```
config:
  snippets:
    pipelineStages:
      - expression: ".*893127398127.*"
```
Can someone helm me how to override dependency chart values?

**Comment by JWilson45** [comment]
For the loki stack I believe you need to specify which application you are targeting. For grafana its `grafana:` Promtail, `promtail:` ... etc.


so it would look something like this:

```yaml
promtail:
    config:
        snippets:
            pipelineStages:
                - expression: ".*893127398127.*"
```

then:

`helm upgrade --install loki-stack grafana/loki-stack --values <path_to_values_file>`

**Comment by JWilson45** [comment]
@elbek did this fix your issue?

**Comment by SerhiiKorolik** [comment]
Hitting the same issue.
Tried to extend Promtail config with:
```
config:
  snippets:
    pipeline_stages:
      - multiline:
         firstline: '^\w+'
         max_lines: 128
         max_wait_time: 3s
 ```
 And don't see the value in resulting secrets or configmap objects
 I believe it's because [this](https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml#L402) part is added to the actual configmap but inside we see [this](https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml#L418) line which is pointing to [this](https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml#L356) code. And for some reason it's only picking up defaults (which are already defined)
