### ISSUE TITLE
[tempo-distributed] Add remaining ingester configs

### ISSUE THREAD

**Issue by AlexDHoffer** [grafana/helm-charts#1485]
It's unfortunate to have to override the global ``config: |`` block when you want to change things like ``flush_check_period``.

The ingester's config block should read:

````
  config:
    replication_factor: []
    trace_idle_period: []
    flush_check_period: []
    max_block_bytes: []
    max_block_duration: []
    complete_block_timeout: []
````
