### ISSUE TITLE
Nginx ingress need to be annotated for live-tail feature

### ISSUE THREAD

**Issue by ysaakpr** [grafana/helm-charts#15]
the new loki logs tail will fail with the default nginx, would be great if we can add nginx ingress snippet to support the live tail feature.

related to: https://github.com/grafana/grafana/issues/19555

**Comment by fragpit** [comment]
added some ingress annotations
```yaml
metadata:
  annotations:
    nginx.org/websocket-services: loki-stack-grafana
spec:
  ingressClassName: nginx
  rules:
  - host: grafana.10.10.3.4.xip.io
    http:
      paths:
      - backend:
          service:
            name: loki-stack-grafana
            port:
              number: 3000
        path: /
        pathType: ImplementationSpecific
      - backend:
          service:
            name: loki-stack-grafana
            port:
              number: 3000
        path: /api/datasources/proxy/1/loki/api/v1/tail
        pathType: ImplementationSpecific
...
```
