### ISSUE TITLE
Dashborads config are not reloaded

### ISSUE THREAD

**Issue by jambaloq** [grafana/helm-charts#1503]
Each time when I update the dashboard in the helm values file. The UI shows the same dashboards. 

My dashboard config

```
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "defaults"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/defaults

dashboards:
  defaults:
    ## Default Dashboards
    aws-ec2:
      url: https://grafana.com/api/dashboards/11265/revisions/2/download
    aws-ebs:
      url: https://grafana.com/api/dashboards/11268/revisions/2/download
    aws-billing:
      url: https://grafana.com/api/dashboards/139/revisions/15/download
    aws-alb:
      url: https://grafana.com/api/dashboards/650/revisions/8/download
    geth-node:
      url: https://grafana.com/api/dashboards/6976/revisions/3/download
```
After first deploy it downloads the dashbroads, but when I disable a dashboared in the config and apply the chart as shown below, the UI still shows old dashboards. it does not update, so I go to grafana pod and remove the dashboard json file manually.
```
   # geth-node:
     # url: https://grafana.com/api/dashboards/6976/revisions/3/download
```
is there anything I am missing, like enableing config reloader?
