### ISSUE TITLE
Loki-simple-scalable - Storage config regarding s3 bucketnames in Readme and doc example does not align with implementation

### ISSUE THREAD

**Issue by MadsHT** [grafana/helm-charts#1533]
In the readme example for the chart [Loki-simple-scalable](https://github.com/grafana/helm-charts/tree/main/charts/loki-simple-scalable) there is an example on how to use an [s3 bucket as storage](https://github.com/grafana/helm-charts/tree/main/charts/loki-simple-scalable#configuration), in this example the bucketNames is set to `loki-data`.

```yaml
loki:
  config:
    common:
      storage:
        filesystem: null
        s3:
          endpoint: minio.minio.svc.cluster.local:9000
          insecure: true
          bucketnames: loki-data
          access_key_id: loki
          secret_access_key: supersecret
          s3forcepathstyle: true
    schema_config:
      configs:
        - from: "2020-09-07"
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            period: 24h
            prefix: loki_index_
```

But when looking at the [_helper.tpl#L129](https://github.com/grafana/helm-charts/blob/e68a0403e8d4eaeba46df61b37bbc748d1456d91/charts/loki-simple-scalable/templates/_helpers.tpl#L129) the bucketname is set to the value of `$.Values.loki.storage.bucketNames.chunks` which means that the bucketnames set in the readme would never actually be used in the config?

```tpl
{{- else if eq .Values.loki.storage.type "s3" -}}
{{- with .Values.loki.storage.s3 }}
s3:
  s3: {{ .s3 }}
  endpoint: {{ .endpoint }}
  region: {{ .region }}
  bucketnames: {{ $.Values.loki.storage.bucketNames.chunks }}
  secret_access_key: {{ .secretAccessKey }}
  access_key_id: {{ .accessKeyId }}
  s3forcepathstyle: {{ .s3ForcePathStyle }}
  insecure: {{ .insecure }}
{{- end -}}
```

The same goes for the [storage documentation](https://grafana.com/docs/loki/latest/configuration/#s3_storage_config), this also shows that we should be able to specify a list of bucketnames.

Is this working as intended?
