### ISSUE TITLE
[promtail] client urls not resolving tpl anymore after 5.0.0 upgrade

### ISSUE THREAD

**Issue by joggeli34** [grafana/helm-charts#1557]
Since the 5.0.0 upgrade, the client urls are not resolved by the "tpl" function anymore.

Therfore, it isn't working when using variables like:

```yaml
config:
  clients:
  - url: http://{{.Release.Name}}-loki:3100/loki/api/v1/push
```

The change happend in following commit: https://github.com/grafana/helm-charts/commit/199071324d9bc3bb2b3118a854af2e3782afbad2
