### ISSUE TITLE
[loki-stack] support configuring jsonData of Prometheus datasource

### ISSUE THREAD

**Issue by uqix** [grafana/helm-charts#1565]
```yaml
{{- if .Values.prometheus.enabled }}
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://{{ include "prometheus.fullname" .}}:{{ .Values.prometheus.server.service.servicePort }}{{ .Values.prometheus.server.prefixURL }}
      version: 1
      isDefault: {{ .Values.prometheus.isDefault }}
      # like this
      jsonData: {{ .Values.prometheus.datasourceJsonData}}
{{- end }}
```
