### ISSUE TITLE
[grafana] cant provision telegram notifier, chatid not found

### ISSUE THREAD

**Issue by c-yco** [grafana/helm-charts#1566]
I am trying to provision a telegram contact point using the helm chart: 

```` yaml
notifiers:
      notifiers.yaml:
        notifiers:
          - name: telegram-channel-1
            type: telegram
            uid: notifier1
            # either
            org_id: 1
            # or
            is_default: true
            send_reminder: true
            frequency: 4h
            disable_resolve_message: false
            # See `Supported Settings` section for settings supported for each
            # alert notification type.
            
            settings:
              ChatID: "${SECRET_TELEGRAM_CHAT_ID}"
              chat-id: "${SECRET_TELEGRAM_CHAT_ID}"
              chat_id: "${SECRET_TELEGRAM_CHAT_ID}"
              bottoken: "${SECRET_TELEGRAM_API_TOKEN}"
            # Secure settings that will be encrypted in the database (supported since Grafana v7.2). See `Supported Settings` section for secure settings supported for each notifier.
            secure_settings:
              bottoken: "${SECRET_TELEGRAM_API_TOKEN}"
````
As stated in the provision documentation: https://grafana.com/docs/grafana/latest/administration/provisioning/

But the grafana pod always crashed on start with: 

> Failed to start grafana. error: Alert notification provisioning error: alert validation error: Could not find Chat Id in settings                                                                             ││ Alert notification provisioning error: alert validation error: Could not find Chat Id in settings                                                                                                             ││ logger=provisioning t=2022-07-03T18:21:59.592555135Z level=error msg="Failed to provision alert notifications" error="Alert notification provisioning error: alert validation error: Could not find Chat Id i    

Version of the helmchart: 6.32
My gitops repo is here, containing the full cluster definition:  https://github.com/c-yco/k3s-homecluster/blob/main/cluster/apps/monitoring/grafana/helm-release.yaml

**Comment by mogaal** [comment]
YAML is case sensitive, following the guide [you pasted](https://grafana.com/docs/grafana/latest/administration/provisioning/) the option is called `chatid`. My working configuration is:

```yaml
notifiers:
  - name: chiguire-chismoso-telegram-bot
    type: telegram
    uid: telegram01
    org_id: 1
    is_default: true
    send_reminder: true
    frequency: 1h
    disable_resolve_message: false
    settings:
      chatid: '572978436'
      uploadImage: true
     secure_settings:
       bottoken: "123456789:XXXXXXXXX"
```

Do you mind giving it a try and letting us know if it works? I hope it helps and good luck

**Comment by c-yco** [comment]
I am aware of the case sensitivity of yaml, but thanks for the hint. 
I gave it another try today, but still no luck. Could you provide a full example from your helm chart? Which grafana version are you deploying?

I am unsure about the hierarchy in the values section of the helm chart:

```` yaml
values:    
  notifiers:
      notifiers.yaml:
        notifiers:
            - name: telegram-channel-1
              type: telegram
              uid: notifier1
              org_id: 1

              is_default: true
              send_reminder: true
              frequency: 4h
              disable_resolve_message: false
              settings:
                chatid: "${SECRET_TELEGRAM_CHAT_ID}"
              # Secure settings that will be encrypted in the database (supported since Grafana v7.2). See `Supported Settings` section for secure settings supported for each notifier.
              secure_settings:
                bottoken: "${SECRET_TELEGRAM_API_TOKEN}"
````
