### ISSUE TITLE
RequestError: send request failed\ncaused by: Delete \"https://chunks.amazonaws.com/loki_cluster_seed.json

### ISSUE THREAD

**Issue by flyerhawk** [grafana/helm-charts#1579]
I am trying to understand why Loki is trying to connect to chunks.amazonaws.com.  

I've tried several iterations to no avail.   But this is my current one..
```
common:
  replication_factor: 1
  path_prefix: /tmp/loki
  storage:
    filesystem: null
    aws:
      s3:
        #s3: https://s3.us-east-1.amazonaws.com
        bucketnames:
          chunks: loki-s3
        region: us-east-1
        s3forcepathstyle: true
```

Any help would be greatly appreciated.

**Comment by trevorwhitney** [comment]
which chart are you using?

**Comment by flyerhawk** [comment]
loki-simple-scalable

**Comment by cebidhem** [comment]
Hi @flyerhawk ,

If the version is > 1.4.0 (maybe even before but I haven't tried to deploy an earlier version during my upgrade from 0.4.0), try this in the values:
```yaml
loki:
   storage:
       bucketNames:
           chunks: loki-s3
           ruler: loki-s3
       s3:
           insecure: false
           region: us-east-1
           s3: s3://us-east-1
           s3ForcePathStyle: true
```

I had some trouble too, hope this helps!
