### ISSUE TITLE
Add option to define existing secret for Loki configuration

### ISSUE THREAD

**Issue by alex1989hu** [grafana/helm-charts#158]
**Is your feature request related to a problem? Please describe.**
If the administrator handles application on cluster in GitOps way, then it is not good practise to commit unencrypted password into version control but the current version of the chart does not support to reference pre-existing secret.

Given:  Administrator has Object Storage, Amazon S3 compatible. 
Then: Administrator creates `values.yaml` (snippet).
```yaml
loki:
  config:
    storage_config:
      aws:
        s3: https://minio_admin:mypassword@minio.foo.bar./loki
```
Then: Administrator commits into version control.
Then: Minio logon is credential leaked via Helm Chart parameters.

**Describe the solution you'd like**
Given:  Administrator has Object Storage, Amazon S3 compatible. 
Then: Administrator creates secret called `my-loki-secret`.
Then: Administrator creates `values.yaml` (snippet).

```yaml
loki:
  config:
    existingSecret: my-loki-secret
```
Then: Minio logon credential is not leaked via Helm Chart parameters.

**Describe alternatives you've considered**
This proposal add alternative solution to the current one.

**Additional context**
A lots of popular chart provide option to define pre-existing secret to set it as reference for application.

xref https://github.com/grafana/loki/issues/3042

**Comment by aledbf** [comment]
Any update on this issue?

**Comment by alex1989hu** [comment]
> Any update on this issue?

Rebased the branch if there is a little chance to get this in 👍

**Comment by haim-ari** [comment]
Is this expected to be added in next release ? 
This will help to configure Loki with GitOps tools such as `Flux2 HelmRelease` together with `Sealed-Secrets`

**Comment by laszlocph** [comment]
I have the exact usecase, and the https://github.com/grafana/helm-charts/pull/159/files PR would solve it perfectly.

**Comment by lingwooc** [comment]
FWIW this kustomize patch helps too. Although really we shouldn't be needing to work round saving creds as clear text.

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: loki
    name: loki
    release: prometheus
  name: prometheus-loki
spec:
  template:
    spec:
      volumes:
      - name: config
        secret:
          secretName: prometheus-loki-custom
```

**Comment by doug-ba** [comment]
Any update on this?

This looks like it's just waiting for a review/rebase?
https://github.com/grafana/helm-charts/pull/542

**Comment by rufreakde** [comment]
> I came up with a workaround for this that I like better than defining the entire config in a secret by using environment variables in the loki config.
> 
> https://grafana.com/docs/loki/latest/configuration/#use-environment-variables-in-the-configuration
> 
> Basically, you create a secret with your secret value(s) at the key(s) of your preference, define an environment variable for whatever secret item(s) you want to insert into config, then reference it with ${VAR} syntax in the config.
> 
> For this to work, you must set `-config.expand-env=true`
> 
> I'm running this in AliyunOSS, which is S3 compliant. Here's an example of the relevant bits:
> 
> ```
> extraArgs:
>   config.expand-env: true
> 
> env:
>   - name: OSS_ACCESS_KEY
>     valueFrom:
>       secretKeyRef:
>         name: loki-access-oss
>         key: key
>   - name: OSS_SECRET_ACCESS_KEY
>     valueFrom:
>       secretKeyRef:
>         name: loki-access-oss
>         key: secret-key
> 
> config:
>   storage_config:
>     aws:
>       s3: s3://oss-cn-hangzhou.aliyuncs.com
>       bucketnames: mybucketnames
>       access_key_id: ${OSS_ACCESS_KEY}
>       secret_access_key: ${OSS_SECRET_ACCESS_KEY}
> ```

So I found this thread but I am a little confused as to where
```
extraArgs:
  config.expand-env: true
```
is set is it inside
```
lokiCanary or write or read?:
  extraArgs:
    config.expand-env: true
```
also the same with `env`? 

PS: It is still not possible to cleanly set an existing secret in the loki helm chart...

**Comment by rufreakde** [comment]
> I came up with a workaround for this that I like better than defining the entire config in a secret by using environment variables in the loki config.
> 
> https://grafana.com/docs/loki/latest/configuration/#use-environment-variables-in-the-configuration
> 
> Basically, you create a secret with your secret value(s) at the key(s) of your preference, define an environment variable for whatever secret item(s) you want to insert into config, then reference it with ${VAR} syntax in the config.
> 
> For this to work, you must set `-config.expand-env=true`
> 
> I'm running this in AliyunOSS, which is S3 compliant. Here's an example of the relevant bits:
> 
> ```
> extraArgs:
>   config.expand-env: true
> 
> env:
>   - name: OSS_ACCESS_KEY
>     valueFrom:
>       secretKeyRef:
>         name: loki-access-oss
>         key: key
>   - name: OSS_SECRET_ACCESS_KEY
>     valueFrom:
>       secretKeyRef:
>         name: loki-access-oss
>         key: secret-key
> 
> config:
>   storage_config:
>     aws:
>       s3: s3://oss-cn-hangzhou.aliyuncs.com
>       bucketnames: mybucketnames
>       access_key_id: ${OSS_ACCESS_KEY}
>       secret_access_key: ${OSS_SECRET_ACCESS_KEY}
> ```

So I found this thread but I am a little confused as to where
```
extraArgs:
  config.expand-env: true
```
is set is it inside
```
lokiCanary or write or read?:
  extraArgs:
    config.expand-env: true
```
also the same with `env`? 

PS: It is still not possible to cleanly set an existing secret in the loki helm chart...

**Comment by rufreakde** [comment]
Okay did it similar as mentioned above but since the kustomize example did not work for me here is the solution I used:
# Note we use ArgoCD
```yaml
# enable argoCD --enable-helm kustomize plugin
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
...
  configManagementPlugins: |
    - name: kustomize-build-with-helm
      generate:
        command: [ "sh", "-c" ]
        args: [ "kustomize build --enable-helm" ]
--- # kustomization.yaml
helmCharts:
- name: loki
  version: 3.6.0
  repo: https://grafana.github.io/helm-charts
  releaseName: monitoring
  namespace: monitoring
  valuesFile: values.yaml
  valuesMerge: merge
  includeCRDs: true

patchesStrategicMerge:
- overlay/loki-read.yaml
- overlay/loki-write.yaml
--- # lok/overlay/patchExample
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki-read
spec:
  template:
    spec:
      volumes:
        - name: config
          configMap:
            $patch: delete
          secret:
            secretName: loki-custom
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki-write
spec:
  template:
    spec:
      volumes:
        - name: config
          configMap:
            $patch: delete
          secret:
            secretName: loki-custom # got fromrendered template `helm template grafana/loki -f ./loki/values.yaml > test.yaml`
---
secret is deployed seperately
```
