### ISSUE TITLE
[loki-stack] Bug: No options to configure retention

### ISSUE THREAD

**Issue by R-Studio** [grafana/helm-charts#1602]
**Bug**
The default retention_period of 30 days does not take affect with the Helm Chart "loki-stack"
[Documentation](https://grafana.com/docs/loki/latest/operations/storage/retention/): 
**If no global retention_period is specified, the default value of 744h (30days) retention is used.**

**Second Issue / Feature to configure the retention**
Unfortunately the loki-stack Helm Chart does not support to configure a retention with the values. With this bug and the "second issue" the Helm Chart "loki-stack" is a bit useless.

**Comment by zanhsieh** [comment]
@R-Studio 
Does the current pinned loki chart not support retention period? Could people who use lok-stack chart just take whatever loki chart values.yaml and put it into loki-stack values.yaml loki section?

**Comment by R-Studio** [comment]
> @R-Studio Does the current pinned loki chart not support retention period? Could people who use lok-stack chart just take whatever loki chart values.yaml and put it into loki-stack values.yaml loki section?

The "locki-stack" chart doen't support retention but the "loki-simple-scalable" support it (for example in the "loki.config" section).
I can't find a "locki-stack values.yaml" section. What do you mean with that?

**Comment by gpantanetti** [comment]
I've just changed the configuration for a *loki-stack* Helm chart deployment (release 2.6.5) and it seems that is correctly implementing the desired configuration.

An extract of my `values.yaml`:

```
[...]
loki:
  config:
    compactor:
      retention_enabled: true
      compaction_interval: 10m
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
    limits_config:
      retention_period: 31d
      retention_stream:
      - selector: '{namespace=~"sample-apps-.*"}'
        period: 1d
[...]
```
