### ISSUE TITLE
[tempo] Support all config options for Tempo metrics generator 

### ISSUE THREAD

**Issue by bilbof** [grafana/helm-charts#1621]
Currently one can't fully configure the Tempo metrics generator using all the config options at https://grafana.com/docs/tempo/latest/configuration/#metrics-generator without overriding the `config` value in values.yaml.

Could we update the values file for the two Tempo charts to support these?

```
config: |
    metrics_generator:
        ...
        registry:
          collection_interval: {{ .Values.metricsGenerator.config.registry.collection_interval }}
          stale_duration: : {{ .Values.metricsGenerator.config.registry.stale_duration }}
          ...
        processor:
          service_graphs:
            max_items: {{ .Values.metricsGenerator.config.service_graphs_max_items }}
            span_metrics:
              dimensions: {{ .Values.metricsGenerator.config.span_metrics.dimensions }} 
          ...
``` 

I'd be happy to put up a PR, just checking if there's a reason for the current config. 😄
