### ISSUE TITLE
Helm all in one command to deploy-loki-stack-loki-fluent-bit-grafana-prometheus with retention period [question]

### ISSUE THREAD

**Issue by teebu** [grafana/helm-charts#163]
Based on: https://grafana.com/docs/loki/latest/installation/helm/#deploy-loki-stack-loki-fluent-bit-grafana-prometheus

I tried to pass all the params for the entire stack. The example given is missing the retention_period, is this the right way to add it this, and how to I check? Would it be in the stateful set yaml?

```
config.table_manager.retention_deletes_enabled : true
config.table_manager.retention_period: 336h 
```

```
helm upgrade --install loki grafana/loki-stack \
  --set fluent-bit.enabled=true,promtail.enabled=false,grafana.enabled=true,prometheus.enabled=true,prometheus.alertmanager.persistentVolume.enabled=false,prometheus.server.persistentVolume.enabled=false,loki.persistence.enabled=true,loki.persistence.storageClassName=standard,loki.persistence.size=5Gi,loki.table_manager.retention_deletes_enabled=true,loki.table_manager.retention_period=336h \
  --create-namespace \
  --namespace=loki-stack
```

**Comment by Ognian** [comment]
Had the same question; opened a shell in the loki-stack-0 pod and with `cat /etc/loki/loki.yaml`you can see that the settings are there...
This is done by the StatefulSet loki-stack.

Ognian

**Comment by teebu** [comment]
Mine says: 

```
storage_config:
  boltdb_shipper:
    active_index_directory: /data/loki/boltdb-shipper-active
    cache_location: /data/loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /data/loki/chunks
table_manager:
  retention_deletes_enabled: false
```
