### ISSUE TITLE
[loki-simple-scalable] Not working with AWS IAM role instead of AccessKey/SecretAccessKey

### ISSUE THREAD

**Issue by samox73** [grafana/helm-charts#1634]
Hi, I want to change loki's access method to the IAM role/`serviceAccount` one from the more dangerous `AccessKey`/`SecretAccessKey` one. I was able to assign the pods the `serviceAccount` by supplying the value 
```yaml
serviceAccount:
  create: false
  name: serviceAccountName
```
however the pods still try to access the S3 bucket by `AccessKey` as seen in the logs:
```
level=error ts=2022-07-25T08:58:36.578100622Z caller=cached_client.go:64 msg="failed to build cache" err="InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.\n\tstatus code: 403, request id: ******", host id: ******"
```
I could not find any value to switch to `rbac` instead of the default `AccessKey` approach.

---

Helm chart version: `1.4.3`

**Comment by samox73** [comment]
This seems to be poorly documented in `loki` itself. There is a [no-creds example](https://grafana.com/docs/loki/latest/configuration/examples/#aws-basic-config-no-credsyaml)  in the doc, but for the chart one has to explicitly set
```yaml
loki:
  storage:
    s3:
      s3: s3://region/bucketname
      region: region
      endpoint: ""
      accessKeyId: ""
      secretAccessKey: ""
```
