### ISSUE TITLE
Grafana Anti Affinity

### ISSUE THREAD

**Issue by sarasensible** [grafana/helm-charts#1655]
I would like to configure Grafana for high availability as documented at https://grafana.com/docs/grafana/next/setup-grafana/set-up-for-high-availability/ .  However the Helm chart does not provide the option for configuring anti affinity to spread the pods across multiple nodes.  

Ideally this could be implemented the same way as kube-prometheus-stack where you don't have to specify the YAML but instead you can specify "hard" or "soft" and the anti affinity topology key and it will configure the antiaffinity as preferred or required.

https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L586

**Comment by sarasensible** [comment]
My bad, this is actually possible with just the `affinity` key.  

Here is the configuration I was looking for:

```
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - grafana
 ```
