### ISSUE TITLE
Tempo-distributed: disabling cache does not work

### ISSUE THREAD

**Issue by pavolloffay** [grafana/helm-charts#1666]
The following `values.yaml`

```yaml
---
memcached:
  enabled: false
search:
  enabled: true
traces:
  jaeger:
    thriftHttp:
      enabled: true
tempo:
  structuredConfig:
    query_frontend:
      search:
        max_duration: 72h0m0s
    overrides:
      ingestion_burst_size_bytes: 15000000000
      ingestion_rate_limit_bytes: 15000000000
      max_traces_per_user: 50000000
      max_bytes_per_tag_values_query: 15000000000
      # default is 5000 (5Kb), 0 means no limit
      max_search_bytes_per_trace: 0
ingester:
  replicas: 1
  config:
    replication_factor: 1

  # maximum length of time before cutting a block
  # (default: 1h)
  # change if needed to flush data to s3 earlier
  #max_block_duration:

  # maximum size of a block before cutting it
  # (default: 1073741824 = 1GB)
  #max_block_bytes:
  resources:
    requests:
      cpu: 1000m
      memory: 1500Mi
    limits:
      cpu: "1000m"
      memory: "1500Mi"
distributor:
  replicas: 1
  affinity: {}
  resources:
    requests:
      cpu: 1000m
      memory: 1500Mi
    limits:
      cpu: "1000m"
      memory: "1500Mi"
querier:
  resources:
    requests:
      cpu: 800m
      memory: 500Mi
    limits:
      cpu: "800m"
      memory: "500Mi"
queryFrontend:
  resources:
    requests:
      cpu: 200m
      memory: 120Mi
    limits:
      cpu: "200m"
      memory: "120Mi"
  query:
    resources:
      requests:
        cpu: 200m
        memory: 120Mi
      limits:
        cpu: "200m"
        memory: "120Mi"
storage:
  trace:
    cache: none # it still does not properly disable memcached in the ingester
    memcached: {}
    backend: "s3"
    s3:
      access_key: tempo
      bucket: tempo
      endpoint: minio.minio.svc:9000
      insecure: true
      secret_key: supersecret
    blocklist_poll: 5m
    wal:
      path: /var/tempo/wal
```

`storage.trace.cache` should not be set to `memcached`.
```
# Source: tempo-distributed/templates/configmap-tempo.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-cluster-tempo-distributed
  namespace: test-tempo
  labels:
    helm.sh/chart: tempo-distributed-0.21.6
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo-cluster
    app.kubernetes.io/version: "1.4.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: distributor
data:
  tempo-query.yaml: |
    backend: 127.0.0.1:3100
    
  overrides.yaml: |
    overrides: {}
    
  tempo.yaml: |
    compactor:
      compaction:
        block_retention: 48h
      ring:
        kvstore:
          store: memberlist
    distributor:
      receivers:
        jaeger:
          protocols:
            thrift_http:
              endpoint: 0.0.0.0:14268
      ring:
        kvstore:
          store: memberlist
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
        tokens_file_path: /var/tempo/tokens.json
    memberlist:
      abort_if_cluster_join_fails: false
      join_members:
      - tempo-cluster-tempo-distributed-gossip-ring
    metrics_generator_enabled: false
    multitenancy_enabled: false
    overrides:
      ingestion_burst_size_bytes: 15000000000
      ingestion_rate_limit_bytes: 15000000000
      max_bytes_per_tag_values_query: 15000000000
      max_search_bytes_per_trace: 0
      max_traces_per_user: 50000000
      per_tenant_override_config: /conf/overrides.yaml
    querier:
      frontend_worker:
        frontend_address: tempo-cluster-tempo-distributed-query-frontend-discovery:9095
    query_frontend:
      search:
        max_duration: 72h0m0s
    search_enabled: true
    server:
      grpc_server_max_recv_msg_size: 4194304
      grpc_server_max_send_msg_size: 4194304
      http_listen_port: 3100
      log_format: logfmt
      log_level: info
    storage:
      trace:
        backend: s3
        blocklist_poll: 5m
        cache: memcached
        local:
          path: /var/tempo/traces
        memcached:
          consistent_hash: true
          host: tempo-cluster-tempo-distributed-memcached
          service: memcached-client
          timeout: 500ms
        s3:
          access_key: tempo
          bucket: tempo
          endpoint: minio.minio.svc:9000
          insecure: true
          secret_key: supersecret
        wal:
          path: /var/tempo/wal
```
