### ISSUE TITLE
[loki-simple-scalable] Are PVCs really required? / Retention not working?

### ISSUE THREAD

**Issue by R-Studio** [grafana/helm-charts#1693]
## My Goal
- Run Loki only with Object Storage from MinIO, if it is possible.
- I want to run Loki scalable and easy as possible, that's why I decided to use [loki-simple-scalable](https://github.com/grafana/helm-charts/tree/main/charts/loki-simple-scalable).

## My Question
- Is it possible to run loki-simple-scalable without PVCs (only S3 from MinIO)? 
  - If yes, how does the configuration look like?
  - If no, why are PVCs required?, Which contents are saved in my PVCs?, Why are my PVCs filling up? 
- Are the retentions configured in the `compactor` and `limits_config` working with S3 or do I need to configure the retention on my MinIO Bucket? As I understand the release notes of [Loki 2.3](https://grafana.com/docs/loki/latest/release-notes/v2-3/) there is no need for external (not loki) retentions (_Loki now has the ability to apply custom retention based on stream selectors! This will allow much finer control over log retention all of which is now handled by Loki, **no longer requiring the use of object store configs for retention**._) -> If yes, how does the configuration look like?
- Just for my interest: What's the difference between configure retention in the `compactor` component and configure retention in `table manager`? In the documentation the following written: _Retention through the Table Manager is achieved by relying on the object store TTL feature, and will work for both boltdb-shipper store and chunk/index store. However retention through the Compactor is supported only with the boltdb-shipper store._ But in the section of the Table Manager it contradicts itself: _When using S3 or GCS, the bucket storing the chunks needs to have the expiry policy set correctly. For more details check S3’s documentation or GCS’s documentation._

## My current configuration
```yaml
gateway:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 80
  ingress:
    enabled: true
  resources:
    limits:
      #cpu: 50m
      memory: 30Mi
    requests:
      cpu: 5m
      memory: 15Mi

loki:
  # The value below "config" must be a string instead of a map
  config: |
    auth_enabled: false
    common:
      path_prefix: /var/loki
      storage:
        filesystem: null
        s3:
          insecure: true
          s3: http://USERNAME:PASSWORD@minio.minio.svc.cluster.local:9000/loki
          s3forcepathstyle: true
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
        shared_store: s3
    schema_config:
      configs:
        - from: "2020-09-07"
          store: boltdb-shipper
          object_store: s3
          schema: v12
          index:
            period: 24h
            prefix: index_
    limits_config:
      retention_period: 1h
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 15m
    compactor:
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
    table_manager:
      retention_deletes_enabled: true
      retention_period: 1h
    chunk_store_config:
      max_look_back_period: 1h
    query_scheduler:
      max_outstanding_requests_per_tenant: 1000
    memberlist:
      join_members:
      - loki-memberlist
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

write:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 80
  persistence:
    size: 5Gi
    storageClass: longhorn
  resources:
    limits:
      #cpu: 400m
      memory: 1200Mi # Don't decrease this limit. Loki uses enough memory to prevent dataloss (when storage backend unavailable)
    requests:
      cpu: 35m
      memory: 300Mi # Don't decrease this limit. Loki can fastly grow up in memory and this can cause OOM-Killing of other pods

read:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 80
  persistence:
    size: 1Gi
    storageClass: longhorn
  resources:
    limits:
      #cpu: 400m
      memory: 150Mi
    requests:
      cpu: 50m
      memory: 75Mi
    
serviceMonitor:
  enabled: true


monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
```

+ Environment specific Helm values:
```yaml
gateway:
  ingress:
    hosts:
    - host: loki.apps-test-1....
      paths: 
      - path: /
        pathType: ImplementationSpecific
    tls:
    - hosts: 
      - loki.apps-test-1....
      secretName: ingress-wildcard-cert
```
