### ISSUE TITLE
[grafana] Values.serviceMonitor.namespace not respected

### ISSUE THREAD

**Issue by Brice187** [grafana/helm-charts#1704]
values.yaml

```yaml
serviceMonitor:
  enabled: true
  namespace: prometheus
  path: /metrics
```

Result:

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 9.0.5
    helm.sh/chart: grafana-6.32.14
  name: grafana
  namespace: grafana
spec:
  endpoints:
  - honorLabels: true
    interval: 1m
    path: /metrics
    port: service
    scheme: http
    scrapeTimeout: 30s
  jobLabel: grafana
  namespaceSelector:
    matchNames:
    - grafana
  selector:
    matchLabels:
      app.kubernetes.io/instance: grafana
      app.kubernetes.io/name: grafana
```
