### ISSUE TITLE
[tempo-distribuited] Unable to init plugins + storage factory

### ISSUE THREAD

**Issue by sergeyshaykhullin** [grafana/helm-charts#1721]
tempo-distributed@0.24.2

```yaml
tempo:
  securityContext:
    allowPrivilegeEscalation: true
```

Seems like this is a root cause, but it is not working with privilege escalation https://github.com/grafana/helm-charts/commit/ec2cec80432b989293d01d4fbe235f82e88c1ba7

`
2022-08-23T08:42:07.034Z [ERROR] tempo-query: plugin init error: error="open /tmp/plugin3684178705: read-only file system" timestamp=2022-08-23T08:42:07.033Z
{"level":"fatal","ts":1661244127.0356429,"caller":"./main.go:107","msg":"Failed to init storage factory","error":"grpc-plugin builder failed to create a store: error attempting to connect to plugin rpc client: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol.","stacktrace":"main.main.func1\n\t./main.go:107\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.5.0/command.go:872\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.5.0/command.go:918\nmain.main\n\t./main.go:168\nruntime.main\n\truntime/proc.go:250"}
2022/08/23 08:47:12 maxprocs: Updating GOMAXPROCS=1: using minimum allowed GOMAXPROCS
`

**Comment by sergeyshaykhullin** [comment]
Fixed for me

```yaml
tempo:
  securityContext:
    allowPrivilegeEscalation: true
    readOnlyRootFilesystem: false
```
