### ISSUE TITLE
[tempo-distributed] Kubernetes clusters with both tempo and loki run the risk of adding each other to the wrong ingester ring

### ISSUE THREAD

**Issue by AlexDHoffer** [grafana/helm-charts#1752]
Seen here:

![image](https://user-images.githubusercontent.com/19369483/187561818-a3346718-813d-4f08-89b3-e905db867d1c.png)

I propose the chart offers the ability to configure the headless gossip service port, the ability to set bind_port for memberlist, and support for experimental ClusterLabels (seen here https://github.com/grafana/tempo/blob/main/vendor/github.com/grafana/dskit/kv/memberlist/memberlist_client.go#L144) so that we can avoid situations where Tempo and Loki collide with each other.

**Comment by AlexDHoffer** [comment]
This, and other ticky tacky tempo.yaml entries I've been adding, are not really necessary anymore with the introduction of the structuredConfig, i.e.:

````
tempo:
  structuredConfig:
    memberlist:
      join_members:
        - tempo-distributed-gossip-ring.tempo.svc.cluster.local:7946
      cluster_label: thanos.tempo
      cluster_label_verification_disabled: false
````
