### ISSUE TITLE
promtail: Default for "log_level" is set to debug

### ISSUE THREAD

**Issue by muffl0n** [grafana/helm-charts#176]
In https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml#L385 "log_level" is set to debug. This should be set to "info" as a sane default, additionally there should be an easy way to configure it without overwriting "config.file" like this:
```yaml
config:
  file: |
    server:
      log_level: info
      http_listen_port: {{ .Values.config.serverPort }}

    client:
      url: {{ .Values.config.lokiAddress }}

    positions:
      filename: /run/promtail/positions.yaml

    scrape_configs:
      {{- tpl .Values.config.snippets.scrapeConfigs $ | nindent 2 }}
```
