### ISSUE TITLE
[Loki-simple-scalable] S3 http_config parameter is not used

### ISSUE THREAD

**Issue by j4rj4r** [grafana/helm-charts#1762]
Hello,

I need to activate the insecure mode to access minio, so i have a chart helm with this configuration.
 
```
loki:
    storage:
      bucketNames:
        chunks: loki-chunks
        ruler: loki-ruler
        admin: loki-admin
      type: s3
      s3:
       endpoint: https://minio.<redacted>:9000
        region: default
        secretAccessKey: null
        accessKeyId: null
        s3ForcePathStyle: true
        insecure: true
        http_config:
          insecure_skip_verify: true
```

Pods launch correctly but they can't connect to minio, I have this error .
`RequestError: send request failed\ncaused by: Delete \"https://<redacted>:9000/loki-chunks/loki_cluster_seed.json\": x509: cannot validate certificate for <redacted> because it doesn't contain any IP SANs`

By editing directly the secret with "kubectl" , i realize that the http_config part has not been taken into account.  (which means that the "insecure" parameter is not used also)
I added the http_config part by editing the secret and the pods manage to communicate with minio.
Can we make the chart helm take into account the http_config part?

version: 1.8.10
