### ISSUE TITLE
[loki-simple-scalable] Tokengen job container uses hard-coded image

### ISSUE THREAD

**Issue by rgarcia6520** [grafana/helm-charts#1766]
Would be very helpful to be able to update/override the image for the `create-secret` container portion of the tokengen job via the helm-chart

eg: 
chart/values.yaml
```
enterprise:
  tokengen:
    # -- Create Secret Job Image to utilize
    image: bitnami/kubectl
```
templates/tokengen/job-tokengen.yaml
```
...
      containers:
        - name: create-secret
          image: {{ .Values.enterprise.tokengen.image }}
...
```
