### ISSUE TITLE
[loki-simple-scalable] Specify storage class does not works

### ISSUE THREAD

**Issue by adthonb** [grafana/helm-charts#1780]
I want to use my own StorageClass. I specify a value in the chart like this:

```
write:
  persistence:
    storageClass: "openebs-hostpath"
read:
  persistence:
    storageClass: "openebs-hostpath"
```

It doesn't work. The chart does not set values correctly.
