### ISSUE TITLE
[Grafana] Image renderer - Failed to send request to remote rendering service

### ISSUE THREAD

**Issue by nonamef** [grafana/helm-charts#1781]
Since CVE-2022-31176 was fixed, have not been able to get image renderer to work
```
logger=rendering renderer=http level=error msg="Failed to send request to remote rendering service" error="Get \"http://localhost:8081/render/version\": dial tcp 127.0.0.1:8081: connect: connection refused"
logger=rendering renderer=http level=info msg="Failed to refresh remote plugin version" err="failed to send request to remote rendering service: Get \"http://localhost:8081/render/version\": dial tcp 127.0.0.1:8081: connect: connection refused"
```
reference: https://grafana.com/blog/2022/08/30/security-release-new-versions-of-grafana-and-grafana-image-renderer-with-a-high-severity-security-fix-for-cve-2022-31176. 

I've tried to enable authentication using a random 40 character string with the following configuration.
```
  grafana.ini:
    rendering:
      renderer_token: qwertyuiopasdfghjklzxcvbnm
    plugin:
      grafana-image-renderer:
        auth_token: qwertyuiopasdfghjklzxcvbnm

  imageRenderer:
    enabled: true
    env:
      AUTH_TOKEN: qwertyuiopasdfghjklzxcvbnm
```

Unsure if it's not working due to missing this config?
```
[reporting]
renderer_token = your-token
```
reference: https://github.com/grafana/grafana-image-renderer/issues/367
