### ISSUE TITLE
[grafana-pod tpl] Allow CSI type for extraVolumeMounts

### ISSUE THREAD

**Issue by FireDrunk** [grafana/helm-charts#1785]
To allow mounting secrets from a CSI volume, the following code should probably be changed:

https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/_pod.tpl#L751
```yaml
{{- range .Values.extraVolumeMounts }}
  - name: {{ .name }}
    {{- if .existingClaim }}
    persistentVolumeClaim:
      claimName: {{ .existingClaim }}
    {{- else if .hostPath }}
    hostPath:
      path: {{ .hostPath }}
    {{- else }}
    emptyDir: {}
    {{- end }}
{{- end }}
```

To add a CSI mount for the Azure Keyvault CSI Driver, one should normally do:
```yaml
volumeMounts:
# Secrets
- mountPath: "/mnt/secrets/<filename>"
  name: grafana-secrets
  subPath: "<item name>"
  readOnly: true

volumes:
# Secrets
- name: grafana-secrets
  csi:
    driver: secrets-store.csi.k8s.io
    readOnly: true
    volumeAttributes:
      secretProviderClass: "grafana-env-spc"
```
(With the correct indention off course)

The `extraVolumeMounts` only allows `persistantVolumeClaim`, `hostPath` or `emptyDir` but not the `csi` type.

I've looked at `extraContainerVolumes` (https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/_pod.tpl#L768) but that doesn't seem to support the matching `volumeMount`.

My proposal would be to introduce a `.csi` boolean, which allows people to do the following example:
values.yaml
```yaml
extraVolumeMounts:
  - name: grafana-secrets
    csi: true
    data:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "grafana-env-spc"
```

and change the template to:

```yaml
{{- range .Values.extraVolumeMounts }}
  - name: {{ .name }}
    {{- if .existingClaim }}
    persistentVolumeClaim:
      claimName: {{ .existingClaim }}
    {{- else if .hostPath }}
    hostPath:
      path: {{ .hostPath }}
    {{- else if .csi }}
    csi:
      {{ .data }}
    {{- else }}
    emptyDir: {}
    {{- end }}
{{- end }}
```
