### ISSUE TITLE
[tempo-distributed] PDB templates cause allowed disruptions = 0

### ISSUE THREAD

**Issue by malnor** [grafana/helm-charts#1792]
Tempo from helmchart version 0.25.0. Kubernetes version 1.24.2.

You cannot use GitOps and have a PDB (PodDisruptionBudget) that allows disruptions with the current templates.

Our GipOps tool (FluxCD) will continuously update the manifests in the cluster if they are changed directly in the cluster (and are not updated through code). The HPA (HorizontalPodAutoscaler) will update the replicas when it scales. Meaning we cannot set replicas as that will cause a bad scaling pattern where the HPA scales up and FluxCD will scale down.

In the templates this will always results in a PDB with maxUnavailable = 0, so if a node need to restart it can't because the tempo-ingester cannot be moved as it has PDB with allowed disruptions = 0.

It would be good to have only 1 PDB template for the ingester, it is really confusing to try and figure out what you will get at this point.

Today there are these PDBs:
https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/templates/ingester/pdb.yaml

```
{{- if .Values.podDisruptionBudget -}}
apiVersion: {{ include "tempo.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "tempo.ingesterFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.ingesterLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "tempo.ingesterFullname" . }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end }}
```
and 

https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/templates/ingester/poddisruptionbudget-ingester.yaml
```
{{- if gt (int .Values.ingester.replicas) 1 }}
apiVersion: {{ include "tempo.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "tempo.ingesterFullname" . }}
  labels:
    {{- include "tempo.ingesterLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "tempo.ingesterSelectorLabels" . | nindent 6 }}
  maxUnavailable: {{ sub (.Values.ingester.replicas) (.Values.ingester.config.replication_factor) }}
{{- end }}
```

When we set prodDisruptionBudget, it will not take.

I cannot make a pull request, as I don't really understand the last PDB where replication_factor is subtracted from replicas.

At the moment, we are stuck with an unscalable tempo ingester :-/  or the nodes cannot be restarted.
