### ISSUE TITLE
Dashboard sidecar stops working after 10 minutes

### ISSUE THREAD

**Issue by PeterGerrard** [grafana/helm-charts#18]
**Describe the bug**
https://github.com/kiwigrid/k8s-sidecar/issues/85
After 10 minutes the dashboard sidecar stops receiving watch notifications

Originally posted on old repo: https://github.com/helm/charts/issues/23565

**Version of Helm and Kubernetes**:
Helm version N/A
Kubernetes 1.16.10

**Which chart**:
stable/grafana

**What happened**:
After 10 minutes the dashboard sidecar stops receiving watch notifications

**What you expected to happen**:
The sidecar to always pick up new dashboards

**How to reproduce it** (as minimally and precisely as possible):
See https://github.com/kiwigrid/k8s-sidecar/issues/85

**Comment by QaiserAli** [comment]
+1

I have the exact same issue, and after a couple of minutes sidecar stops receiving notifications on configmap changes. Also sidecar doesn't detect and import new dashboards via configmaps.

All changes to the dashboards and new dashboards appear after restarting the grafana pod or sidecar container.

**Comment by dry4ng** [comment]
Same issue.

**Comment by bergerx** [comment]
using https://github.com/OmegaVVeapon/kopf-k8s-sidecar instead of kiwigrid/k8s-sidecar may address the issue, here is a comment from @djsly indicating success with that one: https://github.com/kiwigrid/k8s-sidecar/issues/85#issuecomment-749681385

**Comment by QaiserAli** [comment]
Any updates on this?

**Comment by bergerx** [comment]
I tried using OmegaVVeapon/kopf-k8s-sidecar as a replacement for kiwigrid/k8s-sidecar but just hit this issue: https://github.com/OmegaVVeapon/kopf-k8s-sidecar/issues/14

**Comment by bergerx** [comment]
As the OmegaVVeapon/kopf-k8s-sidecar#14 turned out to be a dead end to use it along with this chart, i came up with this very ugly workaround which i'm not proud of, but in 2 hours this is what ai was able to do, we need to craft a PR to address the underlying issue in kiwigrid/k8s-sidecar#85

Here is the values file snippet i used:
```yaml
rbac:
  # The extra rules below are required to run the `kubectl exec ...`
  # command in the force-grafana-dashboard-reload container below.
  extraRoleRules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"] 
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
# This is a workaround for an upstream bug,
# this will force grafana dashboards to be reloaded every 6 minutes.
# Its 6 minutes because the grafana-sc-dashboard pod will regularly be in
# CrashLoopBackOff for 5 minutes after started to be regularly killed. 
# See these issues for details:
# https://github.com/kiwigrid/k8s-sidecar/issues/85
# https://github.com/grafana/helm-charts/issues/18
extraContainers: |
  - name: force-grafana-dashboard-reload
    image: bitnami/kubectl:1.19
    env:    
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    command: ["bash", "-c"]
    args:   
    - while sleep 300; do 
        echo Forcing grafana sidecar to restart ...;
        kubectl exec -n $$POD_NAMESPACE $$POD_NAME -c grafana-sc-dashboard -- kill 1; 
      done    
```
 
And the status of the grafana pod:
![image](https://user-images.githubusercontent.com/45531/107412669-c771d000-6b07-11eb-894f-f51b62d1de8d.png)
