### ISSUE TITLE
Live tailing is not working with nginx ingress:: getting websocket connection error runRequest.catchError Live tailing was stopped due to following error: undefined

### ISSUE THREAD

**Issue by Viswajith96** [grafana/helm-charts#1808]
Hi,

I have configured Loki-distributed as datasource for my grafana instance and using nginx as ingress. everything works fine except the live tailing. it works fine with azure application gateway ingress. tried adding below annotation. and extra path.
       
         
         ```
         nginx.org/websocket-services: grafana

         - backend:
            service:
              name: grafana
              port:
                number: 80
          path: /api/datasources/proxy/1/loki/api/v1/tail
          pathType: ImplementationSpecific
```

error getting in grafana log.

`logger=context traceID=00000000000000000000000000000000 userId=2 orgId=1 uname=viswajith@sedai.io t=2022-09-13T04:49:44.957218667Z level=info msg="Request Completed" method=GET path=/api/datasources/proxy/2/loki/api/v1/tail status=400 remote_addr=10.243.13.41 time_ms=143 duration=143.510193ms size=12 referer= traceID=00000000000000000000000000000000 handler=/api/datasources/proxy/:id/*`
