### ISSUE TITLE
[loki-distributed] Connection to Azure Storage Container seemingly not working

### ISSUE THREAD

**Issue by verejoel** [grafana/helm-charts#1817]
Hello folks,

I originally raised this as an issue on the Loki Github, but as it seems to be more a configuration problem, I thought I would reach out here.

I am having trouble getting Loki distributed helm chart working with Azure as single store backend. No data is being written to the backend, and the logs are full of failures to Put and Delete objects. 

As we are behind istio, connectivity to the blob is of course suspect. However, I have tested both the credentials and the connection using an Azure CLI sidecar container - I could query the blob endpoint that Loki is trying to reach successfully, and also write some test data.

What is more bizarre - I have run Loki locally with the exact same configuration and it worked - data was written to the storage container.

The log lines of interest are primarily from the ingester:
```
level=debug ts=2022-09-16T05:28:02.404576396Z caller=flush.go:142 msg="flushing stream" userid=fake fp=6e9bbcd308cc2062 immediate=false
level=debug ts=2022-09-16T05:28:02.404640095Z caller=flush.go:142 msg="flushing stream" userid=fake fp=11bac131bf478181 immediate=false
level=debug ts=2022-09-16T05:28:02.404648395Z caller=flush.go:142 msg="flushing stream" userid=fake fp=537e6557e355ebe7 immediate=false
level=debug ts=2022-09-16T05:28:02.40893777Z caller=grpc_logging.go:46 method=/logproto.Pusher/Push duration=58.7µs msg="gRPC (success)"
level=error ts=2022-09-16T05:28:03.072306642Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/11bac131bf478181-18331821127-18331effae9-f653d78f?comp=blocklist&timeout=31\": EOF"
level=error ts=2022-09-16T05:28:03.082442582Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/537e6557e355ebe7-18331424838-183316481f0-3a45c56e?comp=blocklist&timeout=31\": EOF"
level=error ts=2022-09-16T05:28:03.092471922Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/6e9bbcd308cc2062-183367fb1cd-183368e3478-78906310?comp=blocklist&timeout=31\": EOF"
```
There are also failing calls to read and delete a cluster seed file:
```
level=debug ts=2022-09-16T05:27:43.76136072Z caller=reporter.go:200 msg="failed to read cluster seed file" err="Get \"https://REDACTED.blob.core.windows.net/loki-default-gen1/loki_cluster_seed.json?timeout=30\": EOF"
level=error ts=2022-09-16T05:27:44.115868087Z caller=reporter.go:203 msg="failed to delete corrupted cluster seed file, deleting it" err="Delete \"https://REDACTED.blob.core.windows.net/loki-default-gen1/loki_cluster_seed.json?timeout=31\": EOF"
```
I am mainly curious where the EOF comes from in the log lines above, as I think understanding this could crack open the whole problem here.

Could anyone with more experience take a look at my helm chart values and see if you can spot anything obviously wrong with how this is setup? 

Cheers!

Loki distributed helm chart values:
```yaml
  loki:
    appProtocol: tcp
    structuredConfig:
      common:
        storage:
          azure:
            account_key: ${STORAGE_ACCOUNT_KEY}
            account_name: REDACTED
            container_name: loki-default-gen1
            request_timeout: 0
      ingester:
        wal:
          enabled: true
          dir: /var/loki/wal
          replay_memory_ceiling: 750MB
    schemaConfig:
      configs:
        - from: 2020-09-07
          store: boltdb-shipper
          object_store: azure
          schema: v11
          index:
            prefix: loki_index_
            period: 24h
    storageConfig:
      boltdb_shipper:
        shared_store: azure
        active_index_directory: /var/loki/boltdb-shipper-active
        cache_location: /var/loki/boltdb-shipper-cache
        cache_ttl: 24h

  ingester:
    appProtocol:
      grpc: tcp
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: loki-secrets
    max_transfer_retries: 0
    chunk_idle_period: 1h
    chunk_target_size: 1536000
    max_chunk_age: 1h
    persistence:
      enabled: true
      size: 20Gi
      storageClass: azuredisk-csi-standard-ssd-delete
```
