### ISSUE TITLE
Grafana sending emails to example@email.com

### ISSUE THREAD

**Issue by mindrunner** [grafana/helm-charts#1819]
Just recently Grafana started to send alert emails to an default address (see screenshot). Could not find a straight forward way to change this setting in values.yaml. Is this expected behaviour? Any advice?

![image](https://user-images.githubusercontent.com/1413542/190634162-046fc564-362a-4374-b7b9-096eb176a998.png)

Cross Post:
https://github.com/prometheus-community/helm-charts/issues/2335

**Comment by zanhsieh** [comment]
@mindrunner 
Could you check if you remove the comment block and change the email here?

https://github.com/grafana/helm-charts/blob/7143ee0fbc3321c2809194acffb981476b64a4f8/charts/grafana/values.yaml#L601

If that doesn't work then we have to escalate to Grafana developers.

**Comment by mindrunner** [comment]
Tried that already
```
  notifiers:
    notifiers.yaml:
      notifiers:
        - name: email-notifier
          type: email
          uid: email1
          org_id: 1
          is_default: true
          settings:
            addresses: x@y.com
```
