### ISSUE TITLE
[grafana] stuck at login screen when using anonymous auth

### ISSUE THREAD

**Issue by miran248** [grafana/helm-charts#1822]
Hey,

Not sure what's going on.. app always redirects to empty `/login`screen upon access.
https://capture.dropbox.com/cA6zKV3P8v3iT3Ve

grafana chart version: `6.38.3`
image: `grafana/grafana:9.1.5`
k8s: `doks.digitalocean.com/version=1.24.4-do.0`

chart values:
```yaml
env:
  GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: true
grafana.ini:
  analytics:
    check_for_updates: false
  auth:
    disable_login_form: true
    disable_signout_menu: true
  auth.anonymous:
    enabled: true
    org_name: lalala
    org_role: Admin
  auth.basic:
    enabled: false
```

`grafana.ini` section in deployed `grafana` configmap:
```ini
[analytics]
check_for_updates = false
[auth]
disable_login_form = true
disable_signout_menu = true
[auth.anonymous]
enabled = true
org_name = lalala
org_role = Admin
[auth.basic]
enabled = false
[grafana_net]
url = https://grafana.net
[log]
mode = console
[paths]
data = /var/lib/grafana/
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
[server]
domain = 
```

**Comment by junaid18183** [comment]
I am facing the same issue , did you find the resolution ?

**Comment by junaid18183** [comment]
Adding the solution here to help someone who stumbles upon the issue in the future, it looks like the org name has to be **Main Org.** without that it doesn't work 
Here is the working input for me 
```
---
grafana.ini:
  auth.anonymous:
    enabled: true
    # Organization name that should be used for unauthenticated users
    org_name: "Main Org."
    # Role for unauthenticated users, other valid values are `Editor` and `Admin`
    org_role: "Admin"
    # Hide the Grafana version text from the footer and help tooltip for unauthenticated users (default: false)
    hide_version: true
sidecar: 
  datasources: 
    enabled: true
```
