### ISSUE TITLE
It is not possible to set contactpoints / notifier

### ISSUE THREAD

**Issue by jlknoch** [grafana/helm-charts#1833]
```
AppVersion: 9.0.9
Helm Chart: 6.38.6
```

We would like to bring our alerting into our Grafana via provisioning. For this we have adapted the values.yaml of the helm chart as follows:

```yaml
## Configure grafana alerting (can be templated)
## ref: http://docs.grafana.org/administration/provisioning/#alerting
##
alerting: {}
  # rules.yaml:
  #   apiVersion: 1
  #   groups:
  #     - orgId: 1
  #       name: '{{ .Chart.Name }}_my_rule_group'
  #       folder: my_first_folder
  #       interval: 60s
  #       rules:
  #         - uid: my_id_1
  #           title: my_first_rule
  #           condition: A
  #           data:
  #             - refId: A
  #               datasourceUid: '-100'
  #               model:
  #                 conditions:
  #                   - evaluator:
  #                       params:
  #                         - 3
  #                       type: gt
  #                     operator:
  #                       type: and
  #                     query:
  #                       params:
  #                         - A
  #                     reducer:
  #                       type: last
  #                     type: query
  #                 datasource:
  #                   type: __expr__
  #                   uid: '-100'
  #                 expression: 1==0
  #                 intervalMs: 1000
  #                 maxDataPoints: 43200
  #                 refId: A
  #                 type: math
  #           dashboardUid: my_dashboard
  #           panelId: 123
  #           noDataState: Alerting
  #           for: 60s
  #           annotations:
  #             some_key: some_value
  #           labels:
  #             team: sre_team_1
  contactpoints.yaml:
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: Mattermost
        receivers:
          - uid: mattermost-notifier
            type: slack
            settings:
              recipient: support-bot
              icon_url: https://example.com/grafana/public/img/grafana_icon.svg
            secure_settings:
              url: http://mattermost.example.com/hooks/tokentokentokentoken

## Configure notifiers
## ref: http://docs.grafana.org/administration/provisioning/#alert-notification-channels
##
notifiers: {}
#  notifiers.yaml:
#    notifiers:
#    - name: email-notifier
#      type: email
#      uid: email1
#      # either:
#      org_id: 1
#      # or
#      org_name: Main Org.
#      is_default: true
#      settings:
#        addresses: an_email_address@example.com
#    delete_notifiers:
```

Unfortunately, this had no effect.

![image](https://user-images.githubusercontent.com/109718804/191698639-e9c8dc17-9696-44eb-9612-3a31fe09c010.png)

we have also tried to customize the notifiers. But unfortunately that didn't work either. Why are there contactpoints and notifier?

Does anyone have an example of a working values.yaml. What are we doing wrong?

Thanks for the help
