### ISSUE TITLE
Unable to deploy Loki Stack to multiple namespaces

### ISSUE THREAD

**Issue by inhumantsar** [grafana/helm-charts#185]
I'm attempting to add Loki to one of our applications. The application has three separate namespaces and 1+ for each developer working on it. eg: prod, stage, dev, bob, alice, alice2. 

The first namespaced install goes alright but the second fails: `PodSecurityPolicy "loki-grafana" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "app-alice": current value is "app-dev"`

```
- name: Install Loki Stack Chart
  community.kubernetes.helm:
    name: loki
    namespace: "{{ app_namespace }}"
    chart_ref: grafana/loki-stack
    wait: true
    values:
      grafana:
        # docs: https://github.com/grafana/helm-charts/tree/main/charts/grafana
        enabled: true
        service: 
          type: NodePort
          annotations:
            kubernetes.io/ingress.class: alb
            alb.ingress.kubernetes.io/tags: "Name={{ app_namespace }}-grafana"
        grafana.ini:
          server:
            domain: "loki.{{ app_namespace }}.example.com"
        ingress:
          enabled: true
          hosts:
            - "loki.{{ app_namespace }}.example.com"
      prometheus:
        enabled: false
      loki:
        # docs: https://github.com/grafana/helm-charts/tree/main/charts/loki
        persistence:
          enabled: true
          storageClassName: gp2
```

```
TASK [Install Loki Stack Chart] **********************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => changed=false 
  command: /usr/bin/helm --namespace=app-alice upgrade -i --reset-values --wait -f=/tmp/tmp4yy8htlk.yml loki grafana/loki-stack
  msg: |-
    Failure when executing Helm command. Exited 1.
    stdout: Release "loki" does not exist. Installing it now.
  
    stderr: Error: rendered manifests contain a resource that already exists. Unable to continue with install: PodSecurityPolicy "loki-grafana" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "app-alice": current value is "app-dev"
  stderr: |-
    Error: rendered manifests contain a resource that already exists. Unable to continue with install: PodSecurityPolicy "loki-grafana" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "app-alice": current value is "app-dev"
  stderr_lines: <omitted>
  stdout: |-
    Release "loki" does not exist. Installing it now.
  stdout_lines: <omitted>
```
