### ISSUE TITLE
How does envFromSecret work in sidecars?

### ISSUE THREAD

**Issue by vsinha** [grafana/helm-charts#1865]
I'd like to load a secret into the pod env variables for grafana, as the `envFromSecret` value supposedly does. Specifically I'd like the env to be set in the alerting sidecars, so I can store things like my Slack token safely. It doesn't seem to be working and other than in the docs I can't find any reference to it in the helm charts. 

I did find PR #30 from 2 years go doing something similar in the datasources sidecar, but those changes appear to have since been reverted. 

Is this functionality deprecated?

**Comment by ChristopherDrum** [comment]
I'm very interested in this as well. I need to set the secret API token for my InfluxDB database setup. Using Grafana's recommendation of an environment variable doesn't seem to work, and that PR #[30](https://github.com/grafana/helm-charts/pull/30) looked promising.

**Comment by ChristopherDrum** [comment]
I could be wrong, but it looks like the templating at 
https://github.com/grafana/helm-charts/blob/2cf626aad06a12506c014aa541f85b8646f0916c/charts/grafana/templates/image-renderer-deployment.yaml#L89
only allows for simple key-value pairs. When using a secret, we need to be able to set `env` like this
```
env:
  - name: SECRET_API_READ_KEY
    valueFrom:
      secretKeyRef:
        name: my-secrets
        key: api_read_key
```
where those values come from an `ExternalSecret`.
There are other patterns for setting secrets as environment variables as well, but the helm-chart doesn't (to my beginner eyes) seem to accommodate those patterns. If I understand correctly, my sample code above will not resolve down to a simple `name` and `value` pair before being used by the template? If so, then what is the better strategy for accomplishing something like this? `kustomization.yaml` patch?

**Comment by hkailantzis** [comment]
That would be great. In my case, I'm creating a service account token type secret based on the provisioned SA. I can pass this to main container via "envFromSecrets", but the idea is to be able to use it sidecar for filling up the secureJsonData of the datasource.yaml with that token value.... I guess have to do it manually for now, maybe with an Initcontainer and envsubst....running out of ideas tbh :-).

**Comment by hkailantzis** [comment]
@vsinha, this reason behind this: https://github.com/grafana/helm-charts/pull/33.

**Comment by OneCricketeer** [comment]
RE: datasources, as noted in #33, the Grafana pod itself should be defined with the env-var, then [a Datasource can be added with a variable reference](https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables)

**Comment by danlhennessy** [comment]
> RE: datasources, as noted in #33, the Grafana pod itself should be defined with the env-var, then [a Datasource can be added with a variable reference](https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables)

This worked for me, to add some specific steps:

Create a secret however you choose in Grafana namespace e.g:
`kubectl create secret generic grafana-env --from-literal=CLIENT_SECRET=XXX --from-literal=SLACK_WEBHOOK=XXX -n observe`

Deploy Grafana helm chart with example values.yaml, to add a datasource with auth. In this case Az monitor:
```grafana:
  envFromSecret: "grafana-env"
  additionalDataSources: 
    - name: Azure Monitor
      type: grafana-azure-monitor-datasource
      access: proxy
      jsonData:
        azureAuthType: clientsecret
        cloudName: azuremonitor
        tenantId: XX
        clientId: XX
        subscriptionId: XX
      secureJsonData:
        clientSecret: $CLIENT_SECRET
      version: 1
  sidecar:
    alerts:
      label: grafana_alert
      enabled: true
      searchNamespace: ALL
      labelValue: "1"
  ```
  
  KEY:VALUE pairs from the secret will be available as env variables to the main grafana pod not the sidecars
  
  Then to use the secret when provisioning other resources like contactpoints:
  
  slack-contact.yaml
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: slack-contactpoint
  labels:
    grafana_alert: "1"
data:
  contactpoint.yaml: |
    apiVersion: 1
    contactPoints:
      - orgId: 1
        name: slack_contact
        receivers:
          - uid: slack
            type: slack
            settings:
              # <string> Optionally provide a Slack incoming webhook URL for sending messages, in this case the token isn't necessary
              url: $SLACK_WEBHOOK
```

alerts sidecar will scan the configmap, and grafana pod inserts the contactpoint, resolving url value to the value from the secret
