### ISSUE TITLE
[grafana] Contact Point provisioning via Alerting sidecar - contact points: Error 1051: Unknown table 'T'

### ISSUE THREAD

**Issue by willhughes-au** [grafana/helm-charts#1869]
Now that PR https://github.com/grafana/helm-charts/pull/1847 is merged, I'm trying to set up contactPoints and alerting via the new alerting configuration. 

Using Helm Chart Version 6.40.1, I have a k8s secret which (after redaction) looks like: 

```yaml
---
apiVersion: 1
contactPoints:
  - orgId: 1
    name: my-slack-channel
    receivers:
      - uid: my-slack-channel
        type: slack
        settings:
          recipient: '#my-slack-channel'
          token: 'xoxb-my-slack-token'
```

I can see through the logs on the sidecar container `grafana-sc-alerts` that it's found the secret, and it puts it on the provisioning path.  When It then calls reload, it gets a HTTP 500. 

`urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/admin/provisioning/alerting/reload (Caused by ResponseError('too many 500 error responses'))` 

At the time this happens, I get these log entries on the main `grafana` container: 

```
logger=provisioning.alerting t=2022-10-04T05:53:20.84774281Z level=info msg="starting to provision alerting"
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-10-04T05:53:20.862035061Z level=error msg= error="contact points: Error 1051: Unknown table 'T'" remote_addr=127.0.0.1 traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-10-04T05:53:20.862214539Z level=error msg="Request Completed" method=POST path=/api/admin/provisioning/alerting/reload status=500 remote_addr=127.0.0.1 time_ms=28 duration=28.576063ms size=75 referer= traceID=00000000000000000000000000000000 handler=/api/admin/provisioning/alerting/reload
```

I am able to manually create a contact point in the Grafana Admin UI via the web interface, so I think Grafana itself is right - but the provisioning configuration isn't right somehow.

**Comment by tarikdem** [comment]
This happened to me after changing the slack configuration in the configMap. What fixed it is disabling and re-enabling the alert sidecar (ie setting `sidecar.alerts.enabled` to `false` and then to `true` again). Hope this helps getting around the issue, but there seems to be a bug here when changing the configuration.

**Comment by EmilyShepherd** [comment]
I also get this via static alerting provisioning (by specifying rules in `alerting.*\.yaml` in the helm file). Sidecar is not used in this case :/

**Comment by yuliyantsvetkov** [comment]
I was able to figure this out via the `grafana-sc-alerts`.

You need to migrate your YAML from `Notifier` to `ContactPoint` which is quite easy when following the documentation [here](https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/#provision-contact-points).

After that you just provision it with `label` - `grafana_alert: "1"`.

Here is one sample of migrated `Notifier` to `ContactPoint`:

```
CONTACT_POINTS_YAML: |-
    contactPoints:
      - org_id: 1
        name: xxx
        receivers:
          - uid: xxxx
            type: slack
            frequency: 1h
            is_default: false
            disable_resolve_message: true
            settings:
              recipient: '#xxxx'
              token: "xxxxx"
              uploadImage: true
              icon_url: 'https://xxxx.com/xxx.png'
```

The `ConfigMap` for the Grafana Helm chart and the SideCar looks like this:

```
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  labels:
    grafana_alert: "1"
type: Opaque
data:
  notifiers.yaml: |-
    {{ .Values.CONTACT_POINTS_YAML | b64enc }}
```

I hope this helps.
