### ISSUE TITLE
[tempo-distributed] centralize port handling

### ISSUE THREAD

**Issue by zalegrala** [grafana/helm-charts#1946]
Currently, the various network ports that are used in this chart are scattered over the templates.  I think it would be a good idea to centralize the values here, and then reference those values from the various locations.  This should allow environments to tune their ports a little more easily, and also pave the way for changing the default if we so choose.

**Comment by faustodavid** [comment]
Will this list also include the trace receiver ports?

Example:
```yaml
ports:
  tempo:
    httpMetrics:
      containerPort: 3100
      servicePort: 3100
      protocol: TCP
    httpMemberlist:
      containerPort: 7946
      protocol: TCP
    grpc:
      containerPort: 9095
      servicePort: 9095
      protocol: TCP
    ...
  traces:
    otlp:
      enabled: true
      containerPort: 4317
      servicePort: 4317
      hostPort: 4317
      protocol: TCP
    otlp-http:
      enabled: true
      containerPort: 4318
      servicePort: 4318
      hostPort: 4318
      protocol: TCP
    ...
```
