### ISSUE TITLE
[tempo-distributed] configuring max_concurrent_queries not possible

### ISSUE THREAD

**Issue by aaronstutzer** [grafana/helm-charts#1966]
I would like to increase the `max_concurrent_queries` for the queried but in the helm-chart this is not possible

current part for `querier` from `config`
```
  querier:
    frontend_worker:
      frontend_address: {{ include "tempo.resourceName" (dict "ctx" . "component" "query-frontend") }}:9095
      {{- if .Values.querier.config.frontend_worker.grpc_client_config }}
      grpc_client_config:
        {{- toYaml .Values.querier.config.frontend_worker.grpc_client_config | nindent 6 }}
      {{- end }}
```

**Comment by rlex** [comment]
try
```
tempo:
   structuredConfig:
       querier:
           max_concurrent_queries: number
```
