### ISSUE TITLE
Cannot add custom scrape jobs

### ISSUE THREAD

**Issue by sandeepbangera** [grafana/helm-charts#197]
The documentation says that we could use `extraScrapeConfigs` to add additional scrape configs.
https://grafana.com/docs/loki/latest/installation/helm/#run-promtail-with-systemd-journal-support 

```
# Add additional scrape config
extraScrapeConfigs:
  - job_name: journal
    journal:
      path: /var/log/journal
      max_age: 12h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'hostname'
```        

But the current chart does not support `extraScrapeConfigs`.
https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml
