### ISSUE TITLE
[grafana] Add `pretext` object to the contactPoints entity in new Grafana alerting system (aka unified_alerts)

### ISSUE THREAD

**Issue by ghost** [grafana/helm-charts#1978]
> My current Grafana version: 9.2.3

Hello dear Grafana contributors,

Can I ask you to add a feature from legacy Alertmanager alerting - `pretext` option for contactPoints.
It won't work now, config (just for example):
```
contactPoints:
  - name: grafana-dev-info
    receivers:
      - uid: grafana-dev-info_uid
        type: slack
        settings:
          recipient: "grafana-dev-info"
          token: ""
          username: "grafana-dev-info"
          icon_emoji: ":grafana_dev:"
          icon_url: ""
          mentionUsers: ""
          mentionGroups: ""
          mentionChannel: ""
          url: https://hooks.slack.com/services/**********
          endpointUrl: ""
          pretext: "*Severity:* `{{ .CommonLabels.severity | toUpper }}`"
          title: |-
            {{ template "title" . }}
          text: |-
            {{ template "text" . }}
```
For now, **pretext section** just duplicates the Title:

![image](https://user-images.githubusercontent.com/104848965/201909478-64fd3be6-c5bb-4feb-aecf-60eeaa7e8e77.png)

As for me, duplicating information does not have much sense :) 

For legacy alerting config, you have supported this option, config:
```
 receivers:
  - name: 'null'
  - name: 'dev-info'
    slack_configs:
    - channel: '#dev-info'
      send_resolved: true
      pretext: "*Severity:* `{{ .CommonLabels.severity | toUpper }}`"
```
It is really usable! For example, alert severity could be added there. Here is how it looks like with it:
![image](https://user-images.githubusercontent.com/104848965/201910642-a6cfb42c-122f-4ea3-a87f-c3443d94f1de.png)

Could you please review adding of it (if it's possible of course)? 
Thanks in advance!
