### ISSUE TITLE
[grafana]remote_cache doesn't work

### ISSUE THREAD

**Issue by caibirdme** [grafana/helm-charts#1984]
I configured remote_cache and database in grafana.ini, and I can access the grafana from the browser, the requests are also routed to different grafana pods. But when I see redis, I didn't find any keys, I found the session is stored in database(pg) rather than in remote_cache(redis):
```yaml
grafana:
  grafana.ini:
    unified_alerting:
      enabled: true
      ha_peers: my-grafana-headless:9094
    alerting:
      enabled: false
    database:
      type: postgres
      host: 1.2.3.4:5432
      name: grafana
      user: admin
      password: Password_123
    remote_cache:
      type: redis
      connstr: addr=my-redis-master:6379,db=1,password=Abcd1234_
```
