### ISSUE TITLE
[grafana] Bug with duplicating alerts with more than one Grafana replica

### ISSUE THREAD

**Issue by Dima-Diachenko-work** [grafana/helm-charts#1989]
Helo dea comrmunity, 

> Grafana version: 9.2.3
> Deployed via [Grafana Helm Chart ](https://artifacthub.io/packages/helm/grafana/grafana/6.43.4).

I detected one **serious bug with using Grafana alerts** (aka "unified_alerts").

When you use deployment with a single Grafana instance - it's perfect! For each triggered alert we have only one notification (in Slack in my case).

But when you set 2 or more replicas (for reliability) of the Grafana deployments - we start to get duplicated notifications from each Grafana pod.
How it looks like:
![image](https://user-images.githubusercontent.com/104848965/202576948-bcd2a6f1-3f1b-458f-98f3-ce08b99161f3.png)

Grafana Helm config:
```
...
replicas: 2
annotations:
  reloader.stakater.com/auto: "true"
# extraConfigmapMounts:
#   - name: grafana-provisioning
#     configMap: grafana-provisioning
#     mountPath: /etc/grafana/provisioning/alerting
#     subPath: ""
#     readOnly: true
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
persistence:
  enabled: false
...
```

I doublechecked this theory:
- have changed replicas to 1 and got only one message in the Slack
- have changed replicas to 3 and got three similar messages at the same time :) 

Could please try it in your lab (or dev) environment - most probably you will have the same.
And if it's actual - want to ask you to fix it since it's a blocker for using the new Grafana alerting system with "true reliability" config.
I appreciate your work!

**Comment by conorevans** [comment]
https://github.com/grafana/helm-charts/tree/main/charts/grafana#high-availability-for-unified-alerting

**Comment by Dima-Diachenko-work** [comment]
@conorevans God bless you man, thanks!
It works for me. I'm closing this issue.

**Comment by OnerInce** [comment]
@Dima-Diachenko-work Did you make any further configurations except the ones in Readme? I have done those steps but still getting duplicate alerts

**Comment by Dima-Diachenko-work** [comment]
@OnerInce hello
No, only config from the README.md
I deployed Grafana using[ kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) (where Grafana chart is in dependency, this is my config part:
```
            unified_alerting:
              enabled: true
              ha_peers: kube-prometheus-stack-grafana-headless:9094
            alerting:
              enabled: false
```
It works for me so probably you doing something wrong.
Please. pay attention that you need to put this code block into grafana.ini file. Double check everything, maybe you will find issue.
