### ISSUE TITLE
[grafana] Drop ALL Capabilities by Default

### ISSUE THREAD

**Issue by JuanPabloSGU** [grafana/helm-charts#1994]
Current it seems that 

```YAML
capabilites:
  drop: 
    - ALL
```

is missing from the container security context. If the container does not require those capabilities, would it be possible to drop them by default?
