### ISSUE TITLE
[grafana] use of Ingress.extraPaths throws YAML parse error

### ISSUE THREAD

**Issue by bryan-lw** [grafana/helm-charts#1996]
With ingress.enabled: true and use of extraPaths section as below, attempting to deploy the helm chart fails with:

`Error: UPGRADE FAILED: YAML parse error on grafana/templates/ingress.yaml: error converting YAML to JSON: yaml: line 26: block sequence entries are not allowed in this context`

Sample values.yaml for ingress section (~lines 197+):
```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: gce
    cert-manager.io/cluster-issuer: my-cluster-issuer
    kubernetes.io/ingress.allow-http: "false"
  labels: {}
  path: /
  pathType: Prefix

  hosts: 
    - grafana.domain.com

  extraPaths:
  - path: /other/
    pathType: Prefix
    backend:
      service:
        name: nginx-router
        port:
          name: nginx
  tls: 
    - secretName: grafana-tls
      hosts:
        - grafana.domain.com

```
