### ISSUE TITLE
[grafana] managed_identity_enabled, how to enable it in deployment?

### ISSUE THREAD

**Issue by xudesheng** [grafana/helm-charts#1997]
The `managed_identity_enabled` default value is `false` in Grafana server configuration `conf/defaults.ini`. How can I enable it to true in Kubernetes deployment?

**Comment by imjoseangel** [comment]
Dear @xudesheng 

Just add 

```yaml
  grafana.ini:
    azure:
      managed_identity_enabled: true
```
