### ISSUE TITLE
No activity on the target bucket

### ISSUE THREAD

**Issue by cilerler** [grafana/helm-charts#1998]
I'm trying to migrate my docker-compose setup into the Minikube.
Unfortunately, I couldn't make logs appear on the MinIO bucket with the setup below.
Here are the exact commands and config file I use. Any idea what I am missing there?

```powershell
minikube start --container-runtime=containerd;

helm install minio-operator minio/operator --namespace minio-operator --create-namespace --wait;
helm install minio-observability minio/tenant --namespace observability --create-namespace --wait --set tenant.certificate.requestAutoCert=false,tenant.buckets[0].name=loki;

helm install promtail grafana/promtail --namespace observability --create-namespace --set config.clients[0].url="http://loki-loki-distributed-gateway.observability.svc.cluster.local/loki/api/v1/push";

helm install loki grafana/loki-distributed --namespace observability --create-namespace -f .\configs\loki.yml
```

## .\configs\loki.yml
```yaml
storage:
  s3:
    s3: null
    endpoint: minio1-hl.observability.svc.cluster.local:9000
    bucketnames: loki
    access_key_id: minio
    secret_access_key: minio123
    s3forcepathstyle: true
    insecure: true
```
