### ISSUE TITLE
query index: rpc error: code = Unavailable desc = name resolver error: produced zero addresses

### ISSUE THREAD

**Issue by patsevanton** [grafana/helm-charts#2006]
Rendered configmap
```
# Source: loki-distributed/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-loki-distributed
  labels:
    helm.sh/chart: loki-distributed-0.65.3
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: "2.6.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    werf.io/version: v1.2.177
data:
  config.yaml: |
    auth_enabled: false
    chunk_store_config:
      max_look_back_period: 0s
    compactor:
      shared_store: s3
    distributor:
      ring:
        kvstore:
          store: memberlist
    frontend:
      compress_responses: true
      log_queries_longer_than: 5s
      tail_proxy_url: http://loki-loki-distributed-querier:3100
    frontend_worker:
      frontend_address: loki-loki-distributed-query-frontend:9095
    ingester:
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_idle_period: 30m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      max_transfer_retries: 0
      wal:
        dir: /var/loki/wal
    limits_config:
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 15m
    memberlist:
      join_members:
      - loki-loki-distributed-memberlist
    query_range:
      align_queries_with_step: true
      cache_results: true
      max_retries: 5
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_items: 1024
            ttl: 24h
    ruler:
      alertmanager_url: https://alertmanager.xx
      external_url: https://alertmanager.xx
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      storage:
        local:
          directory: /etc/loki/rules
        type: local
    runtime_config:
      file: /var/loki-distributed-runtime/runtime.yaml
    schema_config:
      configs:
      - from: "2022-02-01"
        index:
          period: 24h
          prefix: loki_index_
        object_store: s3
        schema: v11
        store: boltdb-shipper
    server:
      http_listen_port: 3100
    storage_config:
      aws:
        access_key_id: xxxxxxxxxxxxxxxxxxxxxxx
        bucketnames: xxxxxxxxxxxxxxxxxx
        s3: http://storage.xxxxxxxxxxxxx.net
        s3forcepathstyle: true
        secret_access_key: xxxxxxxxxxxxx
      boltdb_shipper:
        active_index_directory: /var/loki/boltdb-shipper-active
        cache_location: /var/loki/boltdb-shipper-cache
        cache_ttl: 12h
        index_gateway_client:
          server_address: dns:///loki-loki-index-gateway:9095
        shared_store: s3
      filesystem:
        directory: /var/loki/chunks
    table_manager:
      retention_deletes_enabled: true
      retention_period: 720h
```

Values loki k8s:
```
loki:
  config: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    distributor:
      ring:
        kvstore:
          store: memberlist

    memberlist:
      join_members:
        - {{ include "loki.fullname" . }}-memberlist

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      chunk_idle_period: 30m
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_retain_period: 1m
      max_transfer_retries: 0
      wal:
        dir: /var/loki/wal

    limits_config:
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 15m

    {{- if .Values.loki.schemaConfig}}
    schema_config:
    {{- toYaml .Values.loki.schemaConfig | nindent 2}}
    {{- end}}
    {{- if .Values.loki.storageConfig}}
    storage_config:
    {{- if .Values.indexGateway.enabled}}
    {{- $indexGatewayClient := dict "server_address" (printf "dns:///%s:9095" (include "loki.indexGatewayFullname" .)) }}
    {{- $_ := set .Values.loki.storageConfig.boltdb_shipper "index_gateway_client" $indexGatewayClient }}
    {{- end}}
    {{- toYaml .Values.loki.storageConfig | nindent 2}}
    {{- if .Values.memcachedIndexQueries.enabled }}
      index_queries_cache_config:
        memcached_client:
          addresses: dnssrv+_memcached-client._tcp.{{ include "loki.memcachedIndexQueriesFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}
          consistent_hash: true
    {{- end}}
    {{- end}}

    runtime_config:
      file: /var/{{ include "loki.name" . }}-runtime/runtime.yaml

    chunk_store_config:
      max_look_back_period: 0s
      {{- if .Values.memcachedChunks.enabled }}
      chunk_cache_config:
        enable_fifocache: false
        memcached_client:
          consistent_hash: true
          addresses: dnssrv+_memcached-client._tcp.{{ include "loki.memcachedChunksFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}
      {{- end }}
      {{- if .Values.memcachedIndexWrites.enabled }}
      write_dedupe_cache_config:
        memcached_client:
          consistent_hash: true
          addresses: dnssrv+_memcached-client._tcp.{{ include "loki.memcachedIndexWritesFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}
      {{- end }}

    table_manager:
      retention_deletes_enabled: true
      retention_period: 720h

    query_range:
      align_queries_with_step: true
      max_retries: 5
      cache_results: true
      results_cache:
        cache:
          {{- if .Values.memcachedFrontend.enabled }}
          memcached_client:
            addresses: dnssrv+_memcached-client._tcp.{{ include "loki.memcachedFrontendFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}
            consistent_hash: true
          {{- else }}
          enable_fifocache: true
          fifocache:
            max_size_items: 1024
            ttl: 24h
          {{- end }}

    frontend_worker:
      {{- if .Values.queryScheduler.enabled }}
      scheduler_address: {{ include "loki.querySchedulerFullname" . }}:9095
      {{- else }}
      frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095
      {{- end }}

    frontend:
      log_queries_longer_than: 5s
      compress_responses: true
      {{- if .Values.queryScheduler.enabled }}
      scheduler_address: {{ include "loki.querySchedulerFullname" . }}:9095
      {{- end }}
      tail_proxy_url: http://{{ include "loki.querierFullname" . }}:3100

    compactor:
      shared_store: s3

    ruler:
      storage:
        type: local
        local:
          directory: /etc/loki/rules
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      alertmanager_url: https://alertmanager.xx
      external_url: https://alertmanager.xx

  schemaConfig:
    configs:
    - from: "2022-02-01"
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

  storageConfig:
    boltdb_shipper:
      active_index_directory: /var/loki/boltdb-shipper-active
      cache_location: /var/loki/boltdb-shipper-cache
      cache_ttl: 12h
      shared_store: s3
      index_gateway_client:
        server_address: dns:///loki-loki-index-gateway:9095
    aws:
#      s3: http://${access_key_id}:${secret_access_key}@storage.xxxxxxxxxxx.net:443
      s3: http://storage.xxxxxxxxxxxx.net
      bucketnames: xxxxxxxxxxxxxxxx
      s3forcepathstyle: true

serviceMonitor:
  enabled: false

tableManager:
  enabled: false
```

Install helm chart loki
```
export access_key_id=$(terraform output --raw access_key_sa_storage_admin_for_test_bucket)
export secret_access_key=$(terraform output --raw secret_key_sa_storage_admin_for_test_bucket)
werf helm upgrade --install --wait loki grafana/loki-distributed -n loki \
    --set "loki.storageConfig.aws.access_key_id=$access_key_id"  \
    --set "loki.storageConfig.aws.secret_access_key=$secret_access_key"  \
    -f value-loki-distributed.yaml
```

Logs:
```
loki-loki-distributed-querier-0 querier level=error ts=2022-11-22T15:51:52.339163378Z caller=series_index_store.go:527 org_id=fake msg="error querying storage" err="query index: rpc error: code = Unavailable desc = name resolver error: produced zero addresses"
loki-loki-distributed-querier-0 querier ts=2022-11-22T15:51:52.339246067Z caller=spanlogger.go:80 user=fake method=query.Label level=info org_id=fake latency=fast query_type=labels length=10m0s duration=2.197211ms status=500 label= throughput=0B total_bytes=0B total_entries=0
loki-loki-distributed-querier-0 querier level=warn ts=2022-11-22T15:51:52.339319059Z caller=logging.go:86 traceID=00062f47a86aa58b orgID=fake msg="GET /loki/api/v1/labels?end=1669132312278000000&start=1669131712278000000 (500) 2.376737ms Response: \"query index: rpc error: code = Unavailable desc = name resolver error: produced zero addresses\\n\" ws: false; X-Scope-Orgid: fake; uber-trace-id: 00062f47a86aa58b:6992cf7c8f16fce0:1b6d9050906cdf91:0; "
loki-loki-distributed-querier-0 querier level=error ts=2022-11-22T15:51:52.341348341Z caller=series_index_store.go:527 org_id=fake msg="error querying storage" err="query index: rpc error: code = Unavailable desc = name resolver error: produced zero addresses"
loki-loki-distributed-querier-0 querier ts=2022-11-22T15:51:52.341421717Z caller=spanlogger.go:80 user=fake method=query.Label level=info org_id=fake latency=fast query_type=labels length=10m0s duration=1.180069ms status=500 label= throughput=0B total_bytes=0B total_entries=0
loki-loki-distributed-querier-0 querier level=warn ts=2022-11-22T15:51:52.341472229Z caller=logging.go:86 traceID=00062f47a86aa58b orgID=fake msg="GET /loki/api/v1/labels?end=1669132312278000000&start=1669131712278000000 (500) 1.312523ms Response: \"query index: rpc error: code = Unavailable desc = name resolver error: produced zero addresses\\n\" ws: false; X-Scope-Orgid: fake; uber-trace-id: 00062f47a86aa58b:6992cf7c8f16fce0:1b6d9050906cdf91:0; "
+ loki-loki-distributed-ingester-0 › ingester
loki-loki-distributed-querier-0 querier level=error ts=2022-11-22T15:51:52.342876115Z caller=series_index_store.go:527 org_id=fake msg="error querying storage" err="query index: rpc error: code = Unavailable desc = name resolver error: produced zero addresses"
loki-loki-distributed-querier-0 querier ts=2022-11-22T15:51:52.342936208Z caller=spanlogger.go:80 user=fake method=query.Label level=info org_id=fake latency=fast query_type=labels length=10m0s duration=938.37µs status=500 label= throughput=0B total_bytes=0B total_entries=0
loki-loki-distributed-querier-0 querier level=warn ts=2022-11-22T15:51:52.343003085Z caller=logging.go:86 traceID=00062f47a86aa58b orgID=fake msg="GET /loki/api/v1/labels?end=1669132312278000000&start=1669131712278000000 (500) 1.075839ms Response: \"query index: rpc error: code = Unavailable desc = name resolver error: produced zero addresses\\n\" ws: false; X-Scope-Orgid: fake; uber-trace-id: 00062f47a86aa58b:6992cf7c8f16fce0:1b6d9050906cdf91:0; "
loki-loki-distributed-querier-0 querier level=error ts=2022-11-22T15:51:52.344467694Z caller=series_index_store.go:527 org_id=fake msg="error querying storage" err="query index: rpc error: code = Unavailable desc = name resolver error: produced zero addresses"
loki-loki-distributed-querier-0 querier ts=2022-11-22T15:51:52.344526571Z caller=spanlogger.go:80 user=fake method=query.Label level=info org_id=fake latency=fast query_type=labels length=10m0s duration=799.758µs status=500 label= throughput=0B total_bytes=0B total_entries=0
loki-loki-distributed-querier-0 querier level=warn ts=2022-11-22T15:51:52.344570576Z caller=logging.go:86 traceID=00062f47a86aa58b orgID=fake msg="GET /loki/api/v1/labels?end=1669132312278000000&start=1669131712278000000 (500) 915.911µs Response: \"query index: rpc error: code = Unavailable desc = name resolver error: produced zero addresses\\n\" ws: false; X-Scope-Orgid: fake; uber-trace-id: 00062f47a86aa58b:6992cf7c8f16fce0:1b6d9050906cdf91:0; "
loki-loki-distributed-querier-0 querier level=error ts=2022-11-22T15:51:52.346071035Z caller=series_index_store.go:527 org_id=fake msg="error querying storage" err="query index: rpc error: code = Unavailable desc = name resolver error: produced zero addresses"
loki-loki-distributed-querier-0 querier ts=2022-11-22T15:51:52.346171511Z caller=spanlogger.go:80 user=fake method=query.Label level=info org_id=fake latency=fast query_type=labels length=10m0s duration=840.609µs status=500 label= throughput=0B total_bytes=0B total_entries=0
loki-loki-distributed-querier-0 querier level=warn ts=2022-11-22T15:51:52.346220007Z caller=logging.go:86 traceID=00062f47a86aa58b orgID=fake msg="GET /loki/api/v1/labels?end=1669132312278000000&start=1669131712278000000 (500) 969.538µs Response: \"query index: rpc error: code = Unavailable desc = name resolver error: produced zero addresses\\n\" ws: false; X-Scope-Orgid: fake; uber-trace-id: 00062f47a86aa58b:6992cf7c8f16fce0:1b6d9050906cdf91:0; "
```
