### ISSUE TITLE
[tempo-distributed] /tmp is read only in the tempo-query container

### ISSUE THREAD

**Issue by eric-engberg** [grafana/helm-charts#2024]
By default all containers in the tempo-distributed chart v0.27.9 have `readOnlyRootFilesystem: true`.  This is an issue as the tempo-query container attempts to write to /tmp.

You also can't replace /tmp with an `emptyDir` because there is a binary for tempo-query within /tmp

>2022-11-29T20:28:34.584Z [ERROR] tempo-query: plugin init error: error="open /tmp/plugin4118867345: read-only file system" timestamp=2022-11-29T20:28:34.584Z
>{"level":"fatal","ts":1669753714.584929,"caller":"./main.go:107","msg":"Failed to init storage factory","error":"grpc-plugin builder failed to create a store: error attempting to connect to plugin rpc client: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol.","stacktrace":"main.main.func1\n\t./main.go:107\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.5.0/command.go:872\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.5.0/command.go:918\nmain.main\n\t./main.go:168\nruntime.main\n\truntime/proc.go:250"}`

I'm currently working around this by patching just the tempo-query to have a writable root filesystem
>patchesJson6902:
   - target:
        group: apps
        version: v1
        kind: Deployment
        name: grafana-tempo-distributed-query-frontend
      patch: |-
        - op: replace
           path: /spec/template/spec/containers/1/securityContext/readOnlyRootFilesystem
           value: false

**Comment by lanortizv** [comment]
Same issue with tempo-query container 
2022-12-08T19:40:15.425Z [ERROR] tempo-query: failed to parse configuration file: @module=jaeger-tempo error="open /conf/tempo-query.yaml: no such file or directory" timestamp=2022-12-08T19:40:15.425Z
2022-12-08T19:40:15.427Z [ERROR] tempo-query: plugin init error: error="open /tmp/plugin2742873730: read-only file system" timestamp=2022-12-08T19:40:15.427Z
{"level":"fatal","ts":1670528415.4291558,"caller":"./main.go:107","msg":"Failed to init storage factory","error":"grpc-plugin builder failed to create a store: error attempting to connect to plugin rpc client: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to be recompiled to support the latest protocol.","stacktrace":"main.main.func1\n\t./main.go:107\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.5.0/command.go:872\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.5.0/command.go:990\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.5.0/command.go:918\nmain.main\n\t./main.go:168\nruntime.main\n\truntime/proc.go:250"}

**Comment by BertelBB** [comment]
Here is a workaround that does not require changing file permissions. Not ideal, but it works

First, set the following chart values

```yaml
queryFrontend:
  extraVolumes:
  - name: tmp
    emptyDir: {}
  query:
    extraVolumeMounts:
    - name: tmp
      mountPath: /tmp
      readOnly: false
```

1. Use `helm template` to generate manifests and output them in a file
2. Create kustomization to build the resulting manifests
   - Make sure to set `namespace` property because `helm template` does not support that
4. Patch `tempo-query-frontend` with initContainer that copies the `tempo-query` binary

```yaml
patches:
- target:
    kind: Deployment
    name: tempo-query-frontend # <-- adjust name if needed
  patch: |
    - op: add
      path: /spec/template/spec/initContainers
      value:
      -
        args: ["cp -r /tmp/tempo-query /mnt/tempo-query"]
        command: ["/bin/sh", "-c"]
        image: docker.io/grafana/tempo-query:main-6430d00
        imagePullPolicy: IfNotPresent
        name: copy-container
        volumeMounts:
        - name: tmp
          mountPath: /mnt
```
