### ISSUE TITLE
Getting Rules are not valid for proper rules

### ISSUE THREAD

**Issue by abvijaykumar** [grafana/helm-charts#2037]
Hi I am using loki-distributed. I am using the following values.yaml

```
prometheusRule:
  enabled: true
  namespace: monitoring
  labels:
    release: prometheus
  groups: 
    - name: bozo-book-errors
      rules: 
        - alert: BozoBookErrors
          expr: rate({namespace="bozo-book-library-dev"} |= "ERROR" [5m]) > 5
          for: 1m
          labels:
            severity: critical
            source: loki
          annotations:
            message: "Error in BozoBookLibrary App Pod: {{ $labels.pod }} Node: {{ $labels.node_name}} Error : {{$labels.log}}"
```

I am executing the following command 

`helm install --create-namespace -n loki-distributed loki-distributed grafana/loki-distributed --values ./values/loki-distributed-values.yaml`

I get the following error

```
W1202 10:37:56.833681   65338 warnings.go:70] spec.template.spec.topologySpreadConstraints[0].topologyKey: failure-domain.beta.kubernetes.io/zone is deprecated since v1.17; use "topology.kubernetes.io/zone" instead
Error: INSTALLATION FAILED: admission webhook "prometheusrulemutate.monitoring.coreos.com" denied the request: Rules are not valid
```
The expression works fine on Grafana

if I remove  |= "ERROR" and make the expression 

`expr: rate({namespace="bozo-book-library-dev"} [5m]) > 5`

It works.
