### ISSUE TITLE
promtail: unable to change lokiAddress [loki-stack v2.1.2]

### ISSUE THREAD

**Issue by JihadMotii-REISys** [grafana/helm-charts#204]
I deployed the loki-stack 2.1.2 using helm 3 in EKS v1.18.

I want to provide a configuration to override `lokiAddress` in promtail as mentioned in the [`values.yaml`](https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml#L228) but I always ended up with the following error message of the promtail DaemonSet:
```
Unable to parse config: /etc/promtail/promtail.yaml: yaml: unmarshal errors:
  line 10: field file not found in type main.Config
```

These are the following tries with the config that I provided:
```
loki:
  enabled: true
  ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: loki-server.example.com
        paths:
          - /
    tls:
      - secretName: loki-server.example.com
        hosts:
          - loki-server.example.com
  persistence:
    enabled: true
    accessModes:
    - ReadWriteOnce
    size: 200Gi
promtail:
  enabled: true
  config:
    file: |
      client:
        url: https://loki-server.example.com/loki/api/v1/push
```

Also tried the following config:
```
loki:
  enabled: true
  ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: loki-server.example.com
        paths:
          - /
    tls:
      - secretName: loki-server.example.com
        hosts:
          - loki-server.example.com
  persistence:
    enabled: true
    accessModes:
    - ReadWriteOnce
    size: 200Gi
promtail:
  enabled: true
  config:
    lokiAddress: https://loki-server.example.com/loki/api/v1/push
```

Also tried the following config:
```
loki:
  enabled: true
  ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: loki-server.example.com
        paths:
          - /
    tls:
      - secretName: loki-server.example.com
        hosts:
          - loki-server.example.com
  persistence:
    enabled: true
    accessModes:
    - ReadWriteOnce
    size: 200Gi
promtail:
  enabled: true
  extraArgs:
     - -client.url=https://loki-server.example.com/loki/api/v1/push
```

Still throws the same issue mentioned above. Any help would be appreciate it!

**Comment by JihadMotii-REISys** [comment]
After several tries, I was able to override it but I''m not sure if it is the right way to do it. Here is how it worked for me:

```
loki:
  enabled: true
  ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: loki-server.example.com
        paths:
          - /
    tls:
      - secretName: loki-server.example.com
        hosts:
          - loki-server.example.com
  persistence:
    enabled: true
    accessModes:
    - ReadWriteOnce
    size: 200Gi
promtail:
  enabled: true
  config:
    client:
      url: "https://loki-server.example.com/loki/api/v1/push"
```
If anyone knows or confirm if this is the right way, will be great. Thanks!
