### ISSUE TITLE
loki-mixin-compiled-ssd not fully working

### ISSUE THREAD

**Issue by MaxDiOrio** [grafana/helm-charts#2047]
I have Loki simple scalable deployed, however the mixing for SSD dashboards don't seem to work.  Especially the Operational dashboard.  

For example, the Queries/Second graph fails because there is no job label containing "$namespace/coretex-gw(-internal)?"

```
sum by (status) (
label_replace(
  label_replace(
        rate(loki_request_duration_seconds_count{cluster="$cluster", job=~"$namespace/cortex-gw(-internal)?", route=~"api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values"}[5m]),
  "status", "${1}xx", "status_code", "([0-9]).."),
"status", "${1}", "status_code", "([a-z]+)")
)
```

My monitoring section in the helm deployment looks like:
```
monitoring:
  dashboards:
    namespace: grafana
  rules:
    enabled: true
    alerting: true
    namespace: monitoring
  serviceMonitor:
    enabled: true
    metricsInstance:
      enabled: true
      remoteWrite:
        - url: http://prometheus-server.monitoring.svc.cluster.local/api/v1/write
  selfMonitoring:
    enabled: true
    grafanaAgent:
      installOperator: false
    lokiCanary:
      enabled: false
```

It doesn't appear that all metrics are being scraped, or there's maybe an endpoint missing?  

SSD has deployed 3 read pods, and 3 write pods and 2 gateway pods.  

Any ideas?  It doesn't appear to work out of the box.
