### ISSUE TITLE
Grafana: Datasource basicAuthPassword not read from Secret

### ISSUE THREAD

**Issue by maaft** [grafana/helm-charts#2088]
To add a 2nd prometheus datasource protected by basicAuth, I've got a k8s secret with following content:

```yaml
apiVersion: 1
datasources:
- name: Prometheus-Main
  type: prometheus
  uid: prometheus-main
  url: <url>
  access: proxy
  basicAuth: true
  basicAuthUser: <user>
  basicAuthPassword: <password>
  version: 1
  editable: true
```

When grafana is started, the datasource is loaded correctly by the datasource-sidecar. Except the `basicAuthPassword`: When viewing a metric from that datasource, grafana will ask me for basic-auth credentials (via javascript popup). When I enter the credentials, some template error appears.

When I edit the datasource manually (via Grafana Settings UI) and enter the password, everything works.

Did I miss something? Thanks!

**Comment by pablokbs** [comment]
`basicAuthPassword` must be inside `secureJsonData`, it took me a while to realize this, but it's on the [Grafana docs](https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file)

So in your case should be:

```
apiVersion: 1
datasources:
- name: Prometheus-Main
  type: prometheus
  uid: prometheus-main
  url: <url>
  access: proxy
  basicAuth: true
  basicAuthUser: <user>
  secureJsonData:
    basicAuthPassword: <password>
  version: 1
  editable: true
  ```

Good luck!
