### ISSUE TITLE
[loki-stack] private environment set registry values

### ISSUE THREAD

**Issue by willzhang** [grafana/helm-charts#2093]
how to set registry values in private environment , this not work

```
loki-stack.values.yaml
loki:
  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 7d
  global:
    image:
      registry: 192.168.72.16
```
