### ISSUE TITLE
[tempo-distributed] enterprise traces admin client section is only available with MinIO

### ISSUE THREAD

**Issue by hedss** [grafana/helm-charts#2112]
The `values.yaml` only includes admin client storage when minio is configured:
```
{{- if .Values.minio.enabled }}
  admin_client:
    storage:
      backend: s3
      s3:
        access_key_id: {{ .Values.minio.rootUser }}
        bucket_name: enterprise-traces-admin
        endpoint: {{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc:9000
        insecure: true
        secret_access_key: {{ .Values.minio.rootPassword }}
    {{- end }}
```
See https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/values.yaml#L708

This should be configured in a similar manner to the trace storage configuration, eg. with S3, Azure or GCS configurations as well.
