### ISSUE TITLE
Automatic provisioning of Cortex DataSource does not work with BasicAuth - works when added manually via Web-UI

### ISSUE THREAD

**Issue by sebschlue** [grafana/helm-charts#2122]
helm chart version: 6.49.0

helm chart values:

```
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: CortexDev
      orgId: 1
      type: prometheus
      access: proxy
      url: http://cortex-nginx.monitoring.svc.cluster.local/api/prom
      basicAuth: true
      basicAuthUser: dev
      jsonData:
        httpMethod: POST
        httpHeaderName1: X-Scope-OrgID
      secureJsonData:
        basicAuthPassword: dev
        httpHeaderValue1: dev

grafana.ini:
  log:
    level: debug
```

This automatically provisioned DataSource seems to work fine at first glance: "Test" button in DataSources view reports a successful test.

But "explore" view in Grafana does not work with this DataSource

Error in log is:

```
logger=context t=2023-01-13T11:52:07.305362468Z level=debug msg="Failed to authorize the user" username=dev err="user not found"
logger=context t=2023-01-13T11:52:07.306158296Z level=error msg="invalid username or password" error="invalid username or password" traceID=```

When manually adding asnother DataSource (with different name and identical settings) via Web-UI, it works fine.

```
I cannot find any differences regarding the DataSource itself, so I think there must be something else that needs to be done for these automatically provisioned DataSources to work.

```
[
  {
    "id": 1,
    "uid": "PD583969D6B3E89EE",
    "orgId": 1,
    "name": "CortexDEV",
    "type": "prometheus",
    "typeName": "Prometheus",
    "typeLogoUrl": "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg",
    "access": "proxy",
    "url": "http://cortex-nginx.monitoring.svc.cluster.local/api/prom",
    "user": "",
    "database": "",
    "basicAuth": true,
    "isDefault": false,
    "jsonData": {
      "httpHeaderName1": "X-Scope-OrgID",
      "httpMethod": "POST",
      "prometheusType": "Cortex",
      "prometheusVersion": "1.14.0"
    },
    "readOnly": true
  },
  {
    "id": 2,
    "uid": "DQkHDUhVk",
    "orgId": 1,
    "name": "DEV2",
    "type": "prometheus",
    "typeName": "Prometheus",
    "typeLogoUrl": "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg",
    "access": "proxy",
    "url": "http://cortex-nginx.monitoring.svc.cluster.local/api/prom",
    "user": "",
    "database": "",
    "basicAuth": true,
    "isDefault": false,
    "jsonData": {
      "httpHeaderName1": "X-Scope-OrgID",
      "httpMethod": "POST",
      "prometheusType": "Cortex",
      "prometheusVersion": "1.14.0"
    },
    "readOnly": false
  }
]
```
