### ISSUE TITLE
The loki cluster is destroyed with an error "too many failed ingesters"

### ISSUE THREAD

**Issue by osipovdaniil** [grafana/helm-charts#213]
**Description problem:**

Hi there! I have loki cluster with 3 replicas and connected via a `heandless-service`. But periodically, the error appears once a month and cluster loki is not working. 
In the logs we see on all 3 pods loki:
```
level=warn ts=2021-02-11T14:59:29.462314256Z caller=logging.go:71 traceID=7ac15fcd10a5661e msg="POST /loki/api/v1/push (500) 3.971371ms Response: \"at least 1 live replicas required, could only find 0\\n\" ws: false; Content-Length: 29378; Content-Type: application/x-protobuf; User-Agent: promtail/2.1.0; "
level=warn ts=2021-02-11T14:59:33.319156706Z caller=logging.go:71 traceID=47873591b8ea2a3e msg="POST /loki/api/v1/push (500) 3.981686ms Response: \"at least 1 live replicas required, could only find 0\\n\" ws: false; Content-Length: 29378; Content-Type: application/x-protobuf; User-Agent: promtail/2.1.0; "
level=error ts=2021-02-11T14:59:35.968466049Z caller=pool.go:161 msg="error removing stale clients" err="too many failed ingesters"
level=error ts=2021-02-11T14:59:35.972614805Z caller=pool.go:161 msg="error removing stale clients" err="too many failed ingesters"
level=warn ts=2021-02-11T14:59:38.092933861Z caller=logging.go:71 traceID=1cd86150caf21b45 msg="POST /loki/api/v1/push (500) 4.154229ms Response: \"at least 1 live replicas required, could only find 0\\n\" ws: false; Content-Length: 29378; Content-Type: application/x-protobuf; User-Agent: promtail/2.1.0; "
```

![Снимок экрана 2021-02-11 в 17 59 46](https://user-images.githubusercontent.com/73994399/107664195-37fe2580-6c9d-11eb-99a8-cab853df5389.png)

At this time time, pods in state `running` and don't failure or restarts.
If i restart pods - then work is corectly.

**Environment:**

* Loki running on manage cloud kubernetes, deploy with helm.
* Version chart: 2.3.0
* Version loki: 2.1.0

**Configuration in values file**
```
replicas: 3
resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 256Mi
service:
  type: LoadBalancer
serviceMonitor:
  enabled: true
config:
  storage_config:
    boltdb_shipper:
      shared_store: s3
    aws:
      s3: s3://<path to s3 bucket>
      s3forcepathstyle: true
  ruler:
    alertmanager_url: <url>
  distributor:
    ring:
      kvstore:
        store: memberlist
  ingester:
    lifecycler:
      ring:
        kvstore:
          store: memberlist
        replication_factor: 1
      final_sleep: 0s
    chunk_idle_period: 5m
    chunk_retain_period: 30s
  memberlist:
    join_members:
    - loki-headless
    max_join_backoff: 3m
    max_join_retries: 50
    min_join_backoff: 1s
    leave_timeout: 30s
  limits_config:
    reject_old_samples: false
  schema_config:
    configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h
  ruler:
    storage:
      type: local
      local:
        directory: /rules
    rule_path: /tmp/scratch
    ring:
      kvstore:
        store: inmemory
    enable_api: true
alerting_groups:
  - name: Loki-Alerts
    rules:
      <My alerst>
```

**Question:**
What parameters can be tuning to work more availability? Why does the cluster collapse?
