### ISSUE TITLE
field embedded_cache not found in type local.FSConfig

### ISSUE THREAD

**Issue by patsevanton** [grafana/helm-charts#2133]
Hello! Thanks for loki!

I get error
```
failed parsing config: /etc/loki/config/config.yaml: yaml: unmarshal errors:
  line 99: field embedded_cache not found in type local.FSConfig
```
My flux config:
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: grafana
  namespace: loki
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  install:
    remediation:
      retries: 3 # NB: setting it to `-1` results in infinite retries
  chart:
    spec:
      chart: loki-distributed
      version: 0.69.0
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    global:
      image:
        registry: "harbor.mos.corp/dockerhub"
    gateway:
      enabled: false
    ingress:
      enabled: true
      ingressClassName: nginx
#      annotations:
#        nginx.ingress.kubernetes.io/proxy-send-timeout: "9000"
#        nginx.ingress.kubernetes.io/proxy-read-timeout: "9000"
#        nginx.ingress.kubernetes.io/proxy-connect-timeout: "9000"
#        nginx.ingress.kubernetes.io/client-header-timeout: "9000"
#        nginx.ingress.kubernetes.io/client-body-timeout: "9000"
#        nginx.ingress.kubernetes.io/proxy-request-buffering: off
      paths:
        distributor:
          - /api/prom/push
          - /loki/api/v1/push
        querier:
          - /api/prom/tail
          - /loki/api/v1/tail
        query-frontend:
          - /loki/api
        ruler:
          - /api/prom/rules
          - /loki/api/v1/rules
          - /prometheus/api/v1/rules
          - /prometheus/api/v1/alerts
      hosts:
        - loki-k8s.mos.corp
    serviceMonitor:
      enabled: true
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3100'
      labels:
        release: prometheus-operator
    compactor:
      enabled: true
      persistence:
        enabled: true
        storageClass: yc-network-ssd
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "384Mi"
          cpu: "200m"
    distributor:
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 4
        targetCPUUtilizationPercentage: 60
        targetMemoryUtilizationPercentage: 80
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "200m"
      maxUnavailable: 1
    ingester:
      persistence:
        enabled: true
        storageClass: yc-network-ssd
      affinity: {}
      autoscaling:
        enabled: true
        minReplicas: 5
        maxReplicas: 12
        targetCPUUtilizationPercentage: 60
        targetMemoryUtilizationPercentage: 80
      resources:
        requests:
          memory: "1512Mi"
          cpu: "100m"
        limits:
          memory: "4096Mi"
          cpu: "600m"
      maxUnavailable: 2
    indexGateway:
      enabled: true
      persistence:
        enabled: true
        storageClass: yc-network-ssd
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
      maxUnavailable: 1
    queryScheduler:
      enabled: true
    querier:
      autoscaling:
        enabled: true
        minReplicas: 6
        maxReplicas: 8
        targetCPUUtilizationPercentage: 60
        targetMemoryUtilizationPercentage: 80
      resources:
        requests:
          memory: "1024Mi"
          cpu: "100m"
        limits:
          memory: "4096Mi"
          cpu: "1000m"
      maxUnavailable: 2
    queryFrontend:
      # extraArgs: ['-log.level=debug']
      affinity: {}
      autoscaling:
        enabled: true
        minReplicas: 3
        maxReplicas: 6
        targetCPUUtilizationPercentage: 60
        targetMemoryUtilizationPercentage: 80
      resources:
        requests:
          memory: "256Mi"
          cpu: "150m"
        limits:
          memory: "512Mi"
          cpu: "200m"
      maxUnavailable: 1
    memcached:
      image:
        repository: library/memcached
    loki:
      structuredConfig:
        ingester:
          # Disable chunk transfer which is not possible with statefulsets
          # and unnecessary for boltdb-shipper
          max_transfer_retries: 0
          chunk_idle_period: 1h
          chunk_target_size: 1536000
          max_chunk_age: 1h
        storage_config:
          aws:
            s3: s3://xxxxxx:xxxxxxxxx@storage.xxxxx.xxxxx/
            bucketnames: xxxxx-core-dev-loki
          boltdb_shipper:
            shared_store: s3
        schema_config:
          configs:
            - from: "2020-09-07"
              store: boltdb-shipper
              object_store: s3
              schema: v11
              index:
                prefix: loki_index_
                period: 24h
      config: |
        auth_enabled: false
        server:
          http_listen_port: 3100
          http_server_read_timeout: 150m
          http_server_write_timeout: 150m
        common:
          compactor_address: {{ include "loki.compactorFullname" . }}:3100
        distributor:
          ring:
            kvstore:
              store: memberlist
        memberlist:
          join_members:
            - {{ include "loki.fullname" . }}-memberlist
        ingester:
          lifecycler:
            ring:
              kvstore:
                store: memberlist
              replication_factor: 1
          chunk_idle_period: 30m
          chunk_block_size: 262144
          chunk_encoding: snappy
          chunk_retain_period: 1m
          max_transfer_retries: 0
          wal:
            dir: /var/loki/wal
        limits_config:
          ingestion_rate_mb: 10000
          ingestion_burst_size_mb: 1000
          max_global_streams_per_user: 10000
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          max_cache_freshness_per_query: 10m
          split_queries_by_interval: 15m
          retention_period: 336h
        {{- if .Values.loki.schemaConfig}}
        schema_config:
        {{- toYaml .Values.loki.schemaConfig | nindent 2}}
        {{- end}}
        {{- if .Values.loki.storageConfig}}
        storage_config:
        {{- if .Values.indexGateway.enabled}}
        {{- $indexGatewayClient := dict "server_address" (printf "dns:///%s:9095" (include "loki.indexGatewayFullname" .)) }}
        {{- $_ := set .Values.loki.storageConfig.boltdb_shipper "index_gateway_client" $indexGatewayClient }}
        {{- end}}
        {{- toYaml .Values.loki.storageConfig | nindent 2}}
        {{- if .Values.memcachedIndexQueries.enabled }}
          index_queries_cache_config:
            memcached:
              batch_size: 100
              parallelism: 100
            memcached_client:
              consistent_hash: true
              host: {{ include "loki.memcachedIndexQueriesFullname" . }}
              service: memcached-client
        {{- else}}
            embedded_cache:
              enabled: true
        {{- end}}
        {{- end}}

        runtime_config:
          file: /var/{{ include "loki.name" . }}-runtime/runtime.yaml
        chunk_store_config:
          max_look_back_period: 0s
        table_manager:
          retention_deletes_enabled: false
          retention_period: 0s
        query_range:
          align_queries_with_step: true
          max_retries: 5
          cache_results: true
          results_cache:
            cache:
              {{- if .Values.memcachedFrontend.enabled }}
              memcached_client:
                consistent_hash: true
                host: {{ include "loki.memcachedFrontendFullname" . }}
                max_idle_conns: 16
                service: memcached-client
                timeout: 500ms
                update_interval: 1m
              {{- else }}
              embedded_cache:
                enabled: true
                ttl: 24h
              {{- end }}
        frontend_worker:
          {{- if .Values.queryScheduler.enabled }}
          scheduler_address: {{ include "loki.querySchedulerFullname" . }}:9095
          {{- else }}
          frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095
          {{- end }}
        frontend:
          log_queries_longer_than: 5s
          compress_responses: true
          {{- if .Values.queryScheduler.enabled }}
          scheduler_address: {{ include "loki.querySchedulerFullname" . }}:9095
          {{- end }}
          tail_proxy_url: http://{{ include "loki.querierFullname" . }}:3100
        compactor:
          shared_store: s3
          compaction_interval: 10m
          retention_enabled: true
          retention_delete_delay: 2h
          retention_delete_worker_count: 150
        ruler:
          storage:
            type: local
            local:
              directory: /etc/loki/rules
          ring:
            kvstore:
              store: memberlist
          rule_path: /tmp/loki/scratch
          alertmanager_url: https://alertmanager.xx
          external_url: https://alertmanager.xx
  interval: 5m0s
  releaseName: loki
  targetNamespace: loki
```

My config /etc/loki/config/config.yaml in pod loki-loki-distributed-query-scheduler
```
auth_enabled: false
chunk_store_config:
  max_look_back_period: 0s
common:
  compactor_address: loki-loki-distributed-compactor:3100
compactor:
  compaction_interval: 10m
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  retention_enabled: true
  shared_store: s3
distributor:
  ring:
    kvstore:
      store: memberlist
frontend:
  compress_responses: true
  log_queries_longer_than: 5s
  scheduler_address: loki-loki-distributed-query-scheduler:9095
  tail_proxy_url: http://loki-loki-distributed-querier:3100
frontend_worker:
  scheduler_address: loki-loki-distributed-query-scheduler:9095
ingester:
  chunk_block_size: 262144
  chunk_encoding: snappy
  chunk_idle_period: 1h
  chunk_retain_period: 1m
  chunk_target_size: 1536000
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
  max_chunk_age: 1h
  max_transfer_retries: 0
  wal:
    dir: /var/loki/wal
limits_config:
  enforce_metric_name: false
  ingestion_burst_size_mb: 1000
  ingestion_rate_mb: 10000
  max_cache_freshness_per_query: 10m
  max_global_streams_per_user: 10000
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 336h
  split_queries_by_interval: 15m
memberlist:
  join_members:
  - loki-loki-distributed-memberlist
query_range:
  align_queries_with_step: true
  cache_results: true
  max_retries: 5
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        ttl: 24h
ruler:
  alertmanager_url: https://alertmanager.xx
  external_url: https://alertmanager.xx
  ring:
    kvstore:
      store: memberlist
  rule_path: /tmp/loki/scratch
  storage:
    local:
      directory: /etc/loki/rules
    type: local
runtime_config:
  file: /var/loki-distributed-runtime/runtime.yaml
schema_config:
  configs:
  - from: "2020-09-07"
    index:
      period: 24h
      prefix: loki_index_
    object_store: s3
    schema: v11
    store: boltdb-shipper
server:
  http_listen_port: 3100
  http_server_read_timeout: 150m
  http_server_write_timeout: 150m
storage_config:
  aws:
    bucketnames: xxxxxxxxx-core-dev-loki
    s3: s3://xxxxxxxxxxxxxxxxx@storage.xxxxx.xxxxxxx/
  boltdb_shipper:
    active_index_directory: /var/loki/index
    cache_location: /var/loki/cache
    cache_ttl: 168h
    index_gateway_client:
      server_address: dns:///loki-loki-distributed-index-gateway:9095
    shared_store: s3
  filesystem:
    directory: /var/loki/chunks
    embedded_cache:
      enabled: true
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
```
