### ISSUE TITLE
[Grafana] Add configurable endpoint value enableHttp2 to ServiceMonitor

### ISSUE THREAD

**Issue by Shwethamuralikrishnaa** [grafana/helm-charts#2138]
We need to configure this endpoint value `enableHttp2` in ServiceMonitor

```yaml
spec:
  endpoints:
    - enableHttp2: false
```

Ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml#L155
