### ISSUE TITLE
initPlugins for plugins init container doesn't work.

### ISSUE THREAD

**Issue by hkailantzis** [grafana/helm-charts#2145]
```
sidecar:
    image:
      tag: 1.22.1
    plugins: 
      enabled: true
      label: grafana_custom
      labelValue: "1"
      resource: configmap
      initPlugins: true
 ```

seems that the check is missing from:

https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/_pod.tpl#L20
