### ISSUE TITLE
login button with door does not keep /sub-path

### ISSUE THREAD

**Issue by jessegoodier** [grafana/helm-charts#2159]
The link on the bottom left (the door icon) does not keep the path.

All other links work, and login works by clicking on the grafana logo.
This is the door icon with broken link: 
![image](https://user-images.githubusercontent.com/31039225/215169222-f29fac06-f51e-467f-9327-314e724a2757.png)

settings:

```
  auth.anonymous:
    enabled: true
    org_role:  Editor
    org_name: Main Org.
```

```
grafana.ini:
    server:
      serve_from_sub_path: true
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
```

```
link targets:
http://localhost:9090/dashboards?forceLogin=true
should target:
http://localhost:9090/grafana/dashboards?forceLogin=true
```

Please let me know if I should try something different or if you need any details.
