### ISSUE TITLE
Loki-Stack: Custom values for subcharts

### ISSUE THREAD

**Issue by hutger** [grafana/helm-charts#2161]
Hi There, 

Maybe a silly question, but I deploying Loki using Loki-Stack helm chart (https://artifacthub.io/packages/helm/grafana/loki-stack), which bundles Loki and Promtail.

I'm looking for a way to pass custom values for Loki, as you can see below, but Helm is ignoring the `write` and `read` definitions. 

How can pass those values settings to Loki downstream chart?

```yaml
---
apiVersion: v2
name: loki-stack
version: 1.0.0
dependencies:
  - name: loki-stack
    version: 2.8.9
    repository: https://grafana.github.io/helm-charts

---
loki-stack:
  loki:
    enable: true
    # The value below "config" must be a string instead of a map
    config:
      existingSecret: loki

  write:
    replicas: 2
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
      targetCPUUtilizationPercentage: 60
      targetMemoryUtilizationPercentage: 80
    persistence:
      size: 5Gi
      storageClass: longhorn
    resources:
      limits:
        #cpu: 400m
        memory: 1200Mi 
      requests:
        cpu: 35m
        memory: 300Mi

  read:
    replicas: 2
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
      targetCPUUtilizationPercentage: 60
      targetMemoryUtilizationPercentage: 80
    persistence:
      size: 1Gi
      storageClass: longhorn
    resources:
      limits:
        #cpu: 400m
        memory: 150Mi
      requests:
        cpu: 50m
        memory: 75Mi

  serviceMonitor:
    enabled: true
```
