### ISSUE TITLE
labeling grafana_notifier won't pick up the notifier

### ISSUE THREAD

**Issue by nickhalden** [grafana/helm-charts#218]
`grafana_notifier` for a sidecar in the same namespaces is not picking up the notifier, can someone point out if that's a bug or needs to be added in the template? I see the notifier sidecar created but it does not pick up the following

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: slack-notifier
  labels:
     grafana_notifier: "1"
     namespace: monitoring
data:
  notifierslack.yaml: |
    notifiers:
    - is_default: false
      name: slack-alertsd
      org_id: 1
      settings:
        uploadImage: false
        url: https://hooks.slack.com/services/token
      type: slack
      uid: slack

```

logs sidecar notifier:
```

[2021-02-13 02:45:51] Starting collector
[2021-02-13 02:45:51] No folder annotation was provided, defaulting to k8s-sidecar-target-directory
[2021-02-13 02:45:51] Selected resource type: ('secret', 'configmap')
[2021-02-13 02:45:51] Config for cluster api loaded...
[2021-02-13 02:45:51] Unique filenames will not be enforced.
```

**Comment by nickhalden** [comment]
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: slack-notifier
  labels:
     grafana_notifier: "1"
     namespace: monitoring
data:
  notifierslack.yaml: |
    notifiers:
    - is_default: false
      name: slack-alertsd
      org_id: 1
      settings:
        uploadImage: false
        url: https://hooks.slack.com/services/token
      type: slack
      uid: slack

```
