### ISSUE TITLE
Deploying Helm Chart Doesn't Spin Up Additional Grafana Agents Log Pods

### ISSUE THREAD

**Issue by byronmansfield** [grafana/helm-charts#2180]
Hello. So I have deployed the grafana/grafana-agent-operator helm chart version 0.2.9 and 0.2.10 to a EKS clusters 1.23 and 1.24. Both had the grafana/loki helm chart version 4.4.2 deployed to it. And I'm not seeing any additional grafana-agent-log pods spin up after I deploy a `GrafanaAgent`, `LogsInstance`, and `PodLogs`. Here are my custom values.

Loki Helm Chart:
```
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  storage:
    type: filesystem
monitoring:
  selfMonitoring:
    grafanaAgent:
      installOperator: false
read:
  replicas: 1
write:
  replicas: 1
```

Grafana Agent Operator Helm Values:
```
extraArgs:
- --log.level=debug
kubeletService:
  namespace: monitoring
resources:
  limits:
    cpu: 1000m
    memory: 4096Mi
  requests:
    cpu: 500m
    memory: 2048Mi
```
I should mention, I already have a Grafana running (with the official helm chart), and have added the Loki datasource, and ran a test. It comes back as successful and seems to be able to communicate with http://loki.monitoring.svc.cluster.local:3100 just fine.

I've followed along with the docs from:
https://grafana.com/docs/agent/latest/operator/getting-started/
https://grafana.com/docs/agent/latest/operator/helm-getting-started/
https://grafana.com/docs/agent/latest/operator/deploy-agent-operator-resources/

I'm still not having any success. After discussing with a friend who has successfully deployed this, he has told me that the grafana-agent-operator is suppose to be spinning up additional grafana-agent log pods. And I believe a statefulset of just a grafana-agent-0 pod. Maybe grafana-agent-integrations pods too? But I'm only seeing just the single Deployment pod of grafana-agent-operator and nothing more.

I've noticed that my loki helm chart has deployed a `GrafanaAgent` resource and a `LogsInstances` resource. Are they suppose to be there?

While searching the web and forums, I've also noticed the https://github.com/grafana/agent/tree/helm-chart/0.4.0/operations/helm/charts/grafana-agent helm chart. I'm very confused as to what the difference is and when or why I'd one to use one vs the other, or if I need to use both. Can anyone tell me why I'm not seeing these additional pods and what else I might do to troubleshoot why I'm not. Here are the debug logs from my only grafana-agent-operator pod

```
level=debug ts=2023-02-02T20:22:11.282413791Z controller=node controllerGroup= controllerKind=Node Node="unsupported value type" namespace= name=ip-10-115-5-34.us-west-2.compute.internal reconcileID=bb3bfe62-c565-4df2-85f8-7c9d7cc01f56 msg="reconciling kubelet endpoints" eps=monitoring/kubelet
level=info ts=2023-02-02T20:22:13.939596308Z controller=node controllerGroup= controllerKind=Node Node="unsupported value type" namespace= name=ip-10-115-4-146.us-west-2.compute.internal reconcileID=d8d6c126-41f4-441c-96ef-cccc42305ce6 msg="reconciling node"
level=debug ts=2023-02-02T20:22:13.939734502Z controller=node controllerGroup= controllerKind=Node Node="unsupported value type" namespace= name=ip-10-115-4-146.us-west-2.compute.internal reconcileID=d8d6c126-41f4-441c-96ef-cccc42305ce6 msg="reconciling kubelet service" svc=monitoring/kubelet
level=debug ts=2023-02-02T20:22:13.94981434Z controller=node controllerGroup= controllerKind=Node Node="unsupported value type" namespace= name=ip-10-115-4-146.us-west-2.compute.internal reconcileID=d8d6c126-41f4-441c-96ef-cccc42305ce6 msg="reconciling kubelet endpoints" eps=monitoring/kubelet
```

Should I worry about this `"unsupported value type"`? What other details can I provide in order to answer my question(s)?

**Comment by byronmansfield** [comment]
I finally was able to get grafana-agent pods spinning up once I corrected some of my RBAC configurations. I'm sorry I cannot pin point exactly what the issue was. I deleted the serviceaccount, roles, and rolebindings several times and reapplied. Inspecting my current values they look the same as the [documentation suggests](https://grafana.com/docs/agent/latest/operator/deploy-agent-operator-resources/#deploy-the-grafanaagent-resource). With the exception of the namespace.

One thing which when I originally opened the ticket that I did not understand, and it could have been part of my issue. Is I didn't understand that you need the `LogsInstance` up first, before you start seeing any `grafana-agent-logs-*` pods. Or at least a successfully configured one. After switching from the regular loki helm chart to the loki-distributed, I configured my `LogsInstance` like so

```
apiVersion: monitoring.grafana.com/v1alpha1
kind: LogsInstance
metadata:
  name: primary
  namespace: monitoring
  labels:
    agent: grafana-agent-logs
spec:
  clients:
  - url: http://loki-loki-distributed-gateway.monitoring.svc.cluster.local/loki/api/v1/push
    externalLabels:
      k8s_cluster: core

  podLogsNamespaceSelector: {}
  podLogsSelector:
    matchLabels:
      instance: primary
```

My loki-distrubted is almost completely vanilla with the values

```
gateway:
  maxUnavailable: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: gateway.loki.example.com
        paths:
          - path: /
            pathType: Prefix
```
If anyone else deploys the operator helm chart, and a loki helm chart, and do not see any grafana-agent pods. Maybe this will help.

Closing issue now.
