### ISSUE TITLE
Drop function is not working in promtail configuration

### ISSUE THREAD

**Issue by shreymarkandey-srijan** [grafana/helm-charts#2183]
```
promtail:
  enabled: true
  #
  # Enable Promtail service monitoring
  # serviceMonitor:
  #   enabled: true
  #
  # User defined pipeline stages
  pipelineStages:
    - docker: {}
    - drop:
        source: namespace
        expression: "kube-.*"
```

Updating it still kube-system logs are showing in loki & if I replace it with any other NS then also loki is showing it

**Comment by shreymarkandey-srijan** [comment]
any updates team?

**Comment by shreymarkandey-srijan** [comment]
??? Please can anyone help

**Comment by furst** [comment]
Try:
```yaml
promtail:
  enabled: true

  config:
    snippets:
      pipelineStages:
        - docker: {}
        - drop:
            source: namespace
            expression: "kube-.*"
```

**Comment by shreymarkandey-srijan** [comment]
ya It worked thanks a lot @furst . But can you help in dropping logs from loki its not collecting logs but its been seen in loki can I remove that namespace with any query or any sort of API?

**Comment by furst** [comment]
@shreymarkandey-srijan could you elaborate on the problem?

**Comment by shreymarkandey-srijan** [comment]
> @shreymarkandey-srijan could you elaborate on the problem?
in loki, kube-system namespace  label is still visible how to drop that ?
logs are not  visible but label of kube-system is visible

**Comment by furst** [comment]
@shreymarkandey-srijan the label should disappear once the logs are cleaned up(defined via the retention policy)

**Comment by shreymarkandey-srijan** [comment]
hello @furst  could you give me loki-stack values to enable retention period of 7 days?

**Comment by furst** [comment]
For example:
```yaml
loki:
  enabled: true

  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 7d
```
