### ISSUE TITLE
Loki chart + singleBinary not working, spams `loki-logs-xxxx` pods that gets terminated right away.

### ISSUE THREAD

**Issue by mgcrea** [grafana/helm-charts#2193]
Not sure if I'm doing something wrong but tried to migrate a cluster to the latest chart version (was on 2.x) to latest `4.6.0`.

Once deployed, the namespace gets spammed with created pods that do crash right away: eg.

```
Failed to load logs: container "config-reloader" in pod "loki-logs-ffzcz" is terminated
Reason: BadRequest (400)
```

Any idea what could be going on?

Using the following simple `values.yml`: 

```yaml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'
  hosts:
    - loki.foobar.fr
  tls:
    - hosts:
        - loki.foobar.fr
      secretName: loki-foobar-fr-tls

gateway:
  enabled: false

loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
singleBinary:
  replicas: 1
```

<img width="746" alt="Screenshot 2023-02-10 at 15 58 43" src="https://user-images.githubusercontent.com/108273/218123341-81159590-35c6-46c1-bd09-adff967dda66.png">
