### ISSUE TITLE
loki-stack spam logs

### ISSUE THREAD

**Issue by oxycoder** [grafana/helm-charts#2196]
I am getting a lot of logs below
```
│ grafana t=2023-02-12T11:04:40+0000 lvl=warn msg="[Deprecated] the datasource provisioning config is outdated. please upgrade" logger=provisioning.datasources filename=/etc/grafana/provisioning/datasources/alerting_rules.yml            │
│ grafana t=2023-02-12T11:04:40+0000 lvl=warn msg="[Deprecated] the datasource provisioning config is outdated. please upgrade" logger=provisioning.datasources filename=/etc/grafana/provisioning/datasources/alertmanager.yml              │
│ grafana t=2023-02-12T11:04:40+0000 lvl=warn msg="[Deprecated] the datasource provisioning config is outdated. please upgrade" logger=provisioning.datasources filename=/etc/grafana/provisioning/datasources/loki.yaml                     │
│ grafana t=2023-02-12T11:04:40+0000 lvl=warn msg="[Deprecated] the datasource provisioning config is outdated. please upgrade" logger=provisioning.datasources filename=/etc/grafana/provisioning/datasources/prometheus.yml                │
│ grafana t=2023-02-12T11:04:40+0000 lvl=warn msg="[Deprecated] the datasource provisioning config is outdated. please upgrade" logger=provisioning.datasources filename=/etc/grafana/provisioning/datasources/promtail.yaml                 │
│ grafana t=2023-02-12T11:04:40+0000 lvl=warn msg="[Deprecated] the datasource provisioning config is outdated. please upgrade" logger=provisioning.datasources filename=/etc/grafana/provisioning/datasources/recording_rules.yml 
```

Reproduce:
`value.yaml` file
```
test_pod:
  enabled: false

promtail:
  enabled: true

grafana:
  enabled: true

prometheus:
  enabled: true

loki:
  persistence:
    enabled: true
    storageClassName: ""
    size: 5Gi
```
Helm command:
```
helm upgrade --install monitor grafana/loki-stack -f values.yaml -n app-monitor --create-namespace
```
