### ISSUE TITLE
cannot install plugins using sidecar.

### ISSUE THREAD

**Issue by AkshayAwate** [grafana/helm-charts#2197]
Hello , i was trying to install grafana plugins using grafana sidecar, so i enabled plugin flags in grafana values.yaml as
```
sidecar:
  plugins:
    enabled: true
    label: grafana_plugin
    labelValue: "1"
    resource: configmap
```
and created configmap with above label and label value as
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: plugin-cm
  labels:
    grafana_plugin: "1"
data:
  plugins: satellogic-3d-globe-panel,macropower-analytics-panel
```
and i was able to list plugins inside sidecar container in **cat /etc/grafana/provisioning/plugins/plugins**  as **satellogic-3d-globe-panel,macropower-analytics-panel** But i was not able to find the same from grafana UI:smiling_face_with_tear:. Any suggestions/help would be appreciated.
