### ISSUE TITLE
How to change the embedded sqlite db to external sqlite or Postgres or mysql

### ISSUE THREAD

**Issue by vmalhotra22** [grafana/helm-charts#22]
Hi,

I am trying to look for a way to change the embedded data storage in sqlite to external one created by me.
It could be anything from sqlite or Postgres or mysql.

Also how I can access the sqlite data from inside the container?

Appreciate the timely help.

Cheers

**Comment by te4336** [comment]
Yeah this is sorely needed along with how to utilize an external cache such as redis or memcached.

**Comment by te4336** [comment]
I believe that is set in the actual grafana config. Should be able to set that up as a config map and then in the helm chart have it mounted as a volume.

**Comment by ramrengaswamy** [comment]
Something like the following should work.
https://grafana.com/docs/grafana/latest/administration/configuration/#database
```
  grafana.ini:
    database:
      type: postgres
      host: ${db_host}
      user: ${db_user}
      password: ${db_password}
```
