### ISSUE TITLE
Grafana reports "Error loading Alertmanager config" when routing_key_file is used for PagerDuty config

### ISSUE THREAD

**Issue by johnswarbrick-napier** [grafana/helm-charts#2212]
When AlertManager is configured with `routing_key_file` Grafana shows an error:

![image](https://user-images.githubusercontent.com/105818625/219215477-18877652-b4e7-4695-bfae-52206445b260.png)

Changing `routing_key_file` to `routing_key` allows Grafana to show AlertManager, but then sensitive keys are held in the values.yaml file instead of loaded as a Kubernetes Secret.

Charts:

```
  - name: kube-prometheus-stack
    version: "45.0.0"
    repository: https://prometheus-community.github.io/helm-charts

  - name: "grafana"
    version: "6.50.7"
    repository: "https://grafana.github.io/helm-charts"
```

Config:

```
      receivers:
        - name: 'null' # Required by default "WatchDog" monitor

        - name: 'Pager Duty'
          pagerduty_configs:
          - send_resolved: true
            routing_key_file: '/etc/alertmanager/secrets/aml-monitoring-pagerduty/routing_key'
            description: "{{ range .Alerts }}{{ if .Annotations.description }}{{ .Annotations.description }}{{ else }}{{ .Labels.alertname }}{{ end }}{{ end }}"
            severity: "{{ if .CommonLabels.severity }}{{ .CommonLabels.severity | toLower }}{{ else }}critical{{ end }}"
```
