### ISSUE TITLE
fluent-bit: failed to parse some of kubernetes audit logs 

### ISSUE THREAD

**Issue by apfols** [grafana/helm-charts#222]
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: andrew.corp.ailabs.tw
    http:
      paths:
      - path: /test/?(.*)
        backend:
          serviceName: nginx
          servicePort: 80
```

I turned on kubernetes audit log. Some of logs can be parsed successfully and some cannot, e.g. full request log of creating above ingress. However, it's no problem if I manually turned off `Merge_Log` in configmap. 

Not sure if there is any plan to fix https://github.com/grafana/helm-charts/issues/184 or just simply make Merge_Log to be configurable.
