### ISSUE TITLE
tempo query frontend will crash once enable query

### ISSUE THREAD

**Issue by tarrantro** [grafana/helm-charts#2220]
**Background**

As title, I enabled query in `value.yaml` as following. However, the `tempo-query-frontend` is in crash state. That's because following.

- In https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/templates/_helpers.tpl#L197, this variable doesn't include `tempo-query.yaml` which is needed for `tempo-query` container.
- In `Securecontext` object of `tempo-query-frontend` deployment, the root folder is read-only. However, the `tempo-query` container need to write plugins to `/tmp` by default. That will cause below error. `2023-02-20T06:05:31.690Z [ERROR] tempo-query: plugin init error: error="open /tmp/plugin200397020: read-only file system" timestamp=2023-02-20T06:05:31.690Z`

```
queryFrontend:
  query:
    # -- Required for grafana version <7.5 for compatibility with jaeger-ui. Doesn't work on ARM arch
    enabled: true
```

I manually fixed those in my deployment and running as expected.

**Comment by tarrantro** [comment]
Hello, any plan to fix this in chart?

**Comment by rpuserh** [comment]
I am facing exact same issue. Any update?

**Comment by dbirks** [comment]
Found a workaround that's acceptable in my situation... found that we can relax the `securityContext` to get around the read-only error:

```yaml
tempo:
  securityContext:
    readOnlyRootFilesystem: false
```

**Comment by maxboone** [comment]
@dbirks preferred to making the root fs writeable everywhere, we're doing this:
```
  queryFrontend:
    extraVolumes:
      - name: jaeger-query-store
        emptyDir:
          sizeLimit: 32Mi
    query:
      enabled: true
      extraVolumeMounts:
        - mountPath: /tmp
          name: jaeger-query-store
```
