### ISSUE TITLE
PodSecurityPolicy no longer available

### ISSUE THREAD

**Issue by boehb-efs** [grafana/helm-charts#2226]
The grafana-chart uses by default PodSecurityPolicy. However this Ressource has been deprecated since kubernetes-version 1.21 and removed in 1.25, see: https://kubernetes.io/docs/concepts/security/pod-security-policy/

**Comment by tillig** [comment]
Possible duplicate of #2175

**Comment by patsevanton** [comment]
```
      rbac:
        pspEnabled: false
      testFramework:
        enabled: false
```
