### ISSUE TITLE
operator: helm chart includes namespace-fields in cluster-scoped objects

### ISSUE THREAD

**Issue by rdxmb** [grafana/helm-charts#2231]
I am about to deploy [tempo-distributed](https://github.com/grafana/helm-charts/tree/main/charts/tempo-distributed) with the grafana-agent as dependency.

Within this agent chart, some cluster-scoped objects have namespace-fields included, which results in errors when deploying with GitLab Kubernetes Agent.

```
{"level":"error","time":"2023-02-28T14:42:37.606Z","msg":"Failed to decode manifest objects","mod_name":"gitops-manifest","worker_id":"manifest-repository","error":"resource is cluster-scoped but has a non-empty namespace \"tempo-distributed\"","commit_id":"5cecfd7417af1f2cd3af659762da6929a85db86e","agent_id":42}
```

these are the lines making problems here:

- 
- https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/templates/metamonitoring/grafana-agent-cluster-role-binding.yaml#L7
- https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/templates/metamonitoring/grafana-agent-cluster-role.yaml#L7

As a workaround, I've just removed the namespace-fields afterwards with kustomize:

```
patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: tempo-distributed-grafana-agent
    patch: |-
      - op: remove
        path: /metadata/namespace
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: tempo-distributed-grafana-agent
    patch: |-
      - op: remove
        path: /metadata/namespace
```
