### ISSUE TITLE
[grafana] mounting ca-bundle to container

### ISSUE THREAD

**Issue by lknite** [grafana/helm-charts#2234]
Hello, where I work https is rewritten using a local onprem certificate.

I have the onprem certificate in a secret which I usually mount like this:
```
extraVolumeMounts:
- mountPath: "/etc/ssl/certs"
  name: ca-bundle
extraVolumes:
- name: ca-bundle
  secret:
    secretName: ca-bundle
```

However, the grafana helm chart does not have 'extraVolumes', so I've tried the same solution using:
```
extraSecretMounts:
- name: ca-bundle
  mountPath: "/etc/ssl/certs"
  secretName: ca-bundle
```

This seems to be mounting the ca-bundle as expected.  I tried using a key within the secret of 'ca.crt' and 'ca-certificates.crt', but neither seems to work:
```
$ k -n grafana exec -it grafana-7d59986668-nrfz2 -- bash
Defaulted container "grafana" out of: grafana, init-chown-data (init)
bash-5.1$ wget -O - https://google.com
Connecting to google.com (142.250.217.78:443)
ssl_client: google.com: certificate verification failed: unable to get local issuer certificate
wget: error getting response: Connection reset by peer
```

Could you provide the correct location where I should be mounting the certificates?  Or, if there is an option in the helm chart which I've missed, provide that.
