### ISSUE TITLE
Provisioning Datasource: InfluxDB

### ISSUE THREAD

**Issue by auwaerter** [grafana/helm-charts#2243]
I was using the following provisioned datasource for my InfluxDB with grafana 9.3.6 which was working fine:
```
      - name: Icinga2-InfluxDB
        type: influxdb
        access: proxy
        database: icinga2
        url: http://127.0.0.1:2003
        uid: icinga2-id
        jsonData:
          timeInterval: "15s"
```
Now i've updated to grafana version 9.4.1 with HELM Chart 6.51.1 and it seems like i can't provision the database name, as the following error is being returned with using the Test button:

![image](https://user-images.githubusercontent.com/6923945/222141879-947cd5ec-3bb1-4760-ac25-44dcd50c5105.png)

Also when i'm adding the correct name inside grafana, the same error is being returned. When i'm adding the datasource manually with the grafana UI the connection is working fine.

Did something changed within grafana 9.4.1 where the provisioning is not working any longer? Or am i using wrong values for Influx provisioning?

Thanks! :)
