### ISSUE TITLE
Modification of Email Template ng_alert_notification.html via Helm Chart

### ISSUE THREAD

**Issue by navinpai** [grafana/helm-charts#2244]
I'm using the grafana helm chart to set up grafana for my org. One thing that I'd like to do is edit the `ng_alert_notification.html` email template via helm. Currently, I need to go into my pod and manually edit the `public/emails/ng_alert_notification.html` file.

Is there a way to do this via the helm chart itself or using a sidecar?

Couldn't find any documentation around this.

**Comment by svmaris** [comment]
You can put the template in a ConfigMap and mount it using the [extraConfigmapMounts](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L128) feature (don't forget to use the `subPath`)

**Comment by shivtej-opsverse** [comment]
worked with the following values:
```
    extraConfigmapMounts:
      - name: <name>
        mountPath: /usr/share/grafana/public/emails/ng_alert_notification.html
        subPath: ng_alert_notification.html
        configMap: <configmap-name>
        readOnly: true
  ```
  Thanks @svmaris
