### ISSUE TITLE
[grafana] PersistentVolumeClaim "grafana" is invalid: spec: Forbidden: spec is immutable after creation

### ISSUE THREAD

**Issue by lknite** [grafana/helm-charts#2260]
When performing a clean installation I end up with a successful installation that I can use but always get this error that keeps trying to resolve:
```
error when replacing "/dev/shm/737179964": PersistentVolumeClaim "grafana" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims core.PersistentVolumeClaimSpec{ AccessModes: {"ReadWriteMany"}, Selector: nil, Resources: {Requests: {s"storage": {i: {...}, s: "10Gi", Format: "BinarySI"}}}, - VolumeName: "pvc-0554ac94-8558-430e-beea-8fe73499c4f6", + VolumeName: "", StorageClassName: &"cephfs", VolumeMode: &"Filesystem", ... // 2 identical fields }
```

My values.yaml file looks like this:
```
grafana:

  <ingress & grafana.ini removed for clarity>

  persistence:
    enabled: true
    accessModes:
    - ReadWriteMany
    storageClassName: cephfs
```

Kubernetes v1.25.3
Helm v3.10.3+g835b733

**Comment by lknite** [comment]
I can delete the pvc, it is recreated, then within a couple minutes the error comes back.

**Comment by zzvara** [comment]
Same here using `kube-prometheus-stack` 45.28.1.

**Comment by prasoon-pxc** [comment]
same for me also, I am trying to add my custom `volumeName` field in `prometheus-grafana` PVCs but it giving error on Argocd syncing , it would be good if you can optionally provide `volumeName` field in [PVC](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/pvc.yaml)

**Comment by rek** [comment]
Exact same issue here when using:
```
        grafana:
          persistence:
            enabled: true
            type: pvc
            storageClassName: default
            accessModes:
              - ReadWriteOnce
            size: 4Gi
            finalizers:
              - kubernetes.io/pvc-protection
```
Did we find a way around this?
