### ISSUE TITLE
Passing Data Source config file's content to Grafana Helm values.yaml - additional "|"

### ISSUE THREAD

**Issue by yockgen** [grafana/helm-charts#2263]
Hi Guys,

I'm trying to pass data source config file's content to values.yaml using set-file, instead of hardcoded them inside values file, steps as below:

```
helm template --dry-run --debug \
-f /data/otel/helm/grafana/values.yaml \
--set adminPassword="admin" \
--set persistence.enabled=true \
--set persistence.storageClassName="manual" \
--set-file 'datasources.datasources\.yaml'=/data/otel/helm/grafana/config/config.yaml \
intel-grafana grafana/grafana
```
values.yaml looks like below:
```
...
## Configure grafana datasources
## ref: http://docs.grafana.org/administration/provisioning/#datasources
##
datasources:
  datasources.yaml:
#    apiVersion: 1
#    datasources:
#    - name: Prometheus
#      type: prometheus
#      url: http://prometheus-prometheus-server
#      access: proxy
#      isDefault: true
...
```

/data/otel/helm/grafana/config/config.yaml looks like below:
```
apiVersion: 1
datasources:
  - name: Intel_Influx
    type: influxdb
    access: proxy
    url: http://192.168.1.107:8086
    jsonData:
      version: Flux
      organization: intel
      defaultBucket: intel
      tlsSkipVerify: true
    secureJsonData:
      token: {influx token here}
```

The template result looks like below - additional '|' found caused ERROR!!:
```
......    
  datasources.yaml: |
    |
      apiVersion: 1
      datasources:
        - name: Intel_Influx
          type: influxdb
          access: proxy
          url: http://192.168.1.107:8086
          jsonData:
            version: Flux
            organization: intel
            defaultBucket: intel
            tlsSkipVerify: true
          secureJsonData:
....
---
# Source: grafana/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:

```

Correct mapping should be like following:
```
....
 datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      jsonData:
        defaultBucket: intel
        organization: intel
        tlsSkipVerify: true
        version: Flux
      name: Intel_Influx
      secureJsonData:
   .......
```

What error did I make? Please help.
