### ISSUE TITLE
How to lock grafana plugin version helm chart

### ISSUE THREAD

**Issue by kushalgangan** [grafana/helm-charts#2267]
We have been using grafana on-call plugin and with every restart, it updates to a new version if it's available. We have to lock it down to a specific version. Could you please suggest how we should achieve this in grafana helm chart?

Currently, we are adding an extra init container to install the plugin with a specific version using grafana-cli.

```
      extraInitContainers:
        - image: garafana
          imagePullPolicy: IfNotPresent
          name: grafana-plugins
          command: ['sh', '-c', "grafana-cli plugins install grafana-oncall-app v1.1.31"]
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: storage
```
