### ISSUE TITLE
[grafana] Service Port as Port definition in the deployment

### ISSUE THREAD

**Issue by florianrusch** [grafana/helm-charts#228]
Hi all,

I'm currently setting up a fresh Grafana with the provided helm chart in this repository.
In the review of the generated resource I recognised, that the deployment has two port definitions. One for the container itself (3000) and one for the service (80). 

```yaml
ports:
  - name: service
    containerPort: 80
    protocol: TCP
  - name: grafana
    containerPort: 3000
    protocol: TCP
```
I've took a look and find this part where it comes from:
https://github.com/grafana/helm-charts/blob/88ce3041b84b18d74d968b1803c69a24f42a872a/charts/grafana/templates/_pod.tpl#L303-L309

Can someone explain, why the service port is here also configured?
