### ISSUE TITLE
[grafana] - OIDC auth

### ISSUE THREAD

**Issue by bmgante** [grafana/helm-charts#2280]
Hi All,

Just starting with this helm chart and trying to understand how to setup oidc (oauth) authentication. Can some provide some guidance?

Thanks in advance

**Comment by bmgante** [comment]
Hi @jeswant 
Thank you so much for your prompt support on this. I'll give it a try and provide feedback here.

**Comment by jeswant** [comment]
Hi @bmgante 

> we need to register the grafana application there and set there the grafana callback url which is the url in the browser + "/login/generic_oauth". Is that right?

correct. i'm using a similar pattern for Redirection URI: https://monitor.abc.test.com/login/generic_oauth

> to configure ingress for grafana:
1. Add grafana repo if not added yet: `helm repo add grafana https://grafana.github.io/helm-charts `
2. Fetch values.yaml: `helm show values grafana/grafana > grafana_values.yaml`
3. Open grafana_values.yaml and set `ingress` to `enabled: true`
4. Add hostname in `hosts` and in `tls` section, if "https" is needed, create a secret (grafana-tls) with keys in it and  add hosts to it

> ingress:
>   enabled: true
>   hosts:
>     - monitor.abc.test.com
>    tls:
>     - secretName: grafana-tls
>       hosts:
>         - monitor.abc.test.com

To create a secret:
> kubectl create secret tls "grafana-tls" -n monitoring --cert=/Users/test/Documents/monitor.abc.test.com.pub --key=/Users/test/Documents/monitor.abc.test.com.key  --dry-run=client -o yaml | kubectl apply -f -

**Comment by bmgante** [comment]
Hi @jeswant 
Thanks for your explanation. Regarding the grafana ingress is that config enough? Isn't it required to set the ingress class name and set annotations etc?
Was reading some examples in the web that point to use alb and a lot of annotations...

**Comment by bmgante** [comment]
For example: https://wdfdo1986.medium.com/installing-grafana-with-ingress-a8cd39df41de
Would you mind to share your values.yaml? 
Many thanks

**Comment by jeswant** [comment]
i'm using istio for ingress. So, i haven't enabled ingress in  grafana_values.yaml.

But, it would looks like this:

```
ingress:
  enabled: true
  # ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: xx.xx.xx.0/24, xx.xx.xx.0/26, xx.xx.0.216/29
  labels: {}
  path: /

  pathType: Prefix

  hosts:
    - monitor.sandbox.abc.com
  tls: 
    - secretName: grafana-tls
      hosts:
        - monitor.sandbox.abc.com
```

similar to: https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L211
