### ISSUE TITLE
[loki] How to disable or configure query caching?

### ISSUE THREAD

**Issue by tberreis** [grafana/helm-charts#2289]
Hi everyone,

Please help me to understand the caching mechanisms for queries against loki.
I'm using loki 2.7.3 (helm chart loki-4.8.0).

When running a simple query, the memory usage for the loki read pods increases and the query result seem to be fully cached in memory. After 1h the memory will be freed. Running multiple queries often leads to a memory usage above the defined resource limits and subsequently to OOM.
I tried to disable the caching without success. I also tried to change the max size and ttl for the embedded cache without success. The settings seem to be ignored completely and even with a ttl of 2 minutes, the memory will be freed after 1 hour only.

What I tried already:

<details open>
  <summary>fifocache (deprecated)</summary>

```
    query_range:
      cache_results: true
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_bytes: "128MB"
            ttl: 5m
```

</details>

<details open>
  <summary>embedded_cache</summary>

```		
    query_range:
      cache_results: true
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 128
            ttl: 5m
```

</details>

Memory usage per pod using the config below:
![image](https://user-images.githubusercontent.com/88875030/227233467-54b93988-be84-49d6-8a95-c7299e252b40.png)

Loki is still using the defaults here (ttl 1h and max size 100M):
![image](https://user-images.githubusercontent.com/88875030/227261793-ab22221f-cd56-437a-8d00-767905f42f6d.png)

I'm wondering about the statement `# Enable in-memory cache (auto-enabled for the chunks & query results cache if no other cache is configured).` (see https://grafana.com/docs/loki/v2.7.x/configuration/#cache_config)
Does that mean I can't disable caching completely? Would be ok if I would be able to change the defaults here ...

Can anybody tell me what I'm doing wrong?

<details>
  <summary>My config</summary>

```
auth_enabled: false
query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 16
        ttl: 2m
chunk_store_config:
  max_look_back_period: 0s
compactor:
  shared_store: azure
  working_directory: /var/loki/boltdb-shipper-compactor
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
  max_transfer_retries: 0
  wal:
    dir: /var/loki/wal
    replay_memory_ceiling: 170MB
limits_config:
  enforce_metric_name: false
  max_entries_limit_per_query: 5000
  reject_old_samples: true
  reject_old_samples_max_age: 168h
memberlist:
  join_members:
  - loki-memberlist
ruler:
  alertmanager_url: http://alertmanager.kube-prometheus-stack:9093
  storage:
    local:
      directory: /tmp/rules
    type: local
schema_config:
  configs:
  - from: "2021-12-01"
    index:
      period: 24h
      prefix: index_
    object_store: azure
    schema: v11
    store: boltdb-shipper
server:
  grpc_listen_port: 9095
  http_listen_port: 3100
storage_config:
  azure:
    account_key: ${STORAGE_ACCOUNT_KEY}
    account_name: ${STORAGE_ACCOUNT_NAME}
    container_name: loki
  boltdb_shipper:
    active_index_directory: /var/loki/boltdb-shipper-active
    cache_location: /var/loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: azure
  filesystem:
    directory: /var/loki/chunks
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
```

</details>
