### ISSUE TITLE
auth.JWT not working, possible configmap error

### ISSUE THREAD

**Issue by MarkCupitt** [grafana/helm-charts#2328]
Using latest Grafana

I have the following set in the grafana.ini section of the helm chart
```
  auth:
    basic:
      enabled: false
    jwt:
      enabled: true
      header_name: "BountyUser"
      email_claim: sub
      username_claim: username
      jwk_set_url: "https://{{cluster_url}}:443/.well-known/jwks.json"
      skip_org_role_sync: true
```
and I notice after deployment that the configmap that is deployed has a map[]  for teh values as follows:
```
basic	map[enabled:false]
disable_login	false
disable_login_form	false
disable_signout_menu	false
disable_sync_lock	false
jwt	map[email_claim:sub enabled:true header_name:BountyUser jwk_set_url:[https://bounty.billrush.work:443/.well-known/jwks.json](https://bounty.billrush.work/.well-known/jwks.json) skip_org_role_sync:true username_claim:username]
```
Is this expected? I wondering if the map[] is incorrect and causing grafana to ignore the jwt it gets, interesting auth.basic remains in effect, we can still login with user/pass
