### ISSUE TITLE
loki.storageConfig don`t support s3

### ISSUE THREAD

**Issue by patsevanton** [grafana/helm-charts#2342]
Hello! I use chart: loki-distributed  version: 0.69.11

I try use s3 in
But don`t work:
```
    loki:
      storageConfig:
        s3:
          access_key_id: "xxx"
          secret_access_key: "yyyy"
          bucketnames: "zzzz"
          endpoint: "https://storage.jjjj.net"
          s3forcepathstyle: true
```

Get error:
```
 field s3 not found in type storage.Config. Use `-config.expand-env=true` flag if you want to expand environment variables in your config file
```

**Comment by patsevanton** [comment]
Work config:
```
    loki:
      storageConfig:
        aws:
          access_key_id: "xxxx"
          secret_access_key: "yyyy"
          bucketnames: "zzzz"
          endpoint: "https://storage.jjjjj.net"
          s3forcepathstyle: true
```

**Comment by mrwormhole** [comment]
hello @patsevanton , I use the exact same version you are using and I specified it like this and it works

```yaml
loki:
      compactor:
        enabled: false
      
      schemaConfig:
        configs:
        - from: 2020-09-07
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: loki_index_
            period: 24h

      storageConfig:
        boltdb_shipper:
          shared_store: s3
          active_index_directory: /var/loki/index
          cache_location: /var/loki/cache
          cache_ttl: 168h
        filesystem:
          directory: /var/loki/chunks
        aws:
          # Grafana Helm Charts have a brain damage so doesn't support secretKeyRef
          # TODO use a k8s secret when grafana helm charts support secretKeyRef
          s3: s3://IwWLFLyeKmKxyQ82:u008lL8qxQ1f1k54DarzTC65PENrhRHj@minio.minio-system.svc.cluster.local:9000/logs
          s3forcepathstyle: true
```

however, there is something funny about it, when I deploy a new instance `0.69.14`, I am getting `failed parsing config: /etc/loki/config/config.yaml: parsing time "2020-09-07T00:00:00Z": extra text: "T00:00:00Z". Use `-config.expand-env=true` flag if you want to expand environment variables in your config file`
