### ISSUE TITLE
Template expression in "ingress.hosts" value isn't rendered when included in "grafana.ini"

### ISSUE THREAD

**Issue by MaximPopov** [grafana/helm-charts#2343]
Grafana chart: 6.52.9

If I specify a template expression in `ingress.hosts` value like this:
```
ingress:
    enabled: true
    hosts:
      - monitoring-{{ .Values.global.environment }}.my-hostname.com
```
it gets copied verbatim to "grafana.ini" section of the ConfigMap:
```
  grafana.ini: |
    ...
    [server]
    domain = monitoring-{{ .Values.global.environment }}.my-hostname.com
```

"grafana.ini" section definition in `configmap.yaml` specifies that string values must be processed with `tpl` function:
```
  grafana.ini: |
  {{- range $elem, $elemVal := index .Values "grafana.ini" }}
    {{- if not (kindIs "map" $elemVal) }}
    {{- if kindIs "invalid" $elemVal }}
    {{ $elem }} =
    {{- else if kindIs "string" $elemVal }}
    {{ $elem }} = {{ tpl $elemVal $ }}
    {{- else }}
    {{ $elem }} = {{ $elemVal }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- range $key, $value := index .Values "grafana.ini" }}
    {{- if kindIs "map" $value }}
    [{{ $key }}]
    {{- range $elem, $elemVal := $value }}
    {{- if kindIs "invalid" $elemVal }}
    {{ $elem }} =
    {{- else if kindIs "string" $elemVal }}
    {{ $elem }} = {{ tpl $elemVal $ }}
    {{- else }}
    {{ $elem }} = {{ $elemVal }}
    {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
```
and double quotes around `grafana.ini.server.domain` value in `values.yaml` lead me to believe this value should be considered as a string kind:
```
grafana.ini:
  server:
    domain: "{{ if (and .Values.ingress.enabled .Values.ingress.hosts) }}{{ .Values.ingress.hosts | first }}{{ else }}''{{ end }}"
```

What could be the reason for `tpl` function not being applied to this value?

**Comment by lindeskar** [comment]
I just had the same issue.

My workaround for now is to redefine `grafana.ini.server.domain`:

```yaml
ingress:
  enabled: true
  hosts:
    - "grafana.{{ .Values.global.publicDomain }}"

grafana.ini:
  server:
    domain: "grafana.{{ .Values.global.publicDomain }}"
```
