### ISSUE TITLE
[loki-stack] Typo on loki subchart - templates/services.yaml

### ISSUE THREAD

**Issue by scastellanosnqn** [grafana/helm-charts#2363]
### Describe the bug
There is a typo on loki subchart from loki-statck in file: `loki/templates/services.yaml`:
- On line 15, there is an extra space before `externalTrafficPolicy: `

> {{- if .Values.service.loadBalancerSourceRanges }}
>    externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
> {{- end }}

#### Error message
> Error: YAML parse error on loki-stack/charts/loki/templates/service.yaml: error converting YAML to JSON: yaml: line 14: did not find expected key

### To Reproduce
Setting `loadBalancerSourceRanges` with an external file (or directly setting) :
```
helm upgrade --install loki-stack grafana/loki-stack --namespace loki -f loki-staging.yaml
```
`loki-staging.yaml`
```
loki:
  service:
    loadBalancerIP: "8.8.8.8"
    loadBalancerSourceRanges: 
    - "8.8.4.4/32"
    type: LoadBalancer
```
### Expected behavior
To deploy successfully. I couldn't found corresponding repository so I'm reporting this here.

Regards!
