### ISSUE TITLE
[loki-distributed] helm value querier 

### ISSUE THREAD

**Issue by itsek** [grafana/helm-charts#2367]
helm loki-distributed
Version: 0.69.14

when setting the following:
```
  querier:
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 4
```

the result is a sts with
```
Replicas:           1 desired | 1 total
```

for some reason the heml value of minReplicas does not get passed to the created sts/Pod object, so there is only one querier Pod regardless of the number given in the values
