### ISSUE TITLE
How to override dashboard attributes?

### ISSUE THREAD

**Issue by gajus** [grafana/helm-charts#2370]
```yaml
dashboardproviders.yaml:
  apiVersion: 1
  providers:
    - name: 'default'
      orgId: 1
      folder: 'Default'
      type: file
      disableDeletion: true
      editable: true
      options:
        path: /var/lib/grafana/dashboards/standard
dashboards:
default:
  postgres:
    gnetId: 9628
    datasource: Prometheus
  redis:
    gnetId: 11835
    datasource: Prometheus
```

Is there a way to put `postgres` and `redis` dashboards in different folders without creating a new provider for each?
