### ISSUE TITLE
grafana helm chart:no_proxy variable not working as expected

### ISSUE THREAD

**Issue by ebini** [grafana/helm-charts#238]
Hello,

for the plugins installation i need to set a proxy.

Cool "Feature" would be to have this only for the plugins.
My workaround is setting the Proxy environment variables in the helm chart (chart: grafana-6.4.4):
```
env:
 HTTP_PROXY: "http://proxy.secret:8080"
 HTTPS_PROXY: "http://proxy.secret:8080"
 http_proxy: "http://proxy.secret:8080"
 https_proxy: "http://proxy.secret:8080"
 NO_PROXY: "localhost,127.0.0.1,169.254.169.254,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.local"
 no_proxy: "localhost,127.0.0.1,169.254.169.254,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.local"
```
this works fine for the plugins, but afterwards grafana uses for everything the proxy.

=> The no_proxy/NO_PROXY doesn't seem to work. Any ideas?

To test i connected to the pod and tried it with wget:

```
bash-5.0$ export no_proxy=".local"
bash-5.0$ export NO_PROXY=$no_proxy
bash-5.0$ wget http://loki.svc.cluster.local:3000
Connecting to proxy.secret:8080 (10.6.12.11:8080)
wget: server returned error: HTTP/1.1 503 Service Unavailable
bash-5.0$ printenv | grep -i no_proxy
no_proxy=.local
NO_PROXY=.local
```
so it connects to the proxy, even no_proxy / NO_PROXY is set. (i tried it with different values, ips, *.local, full name, exacpt ip) 
Any ideas?

If i don't set any proxy variable grafana works with the datasources (but i cannot load the plugins)

Thanks in advance
Florian
