### ISSUE TITLE
[loki-stack] values.yaml prometheus commandline flags

### ISSUE THREAD

**Issue by timo1707** [grafana/helm-charts#2390]
Hi, 
i am struggeling with the values.yaml for the loki.stack
my values.yaml looks like below, where i tried to get the commandline flag "--web.enable-remote-write-receiver" enabled. 
i can run the helm installation, but it seems that the declarations in "prometheusSpec" are ignored.
since i am a beginner with kubernetes, it would be great when someone have a hint...
 

```
prometheus:
  enabled: true
  isDefault: false
  url: http://{{ include "prometheus.fullname" .}}:{{ .Values.prometheus.server.service.servicePort }}{{ .Values.prometheus.server.prefixURL }}
  datasource:
    jsonData: "{}"
  prometheusSpec:
    enableRemoteWriteReceiver: true
```

Prometheus Version | 2.34.0

cheers,
Timo
