### ISSUE TITLE
Datasources listed in the values.yaml are not being loaded into Grafana

### ISSUE THREAD

**Issue by LSparkzwz** [grafana/helm-charts#2393]
Hello, 
I'm doing an helm install of the following chart with grafana as dependency:
```
apiVersion: v2
name: test
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
- name: grafana
  version: "^6.56.1"
  repository: "@grafana"
  condition: grafana.enabled
```

My values.yaml looks like this:
```
global:
  env: env1

grafana:
  enabled: true
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus1
        type: prometheus
        access: proxy
        orgId: 1
        url: <url>
        version: 1
        editable: true
        isDefault: true
      - name: Prometheus2
        type: prometheus
        access: proxy
        orgId: 1
        url: <url>
        version: 1
        editable: true
```

But when I try doing an helm install/upgrade I see that these two data sources are not being added, what am I doing wrong?
