### ISSUE TITLE
Grafana alerting HA using the Grafana helm chart

### ISSUE THREAD

**Issue by Nog-Frog** [grafana/helm-charts#2408]
Hey, I'm using the Grafana helm chart from this repo.
I use a HA setup with 3 replicas. I set unified_alerting to True.
My team uses a Slack integration to receive alerts. Whenever an alert enters firing state, we receive 3 notifications on it.

I found this guide from grafana: https://grafana.com/docs/grafana/latest/alerting/set-up/configure-high-availability/#enable-alerting-high-availability-using-kubernetes

But using the current service.yaml template this does not seem possible, as it seems I may only specify 1 port for the service whereas this guide required me to specify an additional port for alerting.

Am I missing something that will make this possible anyway? Thanks in advance.

**Comment by Kot-o-pes** [comment]
+ 1, you also need to deploy additional kind:Service to make it running, so far we have to make workaround with kubectl to achieve this

**Comment by IgorArg** [comment]
Have the same issue. the [guide](https://grafana.com/docs/grafana/latest/alerting/set-up/configure-high-availability/#enable-alerting-high-availability-using-kubernetes) looks like chart needs to be customized in order to create new service for HA. Also i've found short instruction https://github.com/grafana/helm-charts/tree/main/charts/grafana#high-availability-for-unified-alerting without creating service, but i didnt try it yet.

**Comment by iXingo** [comment]
```
As next step you have to setup the grafana.ini in your values.yaml in a way that it will make use of the headless service to obtain all the IPs of the cluster. You should replace {{ Name }} with the name of your helm deployment.

grafana.ini:
  ...
  unified_alerting:
    enabled: true
    ha_peers: {{ Name }}-headless:9094
    ha_listen_address: ${POD_IP}:9094
    ha_advertise_address: ${POD_IP}:9094

  alerting:
    enabled: false
```

Does it mean I can use any `name` I want?
