### ISSUE TITLE
Unable to pass notifcation template from values.yaml

### ISSUE THREAD

**Issue by SaiVamsi95** [grafana/helm-charts#2409]
I have been trying to create a notification template from values but it doesn't seem to be working.

**Code:**
```
    alerting:
        rules.yaml:
          apiVersion: 1
          templates:
            - orgID: 1
              name: Slack Template
              template: |
                {{ define "alert_severity_prefix_emoji" }}
                  {{- if ne .Status "firing" }}
                    :white_check_mark:
                  {{- else if eq .CommonLabels.severity "critical" }}
                    :red_circle:
                  {{- else if eq .CommonLabels.severity "warning" }}
                    :warning:
                  {{ end }}
                {{ end }}
                {{ define "slack.print_alert" }}
                  {{ template "alert_severity_prefix_emoji" . }}
                  [{{.Status}}] {{ .Labels.alertname }}
                  *Labels*:
                  {{ range .Labels.SortedPairs }}
                    - {{ .Name }}: {{ .Value }}
                  {{ end }}
                  {{ if .Annotations }}
                  *Annotations*:
                    {{ range .Annotations.SortedPairs }}
                      - {{ .Name }}: {{ .Value }}
                    {{ end }}
                  {{ end }}
                  {{ if .SilenceURL }}
                    *Silence*: {{ .SilenceURL }}
                  {{ end }}
                  {{ if .DashboardURL -}}
                    *Go to dashboard*: {{ .DashboardURL }}
                  {{ end }}
                {{ end }}
                {{ define "slack.message" -}}
                  {{ if .Alerts.Firing -}}
                    {{ len .Alerts.Firing }} firing alert(s):
                    {{ range .Alerts.Firing }}
                      {{ template "slack.print_alert" . }}
                    {{ end }}
                  {{ end }}
                  {{ if .Alerts.Resolved }}
                    {{ len .Alerts.Resolved }} resolved alert(s):
                    {{ range .Alerts.Resolved }}
                      {{ template "slack.print_alert" .}}
                    {{ end }}
                  {{ end }}
                {{ end }}'
```

Issue here is we have to pass this template in yaml file and yaml thinks {} are structs and because of that its ignoring the whole template. Is there any way that i can pass this whole template as it is ?

**Comment by SaiVamsi95** [comment]
@bcotton @jrockway @maser @zerok

**Comment by EsDmitrii** [comment]
I have this issue too, pls fix ASAP

**Comment by gproxyz** [comment]
Yes, same problem. pls fix it

**Comment by markphughes17** [comment]
I have spent all day today wrestling with this problem, and eventually found that this got it to work.
It seems that it needs the `type` key
```templates:
  - orgID: 1
    name: slack
    type: alert
    template: |
        {{ define "alert_severity_emoji" -}}
          {{- if ne .Status "firing" -}}
          ...

**Comment by Brico87** [comment]
Is the following issue resolution could help you @SaiVamsi95 => https://github.com/helm/helm/issues/2798 ?

**Comment by vsai9594** [comment]
@Brico87 @EsDmitrii I actually fixed it some other way. I had to give the template in the below format

```
{{ "{{" }} define "slack.title" {{ "}}" }}
{{ "{{" }} len .Alerts.Firing {{ "}}" }} firing alert(s):
{{ "{{" }}- if .Alerts.Firing -{{ "}}" }}
{{ "{{" }}- range .Alerts.Firing -{{ "}}" }}
{{ "{{" }} .Labels.alertname {{ "}}" }}
{{ "{{" }}- end -{{ "}}" }}
{{ "{{" }}- end -{{ "}}" }}
{{ "{{" }} end {{ "}}" }}
```

**Comment by rafilkmp3** [comment]
> @Brico87 @EsDmitrii I actually fixed it some other way. I had to give the template in the below format
> 
> ```
> {{ "{{" }} define "slack.title" {{ "}}" }}
> {{ "{{" }} len .Alerts.Firing {{ "}}" }} firing alert(s):
> {{ "{{" }}- if .Alerts.Firing -{{ "}}" }}
> {{ "{{" }}- range .Alerts.Firing -{{ "}}" }}
> {{ "{{" }} .Labels.alertname {{ "}}" }}
> {{ "{{" }}- end -{{ "}}" }}
> {{ "{{" }}- end -{{ "}}" }}
> {{ "{{" }} end {{ "}}" }}
> ```

Hello, can you help me? Did you figure it out? I'm having trouble trying to setup my template on my values.yaml and nothing seems to work. If yours did, could you provide a full file for example? Thank you

**Comment by Brico87** [comment]
Hey @rafilkmp3 , In my "alerting" ConfigMap, I filled that:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting
  namespace: {{ .Release.Namespace }}
data:
  provisionning.yaml: |
    [...]
    templates:
      - orgId: 1
        name: infra-alerting
        template: |
          {{`{{ define "notification.title" }}
          {{ len .Alerts.Firing }} firing alert(s), {{ len .Alerts.Resolved }} resolved alert(s)
          {{ end }}`}}
     contactPoints:
      - orgId: 1
        name: infra-alerting
        receivers:
          - uid: infra-alerting-email
            type: email
            settings:
              addresses: "my address"
              singleEmail: false
              subject: {{`'{{ template "notification.title" . }}'`}}
            disableResolveMessage: false
```

Using the backtick was the winning move for me.
