### ISSUE TITLE
[loki-distributed] Is tsdb index store setup supported ?

### ISSUE THREAD

**Issue by MysterioO** [grafana/helm-charts#2411]
We are running latest version of loki-distributed (0.69.16), we would like to enable [TSDB](https://grafana.com/docs/loki/latest/operations/storage/tsdb/). However, we cannot find if loki-distributed chart supports TSDB store at this moment.

**Comment by juris** [comment]
Tried to follow Grafana TSDB documentation and ended up with
```
unlinkat ./scratch: read-only file system
```
errors

**Comment by CCOLLOT** [comment]
I managed to set it up a while ago with the following configuration:
```yaml
schemaConfig:
      configs:
        - from: 2023-01-01
          store: tsdb 
          object_store: s3
          schema: v12
          index:
            prefix: tsdb_index_
            period: 24h
```
```yaml
storageConfig:
      tsdb_shipper:
        active_index_directory: /var/loki/tsdb-index
        cache_location: /var/loki/tsdb-cache
        index_gateway_client:
          server_address: dns:///loki-index-gateway:9095
        shared_store: s3
```

**Comment by sjherrick** [comment]
+1 . chart is not in line with current recommended deployment in loki docs

**Comment by crstian19** [comment]
If you use monolithic mode can use this config:

``` yaml
  schemaConfig:
    configs:
      - from: 2023-01-01
        store: tsdb 
        object_store: filesystem
        schema: v12
        index:
          prefix: tsdb_index_
          period: 24h
```
``` yaml
  storageConfig:
    tsdb_shipper:
      active_index_directory: /var/loki/tsdb-index
      cache_location: /var/loki/tsdb-cache
  #    index_gateway_client:
  #      server_address: dns:///loki-index-gateway:9095
      shared_store: filesystem
```
