### ISSUE TITLE
Render pipelineStages with tpl function to support templates in pipelines

### ISSUE THREAD

**Issue by tiagodj** [grafana/helm-charts#2412]
In the values file we have this config:

```yaml
    scrapeConfigs: |
      # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet for reference
      - job_name: kubernetes-pods
        pipeline_stages:
          {{- toYaml .Values.config.snippets.pipelineStages | nindent 4 }}
```
https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml#LL425C4-L425C4

Would it be possible to update the code to render the contents of `.Values.config.snippets.pipelineStages` with the `tpl` function? This would allow us to write template code in the pipeline definition.

This is already done in other parts of the definition, for example:

```yaml
 477  {{- tpl (toYaml .Values.config.clients) . | nindent 2 }}
```
https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml#LL477C29-L477C29
