### ISSUE TITLE
[grafana] persist home / dashboard settings

### ISSUE THREAD

**Issue by JPFrancoia** [grafana/helm-charts#2417]
Hi,

I think I successfully installed Grafana on my k8s cluster. Here is the config specific to Grafana:

kube-prometheus-stack-values.yaml:

```yaml
grafana:
  persistence:
    type: pvc
    enabled: true
    storageClassName: local-grafana
    accessModes:
    - ReadWriteOnce
    size: 500Mi
  extraVolumeMounts:
  - name: dashboards
    mountPath: /var/lib/grafana/dashboards
    hostPath: /home/djipey/grafana/dashboards
    readOnly: false
```

pv-grafana.yaml:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-db
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /home/djipey/grafana
    type: DirectoryOrCreate
  storageClassName: local-grafana
```

I'm using local storage. It looks like it's working, when I ls the content of the `grafana` dir on the machine running the cluster:

```
❯ ls 
alerting  csv  dashboards  grafana.db  plugins  png
```

I can then access Grafana in my browser, and I can see the home page, the default dashboards, etc. However, if I change the home page (by removing the default panels for example) or if I star or change a dashboard, I lose the settings when I restart the grafana deployment, i.e: no dasboard will be starred and the default stock panels will be back on the home page.

Is there a way to avoid that?
