### ISSUE TITLE
Custom pipeline stages not getting picked up (applied) by the Promtail agent

### ISSUE THREAD

**Issue by DPIDNB** [grafana/helm-charts#2424]
Promtail deployed on a local minikube cluster via helm chart not applying custom pipeline stages defined in the config section of the values.yaml

I have a simple loki stack setup (loki + promtail + grafana) for monitoring deployed on a local minikube cluster. I did that via the independent helm chart of each component ([loki](https://github.com/grafana/loki/tree/main/production/helm/loki) + [promtail](https://github.com/grafana/helm-charts/tree/main/charts/promtail) + [grafana](https://github.com/grafana/helm-charts/tree/main/charts/grafana)) and not via the dedicated locki-stack chart, but I don't think that it matters for my issue.

I have a couple of .NET APIs running in different pods in the same minikube cluster that implement structured logging via Serilog that I want to scrape with Promtail, store in Loki, and visuailize in Grafana. Here are how my logs are looking on the container level by running` kubectl logs <pod>`. [.net logs](https://i.stack.imgur.com/bVc4d.png) The basic setup is working, and my logs are succesfully picked up by Promtail and I can see them in Grafana [logs in grafana](https://i.stack.imgur.com/vLndy.png). The problem here is that the logs are not correctly parsed by Promtail and it doesn't pick up any fileds from my structured log format(ApplicationName, Environment, etc.) as you can see from the Grafana screenshot.

I have tried to add some custom pipeline stages for parsing the logs by overriding the default config section in the values.yaml file of the Promtail chart but for some reason none of my attempts changed anything as my json stages seem to not even get picked up or applied by Promtail. Here is my promtail config yaml file:

```
config:
  snippets:
    pipelineStages:
    - json:
        expressions:
          log:
          streamTest: stream
          timeTest: time
    - json:
        expressions:
          Environment:
        source: log
```
As you can see from the grafana screenshot not even the streamTest or timeTest fields got applied even though they seem the easiest to parse to me as the stream and time fields are not even nested in the initial json object that get's sent to grafana. I have tested multiple stages in the pipelineStages: section and none of them seem to get applied, also tried to add a - cri: stage before the -json stages, but it also didn't have any effect.

I am able to get the result that I need by parsing the logs via a LogQL query in Grafana: [parsed logs via LogQl](https://i.stack.imgur.com/sRV7N.png), but I really would like to learn and understand what I am doing wrong in the Promtail config and why my custom pipeline stages don't get applied.

**Comment by guerrap** [comment]
Hey, I may have stumbled across the same issue it seems, did you manage to make promtail pick up the custom configuration?

**Comment by Shape-Klug** [comment]
Hello, I managed to make it work using the following config:
```yaml
# values.yaml
config:
  snippets:
    pipelineStages: |
      - json:
          expressions: 
            app: resourceId
            resultDescription: resultDescription
      - replace:
          expression: (^.*\/+)
          source: app
          replace: ""
      - labels:
          app:
      - output:
          source: resultDescription
  file: |
    server:
      log_level: {{ .Values.config.logLevel }}
      log_format: {{ .Values.config.logFormat }}
      http_listen_port: {{ .Values.config.serverPort }}
      {{- with .Values.httpPathPrefix }}
      http_path_prefix: {{ . }}
      {{- end }}
      {{- tpl .Values.config.snippets.extraServerConfigs . | nindent 2 }}

    clients:
      {{- tpl (toYaml .Values.config.clients) . | nindent 2 }}

    positions:
      {{- tpl (toYaml .Values.config.positions) . | nindent 2 }}

    scrape_configs:

      {{- tpl .Values.config.snippets.scrapeConfigs . | nindent 2 }}
        # everything is default but the next 2 lines
        pipeline_stages: 
        {{- tpl .Values.config.snippets.pipelineStages . | nindent 6 }}
      {{- tpl .Values.config.snippets.extraScrapeConfigs . | nindent 2 }}
        

    limits_config:
      {{- tpl .Values.config.snippets.extraLimitsConfig . | nindent 2 }}

    tracing:
      enabled: {{ .Values.config.enableTracing }}
```

Hope it helps.
