### ISSUE TITLE
[tempo-distributed] add metrics_ingestion_time_range_slack to metrics_generator config block

### ISSUE THREAD

**Issue by EStork09** [grafana/helm-charts#2432]
metrics_ingestion_time_range_slack is default value of 30s, it is a pretty quick add. I can create the PR but want to wait for [this issue](https://github.com/grafana/tempo/issues/2508) to get an answer. I believe it should be metrics_ingestion_time_range_slack but would rather not waste the time to update it.

under config:
```
  metrics_generator:
    ring:
      kvstore:
        store: memberlist
    processor:
      {{- toYaml .Values.metricsGenerator.config.processor | nindent 6 }}
    storage:
      {{- toYaml .Values.metricsGenerator.config.storage | nindent 6 }}
    registry:
      {{- toYaml .Values.metricsGenerator.config.registry | nindent 6 }}
    metrics_ingestion_time_range_slack: {{ .Values.metricsGenerator.config.metrics_ingestion_time_range_slack }}
```
and under 
```
metricsGenerator:
  config:
    metrics_ingestion_time_range_slack = 30s
```
I'll make the PR later unless someone beats me to it
