### ISSUE TITLE
Alert Provisioning - Is there a way to import alerts and contact points using url?

### ISSUE THREAD

**Issue by sakos95** [grafana/helm-charts#2437]
I would like to import alerts and contact points to grafana from a yaml file by providing an url. I saw that dashboard json files can be imported from an url like this:
```
dashboards:
  default:
    local-dashboard:
      url: https://raw.githubusercontent.com/user/repository/master/dashboards/dashboard.json
```
But for alerts, I only found examples of inline import and local file import. Is there a way to import alerts and contact points from an url as well? Something like this:
```
alerting:
  alerts.yaml:
    url: https://raw.githubusercontent.com/user/repository/master/alerts/alerts.yaml
```
