### ISSUE TITLE
Duplicate ports defined in grafana deployment

### ISSUE THREAD

**Issue by mts-dyt** [grafana/helm-charts#2447]
# Describe the bug
port 9094 is defined twice in the grafana deployment spec, as in the following example:
```
        - name: grafana
          image: grafana/grafana:9.4.7
          ports:
            - name: grafana
              containerPort: 3000
              protocol: TCP
            - name: gossip-tcp
              containerPort: 9094
              protocol: TCP
            - name: gossip-udp
              containerPort: 9094
              protocol: UDP
```
This is no more compatible with Kubernetes > 1.26
see issue: https://github.com/kubernetes/kubernetes/issues/118261

# To reproduce
- Create a Kubernetes cluster > 1.26
- Install grafana from helm chart
- Delete the pod grafana
- The pod get never deleted and stuck into Terminating state

# Expected behaviour
We should be able to customize these ports
