### ISSUE TITLE
Feature Request: Support for Provisioning Dashboards from Grafana.com

### ISSUE THREAD

**Issue by rafilkmp3** [grafana/helm-charts#2448]
Hello Grafana Helm charts maintainers,

I'm currently using the Grafana Helm chart to deploy Grafana in my Kubernetes clusters as a dependency in my custom Helm chart. Here is the content of my `chart.yaml`:

```yaml
apiVersion: v2
appVersion: "1.0"
description: grafana
name: Grafana
version: 1.0.0
dependencies:
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: ^6.56.6
```

And these are the values I'm using in my custom Helm chart for the Grafana dependency:

```yaml
grafana:
  grafana.ini:
    paths:
      data: /var/lib/grafana/
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    analytics:
      check_for_updates: true
    log:
      mode: console
    grafana_net:
      url: https://grafana.net
    server:
      domain: grafana.foo.bar

  adminPassword: admin

  autoscaling:
    enabled: true
  ingress:
    hosts:
      - grafana.foo.bar
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
      provider:
        foldersFromFilesStructure: true
    datasources:
      enabled: true
      searchNamespace: ALL
    alerts:
      enabled: true
      searchNamespace: ALL
```

However, I've noticed a feature in the Grafana operator that I'd like to see supported in the Helm chart: the ability to provision dashboards directly from Grafana.com.

In the Grafana operator, I can specify a dashboard to be provisioned from Grafana.com simply by specifying the `grafanaCom` field in the `GrafanaDashboard` object:

```yaml
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata:
  name: performance-health-dashboard
  labels:
    app: grafana
spec:
  grafanaCom:
    id: 15160
    revision: 19
  datasources:
    - inputName: "DS_PROMETHEUS"
      datasourceName: "Prometheus"
```

This feature is incredibly useful, as it allows me to easily provision dashboards directly from Grafana.com without needing to manually download and include the JSON in my Kubernetes resources. It would be great if the Helm chart supported something similar. I believe this would be a beneficial addition for many users of the Grafana Helm chart.

Thank you for your time and consideration!
