### ISSUE TITLE
Disabled selfmonitoring and grafana agent (but use Grafana operator)

### ISSUE THREAD

**Issue by DanielCastronovo** [grafana/helm-charts#2467]
Hello,

I want to disable selfMonitoring, and Grafana Agent.
So i use this configuration
```
monitoring:
  # Disable self-monitoring
  selfMonitoring:
    enabled: false
    # Grafana Agent configuration
    grafanaAgent:
      installOperator: false
  # The Loki canary pushes logs to and queries from this loki installation to test
  # that it's working correctly
  lokiCanary:
    enabled: false
  ```
  
But, when i deployed it, an error has been generated related to the Grafana operator.
  ``` Error: error running dry run for a diff: [resource mapping not found for name: "loki" namespace: "" from "": no matches for kind "GrafanaAgent" in version "monitoring.grafana.com/v1alpha1"
│ ensure CRDs are installed first, resource mapping not found for name: "loki" namespace: "" from "": no matches for kind "LogsInstance" in version "monitoring.grafana.com/v1alpha1"
│ ensure CRDs are installed first, resource mapping not found for name: "loki" namespace: "" from "": no matches for kind "PodLogs" in version "monitoring.grafana.com/v1alpha1"
│ ensure CRDs are installed first]
│ 
│   with module.loki.helm_release.loki,
│   on .terraform/modules/loki/main.tf line 5, in resource "helm_release" "loki":
│    5: resource "helm_release" "loki" {
│ 
  ```
  
I don't understand why this error is occured, also when the self-monitoring, grafanagent and lokicanary are disabled.
  
  Loki chart version : 5.7.1

**Comment by bertoneone** [comment]
Same applies here, I am trying to avoid having the agent without any success. I basically tried to disable all parts in monitoring without any success:

```
# Monitoring section determines which monitoring features to enable
monitoring:
  # Dashboards for monitoring Loki
  dashboards:
    # -- If enabled, create configmap with dashboards for monitoring Loki
    enabled: false
  # Autogenerated recording rules for monitoring Loki - required for some dashboards
  rules:
    enabled: false
    alerting: false
  serviceMonitor:
    enabled: false  # ServiceMonitor resources for Prometheus Operator are created when enabled
    metricsInstance:
      enabled: false  # MetricsInstance resources for Grafana Agent Operator are created when enabled
  # Self monitoring determines whether Loki should scrape its own logs.
  # This feature currently relies on the Grafana Agent Operator being installed,
  # which is installed by default using the grafana-agent-operator sub-chart.
  # It will create custom resources for GrafanaAgent, LogsInstance, and PodLogs to configure
  # scrape configs to scrape its own logs with the labels expected by the included dashboards.
  selfMonitoring:
    enabled: false
  # Bug: Telemetry collector not required - disabling selfMonitoring should disable it but it doesn't somehow!
  grafanaAgent:
    installOperator: false
  # The Loki canary pushes logs to and queries from this loki installation to test that it's working correctly
  lokiCanary:
    enabled: false
```

Loki chart 5.8.8

**Comment by weakcamel** [comment]
I'm seeing the same problems even with using the example configuration from https://grafana.com/docs/loki/latest/installation/helm/install-monolithic/

```
+ echo 'Installing helm_v3 chart'
+ helm_v3 install --namespace monitoring --repo https://grafana.github.io/helm-charts --version 5.8.9 loki loki --values /config/values-01_HelmChart.yaml
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "loki" namespace: "" from "": no matches for kind "PodLogs" in version "monitoring.grafana.com/v1alpha1"
ensure CRDs are installed first
```

I tried to fix it by enabling the operator option yet it had no effect.

My full values.yaml:

```
---
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
singleBinary:
  replicas: 1
monitoring:
  selfMonitoring:
    grafanaAgent:
      installOperator: true
```
