### ISSUE TITLE
[grafana] admin pswd not working when using not-sqlite3 db

### ISSUE THREAD

**Issue by MysterioO** [grafana/helm-charts#2472]
We are using postgres DB (gcp), and connecting to it with cloudsql proxy side car. Connection is established and working perfectly. However, local admin password that is needed for initial configuration is not working. We are storing it in a secret.
```
admin:
  ## Name of the secret. Can be templated.
  existingSecret: ""
  userKey: admin-user
  passwordKey: admin-password
```
Once we switch db to sqlite3 in grafana.ini, admin pswd is being recognised. 
```
  database:
    # type: postgres
    # host: 127.0.0.1:5432
    # name: grafana
    # user: grafana-dashboards@xxxxx.iam
    type: sqlite3
    path: /var/lib/grafana/grafana.db

```
Is something wrong with our config or this is some bug ?
