### ISSUE TITLE
error converting YAML to JSON: While upgrading existing grafana chart

### ISSUE THREAD

**Issue by beingnishas** [grafana/helm-charts#2502]
I have installed grafana on my cluster using
```shell
#Install grafana
helm repo add grafana https://grafana.github.io/helm-charts
helm repo update
helm install my-release grafana/grafana -f helm-charts/grafana-values.yaml

```
But I would like to add a persistent storage so I updated grafana-values.yaml to use
```
persistence:
  type: pvc
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  finalizers:
    - kubernetes.io/pvc-protection
  extraPvcLabels: {}

  inMemory:
    enabled: false
```

After enabling persistent storage I run 
```
helm upgrade -i my-release grafana/grafana -f helm-charts/grafana-values.yaml
```
and I get error 

```
Error: UPGRADE FAILED: YAML parse error on grafana/templates/deployment.yaml: error converting YAML to JSON: yaml: line 51: did not find expected key
```
But there is nothing which was changed in deployment.yaml or anything in templates directory. The issue is after simply updating the values.yaml when I run helm upgrade it should allow me to update the chart with latest values.
