### ISSUE TITLE
Compactor not starting with GCS object storage index

### ISSUE THREAD

**Issue by whaleqiss** [grafana/helm-charts#2513]
I'm facing an issue with the Loki compactor not starting when using GCS as the object storage index. I have followed the documentation and made the necessary configurations, but the compactor does not seem to initialize.

Here are the relevant sections from my values.yaml file:
Loki-distributed version: 0.69.11

```
loki:
  ....
  config: |
  ...
  compactor:
      shared_store: gcs
      compaction_interval: 10m
      working_directory: /loki/compactor
      compactor_ring:
       kvstore:
         store: consul
         consul:
            host: "consul-server.consul.svc.cluster.local:8500"
```

```
schemaConfig:
    configs:
    - from: 2020-09-07
      store: cassandra 
      object_store: gcs
      schema: v11
      index:
        prefix: loki_index_
        period: 480h 
      chunks:
        prefix: chunk_
        period: 480h 

  storageConfig:
    gcs:
      bucket_name: pa-loki-dev
    cassandra: 
      addresses: cassandra.loki.svc.cluster.local
      port: 9042
      keyspace: loki
      consistency: ONE
      auth: true
      username: "cassandra"
      password: CASSANDRA_PASSWORD
    index_queries_cache_config:
      redis:
        endpoint: "redis-master.redis.svc.cluster.local:6379"
        expiration: 24h
        db: 4
        timeout: 60s
        pool_size: 20

  structuredConfig: {}
```

However, when I start the Loki deployment, I only see the following logs related to the compactor:

`level=info ts=2023-07-16T21:41:04.464465647Z caller=modules.go:1023 msg="Not using object storage index, not starting compactor"
`

t seems like the object storage index is not being recognized or utilized by the compactor.

I have verified my configuration multiple times and ensured that the necessary dependencies (such as GCS credentials and access) are correctly set up.

Any assistance in resolving this issue would be greatly appreciated. Thank you!
