### ISSUE TITLE
[promtail] promtail display the new logs in one timestamp after redeploy the service pod

### ISSUE THREAD

**Issue by YuWan1117** [grafana/helm-charts#2520]
## Question Description
This afternoon, a colleague reported that after the newly deployed service,It could not query the logs by loki on grafana UI.

After expanding the query time range, it is found that there are significantly more 13:41 logs, and it is determined that the 13:41 log contains the latest log information.

### grafana UI  （Query the logs of the last 140mins）
![image](https://github.com/grafana/helm-charts/assets/7919137/1e5e35bf-7049-4e99-9a9c-fbe6537b9dcc)

### the new log info
> @timestamp: "2023-07-19T06:36:59.523Z" (filebeat process time)
> datetime："2023-07-19T06:36:59.176895791Z" （the log time）
> Time：1689745264963 （2023-07-19 13:41:04）

![image](https://github.com/grafana/helm-charts/assets/7919137/0ff4936c-4f64-4273-b386-34698d72b7e8)

## The questions
1. Why are the logs for this service all written to the same timestamp?
2. Finally recover it by restart Promtail, But Why?
### restart command
`![image](https://github.com/grafana/helm-charts/assets/7919137/4a8b6aa3-9109-4293-b4fd-1840cf8e96b5)

## Others Info
Our log processing flow :  Collecting pod logs through `filebeat`, process them and write them to `Kafka`; Then consume `Kafka` logs through `Promtail`, process them and write them to `Loki`.

### promtail Config
```yaml
    scrapeConfigs: |
      - job_name: kafka
        kafka:
          brokers:
            - XXXXX:9092
            - XXXXX:9092
            - XXXXX:9092
          topics:
            - ^service_.*
          group_id: "promtail-prod"
          version: "1.1.1"
          labels:
            job: kafka
          use_incoming_timestamp: true

        pipeline_stages:
        - json:
            expressions:
              service: service
              cluster: cluster
              message: message

        - regex:
            expression: '(?P<log_time>\d{4}(-|\/)\d{2}(-|\/)\d{2}(?:T| )?\d{2}:\d{2}:\d{2}(?:,|\.)?(?:\d{3})?(?:( |)\+\d{2}(:|)\d{2})?).*'
            source: message

        - labels:
            service:
            cluster:

        - timestamp:
            source: log_time
            format: '2006-01-02 15:04:05.999'
            fallback_formats:
            - '2006-01-02T15:04:05.999-0700'
            - '2006-01-02 15:04:05.999-07:00'
            - '2006-01-02T15:04:05.999'
            location: 'Asia/Shanghai'

        relabel_configs:
          - action: replace
            source_labels:
              - __meta_kafka_topic
            target_label: topic
          - action: replace
            source_labels:
              - __meta_kafka_partition
            target_label: partition
          - action: replace
            source_labels:
              - __meta_kafka_group_id
            target_label: group
```

## Final
We are looking forward to your discussion / response. Thanks~
