### ISSUE TITLE
Issue connecting loki-stack to bucket S3

### ISSUE THREAD

**Issue by aarens66** [grafana/helm-charts#2522]
Hello,
I'm not able to send logs from GKE using loki-stack (helm) to a bucket S3 (Single storage). I added via values.yaml this below loki statement config https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/values.yaml:

storage_config:
    boltdb_shipper:
      active_index_directory: /loki/boltdb-shipper-active
      cache_location: /loki/boltdb-shipper-cache
      cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
      shared_store: s3
    aws:
      s3: s3://<access_key>:<uri-encoded-secret-access-key>@<region>
      bucketnames: buket-name
  schema_config:
    configs:
      - from: 2020-07-01
        store: boltdb-shipper
        object_store: aws
        schema: v11
        index:
          prefix: index_
          period: 24h

Does anyone know if this is a bug or a configuration error?
PD: It seems that the access key is never used, (I have the permissions).
Thanks!

**Comment by david-nano** [comment]
It's really hard to find issues here, YAML can be read well when doing tabbing, please help us by marking your YAML as code block so it'll be readable.
For storage you can read here: https://grafana.com/docs/loki/latest/installation/helm/configure-storage/
Important part here is:
```
loki:
  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    type: s3
    s3:
      s3: null
      endpoint: null #Make sure to provide the relevant endpoint here.
      region: null
      secretAccessKey: null #make sure to add here the keys.
      accessKeyId: null
      signatureVersion: null
      s3ForcePathStyle: false
      insecure: false
      http_config: {}
```

**Comment by aarens66** [comment]
Sorry, I use the values.yaml of loki-stack and added this config:
```
loki:
...
  storage_config:
      boltdb_shipper:
        active_index_directory: /loki/boltdb-shipper-active
        cache_location: /loki/boltdb-shipper-cache
        cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
        shared_store: s3
      aws:
        s3: s3://<access_key>:<uri-encoded-secret-access-key>@<region>
        bucketnames: buket-name
    schema_config:
      configs:
        - from: 2020-07-01
          store: boltdb-shipper
          object_store: aws
          schema: v11
          index:
            prefix: index_
            period: 24h
```

**Comment by aarens66** [comment]
> It's really hard to find issues here, YAML can be read well when doing tabbing, please help us by marking your YAML as code block so it'll be readable. For storage you can read here: https://grafana.com/docs/loki/latest/installation/helm/configure-storage/ Important part here is:
> 
> ```
> loki:
>   storage:
>     bucketNames:
>       chunks: chunks
>       ruler: ruler
>       admin: admin
>     type: s3
>     s3:
>       s3: null
>       endpoint: null #Make sure to provide the relevant endpoint here.
>       region: null
>       secretAccessKey: null #make sure to add here the keys.
>       accessKeyId: null
>       signatureVersion: null
>       s3ForcePathStyle: false
>       insecure: false
>       http_config: {}
> ```

Sorry, I use the values.yaml of loki-stack and added this config:

```
loki:
...
  storage_config:
      boltdb_shipper:
        active_index_directory: /loki/boltdb-shipper-active
        cache_location: /loki/boltdb-shipper-cache
        cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
        shared_store: s3
      aws:
        s3: s3://<access_key>:<uri-encoded-secret-access-key>@<region>
        bucketnames: buket-name
    schema_config:
      configs:
        - from: 2020-07-01
          store: boltdb-shipper
          object_store: aws
          schema: v11
          index:
            prefix: index_
            period: 24h
```

Can I use this repo (https://github.com/grafana/helm-charts/tree/main/charts/loki-stack) or do I have to use the chart you mention?
