### ISSUE TITLE
[promtail] Impossible to scrape only certain pods and discard everything else

### ISSUE THREAD

**Issue by nforced** [grafana/helm-charts#2590]
I am trying to log a very limited amount of data but with default helm config *everything* from /var/log/pods is fed to Loki.
Tried many different approaches but none of them works and all pods logs are sent to Loki which a big overhead that I don't need for many reasons.

Question is: how do I filter what is scraped? I am looking for a negative match to discard everything that doesn't include "-service" in it's pod name and scrape only valid json lines. Thanks!

```
config:
  snippets:
    addScrapeJobLabel: true
    pipelineStages:
      - cri: {}
      - json:
          drop_malformed: true
          expressions:
            message: message
```
