### ISSUE TITLE
Problem loading dashboards from helm chart

### ISSUE THREAD

**Issue by oktayalizada** [grafana/helm-charts#2596]
I have tried to load dashboards from helm chart with the values file:
```
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: prom
      type: prometheus
      isDefault: true
      readonly: false
    - name: Elastic
      type: elasticsearch
      password: ""
      user: ""
      isDefault: false
      readonly: false
dashboardProviders:
   dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: 'default'
       orgId: 1
       folder: ''
       type: file
       disableDeletion: false
       editable: true
       options:
         path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    test:
      json: |
          ${indent(8, file("./dashboards/test.json"))}
```

but 
I am getting this error:

```
msg="failed to load dashboard from " file=/var/lib/grafana/dashboards/default/test.json error="invalid character '$' looking for b
beginning of value"
```

I have also tried the following values:

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: prom
      type: prometheus
      isDefault: true
      readonly: false
    - name: Elastic
      type: elasticsearch
      password: ""
      user: ""
      isDefault: false
      readonly: false
dashboardProviders:
   dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: 'default'
       orgId: 1
       folder: ''
       type: file
       disableDeletion: false
       editable: true
       options:
         path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    test:
      json: |
        file: dashboards/test.json

```
 level=error msg="failed to load dashboard from " file=/var/lib/grafana/dashboards/default/test.json error="invalid character 'i' in literal fa
lse (expecting 'a')"
```
