### ISSUE TITLE
[promtail] passing blank readinessProbe in values file dosent work

### ISSUE THREAD

**Issue by suraj2410** [grafana/helm-charts#2599]
We have issues with promtail when it doesnt pass readiness probe for Daemonset where it cannot find any logs to read and just hangs there forever with the following logs
```
level=warn ts=2023-08-15T14:42:04.3891924Z caller=logging.go:86 msg="GET /ready (500) 38.366µs Response: \"Not ready: Unable to find any logs to tail. Please verify permissions, volumes, scrape_config, etc.\\n\" ws: false; Accept: */*; Connection: close; User-Agent: kube-probe/1.25+; "
```

I tried passing readinessProbe to blank just like livenessProbe as below:
```
readinessProbe: {}
```
However it still comes with the default readiness probe and doesnt somehow read the {} value

promtail chart version: 
```
dependencies:
  - name: promtail
    version: 6.14.1
    repository: https://grafana.github.io/helm-charts
```

**Comment by abdessamad-b** [comment]
@suraj2410 you can set the `health_check_target` to `false`  to ignore the readiness probes

```
  config:
    snippets:
      extraServerConfigs: |
        health_check_target: false
```
