### ISSUE TITLE
sidecar.notifiers - is it used? 

### ISSUE THREAD

**Issue by larsrnielsen** [grafana/helm-charts#260]
I have tried to find examples of how to use `sidecar.notifiers` to create a slack notifier, but google turns up nothing. I found an example in an issue on Github, but when I configure my values.yaml like

```
grafana:
      dashboards:
        enabled: true
        label: grafana_dashboard
        searchNamespace: ALL
      notifiers:
        enabled: true
        label: grafana_notifier
        searchNamespace: ALL
```

then it is not reflected in my Grafana CM like the above dashboards is. `Chart: kube-prometheus-stack, version: 13.13.1`.  This chart has a dependency like

```
- name: grafana
  version: "6.4.*"
  repository: https://grafana.github.io/helm-charts
  condition: grafana.enabled
```

The slack URLs include a secret token, so is it correct to use a ConfigMap? Shouldn't that be a Secret, similar to a DataSource? Basically, should I go the sidecar way or is it still a bit unstable?

Lars

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: slack-notifier
  labels:
     grafana_notifier: "1"
     namespace: monitoring
data:
  notifierslack.yaml: |
    notifiers:
    - is_default: false
      name: slack-alertsd
      org_id: 1
      settings:
        uploadImage: false
        url: https://hooks.slack.com/services/token
      type: slack
      uid: slack
```
