### ISSUE TITLE
Failed to load the data source configuration for Loki: Unable to fetch alert rules. Is the Loki data source properly configured

### ISSUE THREAD

**Issue by jones-traice** [grafana/helm-charts#2601]
Getting the following error when Loki is added as a Datasource.

===========
Failed to load the data source configuration for [Loki](http://10.160.15.210:32019/datasources/edit/ff544df8-ca25-498a-aac8-185ceda452bb): Unable to fetch alert rules. Is the Loki data source properly configured
============

Loki is added using the helm ''grafana/loki-stack''

**Comment by jobcespedes** [comment]
Same here: `loki-stack` along with `kube-prometheus-stack`

**Comment by rahulmr** [comment]
Is there any update or bypass to fix this?
I read below rules must be added but where? What is missing in the alert rules, any documentation on this?
```
loki:
  ruler:
    storage:
      type: local
      local:
        directory: /loki/rules
    rule_path: /tmp/rules/fake/
    alertmanager_url: http://localhost:9093
    ring:
      kvstore:
        store: inmemory
    enable_api: true

```

**Comment by blackdocs** [comment]
Its working for me. I'm using loki-distributed helm chart. Just in case if you are using gateway instead of ingress, you must configure loki datasource url as gateway service url. In case if you are using ingress instead of gateway you must configure loki tadasource url to your ingress host.

**Comment by dark-brains** [comment]
This configurations is working for me until now.

**Comment by ehddnko** [comment]
I also use the loki-distributed Helm chart. I solved this issue by disabling the ‘Manage alerts via Alerting UI’ option in the Loki datasource because I’m not using the ruler component in Loki.

In summary, if you use the ruler component in Loki, set `ruler.directories` as mentioned by @dark-brains. If you do not use the ruler component, disable the ‘Manage alerts via Alerting UI’ option in the datasource to prevent error messages from appearing in the UI.

@jones-traice, I haven’t tested it, but you should be able to disable the ‘Manage alerts via Alerting UI’ option in grafana/loki-stack using the following format.
```
loki:
  datasource:
    jsonData: |
      {
        "manageAlerts": false
      }
```
Or set `ruler.directories` using the following format.
```
loki:
  ruler:
    directories:
      ...
```
