### ISSUE TITLE
Does not deploy on openshift/OKD

### ISSUE THREAD

**Issue by webrod** [grafana/helm-charts#261]
I'm running this command to deploy, specifying securityContext as openshift requires number within a range:
`helm install grafana grafana/grafana     -n grafana     --set persistence.storageClassName="thin"     --set persistence.enabled=true     --set adminPassword='mypassord'   --values ${HOME}/environment/grafana/grafana.yaml **--set securityContext.runAsUser=1000640000,securityContext.runAsGroup=1000640000,securityContext.fsGroup=1000640000**
`

however, pods do not start with this error:
```
message: 'pods "grafana-75bb78bd6b-" is forbidden: unable to validate against
      any security context constraint: [spec.initContainers[0].securityContext.runAsUser:
      Invalid value: 0: must be in the ranges: [1000640000, 1000649999]]'

```

It is hardcoded in the template:
```
https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/_pod.tpl
 securityContext:
      runAsNonRoot: false
      runAsUser: 0
    command: ["chown", "-R", "{{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.runAsGroup }}", "/var/lib/grafana"]

```
So I cannot override this right?
any reason why this is hardcoded?
