### ISSUE TITLE
[tempo-distributed] service tempo-distributor-discovery create annotation for external-dns but it's not needed

### ISSUE THREAD

**Issue by DanielCastronovo** [grafana/helm-charts#2617]
Hi, 

With the tempo-distributed Helm chart, specially on theses components  : 
 - tempo-distributor
 - tempo-distributor-discovery

Theses two service use the same annotation (`.Values.distributor.service.annotations`)

So external-dns create theses, also this is not needed on tempo-distributor-discovery because is not exposed.


```
apiVersion: v1                                                                                                                                                                                                                                                                                                                                                                             
kind: Service                                                                                                                                                                                                                                                                                                                                                                              
  metadata:                                                                                                                                                                                                                                                                                                                                                                                  name: tempo-distributor-discovery                                                                                                                                                                                                                                                                                                                                                        
  namespace: monitoring                                                                                                                                                                                                                                                                                                                                                                    
  labels:                                                                                                                                                                                                                                                                                                                                                                                  
    helm.sh/chart: tempo-distributed-1.6.2                                                                                                                                                                                                                                                                                                                                                 
    app.kubernetes.io/name: tempo                                                                                                                                                                                                                                                                                                                                                          
    app.kubernetes.io/instance: tempo                                                                                                                                                                                                                                                                                                                                                      
    app.kubernetes.io/component: distributor                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    app.kubernetes.io/managed-by: Helm                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
  annotations:                                                                                                                                                                                                                                                                                                                                                                             
    external-dns.alpha.kubernetes.io/hostname: xxx.xxx.xxx
```
