### ISSUE TITLE
[promtail-6.15.1] [bug] About deployment object update strategy

### ISSUE THREAD

**Issue by YuWan1117** [grafana/helm-charts#2637]
## Description
When trying to upgrade `loki` to version `2.8.4`, I found that the indentation of "deployment object update strategy" here is not as expected  in the values file of promtail-6.15.1.

## values.yaml
```YAML
deployment:
  # -- Deploys Promtail as a Deployment
  enabled: false
  replicaCount: 1
  autoscaling:
    # -- Creates a HorizontalPodAutoscaler for the deployment
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage:
    # behavior: {}

    # -- Set deployment object update strategy
    strategy:
      type: RollingUpdate
```
[Reference Code](https://github.com/grafana/helm-charts/blob/3173f67f30fbf791664550d6c88e6461bc98fc31/charts/promtail/values.yaml#L62C9-L63)

## deployment.yaml
```YAML
spec:
  {{- if not .Values.deployment.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  {{- if .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- end }}
  {{- with .Values.deployment.strategy }}
  strategy:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
```
[Reference Code](https://github.com/grafana/helm-charts/blob/3173f67f30fbf791664550d6c88e6461bc98fc31/charts/promtail/templates/deployment.yaml#L20-L23)

## Expected
> should modify the file named values.yaml like this:
```YAML
## values.yaml
```YAML
deployment:
  # -- Deploys Promtail as a Deployment
  enabled: false
  replicaCount: 1
  autoscaling:
    # -- Creates a HorizontalPodAutoscaler for the deployment
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage:
    # behavior: {}

  # -- Set deployment object update strategy
  strategy:
    type: RollingUpdate
```
