### ISSUE TITLE
BUG tempo-distributed - Invalid comparison causes topologySpreadConstraints not to be applied

### ISSUE THREAD

**Issue by herrbpl** [grafana/helm-charts#2641]
Tempo chart decides upon whether to add `topologySpreadConstraints` to manifests or not upon condition:

Example from ingester:
```helm
{{- if ge (.Capabilities.KubeVersion.Minor|int) 19 }}
{{- with .Values.ingester.topologySpreadConstraints }}
topologySpreadConstraints:
  {{- tpl . $ | nindent 8 }}
{{- end }}
{{- end }}
```
However, kubeversion may contain non-string values, resulting conversion to int being 0 and thus no `topologySpreadConstraints` in rendered manifests. 
Following is example of .Capabilities on EKS 1.26, as seen in Rancher internal helm renderer:

```yaml
APIVersions:
  ... omitted
HelmVersion:
  git_commit: 8853d6f9875eb3138d10f4af7a4a67130039e28b
  git_tree_state: clean
  go_version: go1.19.4
  version: v3.11.3-rancher1
KubeVersion:
  Major: "1"
  Minor: 26+
  Version: v1.26.7-eks-2d98532  
```
Recommended fix:
```helm
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
{{- with .Values.ingester.topologySpreadConstraints }}
topologySpreadConstraints:
  {{- tpl . $ | nindent 8 }}
{{- end }}
{{- end }}
```
