### ISSUE TITLE
Configmap handling for Query frontend is broke

### ISSUE THREAD

**Issue by datsabk** [grafana/helm-charts#2650]
Hello, 
Just tried to run query frontend with default configurations and noticed that it is broke. It does not include the `tempo-query.yaml` file in the `/conf` volume leading to crashing of the pod with default configuration. 

Here's [the link](https://github.com/grafana/helm-charts/blob/9442988b2ab0c9fa5b1b47b7c7131b79ad0e05b4/charts/tempo-distributed/templates/_helpers.tpl#L202C1-L206C25) to the code 

Need to replace: 
```
configMap:
  name: {{ tpl .Values.externalConfigSecretName . }}
  items:
    - key: "tempo.yaml"
      path: "tempo.yaml"
```
with 
```
configMap:
  name: {{ tpl .Values.externalConfigSecretName . }}
  items:
    - key: "tempo.yaml"
      path: "tempo.yaml"
   - key: "tempo-query.yaml"
      path: "tempo-query.yaml"
```
