### ISSUE TITLE
Helm chart for Grafana does not support reloading access-control

### ISSUE THREAD

**Issue by BlackDex** [grafana/helm-charts#2651]
Hello there,

It looks like there are a lot of sidecar provisioning reload options available.
but for access-control this seems to be missing.

Could this be added please?

**Comment by karthiktumu** [comment]
We are trying to add add/modify existing RBAC roles using helm chart and noticed the same issue as mentioned here. Is there any timeline on when this feature can be implemented?

**Comment by karthiktumu** [comment]
I was able to workaround this for time being by making use of extraConfigMapMount config param and adding the required role as configmap.

Below is what I did to add public dashboard write action to Basic_Editor role.

**Role-ConfigMap**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-custom-editor-role
data:
  customrole.yaml: |
    apiVersion: 2
    roles:
    - uid: 'basic_editor'
      version: {{ add1 .Values.grafana.customAccessControl.basicEditorCurrentVersion }}
      global: true
      from:
      - uid: 'basic_editor'
        global: true
        version: {{ .Values.grafana.customAccessControl.basicEditorCurrentVersion }}
      permissions:
      - action: 'dashboards.public:write'
        scope: 'dashboards:*'
```

Inside grafana helm chart values.yaml
```yaml
grafana:
  extraConfigmapMounts:
  - name: grafana-custom-editor-role
    mountPath: /etc/grafana/provisioning/access-control
    configMap: grafana-custom-editor-role
    readOnly: true

  customAccessControl:
    basicEditorCurrentVersion: 1
```

**NOTE** :- You have pull the current version (**basicEditorCurrentVersion** above) of the roles you are planning to modify using a get call on http api.
