### ISSUE TITLE
Default values not working for tempo distributed

### ISSUE THREAD

**Issue by Smixi** [grafana/helm-charts#2652]
Hi,
I've been trying to follow the documentation [here](https://grafana.com/docs/tempo/latest/setup/helm-chart/) to setup tempo. I'm quite new to helm and kubernetes management.
The MinIO chart (when minio.enabled is set) will generate its own credentials, which make Tempo configuration wrong.

I figured out that minio related values are incorrect: 

This works:
```yaml
minio:
  enabled: true
  accessKey: 'grafana-tempo'
  secretKey: 'supersecret'
```

In the documentation : 

![image](https://github.com/grafana/helm-charts/assets/27704246/bca6bb38-1959-486d-a642-4fc84cd75fe7)

Which is refering to the wrong version of the MinIO charts (latest vs https://artifacthub.io/packages/helm/minio/minio/8.0.9)
