### ISSUE TITLE
Why is loki-stack chart not using last version of promtail chart

### ISSUE THREAD

**Issue by sbl-matter** [grafana/helm-charts#2653]
Hi,

I'm trying to figure out dependencies in the loki-stack chart.

From what I see, in loki-stack requirements, the promtail requirement is like this : 

```
- name: "promtail"
  condition: promtail.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "^6.7.4"
```

When I do a dry run of loki-stack chart version 2.9.11 like this : 
`helm install --dry-run --create-namespace lokirelease loki/loki-stack --version 2.9.11 -n test`

I see on the promtail daemonset labels this : 
```
# Source: loki-stack/charts/promtail/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lokirelease-promtail
  namespace: test
  labels:
    helm.sh/chart: promtail-6.13.1
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: lokirelease
    app.kubernetes.io/version: "2.8.3"
    app.kubernetes.io/managed-by: Helm
[...]
``` 
The promtail chart version used is the 6.13.1.
My question is, why not a higher version ? I see a release for 6.14 and 6.15.
