### ISSUE TITLE
[tempo-distributed] tempo-distributor and tempo-distributor-discovery uses the same annotations

### ISSUE THREAD

**Issue by manojm321** [grafana/helm-charts#2672]
Ambassador throws a config error due to the same name across 2 services.

example annotation for ambassador proxy.
```yaml
    annotations:
      getambassador.io/config: |
        ---
        apiVersion: getambassador.io/v2
        kind:  Mapping
        name:  tempo_grpc_mapping <----- this will be used  for both
```
