### ISSUE TITLE
How to set grafana-agent-integration-ds containers securityContext?

### ISSUE THREAD

**Issue by eingram23** [grafana/helm-charts#2680]
Using helm chart version 0.3.4 and agent version v0.36.2.

Running on k3s v1.28.1+k3s1 on Rocky 9.2.

When using the node-exporter integration, I get the following in my integration pod logs:

level=error component=integrations integration=node_exporter instance=k3s1:8080 msg="collector failed" name=filesystem duration_seconds=0.000106814 err="open host/proc/1/mounts: permission denied"

If I disable selinux, it works. The typical workaround is to allow privileged access for the containers to be able to access the fs, but it's not clear how to do that when using the agent operator with integrations. Setting values for the helm chart only seem to affect securityContext for the operator pods.

I'm assuming I need to set securityContext in the node-exporter Integration manifest but I'm not sure where. If I put it under spec: it doesn't seem to take effect.

I confirmed I'm able to run privileged pods on my cluster.

This my node-exporter integration. The spec.securityContext settings are my additions but they don't seem to do anything. When I look at the resulting container, it just shows privileged:false.

```
apiVersion: monitoring.grafana.com/v1alpha1
kind: Integration
metadata:
  labels:
    agent: grafana-agent-integrations
  name: node-exporter
  namespace: grafana
spec:
  securityContext:
    capabilities:
      add: ["SYS_TIME"]
    privileged: true
    runAsUser: 0
  config:
    autoscrape:
      enable: true
      metrics_instance: grafana/primary
    procfs_path: host/proc
    rootfs_path: /host/root
    sysfs_path: /host/sys
  name: node_exporter
  type:
    allNodes: true
    unique: true
  volumeMounts:
    - mountPath: /host/root
      name: rootfs
    - mountPath: /host/sys
      name: sysfs
    - mountPath: /host/proc
      name: procfs
  volumes:
    - hostPath:
        path: /
      name: rootfs
    - hostPath:
        path: /sys
      name: sysfs
    - hostPath:
        path: /proc
      name: procfs
```
