### ISSUE TITLE
Add possibility for separately creating volume and volumemount for grafana pod

### ISSUE THREAD

**Issue by anderssonw** [grafana/helm-charts#2685]
I'm attempting to setup workload identity federation for GCP much according to [this documentation](https://cloud.google.com/anthos/clusters/docs/multi-cloud/aws/how-to/use-workload-identity-google#determine_the_workload_identity_pool_for_your_cluster). However, it seems to not be possible with the current available `values.yaml` for the grafana chart.

You have to set the following three things on the deployment:
- Environment variable for the pod, pointing to the location of your application default credentials
- Volume with mount path for the service account wif key
- Volumemount with service account token and configmap souorce

The env var is possible with `env: {}` value

However, creating the volume and volumemount is not possible afaik

Setting the following:
```yaml
extraVolumeMounts:
  - name: gcp-ksa
    readOnly: true
    mountPath: /var/run/secrets/tokens/gcp-ksa

extraContainerVolumes:
  - name: gcp-ksa
    projected:
      defaultMode: 420
      sources:
        - serviceAccountToken:
            audience: <AUD>
            expirationSeconds: 172800
            path: token
        - configMap:
            items:
              - key: config
                path: google-application-credentials.json
            name: wif-setup-configmap
            optional: false
```

Results in an extra emptyDir called `gcp-ksa` due to how the chart handles `extraVolumeMounts`.
