### ISSUE TITLE
How to specific affinity for loki?

### ISSUE THREAD

**Issue by jenia** [grafana/helm-charts#2709]
Hello.

I'm installing [Loki to Kubernetes](https://grafana.com/docs/loki/latest/setup/install/helm/install-scalable/). I'm using minikube on my PC right now :blush: and Loki fails to starts because 2/3 of the loki-write pods have affinity errors: 
```
loki-backend-0                                0/2     Pending   0          85m
loki-backend-1                                2/2     Running   0          85m
loki-backend-2                                0/2     Pending   0          85m
loki-canary-8lmxf                             1/1     Running   0          85m
loki-gateway-5f96d67f97-2mxls                 1/1     Running   0          85m
loki-grafana-agent-operator-d7c684bf9-jqqd8   1/1     Running   0          85m
loki-logs-vnlkk                               2/2     Running   0          85m
loki-read-746d977fdd-d94wz                    1/1     Running   0          85m
loki-read-746d977fdd-smfxb                    0/1     Pending   0          85m
loki-read-746d977fdd-z57z7                    0/1     Pending   0          85m
loki-write-0                                  0/1     Pending   0          85m
loki-write-1                                  1/1     Running   0          85m
loki-write-2                                  0/1     Pending   0          85m

kubectl describe pod loki-write-1
1 node(s) didn't match pod anti-affinity rules. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.. 
```
How do I specify to the this affinity rule for all loki pods:
```
nodeSelector:
    kubernetes.io/hostname: minikube
```
P.S. I know I can use [monolith Loki](https://grafana.com/docs/loki/latest/setup/install/helm/install-monolithic/) but the problem is that it doesn't support minio but only the filesystem as storage. So if possible, I'd like to use the scalable Loki with minio but run it all on one node.

**Comment by Davenury** [comment]
I guess [this is the chart you're using](https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml). If so, you can override default affinity [for write component here](https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml#L821), by simply passing an empty object:
```yaml
write:
  ...
  affinity: {}
```
and it should work (you'll probably need to override it everywhere it's used),

**Comment by dedeira** [comment]
Did work? for me, using grafana/loki 6.18.0 it did not. I tried with 
affinity: {}
affinity: null
 affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: write
              topologyKey: kubernetes.io/hostname
For first two cases I got the default value as if nothing happened.
For the last I got both:

```
spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: write
              topologyKey: kubernetes.io/hostname
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/component: write
              topologyKey: kubernetes.io/hostname
```
No idea how this happens:)

**Comment by mossad-zika** [comment]
this bug still exists

**Comment by Fresa** [comment]
Might also wanna add a note to what the purpose of this affinity rule is for the write component and when to use it. Does it still make sense when enabling HPA for example? What are the consequences (max replicas vs number of nodes). Should you prefer different affinity when using HPA? What about topologySpreadConstraints?

**Comment by manueljishi** [comment]
Hello, this issue still exists on version 6.28.0 of the loki chart.
I have tried the following values on write component for the affinity
- {}
- null
- Overriding with a different affinity settings
For the 1st two options, it didn't change anything and the third one did just merge it into 2 affinity rules

**Comment by diwakar-in** [comment]
> Hello, this issue still exists on version 6.28.0 of the loki chart. I have tried the following values on write component for the affinity
> 
> * {}
> * null
> * Overriding with a different affinity settings
>   For the 1st two options, it didn't change anything and the third one did just merge it into 2 affinity rules
--------------------------------------------------------
Try this , it worked for me : 

deploymentMode: Distributed

ingester:
  replicas: 2 # To ensure data durability with replication
  affinity: 
  topologySpreadConstraints: 
  zoneAwareReplication:
     enabled: false
querier:
  replicas: 2 # Improve query performance via parallelism
  maxUnavailable: 1
  affinity: 
queryFrontend:
  replicas: 2
  maxUnavailable: 1
  affinity: 
queryScheduler:
  replicas: 2
  affinity: 
distributor:
  replicas: 2 
  maxUnavailable: 1
  affinity: 
compactor:
  replicas: 2
  affinity: 
indexGateway:
  replicas: 2
  maxUnavailable: 1
  affinity:

**Comment by FabioGentile** [comment]
We are facing the same issue and the only solution I found so far is to override the label in the antiAffinity rule in my `values.yaml` file:
```
  read:
    replicas: 10
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/component: not-read
            topologyKey: kubernetes.io/hostname
```

But that feels wrong. Is this really the only way to do it? 

Also, does anyone know what's the reason for a hard antiAffinity rule like this? Is the idea that we can only schedule one instance of each loki component per node in the k8s cluster? 
But why would that be?
