### ISSUE TITLE
Helm chart reporting erros since grafana-6.4.6

### ISSUE THREAD

**Issue by andrew-pickin-epi** [grafana/helm-charts#271]
"upgrade failed: unable to recognize \"\": no matches for kind \"Ingress\" in version \"networking.k8s.io/v1\""

Value file is available however this worked file until an hour ago or so, believe the problem is will upstream inconsistency.

**Comment by ymatsiuk** [comment]
There is a breaking change introduced in `6.4.6` and if your `values.yaml` contains ingress configuration, please make sure those comply with `networking.k8s.io/v1` ingress spec.

**Comment by andrew-pickin-epi** [comment]
Breaking changes should not be introduced as a minor version update.

**Comment by ymatsiuk** [comment]
This is completely another story, but I agree!

**Comment by andrew-pickin-epi** [comment]
How? 

This is my current ingress. It looks like it should match the current values.yaml file.

```
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          auth_request_set $user   $upstream_http_x_auth_request_user;
          auth_request_set $email  $upstream_http_x_auth_request_email;
          proxy_set_header X-User  $user;
          proxy_set_header X-Email $email;
      labels: {}
      hosts:
        - grafana__NAME__.epimorphics.net
      paths:
        - /
```

**Comment by ymatsiuk** [comment]
Check comments under [ingress section](https://github.com/grafana/helm-charts/blob/5ccc112675fba1c1d51cb4c59f30a108cda5095e/charts/grafana/values.yaml#L161)

**Comment by andrew-pickin-epi** [comment]
Are you saying that I now need to specify and Ingres Class?
In which case the values.yaml fine needs to show that this is now this mandatory.

My ingress file matches the intent of the current values.yaml file. If this is no longer correct the values.yaml file requires updating to reflect this. Some commented link to documentation is not sufficient.

**Comment by ymatsiuk** [comment]
Just to clarify: I'm in the same situation as you are currently - my helm is also broken due to validation errors. My issue is a bit different though and I've found my answers in the commented out section. 

There is a bug though -> missing `pathType` [here](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/ingress.yaml#L64)

**Comment by alongfield** [comment]
This exact thing is breaking for me with Kubernetes 1.16.  There is no "networking.k8s.io/v1" because it only has "networking.k8s.io/v1beta1" in that k8s version.

**Comment by bkbwese** [comment]
https://github.com/grafana/helm-charts/pull/262/files#diff-3cc6b406041b4e16cbcfce60566d7931bd50051cd73290333657b94865ecca72R7

The change to the ingress object didn't take into account that "networking.k8s.io/v1" has existed for a long time, but "networking.k8s.io/v1/Ingress" hasn't.

The Capabilities APIVersion call needs to check for the ingress object within networking.k8s.io/v1 not just networking.k8s.io/v1.
```
{{- $newAPI := .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
```

The change probably broke anyone using an ingress object not on v1.19.

**Comment by zanhsieh** [comment]
> https://github.com/grafana/helm-charts/pull/262/files#diff-3cc6b406041b4e16cbcfce60566d7931bd50051cd73290333657b94865ecca72R7
> 
> The change to the ingress object didn't take into account that "networking.k8s.io/v1" has existed for a long time, but "networking.k8s.io/v1/Ingress" hasn't.
> 
> The Capabilities APIVersion call needs to check for the ingress object within networking.k8s.io/v1 not just networking.k8s.io/v1.
> 
> ```
> {{- $newAPI := .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
> ```
> 
> The change probably broke anyone using an ingress object not on v1.19.
@bkbwese 
Could you also PR this please ?

**Comment by zanhsieh** [comment]
This version check has been fixed and merged in:

https://github.com/grafana/helm-charts/pull/273

**Comment by jtackaberry** [comment]
#273 has actually broken things for me.  It's resulting in the wrong Ingress configuration for my cluster.

```
$ helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.9-34+69a399560680be", GitCommit:"69a399560680be89d9b60c220c82560cf89adfaf", GitTreeState:"clean", BuildDate:"2021-03-22T17:05:12Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

With a fresh checkout, given this `grafana.yaml`:

```yaml
ingress:
  enabled: true
  pathType: Prefix
  ingressClassName: nginx
  hosts:
    - grafana.example.com
```

It generates the following.  Notice the wrong `apiVersion` value.

```yaml
$ helm template -n monitoring grafana ./helm-charts/charts/grafana/ -f grafana.yaml -s templates/ingress.yaml
---
# Source: grafana/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-6.8.2
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "7.5.3"
    app.kubernetes.io/managed-by: Helm
spec:
  ingressClassName: nginx
  rules:
    - host: grafana.example.com
      http:
        paths:

          - path: /
            backend:
              serviceName: grafana
              servicePort: 80
```

When I revert #273, the resulting Ingress is correct:

```yaml
$ helm template -n monitoring grafana ./helm-charts/charts/grafana/ -f grafana.yaml -s templates/ingress.yaml
---
# Source: grafana/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-6.8.2
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "7.5.3"
    app.kubernetes.io/managed-by: Helm
spec:
  ingressClassName: nginx
  rules:
    - host: grafana.example.com
      http:
        paths:

          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 80
```

**Comment by zanhsieh** [comment]
@kruftik 
Could you take a look at this ^^^ ?

**Comment by kruftik** [comment]
Sure.

I do see the problem the change in the current PR caused. Also it's pretty clear that my fix is able to fix the issue in earlier kube-versions but don't fit well for new ones. Unfortunately, I haven't got any thoughts on how to fix the issue both in backward and forward compatibve ways.

**Comment by jtackaberry** [comment]
> Also it's pretty clear that my fix is able to fix the issue in earlier kube-versions but don't fit well for new ones.

Actually why is that?  I mean based on the Helm documentation I would have thought `.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress"` should work even for k8s 1.19+?

**Comment by kruftik** [comment]
@jtackaberry, yeah, you right

I've taken a look at what is actually rendered by helm v3.5.3 and what it's applied by kube-apiserver v1.19.10 and there's a very strange difference. Namely,

`helm upgrade --install grafana . --namespace=default --debug | less` shows that helm correctly rendered stable v1 resource:
```yaml
# Source: grafana/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: default
  labels:
    helm.sh/chart: grafana-6.8.2
```

whereas `kubectl get ingress grafana -oyaml` reveals that the wrong v1beta1 version has been persisted by kube-apiserver:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: grafana
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-05-01T05:53:12Z"
  generation: 1
```

I don't understand what's going on for now.

**Comment by jtackaberry** [comment]
> whereas `kubectl get ingress grafana -oyaml` reveals that the wrong v1beta1 version has been persisted by kube-apiserver:

I imagine this is the reason:

https://github.com/kubernetes/kubernetes/issues/94761#issuecomment-691982480

So I think it's less important what `kubectl get ingress` returns, as long as Helm is generating the appropriately versioned resource for the cluster.

I wonder if `kubectl api-resources` is instructive here:

```bash
# Microk8s 1.19.9
$ kubectl api-resources | grep Ingress
ingresses                         ing          extensions                     true         Ingress
ingressclasses                                 networking.k8s.io              false        IngressClass
ingresses                         ing          networking.k8s.io              true         Ingress

# EKS 1.18.9
$ kubectl api-resources | grep Ingress
ingresses                         ing          extensions/v1beta1                true         Ingress
ingressclasses                                 networking.k8s.io/v1beta1         false        IngressClass
ingresses                         ing          networking.k8s.io/v1beta1         true         Ingress
```

Notice that apiserver for k8s 1.19 is not reporting versioned API groups, but it does with 1.18.  `kubectl api-versions` meanwhile does report versioned API groups for both k8s versions.

Perhaps this discrepancy is breaking the behavior of Helm's ` .Capabilities.APIVersions.Has`?

**Comment by shinebayar-g** [comment]
I'm getting `apiVersion: extensions/v1beta1` Ingress on my helm template with following values.

```yml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  pathType: Prefix
  hosts:
    - grafana.example.com
```

Helm chart generates 

```yml
# Source: grafana/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: grafana
  labels:
    helm.sh/chart: grafana-6.11.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "7.5.5"
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: grafana.example.com
      http:
        paths:

          - path: /
            backend:
              serviceName: grafana
              servicePort: 80
```

How can I get `networking.k8s.io/v1` Ingress?

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"c6a2f08fc4378c5381dd948d9ad9d1080e3e6b33", GitTreeState:"clean", BuildDate:"2021-05-12T12:27:07Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by agorodetskaya** [comment]
@shinebayar-g actually your change broke it for lower api-versions.
Now it generates Ingress with `apiVersion: networking.k8s.io/v1` for version **v1.16.15** (and also generates unsupported `backend.service.name` and `backend.service.port` instead of `backend.serviceName` and `backend.servicePort`)
So after applying it to k8s I receive error: `no matches for kind "Ingress" in version "networking.k8s.io/v1"`.

---

Kubernetes version: v1.16.15
Values:
```
ingress:
  enabled: true
  annotations: {}
  labels: {}
  path: /
  pathType: Prefix
  hosts:
    - chart-example.local
  extraPaths: []
  tls: []
```
Output Ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: grafana
  labels:
    helm.sh/chart: grafana-6.14.1
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: 8.0.5
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
  - host: chart-example.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 80
```
