### ISSUE TITLE
Setting serviceAccount.autoMount  to false fails the deployment without option to fix it differently

### ISSUE THREAD

**Issue by OmarHawk** [grafana/helm-charts#2713]
Hi,

for security reasons, we are currently changing all our Pods to get rid of automounted serviceAccount API credentials. The helm chart "theoretically" supports this by providing

```serviceAccount.autoMount: false```

Since the containers do require the token, we try to manually mount the token by providing following configuration:

```
extraSecretMounts:
    - name: serviceaccount-token
      mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      readOnly: true
      projected:
        defaultMode: 0444
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            name: kube-root-ca.crt
            items:
            - key: ca.crt
              path: ca.crt
        - downwardAPI:
            items:
            - path: namespace
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
```

This alone will make the grafana container itself work. Additionally, we provide the following:

```
  sidecar:
    dashboards:
      extraMounts:
        - name: serviceaccount-token
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
```

This makes the dashboards container work. 

The last failing container then is the datasources one. Unfortunately, this does not allow to provide `extraMounts`, so there is no way to make that one run, while having `serviceAccount.autoMount: false`.
