### ISSUE TITLE
ServiceMonitor doesn't work in helm chart

### ISSUE THREAD

**Issue by mladenrtl** [grafana/helm-charts#2733]
Hi,

I started to use the `k6-operator` helm chart in our ArgoCD by adding it as a dependency:
```
dependencies:
  - name: k6-operator
    version: 1.2.0
    repository: https://grafana.github.io/helm-charts
    alias: k6-operator
```

This works fine, except serviceMonitor. There are 2 issues:

1. In `serviceMonitor.yaml`, namespace is defined twice:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: "controller-manager"
    namespace: {{- include "k6-operator.namespace" . }}
    app.kubernetes.io/component: monitoring
    {{- include "k6-operator.labels" . | nindent 4 }}
    {{- include "k6-operator.customLabels" . | default "" | nindent 4 }}
  annotations:
    {{- include "k6-operator.customAnnotations" . | default "" | nindent 4 }}
  name: controller-manager-metrics-monitor
  namespace: system
```
and when we try to sync it gives the error that the `system` namespace doesn't exist.

2. If we change `namespace: system` to `namespace: {{- include "k6-operator.namespace" . }}` it syncs successfully but this serviceMonitor is not discoverable in the Prometheus Targets:
![image](https://github.com/grafana/helm-charts/assets/59438904/648a5bb1-82b6-40c8-90f7-c8f9bbc2853c)

I tried to make some changes but those don't work either.

Does anyone experience the same issue?
