### ISSUE TITLE
【Loki-distributed 0.69.9】Querier OOM and other query request also will be failed

### ISSUE THREAD

**Issue by YuWan1117** [grafana/helm-charts#2749]
### The Question Scene

If the label used by a query request is insufficient to segment the logs (almost  a full log query), the querier memory will increase, and then OOM. At the time, querier is in a state of continuous restart, which may be due to the continuous incoming of requests, and some normal query requests by other users cannot be responded to at this time.

For example for one unnormal log query：
```
# this will read all prod cluster log in one time range
# assume the time range is  2 minutes
{cluster="prod"} |= "$traceid"
```

Specific issue:
- Querier allocates Lots of memory during query execution.
- This can and does lead to OOM in resource-limited container environments.
- The issue prevents use of the product as it's just too unstable.

### Some suggestions or doubts

- Introduce memory limits: Individual max mem for individual queries.
- Actively manage mem accounting during query execution.
- Fail the query when we know the memory limits will be breached

And Is there some other configuration that fixes this issue but I didn't find it?

### My try
1. change the `` to  `false`, but the issue also produce.
2. I found the `querier_forget_delay` config in `query_schedule` component, but we don't use the componet, we just use `query_frontend`.

### My Loki Config

```yaml
    auth_enabled: false
    frontend:
      compress_responses: true
      log_queries_longer_than: 10s
      scheduler_worker_concurrency: 30
      tail_proxy_url: http://loki-querier:3100
    frontend_worker:
      frontend_address: loki-query-frontend-headless:9095
      grpc_client_config:
        max_send_msg_size: 104857600
    limits_config:
      enforce_metric_name: false
      ingestion_burst_size_mb: 256
      ingestion_rate_mb: 128
      ingestion_rate_strategy: local
      max_cache_freshness_per_query: 10m
      max_entries_limit_per_query: 50000
      max_global_streams_per_user: 0
      max_query_series: 300000
      max_streams_per_user: 0
      per_stream_rate_limit: 64MB
      per_stream_rate_limit_burst: 256MB
      query_timeout: 5m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 5m
    query_range:
      parallelise_shardable_queries: false
      align_queries_with_step: true
      cache_results: true
      max_retries: 5
      results_cache:
        cache:
          redis:
            endpoint: XXXXXX:6379
            expiration: 30m
    server:
      grpc_server_max_concurrent_streams: 0
      grpc_server_max_recv_msg_size: 33554432
      grpc_server_max_send_msg_size: 33554432
      http_listen_address: 0.0.0.0
      http_listen_port: 3100
      http_server_read_timeout: 300s
      http_server_write_timeout: 300s
      log_level: info
```

Looking forward your help.
Best regards.
