### ISSUE TITLE
Stale dashboard files persist in provider's directory after rename/deletion

### ISSUE THREAD

**Issue by emmanouil-androulidakis** [grafana/helm-charts#2752]
### Problem

In a Grafana deployment with persistence enabled, dashboard files that used to be part of `dashboards` config option, continue to appear with zero size in the provider's directory, even after they are renamed/deleted from `dashboards`.

### Reproduce

This issue was encountered in version `grafana-6.57.3`, but probably affects more versions. This issue affects deployments that use the `persistence` and the `dashboards` options.

1. Assume the following configuration in `values.yaml`:
```
persistence:
  enabled: true
  storageClassName: standard
  type: statefulset
dashboards:
  default:
    mydashboard:
      file: dashboards/mydashboard.json
dashboardProviders:
 dashboardproviders.yaml:
   apiVersion: 1
   providers:
   - name: 'default'
     orgId: 1
     folder: ''
     type: file
     disableDeletion: false
     editable: true
     options:
       path: /var/lib/grafana/dashboards/default  
 ...      
```
2. Run `ls -la` in the provider's directory `/var/lib/grafana/dashboards/default` inside the Grafana Pod and you will see only the  `mydashboard.json` with the correct dashboard contents:
```
drwxrwsrwx    2 root     472           4096 Oct 31 11:06 .
drwxr-xr-x    3 grafana  472           4096 Oct 10 13:32 ..
-rw-r--r--    1 root     472          10249 Oct 31 11:06 mydashboard.json
``` 
3. **Rename** the `mydashboard` dashboard to `mydashboard-2`, by changing only the following section in `values.yaml`:
```
 dashboards:
   default:
-    mydashboard:
+    mydashboard2:
       file: dashboards/mydashboard.json
```
4. Perform a Helm upgrade. 
5. Run `ls -la` in the provider's directory `/var/lib/grafana/dashboards/default` and you will see **2** files, both `mydashboard.json` and `mydashboard2.json`, instead of only the `mydashboard2.json` that was expected.
```  
drwxrwsrwx    2 root     472           4096 Oct 31 11:10 .
drwxr-xr-x    3 grafana  472           4096 Oct 10 13:32 ..
-rwxr-xr-x    1 grafana  472              0 Oct 31 11:06 mydashboard.json
-rw-r--r--    1 root     472          10249 Oct 31 11:10 mydashboard2.json
``` 
The stale file has zero size, and naturally Grafana complains that it cannot load dashboard from empty .file `mydashboard.json`. In Grafana's logs one can see:
```
logger=provisioning.dashboard type=file name=default t=2023-10-25T09:51:33.387972507Z level=error msg="failed to load dashboard from " file=/var/lib/grafana/dashboards/default/mydashboard.json error=EOF
```

### Cause

The root cause is that each time we mount a dashboard (`ConfigMap` key to a file), Kuberentes creates the target file, which is always persisted, because it is created under the PVC's mountpoint. 

In detail, whenever we add a file/json dashboard in `values.yaml`, Helm adds the contents of the dashboard in the `grafana-dashboards-<provider>` `ConfigMap`, declares a volume of that `ConfigMap` in the Grafana Pod, and mounts each key of that volume as a `subPath` in the provider's directory of the Grafana Pod. For example:
```
        volumeMounts:
          - mountPath: /var/lib/grafana/dashboards/default/mydashboard.json
            name: dashboards-default
            subPath: mydashboard.json
            ...
...
      volumes:
        - configMap:
            defaultMode: 420
            name: grafana-dashboards-default
          name: dashboards-default         
``` 
Mounting as a `subPath` means that Kubernetes (`kubelet`) first creates the target file in the file-system and then bind-mounts the file with the file of the volume. When we delete/rename the dashboard, then it is removed from the `ConfigMap` and from the `volumeMounts`, but the file that `kubelet` has created persists in the file-system, because the provider's directory `/var/lib/grafana/dashboards/default` is under `/var/lib/grafana`, which is the mountpoint for the PVC. 

### Solution

One solution would be to mount the whole `ConfigMap` under the provider's directory `/var/lib/grafana/dashboards/default`. However, this is not possible, because it would make the directory read-only, and the `download-dashboards` init container needs to write to that directory any downloadable dashboards.

Therefore, a more promising solution would be to mount an `emptyDir` to the provider's directory. Thus, the directory remains writable for the downloadable dashboards, but is not persistent through Pod restarts, since each time the Pod restarts it is repopulated only with the dashboards configured in the `dashboards` config option of `values.yaml`. Hence, no stale files will ever fall behind. Of course this assumes that we do not need persistency in the provider's directory.  

I would be happy to contribute a patch that fixes this problem, if you agree with the aforementioned solution.
