### ISSUE TITLE
[Grafana] Setup templates using sidecar

### ISSUE THREAD

**Issue by nlamirault** [grafana/helm-charts#2765]
We could provisioning Grafana template using the configuration file: https://grafana.com/docs/grafana/latest/alerting/set-up/provision-alerting-resources/file-provisioning/#provision-templates

It could be useful to use the sidecar pattern to configure Grafana templates

```yaml
sidecar:
  logLevel: INFO
  templates:
    enabled: true
    label: grafana_template
    searchNamespace: ALL
```
