### ISSUE TITLE
[Grafana] Provisioning "provider" using the sidecar pattern

### ISSUE THREAD

**Issue by nlamirault** [grafana/helm-charts#2767]
We could provision Grafana dashboards providers using the configuration file: https://grafana.com/docs/grafana/latest/administration/provisioning/#provision-folders-structure-from-filesystem-to-grafana

It could be useful to use the sidecar pattern to configure Grafana templates

```yaml
sidecar:
  logLevel: INFO
  providers:
    enabled: true
    label: grafana_provider
    searchNamespace: ALL
```
