### ISSUE TITLE
Loki gateway nginx Address family not supported by protokoll

### ISSUE THREAD

**Issue by Jan-Zimmermann** [grafana/helm-charts#2779]
Hi,

i try to install Loki on our on-premise k8s cluster.

All pods are running only Loki-gateway does not start up.
The logs show the following:

/docker-entrypoint.sh: No files found in /docker-entrypoint.d/, skipping configuration
2023/11/10 15:30:16 [emerg] 1#1: socket() [::]:8080 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:8080 failed (97: Address family not supported by protocol)

my config file is pretty simply i think:

`loki:
  storage:
    type: 's3'
    s3:
      endpoint: http://minio.minio.svc.cluster.local:9000
      secretAccessKey: ******
      accessKeyId: log
      s3ForcePathStyle: true
      insecure: true
  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/index_cache
      resync_interval: 5s
      shared_store: s3`

I think the Gateway try to listen on ipv6. This is not supported in our cluster.

Can i disable Ipv6 by config? any help is welcome :)

**Comment by jlec** [comment]
Can we get the ipv6 support optional?

**Comment by rajivreddy** [comment]
@jlec  Did you tried this option by setting it to `false`
```
  nginxConfig:
    # -- Which schema to be used when building URLs. Can be 'http' or 'https'.
    schema: http
    # -- Enable listener for IPv6, disable on IPv4-only systems
    enableIPv6: true
```
