### ISSUE TITLE
Tempo Helm chart installation returns template error

### ISSUE THREAD

**Issue by amrllkmn** [grafana/helm-charts#2797]
Hi there, I tried to install the charts by running:
`helm upgrade tempo grafana/tempo --install --namespace my-namespace --values ./values.yaml`

My `values.yaml` are all default values, taken from this [repo](https://github.com/grafana/helm-charts/tree/4624d11bf9035f7a6da0c891865e64f133ec0f80/charts/tempo).

It returned:
```
Error: template: tempo/templates/statefulset.yaml:7:8: executing "tempo/templates/statefulset.yaml" at <include "tempo.labels" .>: error calling include: template: tempo/templates/_helpers.tpl:52:73: executing "tempo.labels" at <.Values.tempo.tag>: wrong type for value; expected string; got interface {}
```

I checked the `tempo.tag` section, it's currently set as below:

```yaml
# values.yaml
tempo:
    tag: null
```
Then when I checked the templates, it's used [here](https://github.com/grafana/helm-charts/blob/4624d11bf9035f7a6da0c891865e64f133ec0f80/charts/tempo/templates/statefulset.yaml#L57) like below:

```yaml
spec:
      containers:
      - args:
        - -config.file=/conf/tempo.yaml
        - -mem-ballast-size-mbs={{ .Values.tempo.memBallastSizeMbs }}
        {{- range $key, $value := .Values.tempo.extraArgs }}
        - "-{{ $key }}{{ if $value }}={{ $value }}{{ end }}"
        {{- end }}
        image: {{ .Values.tempo.repository }}:{{ .Values.tempo.tag | default .Chart.AppVersion }}
        
 ```
 
 Is there something I'm doing wrong with installing the chart?
 
 Thank you in advance for any guidance with this.
