### ISSUE TITLE
gateway.service.additionalPorts default value should be array?

### ISSUE THREAD

**Issue by fkaksa** [grafana/helm-charts#2801]
**Description:**
Currently, the default value for `gateway.service.additionalPorts` is set to `map[]` in the `values.yaml` file. However, it seems there is an issue when attempting to overwrite this table with a non-table, leading to warnings in the `coalesce.go` file.

```bash
coalesce.go:286: warning: cannot overwrite table with non table for syrius-tracing-infra.tempo.gateway.service.additionalPorts (map[])
coalesce.go:286: warning: cannot overwrite table with non table for syrius-tracing-infra.tempo.gateway.service.additionalPorts (map[])
coalesce.go:286: warning: cannot overwrite table with non table for syrius-tracing-infra.tempo.gateway.service.additionalPorts (map[])
```

**Steps to Reproduce:**
1. Pull the Helm chart using the following configuration:
    ```yaml
    - name: tempo-distributed
      version: 1.6.3
      repository: https://grafana.github.io/helm-charts
    ```
2. Change the `values.yaml` file with the following property:
    ```yaml
    gateway:
      enabled: true
      service:
        additionalPorts:
          - name: https
            port: 443
            targetPort: 8443
            protocol: TCP
    ```

**Expected Behavior:**
The default value for `gateway.service.additionalPorts` should be set to an array, allowing users to customize additional ports without encountering warnings in the `coalesce.go` file.

**Additional Information:**
- Helm Chart Version: 1.6.3
- Repository: https://grafana.github.io/helm-charts
- helm version: version.BuildInfo{Version:"v3.13.2", GitCommit:"2a2fb3b98829f1e0be6fb18af2f6599e0f4e8243", GitTreeState:"clean", GoVersion:"go1.21.4"}

**Note:**
Please review and update the default value for `gateway.service.additionalPorts` to resolve the mentioned warnings.
