### ISSUE TITLE
[loki-distributed] deploying on istio throws Istio Warnings

### ISSUE THREAD

**Issue by cdm-anv** [grafana/helm-charts#2818]
Hi loki-distributed community, 

When deploying latest loki-distributed chart with istio service mesh enabled, then we get this warning message from istio: 

Warning [IST0137] (Deployment logging/logging-loki-distributed-query-frontend) This deployment logging-loki-distributed-query-frontend is associated with multiple services [logging/logging-loki-distributed-query-frontend logging/logging-loki-distributed-query-frontend] using targetPort "grpc" but different ports: [9095 9096].

This setting is defined in the template files of the helm chart. But this is not like Grafana is recommending it.
See Grafana Docs: https://grafana.com/docs/loki/latest/setup/install/istio/

The redundant port definition in the service was added with this PR:
https://github.com/grafana/helm-charts/pull/803

query-frontend service as it's created by loki-distributed: 

```
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3100
      targetPort: http
    - name: grpc
      protocol: TCP
      appProtocol: tcp
      port: 9095
      targetPort: grpc
    - name: grpclb
      protocol: TCP
      appProtocol: tcp
      port: 9096
      targetPort: grpc
```

query-frontend service as it's recommended by Grafana: 

```
spec:
  ports:
  - appProtocol: http
    name: http
    port: 3100
    protocol: TCP
    targetPort: http
  - appProtocol: tcp
    name: grpclb
    port: 9095
    protocol: TCP
    targetPort: grpc

```

Can the service templates updated the way like Grafana recommends?
