### ISSUE TITLE
Please add the option to set the dnsConfig and dnsPolicy in the grafana chart

### ISSUE THREAD

**Issue by weikinhuang** [grafana/helm-charts#2826]
I'm encountering the issue with alpine and dns resolution within my kubernetes cluster. I have to manually set all alpine pods with the following:

```yaml
spec:
  dnsConfig:
    options:
      - name: ndots
        value: '1'
```

I'm currently setting this with a custom mutating webhook. But it would be great if I can set it within the chart itself.

Thanks
