### ISSUE TITLE
[tempo-distributed] Pull Secrets normalization

### ISSUE THREAD

**Issue by EvertonSA** [grafana/helm-charts#2832]
**Problem:**

I have tempo + loki + many other charts deployed under the same helm umbrella.

Tempo distributed made my globals like this:

```
global:
    image:
        pullSecrets:
            - container-registry-readonly
```

https://github.com/grafana/helm-charts/blob/565bfd7ca4ffd90f9d7bd30f5f5d89d1b99f4bea/charts/tempo-distributed/values.yaml#L10

that is ok, but when I tried to add grafana-agent to the same umbrela, helm template complains with the following:

`Error: UPGRADE FAILED: failed to create resource: DaemonSet in version "v1" cannot be handled as a DaemonSet: json: cannot unmarshal string into Go struct field PodSpec.spec.template.spec.imagePullSecrets of type v1.LocalObjectReference`

If I have globals like this:
```
global:
    image:
        pullSecrets:
            - name: container-registry-readonly
```
then grafana agent works fine, but all tempo workloads looks like this:

![image](https://github.com/grafana/helm-charts/assets/30481051/484f5b43-1bbc-4496-b548-8661a04f85c8)

If I understood correctly, there are two issues:
- tempo should use globals like other big charts
```
# globals
global:
    imagePullSecrets:
        - name: container-registry-readonly
```

- grafana agent should not enforce "global" if "local" is set, but it it's not respecting that: https://github.com/grafana/agent/blob/main/operations/helm/charts/grafana-agent/templates/controllers/_pod.yaml#L19. I will open issue on that repo to see what other people thing

**Workaround**
At the moment, I think my only option is: don't install grafana-agent with tempo-distributed under the same helm umbrela.
