### ISSUE TITLE
Allow for multiple dashboardsConfigMaps per provider

### ISSUE THREAD

**Issue by christian-wille** [grafana/helm-charts#2837]
I'm using external ConfigMaps to mount dashboards via the dashboardsConfigMaps value. This is working great, but now that I've added more and more dashboards, I'm running into the max size limitation of a configmap object in Kubernetes.

Is it possible to change the chart to allow multiple configmaps per provider, so I can spread my dashboards over multiple configmaps?

**Comment by robrides** [comment]
I am currently attempting to use multiple configmaps to load dashboards also. I've used the `extraConfigmapMounts` parameter and the dashboards' json files are populating in the container fine at `/var/lib/grafana/dashboards/my-custom-provider`. I add a provider to the parameter `dashboardProviders` and the ui shows the provider folder as desired but the folder is empty. What config will tell grafana to load all the dashboards under all subdirectories at `/var/lib/grafana/dashboards/`?

**Comment by robrides** [comment]
I also just tried using the `dashboardsConfigMaps` parameter which is an object and doesn't allow multiple configmaps for one provider. I instead just named each child object the same as the dashboard json filename. This resulted in a subdirectory being created for each json filename as expected but the dashboards still are not populating in the ui. The json for these dashboards were taken directly from the grafana.db of a previous deployment. There are no errors regarding dashboards in the logs. The logs indicate dashboards were deployed. 

Helm chart version is 8.6.4

```
logger=provisioning.dashboard t=2024-12-16T21:25:16.87323055Z level=info msg="starting to provision dashboards"
logger=provisioning.dashboard t=2024-12-16T21:25:16.873411813Z level=info msg="finished to provision dashboards"
```

**Comment by robrides** [comment]
I was able to accomplish loading multiple config files with the above approach and just adding  a provider for each configmap in `dashboardproviders` parameter. Example below

```
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'dash1'
      orgId: 1
      folder: 'dash1'
      type: file
      disableDeletion: true
      editable: true
      options:
        path: /var/lib/grafana/dashboards/dash1
```
