### ISSUE TITLE
[loki-distributed] loki-querier architecture does not allow KEDA `ScaledObject`

### ISSUE THREAD

**Issue by siryur** [grafana/helm-charts#2860]
Chart version: [loki-distributed v0.77.0](https://github.com/grafana/helm-charts/blob/loki-distributed-0.77.0/charts/loki-distributed)

As the official grafana documentation suggests:

> We recommend using [Kubernetes Event-Driven Autoscaling (KEDA)](https://keda.sh/) to configure autoscaling based on Prometheus metrics. Refer to [Deploying KEDA](https://keda.sh/docs/latest/deploy) to learn more about setting up KEDA in your Kubernetes cluster.

The problem here is that whenever I want to implement a `ScaledObject` on my side,
I don't have a way to not set replicas nor deploy the default Kubernetes HPA.

See:

https://github.com/grafana/helm-charts/blob/9580ada1ce7b682f27bcb936c6e3b3f2e42753df/charts/loki-distributed/templates/querier/deployment-querier.yaml#L15-L17

and 

https://github.com/grafana/helm-charts/blob/9580ada1ce7b682f27bcb936c6e3b3f2e42753df/charts/loki-distributed/templates/querier/hpa.yaml#L1

---

So, in a case where I use this chart as a dependency of my (self-made) chart with:
```yaml
dependencies:
- name: loki-distributed
  repository: https://grafana.github.io/helm-charts
  version: 0.77.0
```

And then I build a [KEDA `ScaledObject`](https://keda.sh/docs/2.12/concepts/scaling-deployments/), I'm stuck because the chart will always deploy
a Deployment with `spec.replicas` or the `kind: HorizontalPodAutoscaler` object:

```yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "loki.querierFullname" $lokiContext }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loki.querierLabels" $lokiContext | nindent 4 }}
spec:
# (...)
```

---

I suggest one of the following:
- We introduce the KEDA `ScaledObject` implementation on the chart
- We introduce an option to not set neither of those objects
