### ISSUE TITLE
Configure Notification Templates using Helm Chart Configs

### ISSUE THREAD

**Issue by shivtej-opsverse** [grafana/helm-charts#2861]
Hey is there a way to configure a [notification template](https://grafana.com/docs/grafana/latest/alerting/manage-notifications/template-notifications/create-notification-templates/)  using the helm chart?
Grafana Version I am using is `9.4.3`.

Also can I change the default subject of the email notification using helm chart configs?

Any insights would be helpful.

**Comment by x61s** [comment]
You can create `values.alerting.templates.yaml` file and use it with helm install/upgrade command.

Here is the example:
`alerting:
  templates.yaml:
    apiVersion: 1
    templates:
    - orgID: 1
      name: slack.custom.title
      template: <HERE STARTS SADISTIC PART>`

**Comment by shivtej-opsverse** [comment]
@x61s tried with the following values just to see whether it reflects in the ui:
```
    alerting:
      templates.yaml:
        apiVersion: 1
        templates: 
          - orgID:
            name: slack.custom.title
            templates: "{{ \"[{{ .Status | toUpper }}\" }}"
  ```
  
  Rendered the following template :
  ```
    templates.yaml: |
    apiVersion: 1
    templates:
    - name: slack.custom.title
      orgID: null
      templates: '[{{ .Status | toUpper }}'
  ```          
  
  Grafana doesn't start
  Logs Say:
  
  ```
  Error: ✗ text templates: invalid object specification: template must have content
  ```

**Comment by navinpai** [comment]
@shivtej-opsverse You have a typo in your yaml: `templates`instead of `template` on the last line.

```
alerting:
  templates.yaml:
    apiVersion: 1
    templates:
    - orgID:
       name: slack_custom_title
       template: "{{ \"[{{ .Status | toUpper }}\" }}"
```

This typo is why you get the `template must have content` error. When you fix this, you should see this in Grafana.

<img width="1138" alt="Screenshot 2024-01-05 at 11 28 00 PM" src="https://github.com/grafana/helm-charts/assets/408863/ef3cfebb-210e-461d-8276-c6ec308d847c">
