### ISSUE TITLE
[Loki-distributed] Question: Sidecar for loading rules? 

### ISSUE THREAD

**Issue by cydergoth** [grafana/helm-charts#2864]
Hi 

It seems as if the Loki single binary chart supports a sidecar for loading Loki Ruler rules from configmaps/secrets, but I can't find the equivalent configuration in the loki-distributed chart.

I think it should be in here? https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/templates/ruler/deployment-ruler.yaml

Also see https://github.com/grafana/loki/blob/26432c0bf86446cb7450bf724c44115daf6930e5/production/helm/loki/values.yaml#L1559

Is provisioning of rules supported in the loki-distributed chart?

**Comment by saeidee** [comment]
You may deploy the config loader sidecar in your Loki ruler, it will load all your alerts(ConfigMaps defined) in your ruler:

```yaml
rulerConfig:
  storage:
    type: local
    local:
      directory: /var/loki/rules
  alertmanager_url: http://alertmanager-operated.observability.svc.cluster.local:9093
  enable_alertmanager_v2: true
  external_labels:
    origin: loki
  rule_path: /var/loki/rules


ruler:
  enabled: true
  replicas: 1
  extraContainers:
    - name: loki-sidecar-rules
      image: kiwigrid/k8s-sidecar:1.28.0
      imagePullPolicy: IfNotPresent
      env:
        - name: METHOD
          value: file
        - name: LABEL
          value: "origin"
        - name: LABEL_VALUE
          value: "loki"
        - name: FOLDER
          value: /var/loki/rules/fake
        - name: RESOURCE
          value: both
        - name: NAMESPACE
          value: "ALL"
      volumeMounts:
        - name: sc-rules-volume
          mountPath: /var/loki/rules
  extraVolumeMounts:
    - name: sc-rules-volume
      mountPath: /var/loki/rules
  extraVolumes:
    - name: sc-rules-volume
      emptyDir: {}
```
