### ISSUE TITLE
[grafana-pod tpl] Allow CSI volume for the main storage volume

### ISSUE THREAD

**Issue by asafhm** [grafana/helm-charts#2876]
Currently, if `persistence` is disabled, the default volume type is `emptyDir`. It will be great if we can have the main `storage` volume to be of csi-type.

A good use case of this for those using GKE is to have a gcs bucket as the backend for this volume, using `gcsfuse` csi driver.

**Comment by mehdicopter** [comment]
Hey, did you find a workaround or how to use a bucket as persistence storage?

**Comment by asafhm** [comment]
@mehdicopter Sadly no. Still using PVCs at the moment.

**Comment by mehdicopter** [comment]
I found something working.

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana-0
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: grafana
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: <YOUR_BUCKET_HERE>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grafana
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: grafana
  volumeName: pv-grafana-0
  ```

And what I have in `values.yaml`

```yaml
persistence:
    enabled: true
    existingClaim: pvc-grafana
  annotations:
    gke-gcsfuse/volumes: "true"
  podAnnotations:
    gke-gcsfuse/volumes: "true"
  initChownData:
    enabled: false
```
