### ISSUE TITLE
Helm templating inconsistency with --namespace flag

### ISSUE THREAD

**Issue by edwardzjl** [grafana/helm-charts#2880]
### What's wrong?

When I try to deploy some Grafana services using helm with the `--namespace` flag, the output seems incorrect.

The issue first arises when I was deploying [Grafana Loki](https://grafana.com/docs/loki/latest/setup/install/helm/install-scalable/) using Helm with the following commands:

```sh
helm repo add grafana https://grafana.github.io/helm-charts

helm repo update

helm template --values values.yaml loki grafana/loki --namespace logging --skip-tests > loki.yaml

kubectl apply -f loki.yaml
```

Despite the explicit specification of the `--namespace logging` flag, the deployment `loki-grafana-agent-operator` appears in the default namespace, and failing with the following log:

```console
level=error ts=2024-01-03T08:52:02.749127555Z controller=node controllerGroup= controllerKind=Node msg="Could not wait for Cache to sync" err="failed to wait for node caches to sync: timed out waiting for cache to be synced"
```

I inspected the generated `loki.yaml` file, all other resources were correctly namespaced under `logging` except the deployment named `loki-grafana-agent-operator`:

```yaml
# Source: loki/charts/grafana-agent-operator/templates/operator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-grafana-agent-operator
  labels:
    app.kubernetes.io/name: grafana-agent-operator
    app.kubernetes.io/instance: loki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: operator
    helm.sh/chart: grafana-agent-operator-0.2.16
    app.kubernetes.io/version: "0.34.1"
spec:
  ...
```

And again when i was deploying [Grafana Agent Flow](https://grafana.com/docs/agent/latest/flow/setup/install/kubernetes/), the generated ServiceAccount resource did not have any `namespace` specified:

```yaml
# Source: grafana-agent/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-agent-flow
  labels:
    helm.sh/chart: grafana-agent-0.29.0
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: grafana-agent-flow
    
    app.kubernetes.io/version: v0.38.1
    app.kubernetes.io/managed-by: Helm
```

While the generated ClusterRoleBinding resource bounds ClusterRole to a namespaced ServiceAccount:

```yaml
# Source: grafana-agent/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-agent-flow
  labels:
    helm.sh/chart: grafana-agent-0.29.0
    app.kubernetes.io/name: grafana-agent
    app.kubernetes.io/instance: grafana-agent-flow
    
    app.kubernetes.io/version: v0.38.1
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-agent-flow
subjects:
  - kind: ServiceAccount
    name: grafana-agent-flow
    namespace: logging
```

I don't know whether it's a issue with helm or not, should I consider unsetting the namespace flag during the `helm template` operation and subsequently specify the namespace when executing `kubectl apply`?

### Steps to reproduce

```sh
helm repo add grafana https://grafana.github.io/helm-charts

helm repo update

helm template grafana-agent-flow grafana/grafana-agent --namespace logging --skip-tests > grafana-agent-flow.yaml
```

### Software version

Helm: `{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}`
