### ISSUE TITLE
Allow setting of envFromSecret for datasources sidecar

### ISSUE THREAD

**Issue by jamesgoodhouse** [grafana/helm-charts#29]
Per [Grafana's docs](https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables), environment variables can be used in the config YAML for datasources. This means that something like a database password could be kept as its own secret in Kubernetes, allowing the datasource to exist as a ConfigMap and thus checked into source code.

Here's an example:

**values.yaml for Grafana Helm chart**
```
sidecar:
  dashboards:
    enabled: true
    envFromSecret: grafana-dashboard-secrets
```

**Secrets**
```
apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasource-influxdb
  labels:
     grafana_datasource: "1"
type: Opaque
stringData:
  INFLUXDB_USERNAME: an-awesome-user
  INFLUXDB_PASSWORD: super-secure
  INFLUXDB_DATABASE: so-database-much-wow
```

**Datasource ConfigMap**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-influxdb
  labels:
     grafana_datasource: "1"
data:
  datasource.yaml: |-
    # config file version
    apiVersion: 1

    # list of datasources that should be deleted from the database
    deleteDatasources: []
      # - name: Graphite
      #   orgId: 1

    # list of datasources to insert/update depending
    # what's available in the database
    datasources:
      # <string, required> name of the datasource. Required
      - name: InfluxDB
        # <string, required> datasource type. Required
        type: influxdb
        # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
        access: proxy
        # <int> org id. will default to orgId 1 if not specified
        orgId: 1
        # <string> custom UID which can be used to reference this datasource in other parts of the configuration, if not specified will be generated automatically
        uid: influxdb
        # <string> url
        url: http://influxdb:8086
        # <string> database user, if used
        user: $INFLUXDB_USERNAME
        # <string> database name, if used
        database: $INFLUXDB_DATABASE
        # <bool> mark as default datasource. Max one per org
        isDefault: true
        # <string> json object of data that will be encrypted.
        secureJsonData:
          password: $INFLUXDB_PASSWORD
        version: 1
        # <bool> allow users to edit datasources from the UI.
        editable: true
```
