### ISSUE TITLE
BUG: curlimages/curl:7.73.0 refuses to download multiple dashboard (stuck at first one)

### ISSUE THREAD

**Issue by eltorio** [grafana/helm-charts#2919]
with grafana 7.2.* (as a dependency of  prometheus-community/kube-prometheus-stack 55.11.0) the download-dashboards init container stuck downloading the first dashboard  
The log shows:   
```log
2024-01-19T10:56:08.968002839Z + set -euf
2024-01-19T10:56:08.968044439Z + mkdir -p /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
2024-01-19T10:56:08.968741482Z + mkdir -p /var/lib/grafana/dashboards/grafana-dashboards-kubernetes-integration
2024-01-19T10:56:08.969561006Z + curl -skf --connect-timeout 60 --max-time 60 -H 'Accept: application/json' -H 'Content-Type: application/json;charset=UTF-8' https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
```

my dashboards in values.yaml are:  
```
grafana:
  adminPassword: "R**************o"
  sidecar:
    dashboards:
      enabled: false
    datasources:
      enabled: false
  ingress:
    enabled: true
    ingressClassName: haproxy
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-azure
    hosts:
    - grafana.l***********s.org
    tls:
    - secretName: grafana-crt
      hosts:
        - grafana.l***********s.org
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'grafana-dashboards-kubernetes'
        orgId: 1
        folder: 'Kubernetes'
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
      - name: 'grafana-dashboards-kubernetes-integration'
        orgId: 1
        folder: 'Integration'
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes-integration
  dashboards:
    grafana-dashboards-kubernetes:
      k8s-system-api-server:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
        token: ''
      k8s-system-coredns:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
        token: ''
      k8s-views-global:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
        token: ''
      k8s-views-namespaces:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
        token: ''
      k8s-views-nodes:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
        token: ''
      k8s-views-pods:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
        token: ''
      k8s-view-pvc:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/k8s-pvc.json
        token: ''
      prometheus:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-addons-prometheus.json
        token: ''
    grafana-dashboards-kubernetes-integration:
      home:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/home.json
        token: ''
      multi:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/multi-cluster.json
        token: ''
      cluster:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/cluster.json
        token: ''
      namespace-pods:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/namespace-pods.json
        token: ''
      namespace-workloads:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/namespace-workloads.json
        token: ''
      node-pods:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/node-pods.json
        token: ''
      pod:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/pod.json
        token: ''
      workload:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/workload.json
        token: ''
      kubelet:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/kubelet.json
        token: ''
      pvc:
        url: https://raw.githubusercontent.com/eltorio/oci-manage/main/miscellaneous/dashboards/pvc.json
        token: ''

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: LocalCluster
        type: prometheus
        url: http://prometheus-kube-prometheus-prometheus:9090
        access: proxy
        isDefault: true
```
While testing the download configmap generated with curlimages/curl:7.73.0 it doesn't like the `>` on a new line.

My workaround is to use my own images -not designed for but including curl 7.81.0 , so i defined in my grafana definition:  
```yaml
 downloadDashboardsImage:
    registry:   docker.io
    repository: highcanfly/net-tools
    tag: latest
```
