### ISSUE TITLE
[Grafana] Add `folderUid` support for dashboards provider

### ISSUE THREAD

**Issue by Rohlik** [grafana/helm-charts#2955]
We hit a problem in our deployment when we had 2 environments (production and dev) and we configured sidecar for provisioning Grafana dashboards:
```yaml
    sidecar:
      dashboards:
        enabled: true
        folder: /tmp/dashboards
        label: grafana_dashboard
        labelValue: "1"
        provider:
          allowUiUpdates: true
          folder: 'Provisioned'
          name: sidecarProvider
          orgid: 1
          type: file
          updateIntervalSeconds: 60
        resource: configmap
```
Related template code below:
https://github.com/grafana/helm-charts/blob/06500b7ed7ff1c281f083139e55d595f985c17a2/charts/grafana/templates/_config.tpl#L141-L157

The problem is when you want a provision a dashboard with the `Dashboard panel` where you define `Folder` which is represented as a UUID in JSON.  
That **UUID is for each environment different** and thus it doesn't work well in one of our deployments.

The solution is possible - add support to specify static UUID via `folderUid` in the Helm chart in that `provider` section, like `folderUid: 'ba6053fb-2100-4e8d-b601-6163c90e06fb'`.

What do you think? 🤔
