### ISSUE TITLE
Grafana SMTP Configuration

### ISSUE THREAD

**Issue by avramenkovladyslav** [grafana/helm-charts#2996]
I'm trying to configure SMTP at least with any configuration (with secret or hardcoded values), but looks Grafana don't provision smtp configuration at all.
[Using this helm chart](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml) and this configuration for SMTP:

```
grafana.ini:
  smtp:
    enabled: true
    skip_verify: true
    from_address: grafana@domain.com
    host: email-smtp.eu-central-1.amazonaws.com:587
    user: "USERNAME"
    password: "PASSWORD"
```

Looks like that helm values for grafana.ini smtp not existing but it should be like this, right?
I deployed this, checked the `/etc/grafana/grafana.ini` file, but there is not smtp field at all
