### ISSUE TITLE
Tempo TLS certs mount not working 

### ISSUE THREAD

**Issue by samyak335** [grafana/helm-charts#3002]
How do we mount certs and keys for grafana/tempo . i have tried to mount the secrets , but couldn't find the volumes section in values.yaml, have only found volume mount section in values.yaml

Here is the brief description of the issue  [https://github.com/grafana/tempo/issues/3439](url)

**Comment by jeffreyflynt** [comment]
You'd have to do it like this:

```
tempo:
  extraVolumeMounts: 
  - name: tempo-certs
    mountPath: /path
extraVolumes:
  - name: tempo-certs
    secret:
       secretName: tempo-certs
```
