### ISSUE TITLE
Failed to extract org id from both grpc and HTTP

### ISSUE THREAD

**Issue by win5923** [grafana/helm-charts#3022]
Hi, I'd like to ask about an issue I'm facing. I've set `multitenancyEnabled: true` in Tempo, and I've configured the following parameters in Mimir:
```
global:
  extraEnv:
    - name: JAEGER_AGENT_HOST
      value: tempo-distributor.tracing
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
```

However, No matter if I remove the headers or set them to `X-Scope-OrgID: anonymous`, I'm unable to receive traces from Mimir when viewing them from Tempo. I found the following issue in the logs.

tempo-distributor:
```
ts=2024-03-14T04:44:52.633295325Z caller=middleware.go:68 msg="failed to extract org id from both grpc and HTTP" err="no org id" client=unknown
ts=2024-03-14T04:44:52Z level=error msg="Processor failed" component=tempo error="no org id"
```

Here is my helm values.yaml:
mimir:
```
# values.yaml
fullnameOverride: mimir

global:
  extraEnv:
    - name: JAEGER_AGENT_HOST
      value: tempo-distributor.tracing
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
  # https://grafana.com/docs/helm-charts/mimir-distributed/latest/run-production-environment-with-helm/configuration-with-helm/#example-of-configuration-managed-with-helm
  extraEnvFrom:
    - secretRef:
        name: azure-storage-account-essentialsblob-secret
  podAnnotations:
    bucketSecretVersion: "0"

mimir:
  structuredConfig:
    limits:
      compactor_blocks_retention_period: 4380h
      max_label_names_per_series: 100 # fix received a series whose number of labels exceeds the limit
      # check https://github.com/grafana/helm-charts/issues/1320#issuecomment-1121539690
      max_global_series_per_user: 1000000 # fix per-user series limit of 150000 exceeded
    common:
      storage:
        backend: azure
        azure:
          account_key: ${azurestorageaccountkey} # This is a secret injected via an environment variable
          account_name: ${azurestorageaccountname}
          endpoint_suffix: "blob.core.windows.net"
          
    blocks_storage:
      backend: azure
      azure:
        container_name: mimir-blocks

    alertmanager_storage:
      backend: azure
      azure:
        container_name: mimir-alertmanager

    ruler_storage:
      backend: azure 
      azure:
        container_name: mimir-ruler

alertmanager:
  enabled: true
  persistentVolume:
    enabled: false
    # Alertmanager data Persistent Volume size
    #
    size: 1Gi
    # A per-zone storageClass configuration in `alertmanager.zoneAwareReplication.zones[*].storageClass` takes precedence over this field.
    # storageClass: "essentialsblob-fuse-standard"

distributor:
  replicas: 1

ingester:
  replicas: 3
  statefulSet:
    enabled: true
  persistentVolume:
    enabled: false
    # Ingester data Persistent Volume size
    size: 2Gi
    # A per-zone storageClass configuration in `ingester.zoneAwareReplication.zones[*].storageClass` takes precedence over this field.
    #
    # storageClass: "essentialsblob-fuse-standard"

querier:
  replicas: 2

query_frontend:
  replicas: 1

query_scheduler:
  enabled: true
  replicas: 2

store_gateway:
  replicas: 1
  persistentVolume:
    # If true Store-gateway will create/use a Persistent Volume Claim
    # If false, use emptyDir
    #
    enabled: false

compactor:
  replicas: 1
  persistentVolume:
    # If true compactor will create/use a Persistent Volume Claim
    # If false, use emptyDir
    #
    enabled: false

minio:
  enabled: false

nginx:
  enabled: false

gateway:
  enabledNonEnterprise: true
  replicas: 1
  autoscaling:
    enabled: false

overrides_exporter:
  enabled: true
  replicas: 1

ruler:
  enabled: true
  replicas: 1

metaMonitoring:
  dashboards:
    enabled: false
  serviceMonitor:
    enabled: ture
  prometheusRule:
    enabled: true
  grafanaAgent:
    enabled: false
```

Tempo:
```
fullnameOverride: tempo

# -- If true, Tempo will report anonymous usage data about the shape of a deployment to Grafana Labs
reportingEnabled: false

# Configuration for the ingester
ingester:
  # -- Number of replicas for the ingester
  replicas: 3
  autoscaling:
    # -- Enable autoscaling for the ingester. WARNING: Autoscaling ingesters can result in lost data. Only do this if you know what you're doing.
    enabled: false

  persistence:
    # -- Enable creating PVCs which is required when using boltdb-shipper
    enabled: false
    # -- use emptyDir with ramdisk instead of PVC. **Please note that all data in ingester will be lost on pod restart**
    inMemory: false
    # -- Size of persistent or memory disk
    size: 8Gi
    # -- Storage class to be used.
    # If defined, storageClassName: <storageClass>.
    # If set to "-", storageClassName: "", which disables dynamic provisioning.
    # If empty or set to null, no storageClassName spec is
    # set, choosing the default provisioner (gp2 on AWS, standard on GKE, AWS, and OpenStack).
    storageClass: null
    # -- Annotations for ingester's persist volume claim
    annotations: {}
  config:
    # -- Number of copies of spans to store in the ingester ring
    replication_factor: 3
  # -- Affinity for ingester pods. Passed through `tpl` and, thus, to be configured as string
  # @default -- Soft node and soft zone anti-affinity
  affinity: |
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                {{- include "tempo.selectorLabels" (dict "ctx" . "component" "ingester") | nindent 12 }}
            topologyKey: kubernetes.io/hostname
        - weight: 75
          podAffinityTerm:
            labelSelector:
              matchLabels:
                {{- include "tempo.selectorLabels" (dict "ctx" . "component" "ingester") | nindent 12 }}
            topologyKey: topology.kubernetes.io/zone
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: agentpool
                operator: In
                values:
                  - cicd

# Configuration for the distributor
distributor:
  # -- Number of replicas for the distributor
  replicas: 1
  autoscaling:
    # -- Enable autoscaling for the distributor
    enabled: false

# Configuration for the compactor
compactor:
  # -- Number of replicas for the compactor
  replicas: 1
  config:
    compaction:
      # -- Duration to keep blocks
      block_retention: 48h

# Configuration for the querier
querier:
  # -- Number of replicas for the querier
  replicas: 1
  autoscaling:
    # -- Enable autoscaling for the querier
    enabled: false

# Configuration for the query-frontend
queryFrontend:
  replicas: 1
  autoscaling:
    # -- Enable autoscaling for the query-frontend
    enabled: false

# Global overrides
global_overrides:
  metrics_generator_processors:
    - service-graphs
    - span-metrics

# Configuration for the metrics-generator
metricsGenerator:
  # -- Specifies whether a metrics-generator should be deployed
  enabled: true
  # -- More information on configuration: https://grafana.com/docs/tempo/latest/configuration/#metrics-generator
  config:
    storage:
      # -- A list of remote write endpoints.
      # -- https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write
      remote_write:
        - send_exemplars: true
          url: http://kube-prometheus-stack-prometheus.monitor:9090/prometheus/api/v1/write

multitenancyEnabled: true

traces:
  jaeger:
    grpc:
      # -- Enable Tempo to ingest Jaeger GRPC traces
      enabled: true
      # -- Jaeger GRPC receiver config
      receiverConfig: {}
    thriftBinary:
      # -- Enable Tempo to ingest Jaeger Thrift Binary traces
      enabled: true
      # -- Jaeger Thrift Binary receiver config
      receiverConfig: {}
    thriftCompact:
      # -- Enable Tempo to ingest Jaeger Thrift Compact traces
      enabled: true
      # -- Jaeger Thrift Compact receiver config
      receiverConfig: {}
    thriftHttp:
      # -- Enable Tempo to ingest Jaeger Thrift HTTP traces
      enabled: true
      # -- Jaeger Thrift HTTP receiver config
      receiverConfig: {}
  zipkin:
    # -- Enable Tempo to ingest Zipkin traces
    enabled: true
    # -- Zipkin receiver config
    receiverConfig: {}
  otlp:
    http:
      # -- Enable Tempo to ingest Open Telemetry HTTP traces
      enabled: true
      # -- HTTP receiver advanced config
      receiverConfig: {}
    grpc:
      # -- Enable Tempo to ingest Open Telemetry GRPC traces
      enabled: true
      # -- GRPC receiver advanced config
      receiverConfig: {}
  opencensus:
    # -- Enable Tempo to ingest Open Census traces
    enabled: true
    # -- Open Census receiver config
    receiverConfig: {}
  # -- Enable Tempo to ingest traces from Kafka. Reference: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/kafkareceiver
  kafka: {}

# To configure a different storage backend instead of local storage:
storage:
  trace:
    # Settings for the block storage backend and buckets.
    block:
      # -- The supported block versions are specified here https://grafana.com/docs/tempo/latest/configuration/parquet/
      version: null
      # -- Lis with dedicated attribute columns (only for vParquet3 or later)
      dedicated_columns: []
    # -- The supported storage backends are gcs, s3 and azure, as specified in https://grafana.com/docs/tempo/latest/configuration/#storage
    backend: azure
    azure:
      container_name: tempo-storage
      storage_account_name: essentialsblob
      storage_account_key: uvxK5nwW+Jw0gGKQSALbOBN2DgKxbqZBWps+6QAXU0J1v3MLovXKzdLvhGbIGZ++BnPtX6DmR8za+AStps6QrA==
    # The worker pool is used primarily when finding traces by id, but is also used by other.
    pool:
      # -- Total number of workers pulling jobs from the queue
      max_workers: 400
      # -- Length of job queue. imporatant for querier as it queues a job for every block it has to search
      queue_depth: 20000
  # Settings for the Admin client storage backend and buckets. Only valid is enterprise.enabled is true.
  admin:
    # -- The supported storage backends are gcs, s3 and azure, as specified in https://grafana.com/docs/enterprise-traces/latest/config/reference/#admin_client_config
    backend: azure


# memcached is for all of the Tempo pieces to coordinate with each other.
# you can use your self memcacherd by set enable: false and host + service
memcached:
  # -- Specified whether the memcached cachce should be enabled
  enabled: true

memcachedExporter:
  # -- Specifies whether the Memcached Exporter should be enabled
  enabled: true
  resources: {}

metaMonitoring:
  # ServiceMonitor configuration
  serviceMonitor:
    # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
    enabled: true

  # metaMonitoringAgent configures the built in Grafana Agent that can scrape metrics and logs and send them to a local or remote destination
  grafanaAgent:
    # -- Controls whether to create PodLogs, MetricsInstance, LogsInstance, and GrafanaAgent CRs to scrape the
    # ServiceMonitors of the chart and ship metrics and logs to the remote endpoints below.
    # Note that you need to configure serviceMonitor in order to have some metrics available.
    enabled: false

    # -- Controls whether to install the Grafana Agent Operator and its CRDs.
    # Note that helm will not install CRDs if this flag is enabled during an upgrade.
    # In that case install the CRDs manually from https://github.com/grafana/agent/tree/main/production/operator/crds
    installOperator: false

# Rules for the Prometheus Operator
prometheusRule:
  # -- If enabled, a PrometheusRule resource for Prometheus Operator is created
  enabled: true
  # -- Alternative namespace for the PrometheusRule resource
  namespace: null
  # -- PrometheusRule annotations
  annotations: {}
  # -- Additional PrometheusRule labels
  labels: {}
  # -- Contents of Prometheus rules file
  groups: []
  # - name: loki-rules
  #   rules:
  #     - record: job:loki_request_duration_seconds_bucket:sum_rate
  #       expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, job)
  #     - record: job_route:loki_request_duration_seconds_bucket:sum_rate
  #       expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, job, route)
  #     - record: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate
  #       expr: sum(rate(container_cpu_usage_seconds_total[1m])) by (node, namespace, pod, container)

minio:
  enabled: false
  mode: standalone
  rootUser: grafana-tempo
  rootPassword: supersecret
  buckets:
    # Default Tempo storage bucket.
    - name: tempo-traces
      policy: none
      purge: false
    # Bucket for traces storage if enterprise.enabled is true - requires license.
    - name: enterprise-traces
      policy: none
      purge: false
    # Admin client bucket if enterprise.enabled is true - requires license.
    - name: enterprise-traces-admin
      policy: none
      purge: false
  persistence:
    size: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  # Changed the mc config path to '/tmp' from '/etc' as '/etc' is only writable by root and OpenShift will not permit this.
  configPathmc: '/tmp/minio/mc/'

# Configuration for the gateway
gateway:
  # -- Specifies whether the gateway should be enabled
  enabled: true
  # -- Number of replicas for the gateway
  replicas: 1
  # Basic auth configuration
  basicAuth:
    # -- Enables basic authentication for the gateway
    enabled: true
    # -- The basic auth username for the gateway
    username: asrdd
    # -- The basic auth password for the gateway
    password: asrddadmin
```
