### ISSUE TITLE
[mimir-distributed] Override alertmanager_url Setting in Mimir Ruler

### ISSUE THREAD

**Issue by reda-ayoub** [grafana/helm-charts#3023]
I'm trying to send mimir ruler alerts to a different alertmanager (grafana alertmanager), but the chart doesn't offer the possibility to override the alertmanager_url setting in the ruler configuration. 

Is there any workaround over this ? or I'm missing something?

**Comment by KoffeinKaio** [comment]
i realize this is old as heck. but I just did this and stumbled over this issue.

For everyone finding this:

```
mimir:
  structuredConfig:
    ruler:
      alertmanager_url: http://alertmanager.alertmanager.svc.cluster.local:9093
```
