### ISSUE TITLE
[Ptomtail] Helm chart broken v6.15.5

### ISSUE THREAD

**Issue by 4s3ti** [grafana/helm-charts#3029]
Helm chart v6.15.5 is broken by default. 

Error message: 

```
Helm install failed for release monitoring/promtail with chart promtail@6.15.5: template: promtail/templates/secret.yaml:18:19: executing "promtail/templates/secret.yaml" at <.Values.config.file>: nil pointer evaluating interface {}.file
```

Steps to reproduce: Follow the instructions at https://grafana.com/docs/loki/latest/send-data/promtail/installation/

my values: 

```
config:
  clients:
  - url: http://loki/loki/api/v1/push
    tenant_id: 1
```
