### ISSUE TITLE
How to add new Role using Helm

### ISSUE THREAD

**Issue by rlugovyy** [grafana/helm-charts#3040]
How can I add new roles to Grafana via helm? I found  `[section](https://grafana.com/docs/grafana/latest/administration/roles-and-permissions/access-control/manage-rbac-roles/#:~:text=Create%20custom%20roles%20using%20the%20HTTP%20API&text=For%20example%2C%20if%20you%20only,users%3Acreate%20action%20to%20it.&text=Refer%20to%20the%20RBAC%20HTTP%20API%20for%20more%20details.,-Update%20basic%20role)` in the doc where man need to add a configmap for the role. I did this

-templates/role.configmap.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-custom-editor-role
data:
  customrole.yaml: |
    apiVersion: 2

    roles:
      - name: custom:users
        description: 'List, create, or update other users.'
        version: 1
        orgId: 1
        permissions:
          - action: 'users:read'
            scope: 'global.users:*'
          - action: 'users:write'
            scope: 'global.users:*'
          - action: 'users:create'
```
-values.yaml
```
grafana:
  extraConfigmapMounts:
  - name: grafana-custom-editor-role
    mountPath: /etc/grafana/provisioning/access-control
    configMap: grafana-custom-editor-role
    readOnly: true
```

but it doesnt work
