### ISSUE TITLE
SMTP configuration error 535 authentication Failed: Bad Username / Password

### ISSUE THREAD

**Issue by redaER7** [grafana/helm-charts#3062]
Using chart grafana-7.3.0, I am looking to configure sendgrid SMTP inside chart values, my configuration is the following:
```
grafana.ini:
  smtp:
    enabled: true
    skip_verify: false
    host: smtp.***
    from_name: Grafana
    from_address: ***
smtp:
  # `existingSecret` is a reference to an existing secret containing the smtp configuration
  # for Grafana.
  existingSecret: "grafana-smtp-secret"
  userKey: "user"
  passwordKey: "password"
```

`grafana-smtp-secret` is the secret where user: is the service account I created, and password is for my SMTP config,
Checking the grafana.ini inside the pod, my infos are there
```
[smtp]
enabled = true
from_address = ****
from_name = Grafana
host = smtp.***
skip_verify = false
```
while secret values are present as environment variables `GF_SMTP_USER` `GF_SMTP_PASSWORD`

When testing, I'm getting error 535 authentication Failed: Bad Username / Password, 
What am I missing here ?
Thank you,
![Screenshot 2024-04-04 at 13 35 16](https://github.com/grafana/helm-charts/assets/83544749/adfea516-0ca0-45b5-a0b1-4beab28be2e9)
