### ISSUE TITLE
Loading dashboards as files results in duplicate warnings in Grafana logs

### ISSUE THREAD

**Issue by nwsteenberg** [grafana/helm-charts#3072]
Using grafana chart 7.3.0 i am loading in some dashboards as files:
```
dashboards:
    someProvider:
      home:
        file: dashboards/someProvider/home.json
```
But also to pick up configmaps with the following configuration:
```
sidecar:
    dashboards:
      folderAnnotation: grafana_dashboard_folder
      searchNamespace: ALL
      # Configmap Dashboard labels
      label: grafana_dashboard
      labelValue: "1"
```
I get a lot of the following warnings in grafana:
```
logger=provisioning.dashboard t=2024-04-11T08:04:33.170882773Z level=warn msg="dashboards provisioning provider has no database write permissions because of duplicates" provider=someProvider orgId=1
logger=provisioning.dashboard t=2024-04-11T08:04:33.170889673Z level=warn msg="dashboards provisioning provider has no database write permissions because of duplicates" provider=sidecarProvider orgId=1
logger=provisioning.dashboard t=2024-04-11T08:05:03.171217608Z level=warn msg="the same UID is used more than once" orgId=1 uid=pS6ZuGV7z times=2 providers="[someProvider sidecarProvider]"
logger=provisioning.dashboard t=2024-04-11T08:05:03.171309409Z level=warn msg="the same UID is used more than once" orgId=1 uid=WmDYPIXGz times=2 providers="[sidecarProvider someProvider]"
logger=provisioning.dashboard t=2024-04-11T08:05:03.171331109Z level=warn msg="dashboard title is not unique in folder" orgId=1 title="Kubernetes cluster overview" folderID=1 times=2 providers="[someProvider sidecarProvider]"
logger=provisioning.dashboard t=2024-04-11T08:05:03.171349109Z level=warn msg="dashboard title is not unique in folder" orgId=1 title="Home" folderID=1 times=2 providers="[someProvider sidecarProvider]"
logger=provisioning.dashboard t=2024-04-11T08:05:03.171362609Z level=warn msg="dashboards provisioning provider has no database write permissions because of duplicates" provider=someProvider orgId=1
logger=provisioning.dashboard t=2024-04-11T08:05:03.171370409Z level=warn msg="dashboards provisioning provider has no database write permissions because of duplicates" provider=sidecarProvider orgId=1
```

I think the reason is that the dashboards are being picked up twice. One loaded from the file, and because the produced configmap has the correct label, then it is picked up again by the sidecar. The issue seems to be introduced in the following commit: 381c2a0
