### ISSUE TITLE
[grafana] Cannot set default folder and folder annotation

### ISSUE THREAD

**Issue by CiucurDaniel** [grafana/helm-charts#3092]
I'm currently setting up the monitoring stack using [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) helm chart, which has a dependency on grafana chart from here.

I have 2 goals:

* change default folder so all the dashabords which the chart comes with are placed in a folder (`Kubernetes`)
* make it able for config maps with dashboards to set an annotation with the desired folder location

I searched a bit and bumped into those issues: #526 and #527 
and saw those 2 comments: 

* [comment on first issue](https://github.com/grafana/helm-charts/issues/526#issuecomment-878534071)
* [comment on second issue](https://github.com/grafana/helm-charts/issues/527#issuecomment-982319638)

and gave it a try with those values but had no success

```yaml
sidecar:
  dashboards:
    # folder in the pod that should hold the collected dashboards (unless `defaultFolderName` is set)
    folder: /tmp/dashboards
    # The default folder name, it will create a subfolder under the `folder` and put dashboards in there instead
    defaultFolderName: Kubernetes
    # If specified, the sidecar will look for annotation with this name to create folder and put graph here.
    # You can use this parameter together with `provider.foldersFromFilesStructure`to annotate configmaps and create folder structure.
    folderAnnotation: grafana_folder
     provider:
        allowUiUpdates: true
        foldersFromFilesStructure: true
```

**1. What is the correct way to group the default dashboards that come with `kube-prometheus-stack` in a folder?**

**2. How can you propery configure the chart so you can annotate dashabord  definitions with the folder you want the dashabord to be in?**
