### ISSUE TITLE
Grafana Alloy Helm Chart - Container not starting: exec /bin/alloy: operation not permitted

### ISSUE THREAD

**Issue by PatMis16** [grafana/helm-charts#3097]
When deploying Grafana Alloy to EKS using the Helm Chart with a `podSecurityContext` where `runAsUser` is used the container does not start. The following error is logged: 
```
exec /bin/alloy: operation not permitted
``` 
The `podSecurityContext` was defined like this:
```
podSecurityContext:
      fsGroup: 2000
      runAsNonRoot: true
      runAsUser: 473
```
This issue is actually the same as the one reported in the Grafana Alloy repository:  https://github.com/grafana/alloy/issues/630

The container must be deployable to an environment where the `podSecurityContext` is required and where all capabilities mut be droped.
