### ISSUE TITLE
Mimir distributed Issues setting up azure blob storage

### ISSUE THREAD

**Issue by Ivalberto** [grafana/helm-charts#3137]
When trying to setup mimir with helm chart I receiving the following error in the mimi-querier component :

```
ts=2024-05-18T01:48:44.763962593Z caller=main.go:226 level=info msg="Starting application" version="(version=2.12.0, branch=HEAD, revision=c7aab9e)"
ts=2024-05-18T01:48:44.764163495Z caller=log.go:103 level=error msg="error running application" err="no s3 endpoint in config file\[ngithub.com/thanos-io/objstore/providers/s3.validate](http://ngithub.com/thanos-io/objstore/providers/s3.validate)\n\t/__w/mimir/mimir/vendor/github.com/thanos-io/objstore/providers/s3/s3.go:353\[ngithub.com/thanos-io/objstore/providers/s3.NewBucketWithConfig](http://ngithub.com/thanos-io/objstore/providers/s3.NewBucketWithConfig)\n\t/__w/mimir/mimir/vendor/github.com/thanos-io/objstore/providers/s3/s3.go:222\[ngithub.com/grafana/mimir/pkg/storage/bucket/s3.NewBucketClient](http://ngithub.com/grafana/mimir/pkg/storage/bucket/s3.NewBucketClient)\n\t/__w/mimir/mimir/pkg/storage/bucket/s3/bucket_client.go:27\[ngithub.com/grafana/mimir/pkg/storage/bucket.NewClient](http://ngithub.com/grafana/mimir/pkg/storage/bucket.NewClient)\n\t/__w/mimir/mimir/pkg/storage/bucket/client.go:163\[ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).initUsageStats](http://ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).initUsageStats)\n\t/__w/mimir/mimir/pkg/mimir/modules.go:1013\[ngithub.com/grafana/dskit/modules.(*Manager).initModule](http://ngithub.com/grafana/dskit/modules.(*Manager).initModule)\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:136\[ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices](http://ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices)\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:108\[ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).Run](http://ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).Run)\n\t/__w/mimir/mimir/pkg/mimir/mimir.go:830\nmain.main\n\t/__w/mimir/mimir/cmd/mimir/main.go:228\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650\ncreate usage-stats bucket client\[ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).initUsageStats](http://ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).initUsageStats)\n\t/__w/mimir/mimir/pkg/mimir/modules.go:1015\[ngithub.com/grafana/dskit/modules.(*Manager).initModule](http://ngithub.com/grafana/dskit/modules.(*Manager).initModule)\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:136\[ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices](http://ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices)\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:108\[ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).Run](http://ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).Run)\n\t/__w/mimir/mimir/pkg/mimir/mimir.go:830\nmain.main\n\t/__w/mimir/mimir/cmd/mimir/main.go:228\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650\nerror initialising module: usage-stats\[ngithub.com/grafana/dskit/modules.(*Manager).initModule](http://ngithub.com/grafana/dskit/modules.(*Manager).initModule)\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:138\[ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices](http://ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices)\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:108\[ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).Run](http://ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).Run)\n\t/__w/mimir/mimir/pkg/mimir/mimir.go:830\nmain.main\n\t/__w/mimir/mimir/cmd/mimir/main.go:228\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"
```

This is my value file taking as example small.yaml form helm chart repo : 

I'm using azure as storage but the erro show s3 I dont know what i missing here or i need to modify from the small.yaml file

```
#New
global:
  extraEnvFrom:
    - secretRef:
        name: mimir
  podAnnotations:
    bucketSecretVersion: "0"
#New
mimir:
  structuredConfig:
    common:
      storage:
        backend: azure
        azure:
          account_name: "devobservability"
          connection_string: ${CONNECTIONSTRING}
          container_name: "mimir"
    blocks_storage:
      backend: azure
      storage_prefix: "blocks"
    ruler_storage:
     backend: azure
     storage_prefix: "ruler"
    memberlist:
      abort_if_cluster_join_fails: false
      compression_enabled: false
      join_members:
      - dns+{{ include "mimir.fullname" . }}-results-cache.{{ .Release.Namespace }}.svc:{{ include "mimir.memberlistBindPort" }}
alertmanager:
  persistentVolume:
    enabled: false
  replicas: 0
  resources:
    limits:
      memory: 1.4Gi
    requests:
      cpu: 1
      memory: 1Gi
  statefulSet:
    enabled: true
compactor:
  persistentVolume:
    size: 20Gi
  resources:
    limits:
      memory: 2.1Gi
    requests:
      cpu: 1
      memory: 1.5Gi
distributor:
  replicas: 1
  resources:
    limits:
      memory: 5.7Gi
    requests:
      cpu: 2
      memory: 4Gi
ingester:
  persistentVolume:
    size: 50Gi
  replicas: 1
  resources:
    limits:
      memory: 12Gi
    requests:
      cpu: 3.5
      memory: 8Gi
  topologySpreadConstraints: {}
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: target # support for enterprise.legacyLabels
                operator: In
                values:
                  - ingester
          topologyKey: '[kubernetes.io/hostname](http://kubernetes.io/hostname)'
        - labelSelector:
            matchExpressions:
              - key: [app.kubernetes.io/component](http://app.kubernetes.io/component)
                operator: In
                values:
                  - ingester
          topologyKey: '[kubernetes.io/hostname](http://kubernetes.io/hostname)'
  zoneAwareReplication:
    topologyKey: '[kubernetes.io/hostname](http://kubernetes.io/hostname)'
admin-cache:
  enabled: true
  replicas: 1
chunks-cache:
  enabled: true
  replicas: 1
index-cache:
  enabled: true
  replicas: 1
metadata-cache:
  enabled: true
results-cache:
  enabled: true
  replicas: 1
minio:
  enabled: false
overrides_exporter:
  replicas: 1
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
querier:
  replicas: 1
  resources:
    limits:
      memory: 5.6Gi
    requests:
      cpu: 2
      memory: 4Gi
query_frontend:
  replicas: 1
  resources:
    limits:
      memory: 2.8Gi
    requests:
      cpu: 2
      memory: 2Gi
ruler:
  replicas: 1
  resources:
    limits:
      memory: 2.8Gi
    requests:
      cpu: 1
      memory: 2Gi
store_gateway:
  persistentVolume:
    size: 10Gi
  replicas: 1
  resources:
    limits:
      memory: 2.1Gi
    requests:
      cpu: 1
      memory: 1.5Gi
  topologySpreadConstraints: {}
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: target # support for enterprise.legacyLabels
                operator: In
                values:
                  - store-gateway
          topologyKey: '[kubernetes.io/hostname](http://kubernetes.io/hostname)'
        - labelSelector:
            matchExpressions:
              - key: [app.kubernetes.io/component](http://app.kubernetes.io/component)
                operator: In
                values:
                  - store-gateway
          topologyKey: '[kubernetes.io/hostname](http://kubernetes.io/hostname)'
  zoneAwareReplication:
    topologyKey: '[kubernetes.io/hostname](http://kubernetes.io/hostname)'
nginx:
  replicas: 1
  resources:
    limits:
      memory: 731Mi
    requests:
      cpu: 1
      memory: 512Mi
# Grafana Enterprise Metrics feature related
admin_api:
  replicas: 0
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
gateway:
  replicas: 1
  resources:
    limits:
      memory: 731Mi
    requests:
      cpu: 1
      memory: 512Mi
```
