### ISSUE TITLE
Unable to drop INFO and DEBUG logs in Promtail configuration

### ISSUE THREAD

**Issue by akramsadab** [grafana/helm-charts#3141]
Hello,

I'm trying to configure Promtail to drop logs with levels INFO and DEBUG, but despite trying multiple configurations, I'm still seeing these logs. Here's my current configuration:
- job_name: system
  static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log
  pipeline_stages:
    - match:
        selector: '{job="varlogs"}'
        stages:
          - regex:
              expression: '^(?P<timestamp>\w{3} \d{1,2} \d{2}:\d{2}:\d{2}) (?P<log>.*)$'
          - timestamp:
              source: timestamp
              format: Jan 2 15:04:05
          - regex:
              expression: '.*\b(?P<level>(debug|DEBUG|trace|TRACE|info|INFO))\b.*'
              source: log
          - labels:
              level: ''
          - drop:
              source: level
              expression: '(debug|DEBUG|trace|TRACE|info|INFO)'
I've tried multiple different alternatives, but none of them seem to work. I'm still seeing INFO and DEBUG logs.

Could anyone please help me understand what I'm doing wrong and how I can correctly configure Promtail to drop these logs?

Thank you in advance for your help.

**Comment by noatudor** [comment]
Hey, I have to deploy Loki, but I'm unable to get my head around the S3 configuration. I got Loki deployed with the Monolithic Helm chart, but I just can't seem to configure S3.

Here's my current configuration:

loki:
  commonConfig:
    replication_factor: 3
  schemaConfig:
    configs:
    - from: "2024-01-01"
      store: tsdb
      index:
        prefix: loki_index_
        period: 24h
      object_store: s3
      schema: v13
  storage:
    type: 's3'
    bucketNames:
      chunks: loki-chunks
      ruler: loki-chunks
      admin: lloki-chunks
    s3:
      endpoint: https://s3.de.io.cloud.ovh.net
      region: de
      secretAccessKey: REDACTED
      accessKeyId: REDACTED
      s3ForcePathStyle: false
      insecure: false
singleBinary:
  replicas: 3

Does anybody have a working values.yaml file that has S3 configured? I'm using the S3 provided by OVH Cloud (OpenStack), so we need to specify the host.

Any help would be appreciated. I've already wasted a week trying to configure S3.

**Comment by akramsadab** [comment]
Please help team

**Comment by jwillmer** [comment]
I have the same problem. This is my config - I also did a couple of iterations but it did not work:

```
scrape_configs:

  - job_name: docker-containers
  
    docker_sd_configs:
      - host: unix:///run/docker.sock
        refresh_interval: 15s
        
    relabel_configs:
        
        # log level from labels
      - source_labels: [__meta_docker_container_label_level]
        target_label: level

        # drop all other Docker internal labels
      - action: labeldrop
        regex: '__meta_docker_.*'
        
    pipeline_stages:
      - docker: {}
      - drop:
          # Drop logs where the level is info, debug, or trace
          source:     ["level"]
          expression:  '(?i)(info|debug|trace)'
```
