### ISSUE TITLE
[tempo-distributed] Missing PodAnnotations

### ISSUE THREAD

**Issue by adamstrawson** [grafana/helm-charts#315]
The documentation states the ability to set Pod Annotations

Example;
```yaml
compactor:
  podAnnotations:
    foo: "bar"
```

However, the annotations are missing from within the templates.

PR to follow with a fix for this.
