### ISSUE TITLE
Correct syntax for enabling querier compression

### ISSUE THREAD

**Issue by hobbsh** [grafana/helm-charts#3155]
I am trying to configure `querier` grpc compression but have not been able to get the configuration/key structure correct.

Based on [this doc](https://docs.aws.amazon.com/waf/latest/developerguide/waf-captcha-and-challenge.html), I would assume that `querier.frontend-client` becomes `querier_frontend_client` (since `ingester.client` becomes `ingester_client`) in `structuredConfig`.

Based on that assumption, I would expect that the structured config to use would be:

```yaml
loki:
  structuredConfig:
    querier_frontend_client:
      grpc_client_config:
        grpc_compression: "gzip"
```
