### ISSUE TITLE
Issue in dynamiclly set volume name.

### ISSUE THREAD

**Issue by tyagivasu** [grafana/helm-charts#3156]
Hi, In my helm diff I am seeing below changes for a dynamically created volume by Azure.

```
# Source: kube-prometheus-stack/charts/grafana/templates/pvc.yaml
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: grafana
    namespace: <namespace>
    labels:
      helm.sh/chart: grafana-7.3.9
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: grafana
      app.kubernetes.io/version: "10.4.1"
      app.kubernetes.io/managed-by: Helm
    finalizers:
      - kubernetes.io/pvc-protection
  spec:
    accessModes:
      - "ReadWriteOnce"
    resources:
      requests:
        storage: "<n>Gi"
-   volumeName: pvc-<dynamic_id_number>
    storageClassName: managed-premium-extensible
```

Further when  I look into this issue, identified that below logic causing it.

`
  {{- if (lookup "v1" "PersistentVolumeClaim" (include "grafana.namespace" .) (include "grafana.fullname" .)) }}
  volumeName: {{ (lookup "v1" "PersistentVolumeClaim" (include "grafana.namespace" .) (include "grafana.fullname" .)).spec.volumeName }}
  {{- end }}
`
refer [link](https://github.com/grafana/helm-charts/commit/7eb35238fff33a59812f9ad629d271a8439a5d05) for more detail.

Can I have some fix to resolve this diff change happeing everytime? Also I would like to understand why this logic needed, and introduced?
