### ISSUE TITLE
[rollout_operator] Resources - Remove default memory limit

### ISSUE THREAD

**Issue by mrclrchtr** [grafana/helm-charts#3158]
The limit cannot be removed in parent charts and is therefore always set.

```
resources:
  limits:
    # cpu: "1"
    memory: 200Mi
```

It should be removed completely so that it can be freely decided whether and which one should be set.

The cpu limit has already been removed in this PR: https://github.com/grafana/helm-charts/pull/2886
