### ISSUE TITLE
[promtail] 6.16.0 breaks the application if you don't include labels with service

### ISSUE THREAD

**Issue by EStork09** [grafana/helm-charts#3162]
With the 6.16.0 release, if you use the service option without any labels it breaks the chart.
Current template
```
metadata:
  name: {{ include "promtail.fullname" . }}-metrics
  namespace: {{ include "promtail.namespaceName" . }}
  labels:
    {{- include "promtail.labels" . | nindent 4 }}
    {{- toYaml .Values.service.labels | nindent 4 }} # default service.labels: {}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
```

rendered:
```
apiVersion: v1
kind: Service
metadata:
  name: release-name-promtail-metrics
  namespace: default
  labels:
    helm.sh/chart: promtail-6.16.0
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "3.0.0"
    app.kubernetes.io/managed-by: Helm
    {}
  annotations:
    {}
```

We need to exclude the empty {} from the service labels to prevent breaking the chart.
I'll try to make a PR if someone doesn't beat me to it, but a simple fix for the time being is:

```
service:
  labels:
    fix: fix
```

The fix would be to look at something like:
```
metadata:
  name: {{ include "promtail.fullname" . }}-metrics
  namespace: {{ include "promtail.namespaceName" . }}
  labels:
    {{- include "promtail.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
```
