### ISSUE TITLE
Error: YAML parse error on promtail/templates/service-metrics.yam

### ISSUE THREAD

**Issue by KateFiroozi** [grafana/helm-charts#3180]
error converting YAML to JSON: yaml: line 11: did not find expected key

version 6.16.0

**Comment by MiroslavSotirov** [comment]
The problem seems to be in the labels section:

Parsed template with serviceMonitor.enabled.true

```
apiVersion: v1
kind: Service
metadata:
  name: loki-promtail-metrics
  namespace: default
  labels:
    helm.sh/chart: promtail-6.16.0
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: "3.0.0"
    app.kubernetes.io/managed-by: Helm
    {}
  annotations:
    {}
```
Which points to the problem in labels "{}"

replacing 
```
{{- toYaml .Values.service.labels | nindent 4 }}
```

with

```
{{- with .Values.service.labels }}
{{- toYaml . | nindent 4 }}
{{- end }}
```

should fix this

also a temporary nasty workaround would be to set a dumb label in the service section

```
service:
  labels:
    dumb: dumb
```
