### ISSUE TITLE
Customization Options for Imported Public Dashboards

### ISSUE THREAD

**Issue by juliendf** [grafana/helm-charts#3190]
Hi everyone,

I'm using the Helm chart to deploy Grafana and import public dashboards. Currently, when importing important public dashboards like the Prometheus stats dashboard, we use a configuration similar to this:

```yaml
dashboards:
  default:
    prometheus-stats:
      gnetId: 2
      revision: 2
      datasource: Prometheus
```

While this works well for bringing in the dashboard, I've identified some limitations in customizing these imported dashboards. Specifically, I'd like to be able to:

1. Add or modify tags for better organization
2. Change the name of the dashboard to fit our naming conventions
3. Potentially set folder locations for these dashboards

Is it currently possible to achieve these customizations when importing public dashboards through the Helm chart? If not, is this functionality planned for a future release?
I believe these customization options would greatly enhance the flexibility and organization of imported dashboards, especially in larger environments with many dashboards.

Thank you
