### ISSUE TITLE
[grafana] dashboards are missing some config values that make them not being created

### ISSUE THREAD

**Issue by NestorRV** [grafana/helm-charts#3192]
### [Overview](#overview)
- dashboards are missing some config values that make them not being create

### [Details](#details)
- I'm using the code you can see below to install [dotdc/grafana-dashboards-kubernetes](https://github.com/dotdc/grafana-dashboards-kubernetes) dashboards:
    <details>
      <summary>Code</summary>

      ```yaml
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - disableDeletion: true
            editable: true
            folder: resource-a
            name: k8s-resource-a
            options:
              path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
            orgId: 1
            type: file
          - disableDeletion: true
            editable: true
            folder: resource-b
            name: k8s-resource-b
            options:
              path: /var/lib/grafana/dashboards/grafana-dashboards-kubernetes
            orgId: 1
            type: file
      dashboards:
        k8s-resource-a:
          k8s-system-api-server-resource-a:
            datasource: resource-a
            token: ""
            url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
        k8s-resource-b:
          k8s-system-api-server-resource-b:
            datasource: resource-b
            token: ""
            url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
      ```
    </details>
- As you can see, I do want two `dashboardsProviders` and a `dashboard` per `dashboardsProvider` as I want the same dashboard for multiple datasources and in multiple folders.
- If I apply this helm chart, I'm getting the following errors:
    ```
    logger=provisioning.dashboard t=2024-06-26T13:31:59.448508732Z level=warn msg="the same UID is used more than once" orgId=1 uid=k8s_system_apisrv times=4 providers="[k8s-prometheus-blue-cluster k8s-prometheus-green-cluster]"
    logger=provisioning.dashboard t=2024-06-26T13:31:59.449236524Z level=warn msg="dashboard title is not unique in folder" orgId=1 title="Kubernetes / System / API Server" folderID=8 times=2 providers=[k8s-prometheus-blue-cluster]
    ```
- I have checked the yaml generated by helm (`helm get all grafana > grafana.yml`) and I can see the `download_dashboards.sh` file which downloads the dashboards. There, I can see that a `sed` command is done to replace the `datasource` within the dashboard.
- I have found that the `download_dashboards.sh` file comes from https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/_config.tpl#L70
- I have checked there and I do not see anyway to allows us tweaking the `uid` or the `title` field of the dashboards

### [Request](#request)
- Can we get some fields that allows us tweaking the `uid` or the `title` field of the dashboard to avoid collisions?
