### ISSUE TITLE
[tempo] Incorrect permissions for PVC

### ISSUE THREAD

**Issue by sircthulhu** [grafana/helm-charts#3197]
When enabling `.Values.persistence.enabled`, PVC is to be created and mounted. But the problem is that tempo works as user `1001` and cannot create directory in PVC mounted as root.
So, tempo won't start with this error:
```
level=error ts=2024-07-01T09:19:42.076129669Z caller=main.go:121 msg="error running Tempo" err="failed to init module services: error initialising module: store: failed to create store: mkdir /var/tempo/wal: permission denied"
```

It can be fixed adding this to the root of `values.yaml`:

```yaml
securityContext:
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  runAsNonRoot: true
```
and PVC will be mounted with correct permissions.

Versions:
- K8s 1.30.1
- Tempo chart 1.10.0
