### ISSUE TITLE
[tempo-distributed] missing ingester statefulset

### ISSUE THREAD

**Issue by benmathews** [grafana/helm-charts#3199]
The ingester statefulset is by default removed in the 1.13 version of tempo-distributed

V1.12 produces a statefulset
```
➜ helm template grafana/tempo-distributed --version 1.12.0|grep -B3 release-name-tempo-ingester
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: release-name-tempo-ingester
--
apiVersion: v1
kind: Service
metadata:
  name: release-name-tempo-ingester-discovery
--
apiVersion: v1
kind: Service
metadata:
  name: release-name-tempo-ingester
--
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-tempo-ingester
```

V1.13 does not produce a statefulset
```
➜ helm template grafana/tempo-distributed --version 1.13.0|grep -B3 release-name-tempo-ingester
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: release-name-tempo-ingester
--
apiVersion: v1
kind: Service
metadata:
  name: release-name-tempo-ingester-discovery
--
apiVersion: v1
kind: Service
metadata:
  name: release-name-tempo-ingester
```
