### ISSUE TITLE
[promtail] service-extra: custom labels not working

### ISSUE THREAD

**Issue by camrossi** [grafana/helm-charts#3219]
As per the values file if I am adding extra services I can add also add custom labels:

For example with the below config I would expect my service to have the `pippo: pluto` label
```
extraPorts:
  syslog:
    name: tcp-syslog
    annotations: {}
    labels:
      pippo: pluto
```
However the service-extra.yaml template and dumps `$` instead of `{{- with $values.labels }}` resulting in a broken Service.
