### ISSUE TITLE
ClusterRole missing permissions to scrape pods

### ISSUE THREAD

**Issue by benniwiit** [grafana/helm-charts#3247]
## Helm Chart

grafana-agent-operator v0.4.0/v0.4.1

## What's the issue

After installing the helm chart and a service monitor for grafana-agent's own metrics, grafana-agent was not able to scrape the metrics. The issue was that the clusterrole was missing the "pods" resource. In the test template "test-grafanaagent.yaml", the clusterrole has the "pods" resource.

## How to reproduce

Deploy helm chart and the following resources in the same namespace:

```yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    operator.agent.grafana.com/name: grafana-agent-metrics
    operator.agent.grafana.com/type: metrics
  name: grafana-agent-metrics
  namespace: observability
spec:
  endpoints:
  - path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - observability
  selector:
    matchLabels:
      operator.agent.grafana.com/name: grafana-agent-metrics
---
apiVersion: monitoring.grafana.com/v1alpha1
kind: MetricsInstance
metadata:
  labels:
    agent: grafana-agent-metrics
  name: grafana-agent-metrics
  namespace: observability
spec:
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  remoteWrite:
  - basicAuth:
      password:
        key: password
        name: grafana-agent-metrics-credentials
      username:
        key: username
        name: grafana-agent-metrics-credentials
    metadataConfig:
      send: true
      sendInterval: 1m
    name: thanos-receive
    queueConfig:
      batchSendDeadline: 10s
      capacity: 120000
      maxBackoff: 5m
      maxSamplesPerSend: 40000
      maxShards: 50
      minBackoff: 5s
      minShards: 1
    remoteTimeout: 30s
    url: ""
    writeRelabelConfigs:
    - action: replace
      sourceLabels:
      - cluster
      targetLabel: app_cluster
    - action: replace
      replacement: pgaas-lab-01
      targetLabel: cluster
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
---
apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
metadata:
  labels:
    app: grafana-agent
  name: grafana-agent-metrics
  namespace: observability
spec:
  containers:
  - name: config-reloader
    resources:
      limits:
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 64Mi
  disableReporting: true
  disableSupportBundle: false
  enableConfigReadAPI: false
  logLevel: info
  metrics:
    externalLabels:
      cluster: ""
    instanceSelector:
      matchLabels:
        agent: grafana-agent-metrics
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 2Gi
  serviceAccountName: grafana-agent-operator
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 5Gi
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-agent-metrics-credentials
  namespace: observability
spec:
  encryptedData:
    password: ""
    username: ""
  template:
    metadata:
      creationTimestamp: null
      name: grafana-agent-metrics-credentials
      namespace: observability
    type: kubernetes.io/basic-auth
```
