### ISSUE TITLE
[Question] Correct DNS Settings for OTLP Configuration with OpenTelemetry

### ISSUE THREAD

**Issue by gustavosett** [grafana/helm-charts#3252]
Hello,

I am currently setting up the OpenTelemetry Collector in my Kubernetes cluster and need some assistance with the correct DNS and endpoints configurations for exporting for grafana services logs, traces, and metrics using OTLP.

lgtm-distributed pods:
![image](https://github.com/user-attachments/assets/04a634ea-690d-4716-ae54-c43b2a332e42)

OpenTelemetry config(I don't know if this is correct):
```yaml
  exporters:
    otlphttp/loki:
      endpoint: http://monitoring-loki-distributor:3100/otlp
      tls:
        insecure: true
      headers: {"X-Scope-OrgId": "1"}
    otlphttp/tempo:
      endpoint: http://monitoring-tempo-distributor:3100
      tls:
        insecure: true
    otlphttp/mimir:
      endpoint: http://monitoring-mimir-distributor:8080
      tls:
        insecure: true
```

Thank you in advance for your assistance!
