### ISSUE TITLE
Deploy Ignore additional Datasource

### ISSUE THREAD

**Issue by weyderfs** [grafana/helm-charts#3254]
Hi Guys,

# TL&DR

I've been trying include `additionalDataSources` more precise the [CloudWatch](https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/).

## My scenario:

- I'm using the [Kube Prometheus Stack](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack): `v61.6.0`
- My Grafana use external database.

## What is I've been tried?

- Include in `values.yaml` the securityContext in my deployment: _No success_.
- When Included manually via Grafana Web UI: works fine. I just have checked in the external database there's no `INSERT` CloudWatch datasource  in the table.
- I've tried included in both `deleteDatasources` and more bellow in the `additionalDataSources`: _No success_

The sample that I'm using to provisioning:

```yaml
additionalDataSources:
    - name: CloudWatch
      type: cloudwatch
      jsonData:
        authType: default
        assumeRoleArn: ${GF_AWS_IAM_ROLE}
        defaultRegion: ${GF_REGION}
```

Anyone have ideia where is my fault?
