### ISSUE TITLE
[grafana] [image-renderer] Service monitor because the ingress network policy does not allow prometheus to connect

### ISSUE THREAD

**Issue by FirelightFlagboy** [grafana/helm-charts#3268]
Hello, I had configured the `grafana-image-renderer` with the `grafana/grafana` helm with the following configuration:

```yaml
imageRenderer:
    enabled: true

    serviceMonitor:
        enabled: true
```

But the service monitor wasn't able to fetch the metrics as it wasn't able to connect to the `grafana-image-renderer` pod with the TPC error `connection refused`.

It appears that the issue is caused by the configured `image-renderer-ingress` network policy that only allow connection from the `grafana` pod.

What I would expect is that when the service monitor is enabled that the ingress is configured to allow prometheus to scrap the metrics from the `image-renderer` pod.

## Workaround

Currently, I have a workaround that use the `extraIngressSelectors` to select the prometheus pod.

```yaml
imageRenderer:
    networkPolicy:
        extraIngressSelectors:
            - namespaceSelector:
                matchLabels:
                    kubernetes.io/metadata.name: siem
              podSelector:
                matchLabels:
                    app.kubernetes.io/instance: prometheus
                    app.kubernetes.io/name: prometheus
```
