### ISSUE TITLE
Loki S3 Config

### ISSUE THREAD

**Issue by iv1310** [grafana/helm-charts#3271]
Hi guys,
I'd like to configure my grafana loki to use s3 as the storage, but it turn out I had to expose the credential in the values file like this.
```yaml
storage_config:
    aws:
      s3: s3://AxxxxxBCEHxxxxxxRY:xxaaaadLaxxxxxyyyyyyyyaaaaaaazzzz02f1@eu-east-2/bucket-name-for-loki-s3-data-storage
```
At first I tried to expose them as environment variables, but it's not working.  Is there any other way to do it?
