### ISSUE TITLE
Grafana Cloud Not Receiving Data Despite Helm Chart Showing 'Deployed' Status with Prometheus Disabled

### ISSUE THREAD

**Issue by WallysonRomeiro** [grafana/helm-charts#3308]
When I apply this helm with Prometheus set up to false the cluster don't show on Grafana Cloud, but the Chart show "deployed". At Cluster already there are Prometheus CRDs

```
  helm repo update &&
  helm upgrade --install --atomic --timeout 300s grafana-k8s-monitoring grafana/k8s-monitoring \
    --namespace "default" --create-namespace --values - <<EOF
cluster:
  name: my-cluster
externalServices:
  prometheus:
    host: https://prometheus-prod-13-prod-us-east-0.grafana.net
    basicAuth:
      username: "REDACTED"
      password: REDACTED
  loki:
    host: https://logs-prod-006.grafana.net
    basicAuth:
      username: "REDACTED"
      password: REDACTED
  tempo:
    host: https://tempo-prod-04-prod-us-east-0.grafana.net:443
    basicAuth:
      username: "REDACTED"
      password: REDACTED
metrics:
  enabled: true
  cost:
    enabled: true
  node-exporter:
    enabled: true
logs:
  enabled: true
  pod_logs:
    enabled: true
  cluster_events:
    enabled: true
traces:
  enabled: true
receivers:
  grpc:
    enabled: true
  http:
    enabled: true
  zipkin:
    enabled: true
opencost:
  enabled: true
  opencost:
    exporter:
      defaultClusterId: my-cluster
    prometheus:
      external:
        url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom
kube-state-metrics:
  enabled: true
prometheus-node-exporter:
  enabled: true
prometheus-operator-crds:
  enabled: true
alloy: {}
alloy-logs: {}
EOF```
```
