### ISSUE TITLE
[tempo] helm parse error on service account labels and annotation

### ISSUE THREAD

**Issue by rbnmk** [grafana/helm-charts#3318]
I am configuring Tempo on AKS with Azure Storage Blob as a backend. For authentication I use Federated (workload) Identity auth. For this I have configured the following in the values.yaml

```yaml
serviceAccount:
  # -- Specifies whether a ServiceAccount should be created
  create: true
  # -- The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name: null
  # -- Image pull secrets for the service account
  imagePullSecrets: []
  # -- Annotations for the service account
  annotations: 
    azure.workload.identity/client-id: "000000-0000-0000-0000"
  # -- Labels for the service account
  labels: 
    azure.workload.identity/use: "true"
  automountServiceAccountToken: true
```

I have added the annotations and labels to work with Federated Auth. but now I get the following error:
`##[error]Error: UPGRADE FAILED: YAML parse error on tempo/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 34: mapping values are not allowed in this context`

I noticed that I do not get this error when running helm upgrade from my computer, I only get the error when running helm upgrade in Azure DevOps pipelines.

output of helm version, which is the same version I am explicitly installing in Azure DevOps pipelines:
`version.BuildInfo{Version:"v3.11.3", GitCommit:"323249351482b3bbfc9f5004f65d400aa70f9ae7", GitTreeState:"clean", GoVersion:"go1.20.3"}`

While researching I found out there might be related issues for other parts that were already fixed, could it be the same?

source: https://github.com/grafana/helm-charts/pull/767
