### ISSUE TITLE
Alerts ConfigMap: json: cannot unmarshal number into Go struct field Config.chatid of type string

### ISSUE THREAD

**Issue by micheljung** [grafana/helm-charts#3322]
My `values.yaml`:
```
  sidecar:
    alerts:
      enabled: true
      searchNamespace: ALL
```

My `alerting.yaml`:

```yaml
apiVersion: 1
contactPoints:
  - orgId: 1
    name: Example
    receivers:
      - uid: cdyl2bf991y4hd
        type: telegram
        settings:
          bottoken: "${telegram_bot_token}"
          chatid: "${telegram_chat_id}"
          disable_notification: false
          disable_web_page_preview: false
          protect_content: false
        disableResolveMessage: false
```

Which results in this ConfigMap:

```
Name:         example-alerting                         
Namespace:    k8s-monitoring                                      
Labels:       grafana_alert=1                                     
Annotations:  <none>                                              
                                                                  
Data                                                              
====                                                              
alerting.yaml:                                                    
----                                                              
apiVersion: 1                                                     
contactPoints:                                                    
  - orgId: 1                                                      
    name: Example                                            
    receivers:                                                    
      - uid: cdyl2bf991y4hd                                       
        type: telegram                                            
        settings:                                                 
          bottoken: Redacted
          chatid: -1009999033491                                  
          disable_notification: false                             
          disable_web_page_preview: false                         
          protect_content: false                                  
        disableResolveMessage: false                              
                                                                  
                                                                  
BinaryData                                                        
====                                                              
```

Which fails with:

```
grafana Error: ✗ failure to map file alerting.yaml: failure parsing contact points: Example: failed to validate integration "Example" (UID cdyl2bf991y4hd) of type "telegram": failed to unmarshal
settings: json: cannot unmarshal number into Go struct field Config.chatid of type string                                                                                                                   
```
