### ISSUE TITLE
tempo-distributed traceql queryFrontend missing traceql metrics configuration options

### ISSUE THREAD

**Issue by ovidiubuligan** [grafana/helm-charts#3323]
The following is the templating composition of `config.yaml` for the whole tempo-distributed from the [values file](https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/values.yaml#L1335) :
```yaml
  query_frontend:
    max_outstanding_per_tenant: {{ .Values.queryFrontend.config.max_outstanding_per_tenant }}
    max_retries: {{ .Values.queryFrontend.config.max_retries }}
    search:
      target_bytes_per_job: {{ .Values.queryFrontend.config.search.target_bytes_per_job }}
      concurrent_jobs: {{ .Values.queryFrontend.config.search.concurrent_jobs }}
    trace_by_id:
      query_shards: {{ .Values.queryFrontend.config.trace_by_id.query_shards }}
```
The traceql metrics options can be seen here : https://grafana.com/docs/tempo/latest/operations/traceql-metrics/#set-traceql-metrics-query-options 
Setting traceql query options is not possible . Can the helm template be future ready with by modifying the above templated config with something like the pseudo helm  :
```yaml
  # values file
  queryFrontend:
    extraConfig : 
         metrics:
             concurrent_jobs: 42
          
```
```yaml
  query_frontend:
    max_outstanding_per_tenant: {{ .Values.queryFrontend.config.max_outstanding_per_tenant }}
    max_retries: {{ .Values.queryFrontend.config.max_retries }}
    search:
      target_bytes_per_job: {{ .Values.queryFrontend.config.search.target_bytes_per_job }}
      concurrent_jobs: {{ .Values.queryFrontend.config.search.concurrent_jobs }}
    trace_by_id:
      query_shards: {{ .Values.queryFrontend.config.trace_by_id.query_shards }}
    {{ .Values.queryFrontend.extraConfig }}
```
