### ISSUE TITLE
Tempo deployed components do not apply global extraEnv

### ISSUE THREAD

**Issue by rbrady** [grafana/helm-charts#3332]
When deploying Tempo via helm, I want to input global AWS env vars that are applied to all of the deployed components that need to utilize S3.  In the current deployment templates, the extraEnv is required to be set on each component:

```yaml
{{- with .Values.distributor.extraEnv }}
env:
  {{- toYaml . | nindent 12 }}
{{- end }}
```

When trying to deploy with helm, I end up having to use multiple extraEnv blocks for the same information:

```yaml
    querier:
      extraEnv:
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: /path/to/serviceaccount/token
        - name: AWS_DEFAULT_REGION
          value: us-gov-west-1
        - name: AWS_REGION
          value: us-gov-west-1
        - name: AWS_USE_FIPS_ENDPOINT
          value: "true"
        - name: AWS_ROLE_ARN
          value: <ARN Value>
    
    distributor:
      extraEnv:
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: /path/to/serviceaccount/token
        - name: AWS_DEFAULT_REGION
          value: us-gov-west-1
        - name: AWS_REGION
          value: us-gov-west-1
        - name: AWS_USE_FIPS_ENDPOINT
          value: "true"
        - name: AWS_ROLE_ARN
          value:  <ARN Value>
```

Mimir uses a different pattern, where it provides a way to apply the global extraEnv to deployed components:

```yaml
{{- if or .Values.global.extraEnv .Values.distributor.env }}
env:
  {{- with .Values.global.extraEnv }}
    {{- toYaml . | nindent 12 }}
  {{- end }}
  {{- with .Values.distributor.env }}
    {{- toYaml . | nindent 12 }}
  {{- end }}
```

Changing Tempo deployment templates to match the pattern in the Mimir would improve the deployment experience.
