### ISSUE TITLE
getting error when trying to add values to the garfana.ini sections

### ISSUE THREAD

**Issue by Daxcor69** [grafana/helm-charts#335]
```
grafana.ini:
    server:
      root_url: 'https://college.net'
      enable_gzip: true
    auth:
      azuread:
        allow_sign_up: false
      generic_oauth:
        allow_sign_up: false
      github:
        allow_sign_up: false
      gitllab:
        allow_sign_up: false
      google:
        allow_sign_up: false
      grafana_com:
        allow_sign_up: false
      grafananet:
        allow_sign_up: false
      ldap:
        allow_sign_up: false
      okta:
        allow_sign_up: false
      proxy:
        allow_sign_up: false
        enable_login_token: true
        enabled: true
        header_name: 'X-WEBAUTH-USER'
        header_property: 'username'
```
This is the error I get:

```
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(ConfigMap): unknown field "enable_login_token" in io.k8s.api.core.v1.ConfigMap, ValidationError(ConfigMap): unknown field "enabled" in io.k8s.api.core.v1.ConfigMap, ValidationError(ConfigMap): unknown field "header_name" in io.k8s.api.core.v1.ConfigMap, ValidationError(ConfigMap): unknown field "header_property" in io.k8s.api.core.v1.ConfigMap]```

Thanks.
Brad
