### ISSUE TITLE
Import folder with dashboards

### ISSUE THREAD

**Issue by fatsolko** [grafana/helm-charts#3371]
I use Grafana chart, there is a folder with dashboards with the structure on.
![Image](https://github.com/user-attachments/assets/2111bcb4-5daa-4a4b-933c-5c7e2ccaad92)
I need these dashboards to be scattered in Grafana UI also in folders automaticaly
![Image](https://github.com/user-attachments/assets/703f9376-88c2-406c-b1cb-bf19fe61b620)
Now I do it manually by adding the file path to each dashboard.
```
dashboardProviders:
  games-provider.yaml:
    apiVersion: 1
    providers:
      - name: 'games'
        orgId: 1
        folder: 'Games'
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/games

dashboards:
  games:
    custom-dashboard:
      file: dashboards/games/custom-dashboard1.json
    custom-dashboard2:
      file: dashboards/games/custom-dashboard2.json
```
Is it possible to implement this, if so, how?
