### ISSUE TITLE
Enable multi login option in Grafana UI [serviceaccount, okta]

### ISSUE THREAD

**Issue by nitishy** [grafana/helm-charts#3387]
Hi Team, 
Current setup: In our grafana, we are using okta to log in using 
``` auth.okta:
      name: Okta
      icon: okta
      enabled: true
      allow_sign_up: true
```
And people can log in using Okta.

Use case: We want to enable login to Grafana UI using a serviceaccount as well.
Things I tried: 
```
auth:
      oauth_auto_login: false
 and also added 
auth.basic:
      enabled: true
auth:
      disable_login_form: true
      oauth_auto_login: true
      disable_signout_menu: false
      oauth_allow_insecure_email_lookup: true
```

I am following this document: https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/#configuring-multiple-identity-providers

Problem: I am still unable to enable the option to log in with serviceaccount or a simple username/password, the only option I get is the okta one. 
Please help, as I want user's to be able to log in via serviceaccount also.
