### ISSUE TITLE
Bloom Filter Support Issue in Loki Distributed Helm Chart

### ISSUE THREAD

**Issue by leehosu** [grafana/helm-charts#3403]
I first upgraded the Loki image version to 3.2.1:

```
loki:
  image:
    tag: 3.2.1
```

Then, based on the [official documentation](https://grafana.com/docs/loki/latest/operations/query-acceleration-blooms/), I added the following configuration:

```
limits_config:
  bloom_creation_enabled: true
  bloom_split_series_keyspace_by: 1024
  bloom_gateway_enable_filtering: true

..

structuredConfig:
  bloom_build:
    enabled: true
    planner:
      planning_interval: 10m
    builder:
      planner_address: bloom-planner.<namespace>.svc.cluster.local:9095

  bloom_gateway:
    enabled: true
    client:
      addresses: dnssrvnoa+_bloom-gateway-grpc._tcp.bloom-gateway-headless.<namespace>.svc.cluster.local
```

However, no resources related to Bloom were created.

It seems that the Helm chart in [grafana/loki](https://github.com/grafana/loki/tree/main/production/helm/loki) does support Bloom filters, but is this feature still unsupported in the grafana/helm-charts loki-distributed chart?
