### ISSUE TITLE
TempoQuery Startup

### ISSUE THREAD

**Issue by trevatk** [grafana/helm-charts#3417]
TempoQuery is failing to start when enabled in helm chart with most recent version 1.13.0. Never looked at the source code for tempoQuery not sure if an argument would fix? But figured without supporting documentation it should not be released? 

````
flag provided but not defined: -query.base-path
Usage of /tempo-query:
  -config string
        A path to the plugin's configuration file
```

submitted a PR to revert breaking jump. 
https://github.com/grafana/helm-charts/pull/3416

**Comment by paul-at-cybr** [comment]
+1 to this issue, also observing it here.

**Comment by jkleinlercher** [comment]
+1 also from my side

**Comment by zet694** [comment]
Hey! Any updates about this problem? I have same problem in 1.16.0 (chart: tempo, version: "1.16.0")

**Comment by lukaszraczylo** [comment]
Patched it with kustomization:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempo
spec:
  template:
    spec:
      containers:
        - name: tempo-query
          args: []
```
