### ISSUE TITLE
Loki - setting Values.fullnameOverride breaks memcached and memcachedExporter image path

### ISSUE THREAD

**Issue by digimago** [grafana/helm-charts#3421]
Loki chart ver 6.10.0

When using the fullnameOverride property in a loki distributed deployment where the memcached and/or memcached image paths are specified with a custom registry, the image path is truncated to just the image and tag. This breaks our deployments.

Reproduce:

```
values:
  fullnameOverride: dummycluster
  deploymentMode: Distributed

# your other configuration here

  memcached:
    chunk_cache:
      enabled: true
    image: registry.fqdn/somepath/image:myversion # or: use the full registry, repository, tag definition....same result
  memcachedExporter:
    enabled: true
    image: 
      registry: registry.fqdn/somepath
      repository: image2
      tag: myversion # or: use the single line definition....same result
```

The above should render a Statefulset for Memcached with the image path set to the configured value.

It however sets the image path for memcached to just 'memcached:myversion' instead, ignoring the customized value of "registry.fqdn/somepath/image:myversion".
For memcachedExporter it similarly completely ignores the values supplied by the user.
