### ISSUE TITLE
Loki network policy doesn't make sense

### ISSUE THREAD

**Issue by fabricetriboix** [grafana/helm-charts#343]
The network policy for the Loki chart doesn't make sense. The file is here:
https://github.com/grafana/helm-charts/blob/main/charts/loki/templates/networkpolicy.yaml

This bit is strange:
```
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ template "client.name" . }}
            release: {{ .Release.Name }}
    - ports:
      - port: {{ .Values.service.port }}
```

Unless I am mistaken, it says: Allow pods with the given app and release labels to access any ports, and allow anyone to access port `{{ .Values.service.port }}`.

It looks like an indentation error to me, I would have expected this:
```
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ template "client.name" . }}
            release: {{ .Release.Name }}
      - ports:
        - port: {{ .Values.service.port }}
```

Which would mean: Allow pods with the given app and release labels to access port `{{ .Values.service.port }}`.
