### ISSUE TITLE
tempo-distributed overwriting the image registry fails

### ISSUE THREAD

**Issue by pvickery-ParamountCommerce** [grafana/helm-charts#3455]
I want to use the public ECR image for memcached while still using the tempo image in DockerHub

My values file:
```yaml
memcached:
  enabled: true
  image:
    registry: "public.ecr.aws"
    repository: "docker/library/memcached"
```

I ran this on v1.22.2 and v1.17.0 of tempo-distributed and got the same image (just with a different tag)
```bash
❯ helm template --validate . --values test-values.yaml | grep image: 
          image: docker.io/grafana/tempo:2.5.0
          image: docker.io/grafana/tempo:2.5.0
          image: docker.io/grafana/tempo:2.5.0
          image: docker.io/grafana/tempo:2.5.0
          image: docker.io/grafana/tempo:2.5.0
        - image: docker.io/docker/library/memcached:1.6.29-alpine
 ```

`.Values.global.image.registry` did work, but it applies globally and doesn't help. I also tried with this but `.Values.tempo.image.registry` did not overwrite the global value.
```
global:
  image:
    registry: public.ecr.aws
tempo:
  image:
    registry: "docker.io"
```

```bash
❯ helm template . --values test-values.yaml | grep image:          
          image: public.ecr.aws/grafana/tempo:2.6.0
          image: public.ecr.aws/grafana/tempo:2.6.0
          image: public.ecr.aws/grafana/tempo:2.6.0
          image: public.ecr.aws/grafana/tempo:2.6.0
          image: public.ecr.aws/grafana/tempo:2.6.0
        - image: public.ecr.aws/memcached:1.6.29-alpine
```

**Comment by Aaron-ML** [comment]
Also seeing the same behavior on 1.32.1

**Comment by ubcharron** [comment]
I had the same problem after doing the same thing in Loki without issue.

`global.image.registry` overrides everything else (see [_helpers.tpl](https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/templates/_helpers.tpl#L31)), and (unlike Loki), it is explicitly set to "docker.io" in [values.yaml](https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/values.yaml#L4).

Therefore, in order to set a component's registry, you must first undefine `global.image.registry`

```
global:
  image:
    registry: null

memcached:
  enabled: true
  image:
    registry: "public.ecr.aws"
```

(And then you probably need to define `tempo.image.registry` to provide a default value for everything else.)

Personally, I would have expected the per-component values to override the global values.
