### ISSUE TITLE
[tempo-distributed] Rolling update tempo-distributed deployment stucks when replicas is equal worker nodes

### ISSUE THREAD

**Issue by khimick** [grafana/helm-charts#3458]
When deployments replicas is equal worker nodes rolling update can't start update because of anti-affinity rules and using default kubernetes upgrade strategy.
tempo-distributor deployment manifest:
```yaml
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
```
But let say in tempo-querier manifest strategy is hard coded like this:
```yaml
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
```
I think, there is a two way:
- change manifest like tempo-querier
- change template for ability to choose strategy in values by the users.
