### ISSUE TITLE
[tempo-distributed] compactor.replicas value interfere with HPA

### ISSUE THREAD

**Issue by etiennep** [grafana/helm-charts#3476]
Unlike the distributor, the compactor.replicas setting is always set regardless if autoscaling is enabled. This is problematic because when deploying with ArgoCD, ArgoCD is constantly detecting that the application is out of sync. 

A simple fix is to add a conditional to only set the number of replicas in the compactor deployment when autoscaling is disabled.

**Comment by mkutlak** [comment]
Workaround for Argo application definition:
```yaml
ignoreDifferences:
  - group: apps
    kind: Deployment
    name: tempo-compactor
    namespace: tempo
    jsonPointers:
      - /spec/replicas

syncPolicy:
  syncOptions:
    - RespectIgnoreDifferences=true
```
