### ISSUE TITLE
Please explain how to disable not needed receivers/ports/services for tempo

### ISSUE THREAD

**Issue by stenub** [grafana/helm-charts#3495]
Hello,

i want to disable all receivers except the otlp receiver in the grafana tempo helm chart. The tempo documentation recommends to disable all ports that are not needed, so i wanted to do so via the helm chart. This worked until commit d48e722ee854376aace5184df74aa3fb842de18a by setting the values to null like so:

<code>
  receivers:
    jaeger: null
    opencensus: null
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318" 
</code>
<br>
But as i already mentioned, this does not work anymore. Can you please give me another possibility to disable jaeger and opencensus?
Thanks a lot!
Kind Regards!

**Comment by Entriopic** [comment]
Can confirm

For some reason setting opencensus  to null works but jaeger doesn't work

I have tried using it like this:
jaeger: null
opencensus: null

results in:

``
Error: UPGRADE FAILED: template: tempo/templates/service.yaml:45:8: executing "tempo/templates/service.yaml" at <include "tempo.udp" .>: error calling include: template: tempo/templates/_ports.tpl:5:24: executing "tempo.udp" at <.Values.tempo.receivers.jaeger.protocols.thrift_compact>: nil pointer evaluating interface {}.protocols

``


I have tried using jaeger: {} **WHICH DOESN'T WORK**
```
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317" # Standard OTLP gRPC endpoint for Alloy
        http:
          endpoint: "0.0.0.0:4318" # Standard OTLP HTTP endpoint for Alloy
    jaeger: {} # Placeholder to disable Jaeger receiver
    opencensus: null # Disable OpenCensus receiver
```

Which results in this when checking configmap's yaml:
```
    distributor:
      receivers:
            jaeger:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:14250
                thrift_binary:
                  endpoint: 0.0.0.0:6832
                thrift_compact:
                  endpoint: 0.0.0.0:6831
                thrift_http:
                  endpoint: 0.0.0.0:14268
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
```
