### ISSUE TITLE
Tempo-distributed helm values typo in comment

### ISSUE THREAD

**Issue by houserx-jmcc** [grafana/helm-charts#3514]
After struggling through problems stemming from #2802, I believe there was a mistake in one of the final 2 PRs from that issue:

https://github.com/grafana/helm-charts/blob/ecf24564a1d5c89abaa651eec0476ee7f971a176/charts/tempo-distributed/values.yaml#L428

Indicates this structure, which doesn't work (crash loops):

```yml
global_overrides:
  defaults:
    metrics_generator_processors: [service-graphs, span-metrics]
```

 but `shinebayar-g`'s comment at the end does work:

```yml
global_overrides:
    defaults:
        metrics_generator:
            processors: ['service-graphs', 'span-metrics']
```
