### ISSUE TITLE
[tempo-distributed]: Add support for `selector` in `persistence` sections

### ISSUE THREAD

**Issue by peske** [grafana/helm-charts#3518]
It would be nice to be able to enforce generated PVCs to use specific PVs, by supporting `persistence.selector` option. Something like:

```yaml
  persistence:
    enabled: true
    size: 23Gi
    storageClass: local-ssd-storage
    selector:
      matchLabels:
        app: tempo.ingester
```

This is especially useful (and even needed) in infrastructures where persistence is based on locally attached disks and local static provisioner.
