### ISSUE TITLE
extraConfigmapMounts defaultMode

### ISSUE THREAD

**Issue by rlandesman** [grafana/helm-charts#353]
This a feature request; The grafana helm chart should support the `defaultMode` configuration for mounted volumeMounts (see here: https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L82-L87)
For example:
```yaml
extraConfigmapMounts:
  - name: certs-configmap
  ... 
  defaultMode: XXX
```

I have a working workaround by copying my mounted configmap onto an empty volume but it would be great to be able to execute the script inside the configmap directly. Thank you!
