### ISSUE TITLE
[tempo-distributed] Ingester PVC not removed when StatefulSet is scaled down, causing the PV associated with the PVC to linger

### ISSUE THREAD

**Issue by HummingMind** [grafana/helm-charts#3542]
Hello,
I am using the latest tempo-distributed chart v1.31.0. I installed the chart with the following settings:
```
ingester:
  replicas: 2
  persistence:
    enabled: true
    storageClass: name_of_my_storage_class
    size: 100Gi
```

Then I changed the replicas count to 1 and upgarded with the new value.

The second pod was removed, and the StatefulSet is now showing 1/1. The issue is that the PVC for the second part is still around. So, if the PVC is still around, the associated PV is still around and bound to it. That costs money in a public cloud.

Based on the following chart default values:
```
ingester:
  persistentVolumeClaimRetentionPolicy:
    enabled: false
    whenScaled: Retain
    whenDeleted: Retain
```

the PVC should not be retained, since the retention policy is not enabled. Seems like a bug? Or am I misunerstanding something?

Thank you!
