### ISSUE TITLE
[loki] issue upgrading from 6.26.0 to 6.27.0

### ISSUE THREAD

**Issue by lpaturel** [grafana/helm-charts#3572]
New version 6.27.0 seems to add an issue with the labels of the components.

In my chart values, on each component, I add a label called "affinity" with the pattern "_loki-${component}_" for anti-affinity calculation because I also have Mimir and Tempo on my nodes and each one of them having same component names (mimir-distributed and tempp-distributed).

So, with 6.26.0, labels are added correctly and everything seem to work fine.
But with 6.27.0, every component have the same labels with value 'loki-query-scheduler' instead of their own component, which prevent my ingesters (4 of them on 4 nodes) to boot. This issue seems to be located on every single component.

example of component in Helm Chart ->
```
ingester:
  extraArgs: ["-config.expand-env=true"]
  extraEnvFrom:
    - secretRef:
        name: loki-s3-credentials
  nodeSelector:
    nodepool: lgtm-nodepool
  replicas: 4
  maxUnavailable: 1
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              affinity: loki-ingester
          topologyKey: kubernetes.io/hostname
  podLabels:
    affinity: loki-ingester
  resources:
    limits:
      cpu: 5
      memory: 24Gi
    requests:
      cpu: 1250m
      memory: 8Gi
  persistence:
    enabled: true
    claims:
      - name: data
        size: 25Gi
  zoneAwareReplication:
    enabled: false
```

which leads to following result with 6.26.0 ->

![Image](https://github.com/user-attachments/assets/c3f16287-5472-44da-b169-42bf736a84e8)

and with 6.27.0 ->

![Image](https://github.com/user-attachments/assets/b21842b8-4ca8-4d82-84e5-a2d591e61f01)

---

So after reading the templates, there's a diff on the way the labels are calculated with a new **merge between loki.podLabels and ${component}.podLabels** instead of dealing with each of them separately.

![Image](https://github.com/user-attachments/assets/81094442-1b1b-4221-8f46-edc7243b3383)

**Comment by lpaturel** [comment]
done another test with 6.28.0, still the same behavior...
I've modified a bit the podLabels part as following : 
```
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              component-affinity: "true"
          topologyKey: kubernetes.io/hostname
  podLabels:
    component-affinity: "true"
```

and here is the result of the new deployment of the Helm Chart on my Distributor Pod (stuck in Pending state due to anti-affinity): 
```
metadata:
  labels:
    distributor_affinity: "true"
    index_gateway_affinity: "true"
    ingester_affinity: "true"
    querier_affinity: "true"
    query_frontend_affinity: "true"
    query_scheduler-affinity: "true"
```

It looks like that podLabels are merging with the whole chart instead of the one dedicated to each component
