### ISSUE TITLE
secret is being mounted as emptyDir{} via helm

### ISSUE THREAD

**Issue by zhajili1991** [grafana/helm-charts#3579]
Hello everyone, 

I created a secret certificate manually via Kubectl containing the **tls.crt and tls.key** and then wanted to mount it to Grafana via values.yaml file. But when I do the helm template I see that it mounts like below with emptyDir {}

```
      volumes:
        - name: config
          configMap:
            name: bguliyev-grafana
        - name: storage
          persistentVolumeClaim:
            claimName: bguliyev-grafana
        - name: grafana-tls-secret
          emptyDir: {}
---
```

My values.yaml is like below.

```
extraVolumeMounts:
  - name: grafana-tls-secret
    mountPath: /etc/grafana/certs
    readOnly: true
  # - name: extra-volume-1
  #   mountPath: /mnt/volume1
  #   readOnly: true
  # - name: grafana-secrets
  #   mountPath: /mnt/volume2

## Additional Grafana server volumes
extraVolumes:
  - name: grafana-tls-secret
    secret:
      defaultMode: 420
      secretName: grafana-tls-secret

```
