### ISSUE TITLE
Gateway API: no healthy upstream

### ISSUE THREAD

**Issue by starteNCS** [grafana/helm-charts#3581]
Hello everyone,

I am hosting Grafana through the kube-prometheus-stack and want to expose it through the kubernetes gateway API using Azures Application Gateway for Containers.

But when routing to the url, I encounter an "no healthy upstream" error. When I replace the backend service with any other service, the routing works.
On the other hand, when spinning up a debugging container in my alb-controller and trying to connect to grafana and do a health check, everything seems fine.
Has anyone encountered this error and can help me?

**Comment by anisf** [comment]
@starteNCS 

Try to configure the health check. The health check expect a 2xx http response.
Grafana is redirecting to /login (i.e. 302 http reponse)

This is what i did on GKE (the key here is the `requestPath`: 

```yaml
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: grafana-hc-config
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 3
    healthyThreshold: 1
    unhealthyThreshold: 2
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_SERVING_PORT
        requestPath: /api/health
  targetRef:
    group: ""
    kind: Service
    name: grafana
```

I faced the same issue recently on keycloak

How to determine the `requestPath` ? Well, I usually use the one used in the `readinessProbe`

**Comment by starteNCS** [comment]
@anisf Firstly, thanks for your response.

I already tried to create a custom health check policy, but it did not work. But if I can make up some time in the next days, I will try with these values

**Comment by starteNCS** [comment]
I've re-tried it with a custom health check policy, but sadly still no success.
Maybe you @anisf can spot something wrong with my policy:

```yaml
apiVersion: alb.networking.azure.io/v1
kind: HealthCheckPolicy
metadata:
  name: grafana-health-check-policy
  namespace: {{.Release.Namespace}}
spec:
  targetRef:
    group: ""
    kind: Service
    name: centralhub-developer-tools-grafana
    namespace: monitoring
  default:
    interval: 10s
    timeout: 3s
    healthyThreshold: 1
    unhealthyThreshold: 2
    port: 80
    http:
      host: grafana.{{ .Values.hostname }}
      path: /api/health
      match:
        statusCodes:
          - start: 200
            end: 399
    useTLS: false
```

On another note: Does somebody know how to check if this health check is marked as "healthy"?

**Comment by anisf** [comment]
Try to see if : 
- the HealthCheckPolicy is created in the same namespace than the HTTPRoute
- the rendered host matches the grafana service
- the port 80 matches the grafana service port or the grafana pod port (mine is 3000)

Also, try:
- to remove the host (let it by default)
- to remove the port (let it by default)

Try this : 
```yaml
apiVersion: alb.networking.azure.io/v1
kind: HealthCheckPolicy
metadata:
  name: grafana-health-check-policy
  namespace: {{.Release.Namespace}}
spec:
  targetRef:
    group: ""
    kind: Service
    name: centralhub-developer-tools-grafana
    namespace: {{.Release.Namespace}}
  default:
    http:
      path: /api/health
    useTLS: false
```

or even to remove the `spec.targetRef.namespace` completely as it should search for the service in the same namespace
