### ISSUE TITLE
using env variable via envFromSecret in datasource does not work

### ISSUE THREAD

**Issue by kgoktas** [grafana/helm-charts#3583]
i am trying to pass github tone to infitinity csv plugin datasource although the env variable exists in grafana pod, grafana pod is not replacing the secure value

values.yaml
```
sidecar:
  dashboards:
    enabled: true
  datasources:
    enabled: true
  plugins:
    - https://grafana.com/api/plugins/yesoreyeram-infinity-datasource/versions/2.12.2/download;yesoreyeram-infinity-datasource
  envFromSecret: grafana-secrets
```

datasource.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasource-infinity
  labels:
    grafana_datasource: 'true'
stringData:
  yesoreyeram-infinity.yaml: |-
    apiVersion: 1
    datasources:
      - name: "yesoreyeram-infinity-datasource"
        type: "yesoreyeram-infinity-datasource"
        uid: "yesoreyeram-infinity-datasource"
        url: "https://xxxxxxx/blabla.csv"
        basicAuth: false
        basicAuthUser: ""
        isDefault: false
        jsonData:
          global_queries: []
          secureQueryName1: "token"
        secureJsonData:
          secureQueryValue1: $GITHUB_TOKEN
        readOnly: false
        apiVersion: ""
```

grafana-secrets.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
type: Opaque
data:
 GITHUB_TOKEN: <base64>
```
