### ISSUE TITLE
[grafana] Incorrect HPA scaleTargetRef creation for StatefulSets

### ISSUE THREAD

**Issue by Ryan-Brice** [grafana/helm-charts#3586]
The [Grafana](https://github.com/grafana/helm-charts/tree/2049e69629b1f9d8bfda37852de393ee6f403005/charts/grafana) chart does not generate the correct `HorizontalPodAutoscaler` `spec.scaleTargetRef.kind` when the `useStatefulSet` value is `true`, and `persistence.type` is set as `pvc`.

## Example values:

```yaml
useStatefulSet: true
persistence:
  enabled: true
  type: pvc
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
```

## Generated Output

```yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
    helm.sh/chart: grafana-8.10.1
    app.kubernetes.io/instance: grafana
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grafana
  minReplicas: 1
  maxReplicas: 5
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
```

## Expected Output

```yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
    helm.sh/chart: grafana-8.10.1
    app.kubernetes.io/instance: grafana
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: grafana
  minReplicas: 1
  maxReplicas: 5
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
```
