### ISSUE TITLE
How to use command option to run custom scripts?

### ISSUE THREAD

**Issue by ashvjits** [grafana/helm-charts#360]
As I understand, command option is given to run user defined commands at container startup. 
I want to update /etc/resolv.conf for our internal hostname resolution.
Is going via command option the right choice? If yes, how can we do it?

**Comment by ashvjits** [comment]
Answering my own question here:
While you can't run scripts unless you build your own docker, for changing files which need root privileges, you can start grafana as root and then execute custom commands by using 'command' option.

Example: 
```
securityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0
command:
  - "/bin/sh"
  - "-c"
  - "echo 'nameserver a.x.y.z' >> /etc/resolv.conf && /run.sh"
  ```
