### ISSUE TITLE
Slack Contact Point Fails to Parse notification template file

### ISSUE THREAD

**Issue by shashidhar087** [grafana/helm-charts#3612]
I’m encountering an issue while configuring a Slack contact point in Grafana using an ExternalSecret. Grafana fails to start due to a YAML parsing error in contactpoint_slack.yaml, specifically regarding the template "slack.title" reference. The error message indicates an invalid map key:

Would you be able to provide any guidance on how to solve this issue ?  Any insights or suggestions would be greatly appreciated!

Thank you for your time and help.

**Grafana logs error:**

`Failed to start grafana. error: failure to parse file contactpoint_slack.yaml: yaml: invalid map key: map[interface {}]interface {}{"template \"slack.title\" .":interface {}(nil)}
failure to parse file contactpoint_slack.yaml: yaml: invalid map key: map[interface {}]interface {}{"template \"slack.title\" .":interface {}(nil)}`

**contactpoint_slack.yaml** file looks like

```
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-contactpoint-slack
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.external_secret.service_account }}
    kind: SecretStore
  target:
    name: grafana-contactpoint-slack
    template:
      data:
        contactpoint_slack.yaml: |
          apiVersion: 1
          contactPoints:
            - orgId: 1
              name: Slack
              receivers:
                - uid: slack
                  type: slack
                  disableResolveMessage: false
                  settings:
                    url: {{ printf "{{ .password | toString }}" }}
                    title: {{ printf "{{`{{ template \"slack.title\" . }}`}}" }}
                    text:  {{ printf "{{`{{ template \"slack.message\" . }}`}}" }}
                    

  data:
  - secretKey: password
    remoteRef:
      key: {{ .Values.external_secret.aws_secret }}
      property: SLACK_HOOK
```

**notification_template.yaml**

```---
kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-notification-template-config
data:
  notification_template.yaml: |
    apiVersion: 1
    templates:
      - orgId: 1
        name: slack.title
        template: |
          {{ `
          {{ define "slack.title" }}
          {{ .CommonLabels.alertname -}}
          {{ end }}
          ` }}
      - orgId: 1
        name: slack.message
        template: |
          {{ `
          {{ define "slack.message" }}
            
             {{ if .Alerts.Firing -}}
              🔥 Firing:
              {{- range .Alerts.Firing -}}
                {{ if gt (len .Annotations) 0 }}
                  *Summary*: {{ .Annotations.summary}}
                  Labels: 
                  {{ range .Labels.SortedPairs }}
                   {{ if or (eq .Name "Environment") (eq .Name "Region") }} 
                     • {{ .Name }}: {{ .Value }}
                    {{ end }}
                  {{ end }}
                {{ end }}
              {{ end }}
            {{ end }}
            {{ if .Alerts.Resolved -}}
              ✔ Resolved:
              {{- range .Alerts.Resolved -}}
                {{ if gt (len .Annotations) 0 }}
                  *Summary*: {{ .Annotations.summary}}
                  Labels: 
                  {{ range .Labels.SortedPairs }}
                    {{ if or (eq .Name "Environment") (eq .Name "Region") }}
                      • {{ .Name }}: {{ .Value }}
                    {{ end }}
                  {{ end }}
                {{ end }}
              {{ end }}
            {{ end }}
          {{ end }}
          ` }}
