### ISSUE TITLE
loki-stack chart, not possible to globally set registry

### ISSUE THREAD

**Issue by patrijua** [grafana/helm-charts#3619]
values.yaml:

```
global:
  image:
    registry: xxx.com
  imageRegistry: xxx.com
```

`helm template grafana/loki-stack  -f values.yaml` command results into:

```
image: "xxx.com/grafana/promtail:2.9.3"
image: "grafana/loki:2.6.1"
image: "bats/bats:1.8.2"
```

Each of those images should respect the global setting. For "loki" chart it should be `global.image.registry` but neither one works.

https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml#L10
