### ISSUE TITLE
[tempo-distributed] "range specified by start and end exceeds..." error when querying beyond 7 days

### ISSUE THREAD

**Issue by diegocejasprieto** [grafana/helm-charts#3623]
Hello, I have deployed grafana tempo using Helm (tempo-distributed chart, version: **1.31.0**) and added it as datasource in Grafana. Also have persistance on PVC (as I'm running the stack on EKS) and S3 as backend storage (traces are uploaded correctly)
Issue comes up when I try to search for traces beyond **7 days** (see screenshot)

I looked for different configurations for queryFrontend and querier to no avail. I set max_duration: 720h (30 days) and still not working.
 What could be wrong or where else should I take a look at?

![Image](https://github.com/user-attachments/assets/98b9f31f-b91c-4966-b990-1486e73cf982)

This is my config both for querier and queryFrontend
```
querier:
  replicas: 1
  hostAliases: []
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    behavior: {}
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: null
  image:
    registry: null
    pullSecrets: []
    repository: null
    tag: null
  priorityClassName: null
  podLabels: {}
  podAnnotations: {}
  extraArgs: []
  extraEnv: []
  extraEnvFrom: []
  resources: {}
  terminationGracePeriodSeconds: 30
  topologySpreadConstraints: |
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          {{- include "tempo.selectorLabels" (dict "ctx" . "component" "querier") | nindent 6 }}
  affinity: |
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nera/workload-type
                operator: In
                values:
                  - karpenter
  maxUnavailable: 1
  tolerations:
    - key: karpenter
      value: 'true'
      effect: NoSchedule
  extraVolumeMounts: []
  extraVolumes: []
  config:
    frontend_worker:
      grpc_client_config: {}
    trace_by_id:
      query_timeout: 10s
    search:
      query_timeout: 30s
      prefer_self: 10
      external_hedge_requests_at: 8s
      external_hedge_requests_up_to: 2
      external_endpoints: []
      external_backend: ''
      google_cloud_run: {}
    max_concurrent_queries: 20
  service:
    annotations: {}
  appProtocol:
    grpc: null


queryFrontend:
  query:
    enabled: false
    image:
      registry: null
      pullSecrets: []
      repository: grafana/tempo-query
      tag: null
    resources: {}
    extraArgs: []
    extraEnv: []
    extraEnvFrom: []
    extraVolumeMounts: []
    extraVolumes: []
    config: |
      backend: 127.0.0.1:3100
  replicas: 1
  hostAliases: []
  config:
    max_outstanding_per_tenant: 2000
    max_retries: 2
    search:
      concurrent_jobs: 1000
      target_bytes_per_job: 104857600
    trace_by_id:
      query_shards: 50
    metrics:
      concurrent_jobs: 1000
      target_bytes_per_job: 104857600
      max_duration: 720h
      query_backend_after: 30m
      interval: 5m
      duration_slo: 0s
      throughput_bytes_slo: 0
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    behavior: {}
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: null
  image:
    registry: null
    pullSecrets: []
    repository: null
    tag: null
  service:
    port: 16686
    annotations: {}
    labels: {}
    type: ClusterIP
    loadBalancerIP: ''
    loadBalancerSourceRanges: []
  serviceDiscovery:
    annotations: {}
    labels: {}
  ingress:
    enabled: false
    annotations: {}
    hosts:
      - host: query.tempo.example.com
        paths:
          - path: /
    tls:
      - secretName: tempo-query-tls
        hosts:
          - query.tempo.example.com
  priorityClassName: null
  podLabels: {}
  podAnnotations: {}
  extraArgs: []
  extraEnv: []
  extraEnvFrom: []
  resources: {}
  terminationGracePeriodSeconds: 30
  topologySpreadConstraints: |
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          {{- include "tempo.selectorLabels" (dict "ctx" . "component" "query-frontend") | nindent 6 }}
  affinity: |
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nera/workload-type
                operator: In
                values:
                  - karpenter
  maxUnavailable: 1
  tolerations:
    - key: karpenter
      value: 'true'
      effect: NoSchedule
  extraVolumeMounts: []
  extraVolumes: []
  appProtocol:
    grpc: null


```
