### ISSUE TITLE
[Grafana] Sidecar labelValue wrong type for value

### ISSUE THREAD

**Issue by robgordon89** [grafana/helm-charts#3628]
Since the latest release 8.11.1 there seems to be an issue with quoting. 

Given the following values 

```
sidecar:
  alerts:
    enabled: true
    label: grafana_alert
    searchNamespace: monitoring
    resource: configmap
    labelValue: 1
```

labelValue is float64 but its expected to be a string, it was previously quoted in the chart.

ref: https://github.com/grafana/helm-charts/pull/3585

To resolve this its easy to add quotes but thought i would open this issue so others can resolve it 👍
