### ISSUE TITLE
[tempo-metrics_generator] cannot configure for traces drilldown

### ISSUE THREAD

**Issue by jkruke** [grafana/helm-charts#3640]
**Problem**

To have a working Traces Drilldown, the [documentation](https://grafana.com/docs/grafana/latest/explore/simplified-exploration/traces/access/) instructs:
> Traces Drilldown requires Grafana Tempo 2.6 or later with [TraceQL metrics configured](https://grafana.com/docs/tempo/latest/operations/traceql-metrics/).

For this, it's not only necessary to configure this:
```
tempo:
  overrides:
    defaults:
      metrics_generator:
        processors:
          - local-blocks
```
, but it is also required to configure storages (as mentioned in https://github.com/grafana/tempo/issues/3401):
```
metrics_generator:
  storage:
    path: /var/tempo/generator/wal
  traces_storage:
    path: /var/tempo/generator/traces
```

**Analysis**

This is currently not possible because the `metrics_generator` section is generated config file only containing options for storage path and remote_write:

https://github.com/grafana/helm-charts/blob/f02f23bb3d4fea77cd1a33eef8452e296ccea0d9/charts/tempo/values.yaml#L196-L200

**Solution Suggestion**

Since there are plenty more possible options to configure the metrics_generator, my advice is to grant more flexibility to the chart user. Compared to other sections (i.e. compactor, ingester, server, ...), the section should be created sth like this:
```
      {{- if .Values.tempo.metricsGenerator.enabled }}
    metrics_generator:
      {{- toYaml .Values.tempo.metricsGenerator| nindent 6 }}
      {{- end }}
```
