### ISSUE TITLE
tempo-query doesn't return anything when forwarding jaeger-ui or jaeger-metrics port

### ISSUE THREAD

**Issue by v0lumehi** [grafana/helm-charts#3642]
Hi. We're deploying tempo in monolithic mode using the tempo helm chart. There's a service monitor in the helm chart that's consistently red because Prometheus can't scrape the jaeger-metrics endpoint. When I forward the port locally and try to access the metrics endpoint, I encounter a timeout.

**Comment by alexkorotysh** [comment]
Has the same

**Comment by alexkorotysh** [comment]
@v0lumehi https://github.com/grafana/helm-charts/blob/main/charts/tempo/templates/_ports.tpl#L30-L34

**Comment by v0lumehi** [comment]
> @v0lumehi https://github.com/grafana/helm-charts/blob/main/charts/tempo/templates/_ports.tpl#L30-L34
> 

I could disable tempo query entirely, but that doesn't fix the issue the app/helm chart very likely has

**Comment by MeirP-3** [comment]
Sharing this here in case it helps anyone.

The tempo-query container **is not required** to connect grafana to tempo.

**Chart version:** 1.23.2

Configure `tempoQuery.enabled: false`, but you can still use the ingress configuration to expose several endpoints.
In my case, I exposed the API endpoint (search, query, etc.) for grafana, and OTLP http endpoint (send traces) for my application.

My working values setup is as follows:
```yaml
... other values ...
tempoQuery:
  enabled: false
  service:
    port: 3200
  # tempo-query container is not needed.
  # However, the ingress config is usable to expose tempo.
  ingress:
    enabled: true
    ingressClassName: <ingress-class-name>
    annotations:
      ...relevant annotations...
    # this is the path for the query API
    path: /api/
    hosts: [ <host-name> ]
    extraPaths:
    - path: /v1/traces # OTLP http endpoint
      pathType: Prefix
      backend:
        service:
          name: tempo
          port:
            number: 4318
```
