### ISSUE TITLE
TempoQuery helm chart invalid configuration

### ISSUE THREAD

**Issue by dontepanlin** [grafana/helm-charts#3660]
TempoQuery from helm chart not work from the box. 
Used default values with tempoQuery enabled = True and enabled Ingres.  Got Bad Gateway
```tempoQuery:
  repository: grafana/tempo-query
  tag: null
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## Refers to: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName

  # -- if False the tempo-query container is not deployed
  enabled: true

  service:
    port: 16686

  ingress:
    enabled: true
    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    # ingressClassName: nginx
    # Values can be templated
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    labels: {}
    path: /
```
In pod of tempoQuery got "Server starts serving" address=0.0.0.0:7777" Why this port if i set 16686 in values.yam

**Comment by meesk** [comment]
Have you figured this out? Currently struggling with the same problem, seems like setting the port to '7777' manually is not working either.

**Comment by bstrdsmkr** [comment]
I'm running into the same issue. I'm still digging, but I did find this: https://github.com/grafana/tempo/blob/dfc430c16bdb3000f6728355a14b62b7325871a8/docs/sources/tempo/release-notes/v2-6.md?plain=1#L250

So I think the 7777 isn't the UI port but a GRPC API.

**Comment by bstrdsmkr** [comment]
Ok, If I'm reading this right, I think the chart and docs need to be updated as they no longer provide a Jaeger UI as part of tempo-query. See `Step 5.` of the PR referenced in the changelog above: https://github.com/grafana/tempo/pull/3840

> Run Jaeger and point to tempo-query.

So it seems now you need a separate instance of Jaeger (which is no longer included in the chart) in order to access the UI

**Comment by Lukiido** [comment]
How did you get grafana to connect to it? I have Grafana in another cluster and it can see the tempo instance, but when I use this ingress it gives 502 as it defaults to the jaeger port... I tried to force 3100 but argo wont sync it when I do.

**Comment by zorek187** [comment]
Hey there! Managed to fix the issue by passing "address: 16686" in values.queryFrontend.query.config .
Found out that the new TempoQuery implementation [expects this variable](https://github.com/grafana/tempo/blob/f7ecf8caf7ef23efc4ac3ac6e37577da85e068af/cmd/tempo-query/tempo/config.go#L28), but isn't defined in the chart.

Also had to override tempo-query container args to pass "-config /conf/tempo-query.yaml" instead of "-config /conf/tempo.yaml" , no idea why this ["fix"](https://github.com/grafana/helm-charts/commit/70d52023f80dc1f4cbc5d4155401b9b2dcfebc18) changed the config file name.

**Comment by MeirP-3** [comment]
Sharing this here in case it helps anyone.

The tempo-query container **is not required** to connect grafana to tempo.

**Chart version:** 1.23.2

Configure `tempoQuery.enabled: false`, but you can still use the ingress configuration to expose several endpoints.
In my case, I exposed the API endpoint (search, query, etc.) for grafana, and OTLP http endpoint (send traces) for my application.

My working values setup is as follows:
```yaml
... other values ...
tempoQuery:
  enabled: false
  service:
    port: 3200
  # tempo-query container is not needed.
  # However, the ingress config is usable to expose tempo.
  ingress:
    enabled: true
    ingressClassName: <ingress-class-name>
    annotations:
      ...relevant annotations...
    # this is the path for the query API
    path: /api/
    hosts: [ <host-name> ]
    extraPaths:
    - path: /v1/traces # OTLP http endpoint
      pathType: Prefix
      backend:
        service:
          name: tempo
          port:
            number: 4318
```
