### ISSUE TITLE
How to send traces from grafana-sampling to cloud OTLP gateway behind VPC Endpoint

### ISSUE THREAD

**Issue by wojciechgrabarz** [grafana/helm-charts#3710]
Hello.

I've been sending traces to Grafana Cloud OTLP gateway through an AWS VPC Endpoint by specifying the VPC endpoint DNS in values.yaml like this:
```
(...)
destinations:
  - name: otlp-grafana-cloud
    type: otlp
    url: https://${otlp_vpc_endpoint}/otlp
    protocol: http
(...)
```
This works ok, but now I want to introduce tail-sampling.
I am using this example:
https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring/docs/examples/features/application-observability/tail-sampling
to implement it but looks like the chart does not let me use anything but gRPC exporter to Tempo via the env var `GRAFANA_CLOUD_TEMPO_ENDPOINT`.

Is there a way to override it somehow? Like through `extraConfig` or similar mechanism?
