### ISSUE TITLE
Explicit download URLs in Chart Manifest causes Artifactory to malfunction and not cache assests

### ISSUE THREAD

**Issue by thameezb** [grafana/helm-charts#372]
Looking at the grafana helm-chart index.yaml file, we see that download URLs are explicitly set to download from github.
E.g
```yaml
 urls:
    - https://github.com/grafana/helm-charts/releases/download/fluent-bit-2.1.0/fluent-bit-2.1.0.tgz
```
in 
```yaml
  - apiVersion: v1
    appVersion: v2.0.0
    created: "2020-12-10T00:03:56.321725129Z"
    description: Uses fluent-bit Loki go plugin for gathering logs and sending them
      to Loki
    digest: e78a4f6c38ee54acb7033b1bc22d7457b68ddcfd4c27228527782d3c81b45af9
    home: https://grafana.com/loki
    icon: https://raw.githubusercontent.com/grafana/loki/master/docs/sources/logo.png
    kubeVersion: ^1.10.0-0
    maintainers:
    - email: lokiproject@googlegroups.com
      name: Loki Maintainers
    name: fluent-bit
    sources:
    - https://github.com/grafana/loki
    urls:
    - https://github.com/grafana/helm-charts/releases/download/fluent-bit-2.1.0/fluent-bit-2.1.0.tgz
    version: 2.1.0
```

This means that when used as a remote helm repository in artifactory, the `index.yaml` is cached, but none of the artifacts. This creates an issue when machines which do not have access to the internet (but do have access to artifactory) attempts to install the chart in a k8s cluster. 

As an example of a working chart where artifacts are cached (https://dandydeveloper.github.io/charts/index.yaml)
```
  - apiVersion: v1
    appVersion: 6.0.7
    created: "2021-03-31T04:44:32.511095223Z"
    description: This Helm chart provides a highly available Redis implementation with a master/slave configuration and uses Sentinel sidecars for failover management
    digest: 64ecc31f8d4d8dcffc3a67004a89e0d4ce5f5f3b1dc3edf3c8f09a7698986a5d
    home: http://redis.io/
    icon: https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Redis_Logo.svg/1200px-Redis_Logo.svg.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - email: salimsalaues@gmail.com
      name: ssalaues
    - email: aaron.layfield@gmail.com
      name: dandydeveloper
    name: redis-ha
    sources:
    - https://redis.io/download
    - https://github.com/DandyDeveloper/charts/blob/master/charts/redis-ha
    - https://github.com/oliver006/redis_exporter
    urls:
    - redis-ha-4.12.9.tgz
    version: 4.12.9
```
note the URL contains just the path to the tarball and not a full URL. 

Beyond the explicit URLs in the different indexes, the config blocks seems to be identical
