### ISSUE TITLE
Can't add extraScrapeConfigs

### ISSUE THREAD

**Issue by StarpTech** [grafana/helm-charts#373]
```
helm template --debug loki grafana/loki-stack --set grafana.enabled=true,prometheus.enabled=true,prometheus.alertmanager.persistentVolume.enabled=true,prometheus.server.persistentVolume.enabled=true,loki.persistence.enabled=true,loki.persistence.storageClassName=hcloud-volumes,loki.persistence.size=10Gi -f values.yaml
```

values.yaml
```yml
promtail:
  extraScrapeConfigs: |
    - job_name: traefik
      scrape_interval: 5s
      scheme: http
      metrics_path: '/metrics'
      static_configs:
      - targets: ['traefik.production.svc.cluster.local:9000']
```

results in (have a look at the `|` character)

```yml
...
  - replacement: /var/log/pods/*$1/*.log
    separator: /
    source_labels:
    - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
    - __meta_kubernetes_pod_container_name
    target_label: __path__
|
  - job_name: traefik
    scrape_interval: 5s
    scheme: http
    metrics_path: '/metrics'
    static_configs:
    - targets: ['traefik.production.svc.cluster.local:9000']
```
