### ISSUE TITLE
Expose Tempo over Ngnix Ingress

### ISSUE THREAD

**Issue by sahil-sharma** [grafana/helm-charts#3766]
I am trying to expose Tempo in my K8s cluster via Nginx but it throws `502 Bad Gateway`.
I am using official helm chart.
Below is the snippet from my `values.yaml`:
```
tempoQuery:
  enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - traces.local.io
    path: /
    pathType: Prefix
    backend:
      service:
        name: tempo
        port:
          number: 3200
```

When I add this URL in my grafana as DataSource:
```
- name: Tempo
  type: tempo
  access: proxy
  url: http://traces.local.io:32080
```
My Nginx is exposed via NodePort: HTTP == 32080 and HTTPS == 32443.
Loki, Prometheus and other components work flawlessly.
As of now everything is running in the same cluster so I can use K8s service DNS but I want to expose it via Ingress.

Below are the logs:

*k -n grafana exec -it grafana-8c9df688f-jf985 -- nslookup traces.local.io*
```
Server:		172.17.0.10
Address:	172.17.0.10:53

Name:	traces.local.io
Address: 192.168.56.72
Name:	traces.local.io
Address: 192.168.56.71
Name:	traces.local.io
Address: 192.168.56.74
Name:	traces.local.io
Address: 192.168.56.73
```
*k -n grafana exec -it grafana-8c9df688f-jf985 -- curl http://tempo.tempo:3200/api/search*
```
{"traces":[],"metrics":{"completedJobs":1,"totalJobs":1}}
```
*k -n grafana exec -it grafana-8c9df688f-jf985 -- curl http://traces.local.io:32080/api/search*
```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
I have added the entry in local `/etc/hosts` file and at other places if required.

Is there any document that can be helpful? Or do suggest some ideas or hints. Many thanks!
