### ISSUE TITLE
[loki-distributed] `global.extraEnvFrom` and `global.extraArgs` are missing

### ISSUE THREAD

**Issue by ordovicia** [grafana/helm-charts#3773]
`loki-distributed` Helm chart has `global.extraEnv`, but `global.extraEnvFrom` and `global.extraArgs` are missing.

https://github.com/grafana/helm-charts/blob/e3fec0d9cd9118691623220e6501538b74b9f1f3/charts/tempo-distributed/values.yaml#L19-L21

They can be useful to set the same `spec.containers.envFrom` and `spec.containers.args` across all components.
In my specific case, I need to set the following config to `ingester`, `distributor`, `compactor`, `querier`, and `queryFrontend`.

```yaml
extraEnvFrom:
- configMapRef:
    name: traces # This ConfigMap contains the access info of "traces" bucket
- secretRef:
    name: traces # This Secret contains the credential for accessing "traces" bucket
extraArgs:
- -config.expand-env=true # Enable expanding environment variables injected via the above settings
```
