### ISSUE TITLE
No long configuration values possible in grafana.ini

### ISSUE THREAD

**Issue by czenker** [grafana/helm-charts#378]
**When generating the ConfigMap for grafana.ini, lines longer than 120 chars will be wrapped causing an invalid yaml file.**

Previously, up to version `6.4.4`, the same values where rendered correctly in one line. It seems this is caused by [a recent change](https://github.com/grafana/helm-charts/compare/0c531b7a6c1bca9b9c7e762623e787502acea05b...d919157de0b58d97422063463aa17fd8b084cb1b).

## Example 

```yaml
grafana.ini:
  # ...
  auth.generic_oauth:
    # ...
    role_attribute_path: contains("cognito:groups"[*], 'IAmAdmin') && 'Admin' || length("cognito:groups"[?starts_with(@, 'Team-')]) && 'Editor' || 'Viewer'
```
grafana/grafana 6.7.3 breaks the line at 120 chars and renders this as

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  # ...
data:
  grafana.ini: |
    # ...
    [auth.generic_oauth]
    role_attribute_path = contains("cognito:groups"[*], 'IAmAdmin') && 'Admin' || length("cognito:groups"[?starts_with(@,
  'Team-')]) && 'Editor' || 'Viewer'
```
which leads to 

```bash
Error: YAML parse error on grafana/templates/configmap.yaml: error converting YAML to JSON: yaml: line 50: could not find expected ':'
```
