### ISSUE TITLE
Loki configuration with Minio

### ISSUE THREAD

**Issue by tomerleib** [grafana/helm-charts#393]
Hi,
I'm trying to setup Loki with Minio per [instructions](https://grafana.com/docs/loki/latest/storage/#on-prem-deployment-minio-single-store):
```
storage_config:
  aws:
    s3: http://loki:secret@minio.storage:9000
    s3forcepathstyle: true
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: s3
```

I've created the user `loki` with the permissions to use a specific bucket.
However, when I deploy Loki, it won't work and report the following error:
` 1 validation error(s) found. - minimum field size of 1, ListObjectsV2Input.Bucket.`

Any idea what is missing in the configuration?
