### ISSUE TITLE
the loki-stack chart generate outdated yaml

### ISSUE THREAD

**Issue by longkai** [grafana/helm-charts#403]
Hi.

I am applying the lock-stack chart to my k8s cluster. It seems helm will download the release tag `loki-stack-2.3.1` which seems the current latest tgz file in local cache.

There is an outdated field in promtail [daemonset](https://github.com/grafana/helm-charts/blob/loki-stack-2.3.1/charts/promtail/templates/daemonset.yaml#L92):

```yaml
ports:
- containerPort: {{ .Values.config.server.http_listen_port }}
  name: http-metrics
```

The `protocol` field which [required before k8s 1.20](https://github.com/kubernetes/api/commit/71efbb18d63cd30604981514ac623a6be1d413bb#diff-e07359f4183d8c98bbea2c485e2863da5be7d8348ce3b9dc06c0f32b108c5f84) is missing and will fail to apply using `controler-runtime` go pkg before 1.20.

However, in the main branch, that field is present.

I hope you could issue a new release to resolve the issue.

Thanks.
