### ISSUE TITLE
[loki-distributed] Is there a way to set config.expand-env=true ?

### ISSUE THREAD

**Issue by theophanevie** [grafana/helm-charts#406]
Since 2.1, Loki provide the support of env variable in config file. I want to use to it to set up aws credentials but in order to do this I need config.expand-env to be set to True. Here an exemple of what i want to do :

values.yaml
``` yaml
loki-distributed:
  ingestor:
    extraEnvFrom:
      - secretRef:
          name: loki-secrets
  loki:
    config: |
      ....
      storage_config:
        aws:
          region: ${AWS_DEFAULT_REGION}
          access_key_id: ${AWS_ACCESS_KEY_ID}
          secret_access_key: ${AWS_SECRET_ACCESS_KEY}
          bucketnames: loki-logs
      ....
```

secrets.yaml
``` yaml
apiVersion: v1
kind: Secret
metadata:
  name: loki-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ xxxxx | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ xxxxx | b64enc | quote }}
  AWS_DEFAULT_REGION: {{ xxxxx | b64enc | quote }}
```

I can do a MR which pass the flag based on the fact that `extraEnvFrom` or `extraEnv` are set but i do not know if it is the right way to do it. Thank you in advance for the time you will take to answer.

links : 
* [env variables support in loki](https://grafana.com/docs/loki/latest/configuration/)
* [actual chart config flag](https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/templates/ingester/statefulset-ingester.yaml#L46)
