### ISSUE TITLE
[Promtail] Promtail cannot find logs even log file is there.

### ISSUE THREAD

**Issue by hehe717** [grafana/helm-charts#414]
Here are my scrape configs

```
      - job_name: kubernetes-pods-app
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
              - asr
              - asr-azure
              - pdss
        relabel_configs:
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_label_app
          target_label: app
        - action: replace
          source_labels:
            - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_node_name
          target_label: node_name
        - action: replace
          source_labels: ['__meta_kubernetes_pod_node_name']
          target_label: '__host__'
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_name
          target_label: pod
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_container_name
          target_label: container
        - action: replace
          replacement: "/var/log/project/**/*.log"
          target_label: __path__
```

and promtail found the pods matching above configurations.
But promtail cannot find the logs file even file is there with this error

```

```
level=debug ts=2021-04-30T07:36:34.734203661Z caller=filetarget.go:196 msg="no files matched requested path, nothing will be tailed" path=/var/log/project/**/*.log
```
evel=debug ts=2021-04-30T07:38:59.730705894Z caller=filetargetmanager.go:200 msg="new target" labels="{__address__=\"*****\", __meta_kubernetes_node_address_ExternalIP=\"**.**.**.**\", __meta_kubernetes_node_address_Hostname=\"gke-mobile-0bb69a75-pw3u-wjsz.us-west1-a.****.9121.internal\", __meta_kubernetes_node_address_InternalDNS=\"gke-mobile-0bb69a75******\", __meta_kubernetes_node_address_InternalIP=\"***\", instance=\"*****\"}"
```
(Sorry for masking for security)
```
wonjae.na@gke-mobile-0bb69a75-pw3u /var/log/project/logs/my-project-5d75c49cc-jk7jm $ ls
server-2021-04-28-23-1.log.gz  server-2021-04-29-23-1.log.gz  server.log
```

Why promtail cannot scrape file even promtail find pods well, and there is file also?
