### ISSUE TITLE
[Grafana chart] cannot deploy to Kubernetes with Azure DevOps pipeline

### ISSUE THREAD

**Issue by rik1599** [grafana/helm-charts#417]
I have an AKS cluster and I want to deploy the chart using CI/CD Azure DevOps pipelines, but with default rbac configuration I always receive this error:

> ##[error]Error: UPGRADE FAILED: could not get information about the resource: podsecuritypolicies.policy "grafana" is forbidden: User "system:serviceaccount:default:***" cannot get resource "podsecuritypolicies" in API group "policy" at the cluster scope

I resolved this error with this values:

````yaml
rbac:
  create: false
  pspEnabled: false
  useExistingRole: grafana-clusterrole
````

And I had to redefine the ClusterRole:
````yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-clusterrole
rules:
- apiGroups: ["rbac.authorization.k8s.io"] # "" indicates the core API group
  resources: ["clusterroles"]
  verbs: ["get"]
````

This is the pipeline I wrote:
````yaml
trigger:
- master

pool:
  vmImage: ubuntu-latest
  
variables:
  release: grafana
  chart: grafana/grafana
  repository: https://grafana.github.io/helm-charts
  valueFile: grafana_values.yaml

steps:
- task: HelmDeploy@0
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 
    namespace: 'default'
    command: 'repo'
    arguments: 'add $(release) $(repository)'

- task: HelmDeploy@0
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 
    namespace: 'default'
    command: 'repo'
    arguments: 'update'

- task: HelmDeploy@0
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection:
    namespace: 'default'
    command: 'upgrade'
    chartType: 'Name'
    chartName: $(chart)
    releaseName: $(release)
    valueFile: $(valueFile)

````
