### ISSUE TITLE
Loki Helm chart: Namespace not set on ServiceMonitor

### ISSUE THREAD

**Issue by vrivellino** [grafana/helm-charts#434]
I'm using a combination of Helm and Kustomize to deploy Loki w/ Fluentbit. When I enable a ServiceMonitor, the namespace is not being set.

Script I'm using to build the manifests using helm:

```bash
#!/usr/bin/env bash

set -ex

# https://grafana.com/docs/loki/latest/installation/helm/
# Script inspired from https://blog.container-solutions.com/using-helm-and-kustomize-to-build-more-declarative-kubernetes-workloads

test -d base || mkdir base
helm repo list | grep -q grafana || helm repo add grafana https://grafana.github.io/helm-charts
helm repo update
helm template loki \
  --namespace loki \
  --output-dir base \
  --values conf/values.yaml \
  grafana/loki-stack

cd base
cat > kustomization.yaml << _END_
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
_END_
for yaml in $(find ./loki-stack/charts/loki/templates ./loki-stack/charts/fluent-bit/templates -type f -name "*.yaml") ; do
    echo "  - $yaml" >> kustomization.yaml
done
```

Resulting ServiceMonitor:

```yaml
---
# Source: loki-stack/charts/loki/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki
  labels:
    app: loki
    chart: loki-2.3.0
    release: loki
    heritage: Helm
    name: loki-prometheus-servicemonitor
spec:
  selector:
    matchLabels:
      app: loki
      release: "loki"
      variant: headless
  namespaceSelector:
    matchNames:
      - "loki"
  endpoints:
  - port: http-metrics
    interval: 60s
```

Note that `namespace` is not set in metadata.
