### ISSUE TITLE
[loki-stack] Question: configure promtail jobs

### ISSUE THREAD

**Issue by indeedhat** [grafana/helm-charts#442]
Please forgive the probably stupid question but i am quite new to kubernetes and totally new to using helm and i am having some issues getting logging to work.

I am trying to get promtail to capture the logs from journald but im really confused about how to actually do that. I have had a look at the helm docs for values and my assumption was that i would need to create a values file with the journald job as shown in the readme and pass that the the helm installation command.

I am clearly doing something wrong as the only promtail pod that is actually tracking anything is a node that is using json-file as its logging driver and all of the journald ones give me 
> Not ready: Unable to find any logs to tail. Please verify permissions, volumes, scrape_config, etc.

I have checked the promtail pods and i dont have a /var/log/journal mound in any of then and there is no journal job in the /etc/promtail/promtail.yaml file (although i dont know if that is even where they would be)

Any help would be really appreciated.

### My values.yml file
```yaml
# Add additional scrape config
extraScrapeConfigs:
  - job_name: journal
    journal:
      max_age: 12h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'hostname'

# Mount journal directory into promtail pods
extraVolumes:
  - name: journal
    hostPath:
      path: /var/log/journal

extraVolumeMounts:
  - name: journal
    mountPath: /var/log/journal
    readOnly: true
```

### My install command
```bash
helm upgrade --install loki grafana/loki-stack  \
    --set grafana.enabled=true,prometheus.enabled=true,prometheus.alertmanager.persistentVolume.enabled=false,prometheus.server.persistentVolume.enabled=false,loki.persistence.enabled=true,loki.persistence.storageClassName=standard,loki.persistentVolume.enabled=true \
    -f promtail-values.yml \
    -n loki
```

**Comment by dpkirchner** [comment]
Your `promtail-values.yml` file contents need to be inside an object named `promtail`, e.g:

```yaml
promtail:
  extraScrapeConfigs:
  - job_name: journal
# etc
```
