### ISSUE TITLE
[loki] Ability to disable test framework for loki

### ISSUE THREAD

**Issue by psibi** [grafana/helm-charts#449]
For some use cases, people might not want to run the test framework for loki and having the ability to disable it would be nice. Grafana's helm chart already supports this and having a similar syntax would be nice:

```
testFramework:
  enabled: true
  image: "bats/bats"
  tag: "v1.1.0"
  imagePullPolicy: IfNotPresent
  securityContext: {}
```

This would also fix this issue: https://github.com/grafana/helm-charts/issues/296
