### ISSUE TITLE
[grafana] Grafana.ini paths not respected in container

### ISSUE THREAD

**Issue by jacksgt** [grafana/helm-charts#450]
I recently wanted to re-configure the directories Grafana uses to store data.
This Helm chart exposes the "paths" under the "grafana.ini" section, so I thought changing those should have the desired effect.

https://github.com/grafana/helm-charts/blob/76ef792c3d2910f2a4c4996a66c77cc65daa0074/charts/grafana/values.yaml#L529-L538

So I changed those:
```yaml
grafana.ini:
  paths:
    data: /test/data
    plugins: /test/plugins
```

After re-deploying the Helm chart, I was surprised to find out that Grafana was still writing the data to the old directories.
After tracking this issue down, it seems that the Helm chart only modifies the *grafana.ini config file*, but not the launch options of the Grafana container.
The Grafana container uses the environment variables `GF_PATHS_DATA` etc. for launching the Grafana server:
https://github.com/grafana/grafana/blob/0f4806db8a6fba20974a7caf7755f83ac5a7944f/packaging/docker/run.sh#L80-L89

Thus, I was able to achieve the desired effect by setting:
```yaml
env:
  GF_PATHS_DATA: /test/data
  GF_PATHS_PLUGINS: /test/plugins

grafana.ini:
  paths:
    data: /test/data
    plugins: /test/plugins
```

But I think this (setting appropriate environment variables) should be the default behavior when the user explicitly sets `grafana.ini.paths.data` and friends.

I'm happy to make a PR for this if there is consensus.
