### ISSUE TITLE
[loki-stack] "Alert rules" in Grafana always empty despite configured alerts

### ISSUE THREAD

**Issue by dpkirchner** [grafana/helm-charts#462]
This may not be a bug but instead a misunderstanding on my part. I don't see my alerts in the Grafana UI. I've created an alert in my values.yaml and can confirm that the query involved is running based on the logs output from the `loki-0` pod, and the alert is firing, but the "Alerting: Alert rules" page (`/alerting/list`) is empty. 

From values.yaml:

```yaml
loki:
  alerting_groups:
  - name: cluster
    rules:
    - alert: ClusterNotLogging
      expr: absent_over_time({job=~"default/.+",cluster="xyz"}[5m])
      for: 2m
```

Logs showing that the alert query is running:

```
level=info ts=2021-06-01T22:15:24.158263392Z caller=metrics.go:91 org_id=..2021_06_01_22_14_52.289806603 traceID=3fed6aadb50c9d91 latency=fast query="absent_over_time({job=~\"default/.+\", cluster=\"xyz\"}[5m])" query_type=metric range_type=instant length=0s step=0s duration=167.599702ms status=200 limit=0 returned_lines=0 throughput=0B total_bytes=0B
```

I expected to see the alert configuration on that `/alerting/list` page, although I don't know what it would look like.
