### ISSUE TITLE
[grafana/grafana] LOST all my data after upgrading to grafana:8.0.0 

### ISSUE THREAD

**Issue by waterdrop01** [grafana/helm-charts#478]
Hello,
I updated grafana docker image version to `8.0.0` in my helm `values.yml` file, and then ran this command:
```
helm repo update
helm upgrade grafana grafana/grafana --namespace=monitoring --values values.yml
```
And now if I log into my grafana dashboard, **all my dashboards/settings are GONE**. Very frustrating as you can imagine...

Here is my `values.yml` file:
```
image:
  repository: grafana/grafana
  tag: 8.0.0
  pullPolicy: IfNotPresent

persistence:
  type: pvc
  enabled: true
  storageClassName:
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  annotations: {}
  finalizers:
    - kubernetes.io/pvc-protection

adminUser: admin
adminPassword: my_password

sidecar:
  dashboards:
    enabled: true
  provider:
    enabled: true

deploymentStrategy:
  type: Recreate

grafana.ini:
  paths:
    data: /var/lib/grafana/data
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
  server:
    root_url: https://grafana.my.domain

plugins:
  - grafana-piechart-panel
```

If i `exec` into the grafana container `kubectl exec -it grafana-6d9dc56d88-zzn27 --container grafana -n monitoring -- /bin/sh`, and run `ls -ahl /var/lib/grafana/data/` I see this:
```
drwxrwsr-x    4 grafana  472         4.0K Jun  8 10:59 .
drwxrwsr-x    6 grafana  472         4.0K Jun  8 09:45 ..
drwxrws---    2 grafana  472         4.0K Jun  8 09:45 csv
-rw-rw----    1 grafana  472       584.0K Jun  8 10:59 grafana.db
drwxrws---    2 grafana  472         4.0K Jun  8 09:45 png
```
Any help would be much appreciated.

Also, any chance to recover the data? Grafana IS still using the PVC that was created months ago. It seems like upgrading to V8.0.0 erased the existing data?

Thanks for your help
