### ISSUE TITLE
Manually created dashboard and datasources from grafana ui getting lost when we upgrade from 6.10.0 to 6.11.0

### ISSUE THREAD

**Issue by svchinche** [grafana/helm-charts#486]
helm upgrade --install grafana grafana/grafana -n grafana --version 6.10.0 -f values.yaml 
helm upgrade --install grafana grafana/grafana -n grafana --version 6.11.0 -f values.yaml 

values.yaml file
```
admin:
  existingSecret: grafana
persistence:
  enabled: true
  storageClassName: ebs-sc
  type: statefulset
```
