### ISSUE TITLE
How to add extra scrape configs to prometheus?

### ISSUE THREAD

**Issue by mckernanin** [grafana/helm-charts#491]
I have loki-stack deployed in kubernetes using helm, my values look like this. I am unsure where to add extra scrape configs.

```
        loki:
          persistence:
            enabled: true
            storageClassName: longhorn
            size: 5Gi
        grafana:
          enabled: true
          service:
            type: LoadBalancer
        prometheus:
          enabled: true
          alertmanager:
            persistentVolume:
              enabled: false
          server:
            service:
              type: LoadBalancer
            persistentVolume:
              enabled: true
```

**Comment by monofone** [comment]
You can do so by using the `extraScrapeConfigs:`

example using external gitlab

```yaml
  extraScrapeConfigs: |
    - job_name: gitlab
      static_configs:
      - targets:
        - gitlab.instance.org
      metrics_path: /-/metrics
      params:
        token: 
        - <secret>
      scheme: https
```
