### ISSUE TITLE
Grafana - Cloudwatch datasource

### ISSUE THREAD

**Issue by AmitBaranes** [grafana/helm-charts#510]
i have followed the documentation about how to connect grafana to cloudwatch using IAM Role.

The logs say that the AWS session created Successfully:

```
{"@level":"debug","@message":"Authenticating towards AWS with shared credentials","@timestamp":"2021-06-20T09:31:54.865609Z","profile":"","region":"eu-west-1"}
{"@level":"debug","@message":"Successfully created AWS session","@timestamp":"2021-06-20T09:31:54.865729Z"}
```

But, later I face this issue :

```
SharedCredsLoad: failed to load shared credentials file
caused by: FailedRead: unable to read file caused by: read /usr/share/grafana/.aws/credentials: is a directory
```

This is my values.yaml - 

```
env:
  AWS_ROLE_ARN: arn:aws:iam::XXXX:role/monitoring
  AWS_WEB_IDENTITY_TOKEN_FILE: /usr/share/grafana/.aws/credentials/token
  AWS_REGION: eu-west-1


extraSecretMounts:
  - name: aws-iam-token
    mountPath: /usr/share/grafana/.aws/credentials/token
    readOnly: true
    projected:
      defaultMode: 420
      sources:
        - serviceAccountToken:
            audience: sts.amazonaws.com
            expirationSeconds: 86400
            path: token
```

Do I miss something? 

Thanks in advance.
