### ISSUE TITLE
Sidecar can't store dashboards

### ISSUE THREAD

**Issue by nlamirault** [grafana/helm-charts#515]
Hi,
i configure providers like that : 

```yaml
dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: true
            editable: false
            options:
              path: /var/lib/grafana/dashboards/default
          - name: 'flux'
            orgId: 1
            folder: 'flux'
            type: file
            disableDeletion: true
            editable: false
            options:
              path: /var/lib/grafana/dashboards/flux
          - name: 'kubernetes'
            orgId: 1
            folder: 'kubernetes'
            type: file
            disableDeletion: true
            editable: false
            options:
              path: /var/lib/grafana/dashboards/kubernetes
```

and sidecar : 

```yaml
  grafana-sc-dashboard:                                                                                                                                                                                             
    Container ID:   containerd://c170ed4034ce6a48a95f388149c81fa74f86f5dc89c51ea680553860b72bb0fd                                                                                                                   
    Image:          quay.io/kiwigrid/k8s-sidecar:1.10.7                                                                                                                                                             
    Image ID:       quay.io/kiwigrid/k8s-sidecar@sha256:18feb3906286814364b2f42eeaf82649b4847a4d0a779222a613c79c9da7ad87                                                                                            
    Port:           <none>                                                                                                                                                                                          
    Host Port:      <none>                                                                                                                                                                                          
    State:          Running                                                                                                                                                                                         
      Started:      Tue, 22 Jun 2021 07:59:05 +0200                                                                                                                                                                 
    Ready:          True                                                                                                                                                                                            
    Restart Count:  0                                                                                                                                                                                               
    Limits:                                                                                                                                                                                                         
      cpu:     100m                                                                                                                                                                                                 
      memory:  100Mi                                                                                                                                                                                                
    Requests:                                                                                                                                                                                                       
      cpu:     20m                                                                                                                                                                                                  
      memory:  32Mi                                                                                                                                                                                                 
    Environment:                                                                                                                                                                                                    
      METHOD:                                                                                                                                                                                                       
      LABEL:              grafana-dashboard                                                                                                                                                                         
      FOLDER:             /tmp/dashboards                                                                                                                                                                           
      RESOURCE:           both                                                                                                                                                                                      
      NAMESPACE:          ALL                                                                                                                                                                                       
      FOLDER_ANNOTATION:  grafana-folder                                                                                                                                                                            
    Mounts:                                                                                                                                                                                                         
      /tmp/dashboards from sc-dashboard-volume (rw)                                                                                                                                                                 
      /var/run/secrets/kubernetes.io/serviceaccount from grafana-token-j4gf7 (ro)         
```

I've got some errors in logs : 

```
[2021-06-22 06:40:55] Working on configmap monitoring/prometheus-mixin-prometheus
[2021-06-22 06:40:55] File in configmap prometheus.json ADDED
[2021-06-22 06:40:55] Contents of prometheus.json haven't changed. Not overwriting existing file
[2021-06-22 06:40:55] Working on configmap monitoring/kubernetes-mixin-namespace-by-pod
[2021-06-22 06:40:55] Found a folder override annotation, placing the kubernetes-mixin-namespace-by-pod in: /var/lib/grafana/dashboards/kubernetes
[2021-06-22 06:40:55] File in configmap namespace-by-pod.json ADDED
[2021-06-22 06:40:55] Error: insufficient privileges to create /var/lib/grafana/dashboards/kubernetes. Skipping namespace-by-pod.json.
[2021-06-22 06:40:55] Received unknown exception: unsupported operand type(s) for |=: 'bool' and 'NoneType'
```

The container sidecar doesn't mount the volume which contains  */var/lib/grafana/*, like the **download-dashboards** container (https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/_pod.tpl#L68)

How can i fix that ?

**Comment by nlamirault** [comment]
It works if i use the `/tmp/dashboards` directory.

**Comment by yacinelazaar** [comment]
hey @nlamirault, did you find a fix for this? other than storing in a tmp folder?

**Comment by nlamirault** [comment]
@yacinelazaar No. i change my method to add dashboards to Grafana. I'm using ConfigMap.

**Comment by yacinelazaar** [comment]
Curious about the approach you mentioned. Does it support dynamic config through configmap updates or does it need grafana restart? Where do you mount the configmaps and how do you structure it's data?

**Comment by krichter722** [comment]
I can confirm that `Received unknown exception: unsupported operand type(s) for |=: 'bool' and 'NoneType'`  indicates that directories `path` in

```
grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      providers:
        - options:
            path: /tmp/dashboards/backend
```

in the Helm values of `kube-prometheus-stack` are not placed in `/tmp/dashboard/[provider name]`. That's speculation, but switching from `/var/lib/grafana/dashboards` to `/tmp/dashboards` fixes this issue.

This is maybe useful for other who are reverse-engineering the missing Grafana docs from bits and pieces in old issues.
