### ISSUE TITLE
Error deploying when only GF_SECURITY_ADMIN_USER__FILE is set

### ISSUE THREAD

**Issue by Heimrych** [grafana/helm-charts#518]
**What happened:**
When I tried to deploy the chart with the following values:
  ```
adminUser: ""
  adminPassword: ""
  env:
    GF_SECURITY_ADMIN_USER__FILE: /path/to/user/file
    GF_SECURITY_ADMIN_PASSWORD__FILE: /path/to/password/file
```

The chart still expected the values populated in the secret created by the `.Values.admin.existingSecret` key, even on cases where it's not being created. 

**Why it happened:**
This happens because the conditional clauses regarding the GF_SECURITY_ADMIN_USER env var initialization are different from the ones in GF_SECURITY_ADMIN_PASSWORD.

**GF_SECURITY_ADMIN_USER**

`{{- if and (not .Values.env.GF_SECURITY_ADMIN_USER) (not .Values.env.GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION) }`

**GF_SECURITY_ADMIN_PASSWORD**

`{{- if and (not .Values.env.GF_SECURITY_ADMIN_PASSWORD) (not .Values.env.GF_SECURITY_ADMIN_PASSWORD__FILE) (not .Values.env.GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION) }}`

This misconfiguration can be found in `templates/_pod.tpl`, line 316 and 323. Any reason why they're different? If there's no reason, I can happily create a PR to fix this issue.
