### ISSUE TITLE
loki-stack: specifying an already existing, host path based persistent volume

### ISSUE THREAD

**Issue by kelleryvo** [grafana/helm-charts#524]
I am trying to get Loki and Grafana in loki-stack (https://github.com/grafana/helm-charts/tree/main/charts/loki-stack) to use an existing Persistent Volume that is hostPath based, instead of the automatically provisioned ones when persistence is activated.

I looked at the values.yaml of loki for reference: https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml

```
persistence:
  enabled: false
  accessModes:
  - ReadWriteOnce
  size: 10Gi
  annotations: {}
  # selector:
  #   matchLabels:
  #     app.kubernetes.io/name: loki
  # subPath: ""
  # existingClaim:
```

Specifying a PVC in `existingClaim` did not work, and I could not find any documentation on this. How can I change the values.yaml to use a specific Persistent Volume? Or is this something that is not supported? Thanks for any insight on this.
