### ISSUE TITLE
Dashboard created in General folder, ignoring folder name in dashboardProviders

### ISSUE THREAD

**Issue by tringuyen-yw** [grafana/helm-charts#526]
Using Grafana helm chart version 6.13.2, which is an upstream dependency from [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack).

I would like to import some dashboards created in a configmap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-strimzi-dashboards
  # if different namespace than kube-prometheus-stack
  # must set value `searchNamespace` https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L637
  #namespace: <where the kube-prometheus-stack helm release is installed>
  labels:
    app: strimzi
    grafana_dashboard: "1"
  annotations:
    k8s-sidecar-target-directory: "/tmp/dashboards/strimzi"
data:
  strimzi-kafka.json: |-
    { 
       json code of the Grafana dashboard
    }
  dashboard2.json: |-
    {
       json code
    }
```
Customize `my-helm-values.yaml`. Please note: here the helm values is written for Grafana helm chart. For `kube-prometheus-stack` helm chart, I have to nest the content under the root element `grafana:`

```
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    folder: /tmp/dashboards

dashboardProviders:
  strimzi-provider.yaml:
    apiVersion: 1
    providers:
      - name: 'strimzi'
        orgId: 1
        folder: 'KAFKA'
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /tmp/dashboards/strimzi
```

Then deploy by 

```
helm install my-grafana grafana -n monitoring -f my-helm-values.yaml
```

**What happenned?**

- The dashboards `*.json` files are correctly saved in `/tmp/dashboards/strimzi`. The `strimzi-provider.yaml` correctly created in ` /etc/grafana/provisioning/dashboards`.
- Grafana UI show the dashboard folder `KAFKA` is created but has zero dashboards.
- The dashboards which are supposed to be in the `KAFKA` folder are visible in the `General` folder.

**What is the expected results**

Would prefer the custom dashboards specified in the configmap to be created in the custom dashboard folder as specified in the `dashboardProviders.providers` helm value.

**Comment by joeyenfield-verint** [comment]
I had the same issue. 
In my values.yaml 
 You need to add

```
  sidecar:
    dashboards:
      label: grafana_dashboard
      folderAnnotation: grafana_folder
      provider:
        foldersFromFilesStructure: true
```

Then i can add 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-dashboard
  namespace: monitoring
  labels:
     grafana_dashboard: "1"
  annotations:
     grafana_folder: "common"
```

**Comment by tringuyen-yw** [comment]
@joeyenfield-verint That's cool thanks. Just to clarify.

Q1. is `grafana_folder: "common"` the name of the dashboard folder in the Grafana UI?
Q2. For the dashboards in `common` folder, What is the physical path where the `*.json` files are stored?
Q3. Can you confirm you don't define any `dashboardProviders` value for the Grafana helm value?

**Comment by tringuyen-yw** [comment]
@joeyenfield-verint  fantastic your solution works perfectly. Answering my own question hopefully to help future readers

> Q1. is `grafana_folder: "WhateverNameYouWant"` the name of the dashboard folder in the Grafana UI?
> Q2. For the dashboards in `common` folder, What is the physical path where the `*.json` files are stored?

Yes, the `grafana-sc-dashboard` sidecar container will process the ConfigMap. It will store all the dashboards defined in the ConfigMap in a Grafana dashboard folder named in the value of the `grafana_folder` label key. There is no need to create that folder in advance. The Grafana helm values bebome much simpler! In the example below, the sidecar will create a subdir named `WhateverNameYouWant` (configured in ConfigMap) within the dashboard dir `/tmp/dashboards` (configured in sidecar.dashboards.folder`). The `*.json` of the dashboards defined in the ConfigMap are stored in this subdir.

In the Grafana UI, the dashboards in `/tmp/dashboards/WhateverNameYouWant` are provisioned in the dashboard folder named `WhateverNameYouWant` (instead of the `General` dashboard folder).

```yaml
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    folder: /tmp/dashboards
    folderAnnotation: grafana_folder

    provider:
      allowUiUpdates: true
      foldersFromFilesStructure: true
```

> Q3. Can you confirm you don't define any `dashboardProviders` value for the Grafana helm value?

Confirmed. There is no need. the Grafan helm values I use above doesn't have `dashboardProviders`. For completeness, here is my updated ConfigMap which just mirror the solution you suggested. The important point is the annotation `k8s-sidecar-target-directory`  is replaced by `grafana_folder` label.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-strimzi-dashboards
  labels:
    app: strimzi
    grafana_dashboard: "1"
  annotations:
    grafana_folder: "WhateverNameYouWant"
data:
  dashboard1.json: |-
    { 
       json code of the Grafana dashboard
    }
  dashboard2.json: |-
    {
       json code
    }
```

Overall the comments in [grafana/values.yaml](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml) are confusing (or outdated).
