### ISSUE TITLE
Add secrets for auth

### ISSUE THREAD

**Issue by prateekkhera** [grafana/helm-charts#536]
Currently for oauth - grafana helm chart requires you to set client secret in values.yaml:

**Comment by Bfoster-melrok** [comment]
also waiting for this. Maybe it can be handled similarly to the SMTP config? provide most of the config in the grafana.ini section, and the sensitive bits can be loaded into environment variables from an existing secret?

**Comment by sathieu** [comment]
You can do something like this (example with a subchart):

```yaml
grafana:
    envValueFrom:
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
        secretKeyRef:
          name: keycloak-client-secret-grafana
          key: CLIENT_ID
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
        secretKeyRef:
          name: keycloak-client-secret-grafana
          key: CLIENT_SECRET
```

**Comment by mihaigalos** [comment]
> You can do something like this (example with a subchart):
> 
> ```yaml
> grafana:
>     envValueFrom:
>       GF_AUTH_GENERIC_OAUTH_CLIENT_ID:
>         secretKeyRef:
>           name: keycloak-client-secret-grafana
>           key: CLIENT_ID
>       GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
>         secretKeyRef:
>           name: keycloak-client-secret-grafana
>           key: CLIENT_SECRET
> ```

Hi @sathieu, this goes in the direction of what I'm looking for.

Can you show how you consume the set `GF_AUTH_GENERIC_OAUTH_CLIENT_ID` and `GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET`?

P.S.: Security best practices in our company say that we shouldn't use environment variables for mounitng secrets into pods, but instead prefer mounting secrets.

**Comment by mihaigalos** [comment]
[This](https://www.techiescorner.in/grafana-sso-authentication-using-azure-ad/#google_vignette) talks about consuming a mounted file with the secret.

Kubeseal is used to produce a `kind: SealedSecret` resource which is encrypted and storable in Git. The corresponding k8s operator can unseal it and produce a `kind: Secret`.

The secret is bind-mounted into a file consumed by the Grafana pod.

Example:
```yaml
grafana.ini:
  auth.generic_oauth:
     enabled: true
     icon: signin
     name: SSO
     allow_sign_up: true
     auto_login: true
     scopes: "openid email profile"
     auth_url: https://login.microsoftonline.com/111-11240-11111/oauth2/v2.0/authorize
     token_url: https://login.microsoftonline.com/111-11240-11111/oauth2/v2.0/token
     client_id: xxxxxxx-xxxxx-xxx-1111
     client_secret: $__file{/etc/secrets/grafana-secret/client_secret}
extraSecretMounts: 
- name: grafana-secret
  secretName: grafana-secret
  defaultMode: 0440
  mountPath: /etc/secrets/grafana-secret
  readOnly: true
```

IMHO this issue is solved if the above works as designed (untested).
