### ISSUE TITLE
[loki-distributed] Ruler pod won't start. err="mkdir /etc/loki/rules..."

### ISSUE THREAD

**Issue by shinebayar-g** [grafana/helm-charts#537]
I deployed loki-distributed chart version `0.35.0`. Everything works except **ruler** deployment.

Ruler pod is in CrashLoopBackOff state. Container logs:

```
level=info ts=2021-06-30T23:20:29.78038997Z caller=main.go:130 msg="Starting Loki" version="(version=2.2.1, branch=HEAD, revision=babea82ef)"
level=info ts=2021-06-30T23:20:29.780829415Z caller=server.go:229 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=error ts=2021-06-30T23:20:29.781016741Z caller=log.go:106 msg="error running loki" err="mkdir /etc/loki/rules: read-only file system\nerror initialising module: ruler-storage\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:105\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:220\nmain.main\n\t/src/loki/cmd/loki/main.go:132\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"
```

Helm values

```yaml
loki:
  config: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    distributor:
      ring:
        kvstore:
          store: memberlist

    memberlist:
      join_members:
        - {{ include "loki.fullname" . }}-memberlist

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      chunk_idle_period: 30m
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_retain_period: 1m
      max_transfer_retries: 0

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m

      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20

    schema_config:
      configs:
        - from: 2021-06-01
          store: boltdb-shipper
          object_store: aws
          schema: v11
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      aws:
        region: us-east-1
        bucketnames: mybucket.name
      boltdb_shipper:
        shared_store: s3
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 168h

    chunk_store_config:
      max_look_back_period: 2160h

    table_manager:
      retention_deletes_enabled: true
      retention_period: 2160h

    query_range:
      align_queries_with_step: true
      max_retries: 5
      split_queries_by_interval: 15m
      cache_results: true
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_items: 1024
            validity: 24h

    frontend_worker:
      frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095

    frontend:
      log_queries_longer_than: 5s
      compress_responses: true
      tail_proxy_url: http://{{ include "loki.querierFullname" . }}:3100

    compactor:
      shared_store: s3

    ruler:
      storage:
        type: local
        local:
          directory: /etc/loki/rules
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      alertmanager_url: http://alertmanager.xx
      external_url: http://alertmanager.xx
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: <role.arn>
ingester:
  persistence:
    enabled: true
    size: '20Gi'
    storageClass: 'gp2'
querier:
  persistence:
    enabled: true
    size: '20Gi'
    storageClass: 'gp2'
tableManager:
  enabled: true
compactor:
  enabled: true
  persistence:
    enabled: true
    size: '20Gi'
    storageClass: 'gp2'
ruler:
  enabled: true
```

Please let me know how can I fix the error

**Comment by shinebayar-g** [comment]
Ah, just found out I had to supply `directories`. 

```yaml
ruler:
  enabled: true
  directories:
    fake:
      rules1.txt: |
        groups:
          - name: should_fire
            rules:
              - alert: HighPercentageError
                expr: |
                  sum(rate({app="loki"} |= "error" [5m])) by (job)
                    /
                  sum(rate({app="loki"}[5m])) by (job)
                    > 0.05
                for: 10m
                labels:
                  severity: warning
                annotations:
                  summary: High error rate
```
