### ISSUE TITLE
Grafana Dashboards multi org

### ISSUE THREAD

**Issue by davidphayanouvong** [grafana/helm-charts#544]
Hello,

I want to configure through helm  my grafana dashboard.

I have multiple org and I can't found how to define a dashboard (inside a configmap) to a specific org.

I found 2 post about that, but it doesn't work, maybe I did something wrong?
- https://github.com/helm/charts/issues/15805
- https://community.grafana.com/t/create-dashboards-in-multiple-orgs-using-provisioning/42855

For information I use the helm chart kube-prometheus-stack-prometheus and this is my configuration for grafana:

````yaml
grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /tmp/dashboards/org1
        - name: 'org2'
          orgId: 2
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /tmp/dashboards/org2
  sidecar:
    image:
      repository: quay-remote.artifactory.swisscom.com/kiwigrid/k8s-sidecar
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /tmp/dashboards

      ## Annotations for Grafana dashboard configmaps
      ##
      annotations: {}
      multicluster: false
````

and on my configmap:
````yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_dashboard: "1"
  name: traefik-test
  annotations:
    k8s-sidecar-target-directory: "/tmp/dashboards/org2"
data:
  traefik-test.json: |-
    {
      ...
      ...
    }
````

Thanks,
David
