### ISSUE TITLE
[Grafana] availability to template extraInitContainers

### ISSUE THREAD

**Issue by DeadEternity** [grafana/helm-charts#548]
I'm using init container(shared volume with grafana container) for dashboard provisioning. When using git ref stages i want to set custom image for this container, but there's a [problem with helm](https://github.com/helm/helm/issues/6847). When using `helm --set "grafana.extraInitContainers[0].image"` and init container spec in values like: 
```
extraInitContainers:
    - name: dashboards-provider
      imagePullPolicy: Always
      command:
      - "cp"
      - "-r"
      - "/dashboards/"
      - "/provided-dashboards"
      volumeMounts:
      - name: dashboard-provisioning
        mountPath: "/provided-dashboards"
```
All values are overrided and only image provided in rendered template. Pls add availability to template values inside extraInitContainers with tpl. To use it like this, for example:
```
initDashboardsProviderImageTag: mynotlatesttag
grafana:
  extraInitContainers:
      - name: dashboards-provider
        image: my.docker.host/dashboards-image:{{ .Values.initDashboardsProviderImageTag }}
        imagePullPolicy: Always
        command:
        - "cp"
        - "-r"
        - "/dashboards/"
        - "/provided-dashboards"
        volumeMounts:
        - name: dashboard-provisioning
          mountPath: "/provided-dashboards"
```
