### ISSUE TITLE
failed to install plugin grafana-piechart-panel

### ISSUE THREAD

**Issue by paul-mesnilgrente** [grafana/helm-charts#550]
Hi,

I am currently running grafana 7 with the chart version 6.11.0. When I try to upgrade to version 8, I get this error in container logs:

```
✔ Downloaded devopsprodigy-kubegraf-app v1.5.2 zip successfully

Fetching devopsprodigy-kubegraf-app dependencies...

Error: ✗ failed to install plugin grafana-piechart-panel: grafana-piechart-panel v>=1.3.7 either does not exist or is not supported on your system (Grafana v8.0.3 linux-amd64)
```

I downgraded to version 7 and it works fine. Did something change?

Here are my values if that can help...

```yaml
rbac:
  pspUseAppArmor: false
service:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: grafana.example.org
persistence:
  enabled: true
  existingClaim: grafana-data
ingress:
  enabled: true
  hosts: [grafana.example.org]
adminPassword: 'my-password'
plugins:
  - devopsprodigy-kubegraf-app
  - grafana-piechart-panel
deploymentStrategy: { "type": "Recreate" }

grafana.ini:
  smtp:
    enabled: true

smtp:
  existingSecret: smtp-aws
  userKey: SMTP_USER
  passwordKey: SMTP_PASSWORD

resources:
  limits:
    cpu: 750m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi
```
