### ISSUE TITLE
Helm chart suggestions surrounding Tempo and Agent

### ISSUE THREAD

**Issue by cabrinha** [grafana/helm-charts#551]
First of all, I'd like to thank the team at Grafana Labs for providing such awesome tools like Tempo!

I've heard that there is a dilemma between making helm charts more maintainable vs. more extensible. Example:

# Tempo
The tempo chart uses multiline strings to add yaml to the configmap object [here](https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/values.yaml#L338). But, that makes it hard to change just one value because you'd have to copy the entire (multi-line) string to just add or change one line.

As a solution, I'd suggest to use the [with statement](https://helm.sh/docs/chart_template_guide/control_structures/#modifying-scope-using-with), because this would allow us to merge defaults from the values.yaml file with user defined overrides. Example:

## configmap-tempo.yaml
```yaml
# configmap-tempo.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tempo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.distributorLabels" . | nindent 4 }}
data:
  {{- with .Values.queryFrontend.query.config }}
  tempo-query.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.overrides }}
  overrides.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.config }}
  tempo.yaml: | # does this need to be a multiline string?
    {{- toYaml . | nindent 4 }}
  {{- end }}
```

## values.yaml
```yaml
# values.yaml
---
config: # no multiline string syntax here
  multitenancy_enabled: false
  compactor:
    compaction:
      block_retention: 48h
    ring:
      kvstore:
        store: memberlist
  distributor:
    ring:
      kvstore:
        store: memberlist
```

Using this pattern, users can either extend or override the the config, while still keeping all defaults in place.

To change just one option, a user can just pass in:
`helm install -f values.yaml --set config.multitenancy_enabled=true`

All defaults would be preserved and only one option would be changed.

This seems to be a fair way to strike a balance between maintainability and extensibility.

I'd also like to suggest the ability to create an ingress. With a large deployment like Cortex, writing directly into the distributor service could put a lot of load on the kube-proxy. By using an ingress, that load could be shifted to nginx-ingress controller or whatever ingress solution the user employs on their cluster.

An ingress for the Jaeger web UI would be very nice, as well as an ingress for the distributor so we could hit `/ring` to remove unhealthy ingesters, check status of memberlist and so on. Here is a longish thread from Slack where another user was having issues getting into the ring: https://grafana.slack.com/archives/C01D981PEE5/p1623701114220300

Hope my suggestions shed some light on the issue. I'd be happy to open some PRs to get this stuff going.

# Agent

I understand that an operator is in the works to deploy grafana-agent, but we don't know how long that'll take to release. Even after release, some users may not want to deploy a full fledged operator and may instead prefer a simple helm chart to deploy agent.

In the meantime, I'd love to see a helm chart created for deploying Grafana Agent. I'd be happy to work on this as well.

# References from Cortex

Also, Tempo is pretty much Cortex under the hood. Maybe some inspiration could be drawn from how that chart is written and maintained: https://github.com/cortexproject/cortex-helm-chart

I'm one of the maintainers of the chart. One of my biggest gripes is that the config is all hidden away in a secret object, but other than that, it's a pretty solid design.
