### ISSUE TITLE
Downloading remote dashboard with sidecar provider?

### ISSUE THREAD

**Issue by servo1x** [grafana/helm-charts#56]
Hi, can anyone provide an example for how we can download remote dashboards with the sidecar provider?

**Comment by servo1x** [comment]
Found an example:

> If the filename ends with .url suffix, the content will be processed as an URL the target file will be downloaded and used as the content file.
> https://github.com/kiwigrid/k8s-sidecar#usage

```yaml
# configmap.yaml
...
data:
  data.json.url: http://localhost.local/dashboard.json
```
