### ISSUE TITLE
[loki-distributed] Gateway Ingress doesn't create networking.k8s.io/v1 on EKS 1.19

### ISSUE THREAD

**Issue by shinebayar-g** [grafana/helm-charts#574]
We're on EKS `v1.19.8-eks-96780e`, chart's `loki.ingress.enabled`  doesn't create `networking.k8s.io/v1` resource on EKS 1.19. Instead it creates `networking.k8s.io/v1beta1`

Here is my `values.yaml`.

```yaml
gateway:
  # Gateway ingress configuration
  ingress:
    # -- Specifies whether an ingress for the gateway should be created
    enabled: true
    # -- Ingress Class Name. MAY be required for Kubernetes versions >= 1.18
    # ingressClassName: nginx
    # -- Annotations for the gateway ingress
    annotations:
      kubernetes.io/ingress.class: nginx
    # -- Hosts configuration for the gateway ingress
    hosts:
      - host: gateway.loki.example.com
        paths:
          - path: /
            # -- pathType (e.g. ImplementationSpecific, Prefix, .. etc.) might also be required by some Ingress Controllers
            pathType: Prefix
```

```
helm template grafana-loki-distributed --namespace loki --version 0.35.0 --values loki-distributed-0.35.0.yaml grafana/loki-distributed > loki-template.yaml
```
Result:

```yaml
---
# Source: loki-distributed/templates/gateway/ingress-gateway.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana-loki-distributed-gateway
  labels:
    helm.sh/chart: loki-distributed-0.35.0
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: grafana-loki-distributed
    app.kubernetes.io/version: "2.2.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gateway
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "gateway.loki.example.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana-loki-distributed-gateway
              servicePort: 80
```

**Comment by sherifkayad** [comment]
@shinebayar-g hey hey .. According to the latest Chart version (0.35.0), normally if your k8s API is supporting `networking.k8s.io/v1` then you should get it. 

Here's the Helm template used for the Gateway Ingress:
```yaml
{{- if .Values.gateway.enabled }}
{{- if .Values.gateway.ingress.enabled -}}
{{- $newAPI := .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
{{- if $newAPI -}}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}

....
```

**Comment by sherifkayad** [comment]
I can't speak for EKS 1.19 .. However with my current EKS cluster running 1.20, I do get:
```bash
$ kubectl version
...
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-eks-6b7464", GitCommit:"6b746440c04cb81db4426842b4ae65c3f7035e53", GitTreeState:"clean", BuildDate:"2021-03-19T19:33:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
```bash
$ helm upgrade --install loki --namespace=logging -f my-values.yml grafana/loki-distributed --version="0.35.0" --dry-run
```
```yaml
...
---
# Source: loki-distributed/templates/gateway/ingress-gateway.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-loki-distributed-gateway
  labels:
    helm.sh/chart: loki-distributed-0.35.0
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: "2.2.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gateway
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "loki-gateway.mydomain.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loki-loki-distributed-gateway
                port:
                  number: 80
---
...
```

My own `values.yml` snippet:
```yaml
...
ingress:
    # -- Specifies whether an ingress for the gateway should be created
    enabled: true
    # -- Ingress Class Name. MAY be required for Kubernetes versions >= 1.18
    # ingressClassName: nginx
    # -- Annotations for the gateway ingress
    annotations:
      kubernetes.io/ingress.class: nginx
    # -- Hosts configuration for the gateway ingress
    hosts:
      - host: loki-gateway.mydomain.com
        paths:
          - path: /
            # -- pathType (e.g. ImplementationSpecific, Prefix, .. etc.) might also be required by some Ingress Controllers
            pathType: Prefix
...
```

**Comment by shinebayar-g** [comment]
Hmm. Here is my `values.yaml`.

```yaml
  # Gateway ingress configuration
  ingress:
    # -- Specifies whether an ingress for the gateway should be created
    enabled: true
    # -- Ingress Class Name. MAY be required for Kubernetes versions >= 1.18
    # ingressClassName: nginx
    # -- Annotations for the gateway ingress
    annotations:
      kubernetes.io/ingress.class: nginx
    # -- Hosts configuration for the gateway ingress
    hosts:
      - host: gateway.loki.example.com
        paths:
          - path: /
            # -- pathType (e.g. ImplementationSpecific, Prefix, .. etc.) might also be required by some Ingress Controllers
            pathType: Prefix
```

```
helm template grafana-loki-distributed --namespace loki --version 0.35.0 --values loki-distributed-0.35.0.yaml grafana/loki-distributed > loki-template.yaml
```
Result:

```yaml
---
# Source: loki-distributed/templates/gateway/ingress-gateway.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana-loki-distributed-gateway
  labels:
    helm.sh/chart: loki-distributed-0.35.0
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: grafana-loki-distributed
    app.kubernetes.io/version: "2.2.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gateway
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "gateway.loki.example.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana-loki-distributed-gateway
              servicePort: 80
```

**Comment by sherifkayad** [comment]
@shinebayar-g weird .. Can you run the Helm upgrade command with the `dry-run` flag? .. e.g.:
``` bash
$ helm upgrade --install loki --namespace=logging -f my-values.yml grafana/loki-distributed --version="0.35.0" --dry-run
```

I am afraid that for whatever reason your command isn't running against a cluster and hence this part is always evaluating to false:
```
{{- $newAPI := .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
```

**Comment by shinebayar-g** [comment]
Cool.

```
helm upgrade --install loki --namespace=logging -f loki.yaml grafana/loki-distributed --version="0.35.0" --dry-run
```

returns

```yml
# Source: loki-distributed/templates/gateway/ingress-gateway.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-loki-distributed-gateway
  labels:
    helm.sh/chart: loki-distributed-0.35.0
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: "2.2.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gateway
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "gateway.loki.example.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loki-loki-distributed-gateway
                port:
                  number: 80
```

Just to compare results I ran again

```
helm template loki --namespace logging --version 0.35.0 --values loki.yaml grafana/loki-distributed
```

and it returns v1beta1.

```yaml
# Source: loki-distributed/templates/gateway/ingress-gateway.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: loki-loki-distributed-gateway
  labels:
    helm.sh/chart: loki-distributed-0.35.0
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: "2.2.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gateway
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "gateway.loki.example.com"
      http:
        paths:
          - path: /
            backend:
              serviceName: loki-loki-distributed-gateway
              servicePort: 80
```

**Comment by sherifkayad** [comment]
I think your problem might be with Helm then and not really this repo here .. Also check https://github.com/helm/helm/issues/3377

**Comment by shinebayar-g** [comment]
I'm on latest available version..

```
$ helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

Grafana helm chart had similar issues and this PR https://github.com/grafana/helm-charts/pull/505 fixed it. I think this chart may need same fix.

**Comment by sherifkayad** [comment]
@shinebayar-g I am asking myself the following questions:
- Isn't the Grafana solution more or less the same as the one introduced here?! .. What are the differences from your view?
- Is the Helm template command for the Grafana chart getting you the desired outcome that you don't get here in the Loki Distributed chart?!

**Comment by stevehipwell** [comment]
As the author of #505 this isn't exactly the same as this chart doesn't even try and get the ingress working correctly.  I don't have a v1.19 cluster to test with but I suspect it might be something to do with `{{- $newAPI := .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}` when I'd have expected to be `{{- $newAPI := .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}`.

As a side note I would make the changes in #505 differently if was doing them again, basically `semverCompare ">= 1.19-0" .Capabilities.KubeVersion.Version` would be good enough to do away with the regex function to cleanup pre-release versions.

**Comment by stevehipwell** [comment]
@shinebayar-g if I open a PR to fix up the ingress would you be able to test the chart locally?

**Comment by stevehipwell** [comment]
@shinebayar-g @sherifkayad actually this doesn't even work correctly on a v1.21 cluster due to the issue I highlighted above, I'll open a PR to fix this as well as support `pathType` on K8s v1.18.

**Comment by sherifkayad** [comment]
@stevehipwell in that case I guess @Whyeasy would be able to help with a review.

BTW I do have a k8s cluster with v1.21 (EKS) and the current version works just fine .. I don't really get the problem, however, if something would be a "hardened / better" solution, I am in for it.

**Comment by stevehipwell** [comment]
@sherifkayad I think there is an issue with the resources being used in the `.Capabilities.APIVersions.Has` test, which is why testing for the API and K8s version is a safer bet. Based on the cases I've seen I think this is related to the `helm template` workflow compared to the `helm upgrade --install` workflow.

**Comment by sherifkayad** [comment]
@stevehipwell gotcha .. so your PR will be more of an enhancement / hardening if I got you right

**Comment by stevehipwell** [comment]
I've created https://github.com/grafana/helm-charts/pull/585 which will fix the ingress behaviour for `pathType` and `ingressClassName` as well as work with any client that doesn't have API resource capabilities.

**Comment by shinebayar-g** [comment]
@stevehipwell thanks for your attention. How do I test the chart locally?

**Comment by stevehipwell** [comment]
@shinebayar-g you can pull the branch and try the chart from the file system.

**Comment by shinebayar-g** [comment]
Just tested the changes.

My values

```yml
gateway:
  ingress:
    # -- Specifies whether an ingress for the gateway should be created
    enabled: true
    # -- Ingress Class Name. MAY be required for Kubernetes versions >= 1.18
    # ingressClassName: nginx
    # -- Annotations for the gateway ingress
    annotations:
      kubernetes.io/ingress.class: nginx
    # -- Hosts configuration for the gateway ingress
    hosts:
      - host: gateway.loki.example.com
        paths:
          - path: /
            # -- pathType (e.g. ImplementationSpecific, Prefix, .. etc.) might also be required by some Ingress Controllers
            pathType: Prefix
    # -- TLS configuration for the gateway ingress
    tls: []
```

Not sure `--version 0.35.1` was correct input, but did the job. Looks like I have correct results yay! 🚀 
```
helm template loki --namespace logging --version 0.35.1 --values myloki.yaml ./charts/loki-distributed/
```

```yml
---
# Source: loki-distributed/templates/gateway/ingress-gateway.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-loki-distributed-gateway
  labels:
    helm.sh/chart: loki-distributed-0.35.1
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: "2.2.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gateway
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "gateway.loki.example.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loki-loki-distributed-gateway
                port:
                  number: 80
```
