### ISSUE TITLE
Fail to deploy the Grafana with enabling https and NodePort

### ISSUE THREAD

**Issue by Kaka1127** [grafana/helm-charts#582]
I met the issue that Grafana did not deploy with using the values.yml file( enabled the https).   If comment out the https settings on garafana.ini file, grafana run correctly.   
Would you please give us your comments to deploy the grafana with https enabled and using the nodePort?
Here is the value file.

- value.yml
```
  service:
    type: NodePort
    nodePort: 30300
    portName: service
  grafana.ini:
    server:
      protocol: https
      cert_file: /etc/grafana/ssl/server.crt
      cert_key: /etc/grafana/ssl/server.key
  extraSecretMounts:
    - name: tls-crt-file
      mountPath: /etc/grafana/ssl/server.crt
      secretName: grafana-crt-file
      readOnly: false
      subPath: "server.crt"
      defaultMode: 0640
    - name: tls-key-file
      mountPath: /etc/grafana/ssl/server.key
      secretName: grafana-key-file
      readOnly: false
      subPath: "server.key"
      defaultMode: 0640
```
- Env 
   - kubernetes: v1.20.4
   - Grafana chart: latest

If you have any questions, please let me know.
Best regards.
Kaka

**Comment by cpawlyszyn** [comment]
@Kaka1127 I ran into a few issues with this as well, probably too late for you but figured I'd post my solution in case it helps someone in the future.

```yaml
ingress:
  enabled: True
  tls:
  - secretName: cert-secret
    hosts:
        - <DNS_alias>
  hosts:
    - <DNS_alias>
grafana.ini:
  server:
    protocol: https
    cert_file: /etc/grafana/certs/server.crt
    cert_key: /etc/grafana/certs/server.key
extraSecretMounts:
  - name: grafana-certs
    secretName: cert-secret
    mountPath: /etc/grafana/certs
    items:
      - key: tls.crt
        path: server.crt
      - key: tls.key
        path: server.key
readinessProbe:
  httpGet:
    scheme: HTTPS
livenessProbe:
  httpGet:
    scheme: HTTPS
service:
  type: NodePort
  nodePort: 30443
  port: 3000
```
