### ISSUE TITLE
Loki remote_write Not Working and No Error Message

### ISSUE THREAD

**Issue by Mark-Smithh** [grafana/helm-charts#631]
I have created a recording alert however I do not see the metric in Prometheus.  I see the alert running in the Loki log, and the log has zero error messages.  I also checked the Prometheus log and do not see an error related to this metric.

Remote write is enabled on the Prometheus instance and it is confirmed working.  Other processes are able to write to it successfully.

Expected Result:
If Loki cannot write the metric an error message should be returned.

Here is the recording rule.
```
groups:
  - name: jira
    rules:
    - expr: sum by (pod_namespace) (count_over_time({forwarder="vector"}[30d]))
      labels:
        severity: Medium
      record: xyz:xyz_HighJiraCaptcha403Count:sum
```

Here is a log entry that shows the rule runs:
```
level=info ts=2021-08-20T00:04:56.634724272Z caller=metrics.go:92 org_id=..data traceID=0f66bef5caa3edee latency=fast query="sum by(pod_namespace)(count_over_time({forwarder=\"vector\"}[30d]))" query_type=metric range_type=instant length=0s step=0s duration=2.695675ms status=200 limit=0 returned_lines=0 throughput=0B total_bytes=0B
```

Here is the rule config from the loki.yaml:
```
ruler:
  remote_write:
    client:
      basic_auth:
        password: ${PROM_PASSWORD}
        username: ${PROM_USER}
      tls_config:
        insecure_skip_verify: false
      url: https://myprometheus.com/api/v1/write
    enabled: true
  ring:
    kvstore:
      store: inmemory
  rule_path: /tmp/scratch
  storage:
    local:
      directory: /rules
    type: local
```

I also tried it like this:
```
ruler:
  enable_api: true
  remote_write:
    client:
      authorization:
        credentials: basic-auth-secret
        type: basic_auth
      tls_config:
        insecure_skip_verify: true
      url: https://myprometheus.com/api/v1/write
    enabled: true
  ring:
    kvstore:
      store: inmemory
  rule_path: /tmp/scratch
  storage:
    local:
      directory: /rules
    type: local
```
