### ISSUE TITLE
Does loki suport real cluster under multiple loki pods using this repo deployed

### ISSUE THREAD

**Issue by ningyougang** [grafana/helm-charts#637]
I did some test about local filesystem storage and ceph s3 both.

I deployed 3 loki pods including loki-0, loki-1, loki-2 and several promtail pods using `grafana/loki-stack helm chars`

### Local filesystem
* if the loki-0 pod stored the logs into local filesystem, but other pod(e.g. loki-1 or loki-2) recevied the query log request, can't query the logs. 
* It seems the log was not replicated between loki pods, so running Loki clustered is not possible with the local filesystem. My  test result proved the official document: https://grafana.com/docs/loki/latest/operations/storage/filesystem/
### ceph s3.
part of configuration as below
```
  schema_config:
    configs:
    - from: 2021-08-12
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h
  server:
    http_listen_port: 3100
  storage_config:
    boltdb_shipper:
      active_index_directory: /data/loki/boltdb-shipper-active
      cache_location: /data/loki/boltdb-shipper-cache
      cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
      shared_store: s3
    aws:
      s3: s3://xxx:xxx@xx.xx.xx.xx:80/<bucketName>
      s3forcepathstyle: true
```
* if the loki-0 pod stored the logs into ceph s3,  and if other pod(e.g. loki-1 or loki-2) recevied the query log request,  query the logs successfully, but exist some delay time, for my test, several minutes.
* I observed that after some time(maybe interval time), the index data will sync from ceph s3 to local filesystem.  e.g.

  ```
  level=info ts=2021-08-24T01:34:19.967296302Z caller=util.go:55 msg="downloaded file index_18863/loki-0-1629764359888401816-1629767700.gz"
  ```
  Also proved the document as well: https://grafana.com/docs/loki/latest/operations/storage/boltdb-shipper/

For my tests, i have `2` questions
* Not only filesystem but also shared storage(e.g. ceph s3), the loki pods are not form as a whole cluster like elasticsearch.

   Maybe on shared storage, these loki pods just look like a whole cluster, e.g. 
  - when write log, data flow is : log-> stored into `active_index_directory` locally -> sync the data to ceph s3. 

    BoltDB Shipper keeps looking for new and updated files in that directory every 15 Minutes to upload them to the shared object store

  - when query log, data flow is: sync the data from ceph s3 to `cache_location` -> to user 

    When a querier receives a read request, the query range from the request is resolved to period numbers and all the files for those period numbers are downloaded to cache_location, if not already. Once we have downloaded files for a period we keep looking for updates in shared object store and download them every 5 Minutes by default
  
  I don't know why in official doument, call it `loki cluster` ? it seems just multiple loki nodes.

* On ceph s3, in spite of query logs successfully on all loki pods, but still exist some delay time, have any mothod to improve it? e.g.
  - I tested more, need about 15 minutes of `all loki pods can query the log data after send create log request to one of the pod`
  - can query the data from all loki pods in real time? from document, it seems it is not possible to support it due to `it would consume some time for below operations`, e.g.
     - sync data from local filesystem(e.g. active_index_directory) to ceph s3,   it is 15 minutes  by default
     - sync data from ceph s3 to local filesystem(e.g. cache_location), it is 5 minutes by default
  - Have any other method to reduce the delay time?  e.g. if write request is sent to one of the loki pods, it is better to query the logs in 1 minute on all loki pods.
