### ISSUE TITLE
[promtail] Allow to configure all daemonset volumes

### ISSUE THREAD

**Issue by yafanasiev** [grafana/helm-charts#644]
Hi! 
As a part of running Promtail to collect logs from our Windows EKS worker nodes, I hit an issue with re-using the official chart with our custom-build image. Right now chart allows to configure mounting container log directories from host, but mount for positions file is hardcoded:
https://github.com/grafana/helm-charts/blob/2d25705d20e439a51b5d7e3363bd79056036f3ea/charts/promtail/templates/daemonset.yaml#L124-L126
If this volume is moved to `defaultVolumes` in values as well, we can re-use the chart without the need to fork it.
I can share the details on our current setup as well.

**Comment by Schildkroete23** [comment]
Hi @yafanasiev. Can you share the details of your current setup please? I am interested on using promtail for our windows nodes as well:)

**Comment by yafanasiev** [comment]
@Schildkroete23 of course. Our Dockerfile looks something like this:

```
# escape=`

FROM mcr.microsoft.com/windows/servercore:ltsc2019

ARG PROMTAIL_VERSION=2.3.0

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN New-Item -Type Directory -Path /promtail; `
	Invoke-WebRequest -Uri "https://github.com/grafana/loki/releases/download/v$($env:PROMTAIL_VERSION)/promtail-windows-amd64.exe.zip" -OutFile /promtail/promtail.zip; `
    Expand-Archive -Path /promtail/promtail.zip -Destination /promtail; `
	Remove-Item /promtail/promtail.zip; `
    Move-Item -Path /promtail/promtail-windows-amd64.exe -Destination /promtail/promtail.exe

ENTRYPOINT ["/promtail/promtail.exe"]
CMD ["-config.file=/etc/promtail/config.yml"]
```

and I had to copy over the promtail chart removing the aforementioned `run` volume.
These are the values that I use for the customized chart:

```
image:
  registry: REDACTED
  repository: REDACTED
  tag: 1.0.0
defaultVolumes:
  - name: varlog
    hostPath:
      path: C:/var
  - name: varlibdockercontainers
    hostPath:
      path: C:/ProgramData/Docker/containers
defaultVolumeMounts:
  - name: varlog
    mountPath: C:/var
    readOnly: false
  - name: varlibdockercontainers
    mountPath: C:/ProgramData/Docker/containers
    readOnly: true
podSecurityContext: null
nodeSelector:
  beta.kubernetes.io/arch: amd64
  beta.kubernetes.io/os: windows
tolerations:
  - operator: "Exists"
serviceMonitor:
  enabled: true
  labels:
    app: kube-prometheus-stack
    release: kube-prometheus-stack
  interval: 15s
  scrapeTimeout: 5s
config:
  lokiAddress: REDACTED
  snippets:
    extraClientConfigs: |
      basic_auth:
        username: REDACTED
        password: REDACTED
      external_labels:
        environment: staging
    pipelineStages:
      - docker: { }
      - labeldrop:
          - '__name__'
          - 'filename'
    common:
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_node_name
        target_label: node_name
      - action: replace
        source_labels:
          - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        replacement: $1
        separator: /
        source_labels:
          - namespace
          - app
        target_label: job
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: container
      - action: replace
        replacement: C:/var/log/pods/*$1/*.log
        separator: /
        source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: replace
        replacement: C:/var/log/pods/*$1/*.log
        regex: true/(.*)
        separator: /
        source_labels:
          - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
          - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
          - __meta_kubernetes_pod_container_name
        target_label: __path__
  file: |
    server:
      log_level: {{ .Values.config.logLevel }}
      http_listen_port: {{ .Values.config.serverPort }}

    client:
      url: {{ tpl .Values.config.lokiAddress . }}
      {{- tpl .Values.config.snippets.extraClientConfigs . | nindent 2 }}

    positions:
      filename: C:/var/positions.yaml

    scrape_configs:
      {{- tpl .Values.config.snippets.scrapeConfigs . | nindent 2 }}
      {{- tpl .Values.config.snippets.extraScrapeConfigs . | nindent 2 }}
```

This is running in production AWS EKS for 3 month for us without any issues. It would be great if this issue got some traction as this change is fairly simple but would go a long way for Windows users. Maybe even an official Windows Containers image? 😄
