### ISSUE TITLE
[enterprise-logs] Run GEL containers as non root user

### ISSUE THREAD

**Issue by chaudum** [grafana/helm-charts#687]
The Pods that are created by the parent chart do not have a security context configured. However, since the GEL Docker container runs as user `enterprise-logs` (`uid=10001,gid=10001`), their security context needs to be configured accordingly.

```yaml
securityContext:
  runAsNonRoot: true
  runAsGroup: 10001
  runAsUser: 10001
  fsGroup: 10001
```
