### ISSUE TITLE
cannot patch "gateway" with kind Ingress: admission webhook "vingress.elbv2.k8s.aws" denied the request: invalid ingress class: IngressClass.networking.k8s.io "nginx" not found

### ISSUE THREAD

**Issue by ilovemysillybanana** [grafana/helm-charts#688]
Unable to upgrade from version `0.35.0` of the Helm chart, tried going to `0.36.0` and `0.37.0`. 

This is what the configuration for it looks like:

```yaml
gateway:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    tls:
      - secretName: ${certificate_secret_name}
        hosts:
          - ${hostname}
    hosts:
      - host: ${hostname}
        paths:
          - path: /
            pathType: Prefix
  service:
    type: "NodePort"
    port: 8080
```

But this matches the existing example in the documentation:

```yaml
gateway:
  ingress:
    enabled: true
    # Newly added optional property
    ingressClassName: nginx
    hosts:
      - host: gateway.loki.example.com
        paths:
          # New data structure introduced
          - path: /
            # Newly added optional property
            pathType: Prefix
```
