### ISSUE TITLE
Question: How to set anonymous login via the helm chart?

### ISSUE THREAD

**Issue by sfro** [grafana/helm-charts#71]
I want disable the login screen for anonymous users, so that anyone can go in as a ReadOnly user. I know this is possible to set in grafana.ini, but I am failing to set this in values.yaml. This is what I have tried with:

```
auth.anonymous:
  enabled: true
  org_role: VIEWER
  org_name: 'Main Org.'
```

Am I missing something? There is no example for this in values.yaml, so perhaps there is no support for this yet?

**Comment by sfro** [comment]
I worked it out, it had to go under the `grafana.ini` key 😛

**Comment by raj-shekhar1** [comment]
I tried this with the main org but it is not working for me without the login. Did you configured anything else also apart from this? @sfro

**Comment by nichelia** [comment]
For future reference, I have added the below to my values.
```yaml
grafana:
  enabled: true
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_name: <organisation name>
      org_role: Viewer
```
