### ISSUE TITLE
How to solve issue about Promtail extraScrapeConfigs not being picked up?

### ISSUE THREAD

**Issue by yusufkaratoprak** [grafana/helm-charts#730]
**Describe the bug**
It seems that dropping a namespace **kube-system** and saving a gateway **ambassador** by using the configuration below does not work:
**To Reproduce**
1.Writing configuration 👍  loki-stack-values-v2.4.1.yaml

```
loki:
  enabled: true
  config:

promtail:
  enabled: true
  extraScrapeConfigs:
  - job_name: kubernetes-pods-name
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: drop
        regex: .+
      - action: keep
        regex: ambassador
        source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_namespace
  - job_name: kubernetes-pods-app
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: drop
        regex: .+
      - action: keep
        regex: ambassador
        source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_namespace
 
  - job_name: kubernetes-pods-direct-controllers
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: drop
        regex: .+
      - action: keep
        regex: ambassador
        source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_namespace

  - job_name: kubernetes-pods-indirect-controller
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: drop
        regex: .+
      - action: keep
        regex: ambassador
        source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_namespace

  - job_name: kubernetes-pods-static
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: drop
        regex: .+
      - action: keep
        regex: ambassador
        source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_namespace


fluent-bit:
  enabled: false

grafana:
  enabled: false

prometheus:
  enabled: false
```
2. Started Promtail (SHA or version) to tail '...' 👍 
```
helm upgrade loki grafana/loki-stack --version "2.4.1" \
  --namespace=monitoring \
  --create-namespace \
  -f "loki-stack-values-v2.4.1.yaml" 
```

3. Query: `{namespace="ambassador"}`

**Expected behavior**
I am waiting some logs on screen.But I didn't see any `ambassador` logs also autocomplete stop working. 
**Environment:**
 - Infrastructure: [ Kubernetes v1.22.2 (client) ,  kubernetes v1.21.3 (server), Digitalocean ]
 - Deployment tool: [helm]

**Screenshots, Promtail config, or terminal output**
Actually, I am using only the above configuration. 

when I check logs and description : 

Describe : 
```
kubectl describe pod loki-promtail-mjn9j -n monitoring > test2.yaml
```
```
  Type     Reason     Age                     From     Message
  ----     ------     ----                    ----     -------
  Warning  Unhealthy  4m43s (x5040 over 14h)  kubelet  Readiness probe failed: HTTP probe failed with statuscode: 500
```
Logs:

```
kubectl logs loki-promtail-mjn9j -n monitoring > test1.yaml
```

output:

```
level=info ts=2021-10-05T20:46:34.209638183Z caller=kubernetes.go:263 component=discovery discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-10-05T20:46:34.212270245Z caller=server.go:225 http=[::]:3101 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2021-10-05T20:46:34.21290287Z caller=main.go:110 msg="Starting Promtail" version="(version=2.1.0, branch=HEAD, revision=1b79df375)"
level=warn ts=2021-10-05T20:46:52.759679036Z caller=logging.go:71 msg="GET /ready (500) 92.638µs Response: \"Not ready: Unable to find any logs to tail. Please verify permissions, volumes, scrape_config, etc.\\n\" ws: false; Accept: */*; Connection: close; User-Agent: kube-probe/1.21; "
```

**Comment by zanhsieh** [comment]
loki-stack updated: See: https://github.com/grafana/helm-charts/pull/1692

@dannykopping @yusufkaratoprak 
Feel free to close this issue if you feel satisfied.

**Comment by ndlanier** [comment]
This issue is old so I'll comment, I don't think it fixed it. I'm not seeing a syslog job in grafana and no mention of syslog in the container logs for promtail. I'm using argocd and when I edit the values field with my overrides, none of the resources goes out of sync. 

My overrides:
```
promtail:
  extraScrapeConfigs:
  - job_name: syslog
    syslog:
      listen_address: 172.16.0.174:30000
      labels:
        job: "syslog"
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
  syslogService:
    enabled: true
    type: LoadBalancer
    port: 30000
```
