### ISSUE TITLE
Grafana image renderer CrashLoopBackoff due to NetPol

### ISSUE THREAD

**Issue by clementnuss** [grafana/helm-charts#795]
The issue is the following:
if you enable `imageRenderer: true` in your Grafana Helm Chart, a default Network Policy will be created, which will only allow the traffic coming from namespace labeled as follows: ([here is the Helm chart](https://github.com/grafana/helm-charts/blob/grafana-6.17.5/charts/grafana/templates/image-renderer-network-policy.yaml#L27))
```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: my-ns
  name: my-ns
```

In my case though, the namespace didn't have this label but only a `kubernetes.io/metadata.name: my-ns`  label.
The liveness probe was therefore failing and my container was in the CrashLoopBackoff state.

Adding the label `name: my-ns` solves the issue for the grafana pod, but the liveness probe still fails.
