### ISSUE TITLE
[tempo] native tempo search

### ISSUE THREAD

**Issue by kseniyashaydurova** [grafana/helm-charts#813]
Hi! Are you sure that native tempo search works correctly? I enabled search in the helm chart with `searchEnabled: true` param, updated tempo to `0.10.0` and grafana to `6.17.5` versions, but I don't see any `Search` tab in grafana.

What am I doing wrong?

![image](https://user-images.githubusercontent.com/26448672/141455836-77c82836-72be-4486-ba45-58bb81a9f47c.png)

I have this `tempo` ConfigMap:

```yaml
apiVersion: v1
data:
  overrides.yaml: |
    overrides:
  tempo.yaml: |
    auth_enabled: false
    search_enabled: true
    compactor:
      compaction:
        compacted_block_retention: 240h
    distributor:
      receivers:
        jaeger:
          protocols:
            grpc:
              endpoint: 0.0.0.0:14250
            thrift_binary:
              endpoint: 0.0.0.0:6832
            thrift_compact:
              endpoint: 0.0.0.0:6831
            thrift_http:
              endpoint: 0.0.0.0:14268
        opencensus:
          endpoint: 0.0.0.0:55678
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:55681
        zipkin:
          endpoint: 0.0.0.0:9411
    ingester:
      max_block_bytes: 1000000
      max_block_duration: 5m
      trace_idle_period: 10s
    server:
      http_listen_port: 3100
    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
        wal:
          path: /var/tempo/wal
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tempo
    app.kubernetes.io/version: 1.2.0
    argocd.argoproj.io/instance: tempo
    helm.sh/chart: tempo-0.10.0
  name: tempo
  namespace: monitoring
```
