### ISSUE TITLE
Unable to use AWS EFS persistent volume claim with Grafana

### ISSUE THREAD

**Issue by alysonfranklin** [grafana/helm-charts#814]
helm chart version: 6.16.13

Describe the bug After installing Grafana with the below YAML, status of pod grafana is "Init:Error". This pod uses Amazon EFS persistent volume claim. On describing the pod, the error message is **"Error from server (BadRequest): container "grafana" in pod "grafana-57cbcf64bd-rl49h" is waiting to start: PodInitializing"**.

```yaml
persistence:                                                                                                                                                  
  type: pvc                                                                                                                                                   
  enabled: true                                                                                                                                               
  storageClassName: aws-efs                                                                                                                                       
  accessModes:                                                                                                                                                
    - ReadWriteOnce                                                                                                                                           
  size: 20Gi                                                                                                                                                  
  # annotations: {}                                                                                                                                           
  finalizers:                                                                                                                                                 
    - kubernetes.io/pvc-protection                                                                                                                            
  # selectorLabels: {}                                                                                                                                        
  # subPath: ""                                                                                                                                               
  existingClaim: grafana-efs 
  ```

Has anyone managed to provision grafana with aws EFS?
