### ISSUE TITLE
promtail cannot send log to loki-gateway server with error 401 Unauthorized message

### ISSUE THREAD

**Issue by alysonfranklin** [grafana/helm-charts#819]
I Added auth_basic to loki-gateway, but promtail cannot connect to loki-gateway using auth_basic.

**Loki-distributed helm chart version: 0.38.0
Promtail helm chart version: 3.8.1**

I'm getting the following error in Promtail:

```
level=error ts=2021-11-13T19:02:12.291631019Z caller=client.go:355 component=client host=loki-loki-distributed-gateway msg="final error sending batch" s
tatus=401 error="server returned HTTP status 401 Unauthorized (401): <html>" 
```

```yaml
  snippets:                                                                                                                                             
    extraClientConfigs: |                                                                                                                               
      basic_auth:                                                                                                                                       
        username: loki_user                                                                                                                  
        password: loki_password                                                                                                          
      tenant_id: 1
```
