### ISSUE TITLE
[enterprise-logs] extraArgs is an object but in loki-distributed it is an array

### ISSUE THREAD

**Issue by jdbaldry** [grafana/helm-charts#850]
In order to set `--log.level=debug` on all microservices:

In GEL controlled templates:
```yaml
gateway:
  extraArgs:
    log.level: debug
```

In loki-distributed:
```yaml
querier:
  extraArgs:
    - --log.level=debug
```
