### ISSUE TITLE
Question: How to add values to plugin datasource

### ISSUE THREAD

**Issue by aekiratli** [grafana/helm-charts#86]
![image](https://user-images.githubusercontent.com/52128960/99307547-b3e7fd80-2867-11eb-9e3b-b3fdaf9d6875.png)

I'm using alertmanager datasource and this is my config:

```
plugins: 
  - camptocamp-prometheus-alertmanager-datasource

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
      isDefault: true

    - name: 'Prometheus AlertManager'
      type: 'camptocamp-prometheus-alertmanager-datasource'
      url: http://prometheus-alertmanager.monitoring.svc.cluster.local
      isDefault: false
      editable: true
```

How can I edit severity levels or is this even possible?
