### ISSUE TITLE
Allow setting home path declaratively

### ISSUE THREAD

**Issue by holmesb** [grafana/helm-charts#88]
Add ability to set [default_home_dashboard_path](https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L256) using this helm chart.

**Comment by owenmonagan** [comment]
Im passing a values file that has this set.

```
 grafana.ini:
   dashboards:
     default_home_dashboard_path: <PATH-TO-DASHBOARD>
```
and it works fine.

**Comment by SoerenHenning** [comment]
For me, this simply doesn't work. I'm always getting the *Welcome to Grafana* dashboard. My values.yaml file looks as follows:

```yaml
grafana:
  image:
    repository: grafana/grafana
    tag: 6.7.3
    pullPolicy: IfNotPresent
  adminUser: admin
  adminPassword: admin
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_role: Admin
    users:
      default_theme: light
  grafana.ini:
    dashboards:
      default_home_dashboard_path: "/tmp/dashboards/k8s-dashboard.json"
```

Could this be due to the sidecar, which loads the dashboard from a ConfigMap?

```yaml
  sidecar:
    image:
      repository: "kiwigrid/k8s-sidecar"
      tag: "0.1.99"
    imagePullPolicy: IfNotPresent
    dashboards:
      enabled: true
      provider:
        allowUiUpdates: true
```

Do you have any ideas how to debug this? I can't find any log messages saying something like the provided path is wrong or so.
