### ISSUE TITLE
Promtail and loki-prometheus-node-exporter are trying to run on AKS windows nodes

### ISSUE THREAD

**Issue by filipc** [grafana/helm-charts#886]
AKS supports to have Windows nodes attached to the K8s cluster. The system version is Windows 2019 Datacenter.

Loki deployed from _loki-stack_ helm chart. **Promtail** and **prometheus-node-exporter** pods are trying to run there, but there's no windows version.

So far I've prevented promtail execution by setting up nodeSelector:

`--set promtail.nodeSelector."kubernetes\.io/os"=linux`

and it works for promtail, but I don't know how to set the same for loki-prometheus-node-exporter

Shouldn't it be set by default to execute on linux based nodes only?

**Comment by hrodrig** [comment]
Hi, we are using loki-stack to deploy all grafana stack. We have an AKS cluster with system and user node pool sets. To avoid that prometheus-node-exporter will be deployed as daemonset on the system node pool nodes, afetr may tries we found that using `nodeSelector` and correct node label, we can restrict that prometheus-node-exporter only to user pool nodes.

Here all all our loki-stack-values.yaml file. For simplicity we use a simple bash command to upgrade/install helm chart.


```bash
helm  upgrade --install loki grafana/loki-stack --namespace=mynamespace --set version="2.6.5" -f ./loki-stack-values.yaml
```

The content of our loki-stack-values.yaml file is the following. Search by `nodeExporter` key...

Other deployment works fine using the `affinity` spec.

```yaml
#--------------------------------------------------------
# https://github.com/grafana/helm-charts/tree/main/charts/loki
#--------------------------------------------------------
# https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml
#======================================
loki:
  enabled: true
  isDefault: false
  persistence:
    enabled: true
    storageClass: default
    accessModes:
      - ReadWriteOnce
    size: 128Gi
  resources:
    limits:
      cpu: 1500m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  config:
    #----------------------------------------------------------------
    limits_config:
      # Whether or not old samples will be rejected.
      reject_old_samples: true
      # Maximum accepted sample age before rejecting.
      reject_old_samples_max_age: 720h
      # Maximum number of log entries that will be returned for a query.
      max_entries_limit_per_query: 50000
      # Most recent allowed cacheable result per-tenant, to prevent caching very
      # recent results that might still be in flux.
      max_cache_freshness_per_query: 20m
      # Split queries by a time interval and execute in parallel. The value 0 disables
      # splitting by time. This also determines how cache keys are chosen when result
      # caching is enabled.
      split_queries_by_interval: 25m
    #----------------------------------------------------------------
    # Configure loki to reduce memory consumption after many days
    #
    # The chunk_store_config block configures how chunks will be cached and how long
    # to wait before saving them to the backing store.
    # https://github.com/grafana/loki/issues/9110
    chunk_store_config:
      # The maximum amount of time to look back for log lines. Used only for instant
      # log queries.
      # CLI flag: -querier.engine.max-lookback-period
      max_look_back_period: 0s
      chunk_cache_config:
        # The maximum number of enqueued asynchronous writeback cache allowed.
        async_cache_write_back_buffer_size: 1
        default_validity: 5m
        fifocache:
          ttl: 5m
          size: 0
          max_size_bytes: 1GB
    #----------------------------------------------------------------
  nodeSelector: {}
  annotations:
    sidecar.istio.io/inject: "false"
  podAnnotations:
    sidecar.istio.io/inject: "false"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.azure.com/agentpool
            operator: In
            values:
            - user
          - key: kubernetes.azure.com/mode
            operator: In
            values:
            - user
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.azure.com/mode
            operator: In
            values:
            - user
  tolerations: []
#--------------------------------------------------------
# https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml
#======================================
promtail:
  enabled: true
  config:
    lokiAddress: http://{{ .Release.Name }}:3100/loki/api/v1/push
  resources:
    limits:
      cpu: 200m
      memory: 1024Mi
    requests:
      cpu: 10m
      memory: 128Mi
  nodeSelector: {}
  annotations:
    sidecar.istio.io/inject: "false"
  podAnnotations:
    sidecar.istio.io/inject: "false"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.azure.com/agentpool
            operator: In
            values:
            - user
          - key: kubernetes.azure.com/mode
            operator: In
            values:
            - user
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.azure.com/mode
            operator: In
            values:
            - user
  tolerations: []
#======================================
grafana:
  enabled: true
  containerSecurityContext:
    runAsNonRoot: true
    runAsUser: 472
    runAsGroup: 472
  sidecar:
    datasources:
      enabled: true
      maxLines: 1000
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 50Mi
    securityContext:
      capabilities:
        drop:
        - ALL
      allowPrivilegeEscalation: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472
    capabilities:
      drop:
      - ALL
    allowPrivilegeEscalation: false
  persistence:
    enabled: true
    type: pvc
    accessModes:
      - ReadWriteOnce
    size: 64Gi
    finalizers:
      - kubernetes.io/pvc-protection
  admin:
    existingSecret: "loki-stack"
    userKey: GRAFANA_ADMIN
    passwordKey: GRAFANA_PASSWORD
  resources:
    limits:
      cpu: 800m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.azure.com/agentpool
            operator: In
            values:
            - user
          - key: kubernetes.azure.com/mode
            operator: In
            values:
            - user
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.azure.com/mode
            operator: In
            values:
            - user
  nodeSelector: {}
  annotations:
    sidecar.istio.io/inject: "false"
  podAnnotations:
    sidecar.istio.io/inject: "false"
  tolerations: []
  grafana.ini:
    paths:
      data: /var/lib/grafana/
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    analytics:
      check_for_updates: false
      reporting_enabled: false
    log:
      mode: console
    grafana_net:
      url: https://grafana.net
    security:
      allow_embedding: true
    auth:
      anonymous:
        enabled: false
    server:
      # FIXME: set valid value here
      root_url: https://mytelemetry.url.co/
      serve_from_sub_path: true
#======================================
prometheus:
  enabled: true
  isDefault: false
  server:
    persistentVolume:
      enabled: true
      size: 64Gi
    resources:
      limits:
        cpu: 500m
        memory: 2048Mi
      requests:
        cpu: 100m
        memory: 128Mi
    nodeSelector: {}
    annotations:
      sidecar.istio.io/inject: "false"
    podAnnotations:
      sidecar.istio.io/inject: "false"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.azure.com/agentpool
              operator: In
              values:
              - user
            - key: kubernetes.azure.com/mode
              operator: In
              values:
              - user
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: kubernetes.azure.com/mode
              operator: In
              values:
              - user
    tolerations: []
  #--------------------------------------------------------
  kubeStateMetrics:
    enabled: true
  ## kube-state-metrics sub-chart configurable values
  ## Please see https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics
  ##
  kube-state-metrics:
    resources:
      limits:
        cpu: 800m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 128Mi
    nodeSelector: {}
    annotations:
      sidecar.istio.io/inject: "false"
    podAnnotations:
      sidecar.istio.io/inject: "false"
    affinity: {}
    tolerations: []
  #--------------------------------------------------------
  nodeExporter:
    enabled: true
    resources:
      limits:
        cpu: 400m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 128Mi
    nodeSelector:
      kubernetes.io/os: linux
      kubernetes.azure.com/agentpool: user
      kubernetes.azure.com/mode: user
    annotations:
      sidecar.istio.io/inject: "false"
    podAnnotations:
      sidecar.istio.io/inject: "false"
    tolerations: []
  #--------------------------------------------------------
  alertmanager:
    enabled: false
    persistentVolume:
      enabled: true
      size: 16Gi
    resources:
      limits:
        cpu: 200m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 128Mi
    nodeSelector: {}
    annotations:
      sidecar.istio.io/inject: "false"
    podAnnotations:
      sidecar.istio.io/inject: "false"
    affinity: {}
    tolerations: []
  #--------------------------------------------------------
  configmapReload:
    prometheus:
      enabled: true
      name: configmap-reload
      resources:
        limits:
          cpu: 100m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 128Mi
      nodeSelector: {}
      annotations:
        sidecar.istio.io/inject: "false"
      podAnnotations:
        sidecar.istio.io/inject: "false"
      affinity: {}
      tolerations: []
    alertmanager:
      enabled: true
      name: configmap-reload
      resources:
        limits:
          cpu: 100m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 128Mi
      nodeSelector: {}
      annotations:
        sidecar.istio.io/inject: "false"
      podAnnotations:
        sidecar.istio.io/inject: "false"
      affinity: {}
      tolerations: []
  #--------------------------------------------------------
  pushgateway:
    enabled: false
    resources:
      limits:
        cpu: 200m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 128Mi
    nodeSelector: {}
    annotations:
      sidecar.istio.io/inject: "false"
    podAnnotations:
      sidecar.istio.io/inject: "false"
    affinity: {}
    tolerations: []
  #--------------------------------------------------------
#======================================

```
