### ISSUE TITLE
loki - ingress failing after upgrading from 2.8.1

### ISSUE THREAD

**Issue by AlaaAttya** [grafana/helm-charts#912]
values file

```
image:
  repository: grafana/loki
  tag: 2.4.1
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: loki.trxy.local
      paths:
        - /

## Pod Annotations
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "http-metrics"    


resources:
  limits:
    cpu: 200m
    memory: 1000Mi
  requests:
    cpu: 100m
    memory: 1000Mi

persistence:
  enabled: true
  accessModes:
  - ReadWriteOnce
  size: 15Gi    
  storageClassName: longhorn-custom

```
