### ISSUE TITLE
[grafana] https not working with service type LoadBalancer

### ISSUE THREAD

**Issue by wilinger** [grafana/helm-charts#914]
I can't seem to get https working with service.type: LoadBalancer on my bare metal cluster even though I have the same settings on every other application's helm chart and https is working for those applications. Tried both service.port: 443 and 80 but does not work.  

Grafana Chart version: 6.20.3
App version 8.3.4

```
kubectl get all
NAME                           READY   STATUS    RESTARTS   AGE
pod/grafana-859b679c6c-brwd7  1/1     Running   0          57s

NAME              TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
service/grafana   LoadBalancer   10.233.17.191   10.10.30.76   80:31742/TCP   58s

```
```
  service:
    enabled: true
    type: LoadBalancer
    loadBalancerIP: "10.10.10.50"
    port: 80
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true" 
    path: /
    pathType: Prefix
    hosts:
      - grafana.example.org
    extraPaths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
    tls:
      - secretName: letsencrypt-prod
        hosts:
          - grafana.example.org
```
