### ISSUE TITLE
[tempo-distributed] Adding custom grpc client config for querier

### ISSUE THREAD

**Issue by irizzant** [grafana/helm-charts#930]
Hello
at the moment it's not possible to add a custom grpc client configuration in the [values file](https://github.com/grafana/helm-charts/blob/c490602c674b108b61ee4a4d2807e621f278bdf4/charts/tempo-distributed/values.yaml#L199) unless you redefine the config like this:

```yaml
config: |
  querier:
    frontend_worker:
      frontend_address: {{ include "tempo.queryFrontendFullname" . }}-discovery:9095
      grpc_client_config:
        {{- toYaml .Values.querier.config.grpc_client_config | nindent 6 }}
```

It would be useful to allow this configuration in the values file directly, like for compactor [storage retention](https://github.com/grafana/helm-charts/blob/c490602c674b108b61ee4a4d2807e621f278bdf4/charts/tempo-distributed/values.yaml#L196)
