### ISSUE TITLE
Question : OpsGenie notifier integration

### ISSUE THREAD

**Issue by qdupuy** [grafana/helm-charts#940]
Hello, 🖖 

When I try to configure opsgenie on grafana via the helm charts in the notifiers section, the configuration is not present on grafana.

Did I forget an option or a configuration?

Configuration file : 

```
      - name: opsgenie-notifier
        type: opsgenie
        uid: opsgenie-notifier
        description: 'Sends notifications to OpsGenie'
        # either
        org_id: 1
        # or
        #org_name: Main Org.
        is_default: false
        send_reminder: true
        frequency: 30m
        disable_resolve_message: false
        settings:
          recipient: '#infra-alerts'
          uploadImage: true
          apiKey: x
          apiUrl: x
          autoClose: true
```
