### ISSUE TITLE
[loki] grpc 

### ISSUE THREAD

**Issue by pindge** [grafana/helm-charts#946]
## Our config

```
    extraArgs:
      # increase default: https://grafana.com/docs/loki/latest/configuration/#server_config
      # address error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (10453341 vs. 4194304)
      # extraArg can be found with loki help command ./loki -h
      server.grpc-max-recv-msg-size-bytes: 12582912 # triple the default
      server.grpc-max-send-msg-size-bytes: 12582912 # triple the default
```

## Issue

The `max-msg-size-byte` is converted to scientific notation and causing loki failing to start
```
invalid value "1.2582912e+07" for flag -server.grpc-max-recv-msg-size-bytes: parse error
Run with -help to get list of available parameters
```

##  Problem code
https://github.com/grafana/helm-charts/blob/main/charts/loki/templates/statefulset.yaml#L60
