### ISSUE TITLE
[grafana] Can not set generic_oauth in grafana.ini

### ISSUE THREAD

**Issue by devent** [grafana/helm-charts#948]
Try to set generic_oauth in grafana.ini:

```
  grafana.ini:
    paths:
      data: /var/lib/grafana/
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    analytics:
      check_for_updates: true
    log:
      mode: console
    grafana_net:
      url: https://grafana.net
    auth:
      disable_login_form: true
      generic_oauth:
        enabled: true
        name: OAuth
        allow_sign_up: false
        client_id: "grafana.xxx"
        client_secret: "xxx"
        scopes: "openid profile email"
        auth_url: "https://xxx/auth"
        token_url: "https://xxx/token"
        api_url: "https://xxx/userinfo"

```

Resulted grafana.ini:

```
[...]
[auth]
disable_login_form = true
generic_oauth = map[allow_sign_up:false api_url:https://sso.xxx/auth/realms/infra/protocol/openid-connect/userinfo auth_url:https://sso.xxx/auth/realms/infra/protocol/openid-connect/auth client_id:grafana.xxx client_secret:xxx enabled:true name:OAuth scopes:openid profile email token_url:https://sso.xxx/auth/realms/infra/protocol/openid-connect/token]

```

Chart Version 6.20.5

**Comment by devent** [comment]
Ok, it should be 
```
    auth:
      disable_login_form: true
    auth.generic_oauth:
      enabled: true
      name: OAuth
```
