### ISSUE TITLE
[loki-stack]: loki pod high memory consumption.

### ISSUE THREAD

**Issue by thuban-arrakis** [grafana/helm-charts#954]
Stagting from 05.01.2022 Loki continuously killed by OOM, after get hits 1Gi StatefulSet resource limits.
Before that, average memory usage is about 400M.

- 'loki-stack' chart with version '2.5.1'
- environment: GKE
-  images: grafana/loki:2.4.1 & grafana/promtail:2.1.0

No configuration changes was made, no extreme logs load.

![image](https://user-images.githubusercontent.com/41233597/148992424-37c34827-0784-4b7b-bad7-146630592c80.png)
![image](https://user-images.githubusercontent.com/41233597/148995951-2979049a-9bfe-4f40-9565-8f42ba50412e.png)

HelmChart values:

```
    loki:
      replicas: 1

      resources:
        requests:
          cpu: 2000m
          memory: 1024Mi
        limits:
          memory: 1024Mi

      persistence:
        enabled: true
        size: 200Gi

      config:
        server:
          log_level: info
        limits_config:
          ingestion_rate_mb: 10
          ingestion_burst_size_mb: 20
          max_concurrent_tail_requests: 20
          max_cache_freshness_per_query: 10m
        schema_config:
          configs:
            - from: "2021-02-28"
              store: boltdb-shipper
              schema: v11
              object_store: gcs
              index:
                prefix: idx_
                period: 24h

        table_manager:
          retention_deletes_enabled: true
          retention_period: 672h
```

go tool pprof:

![out](https://user-images.githubusercontent.com/41233597/148994411-5fe7d67d-f2de-44d3-9c03-81ec3a55f321.png)

Any suggestions to resolve issue are apreciated.

**Comment by bkupidura** [comment]
Can confirm same behavior, after upgrading from 2.5.0 helm chart to 2.6.0 i see high memory usage by loki pod.

My config for loki-stack are very basic:
```
  valuesContent: |-
    loki:
      enabled: true
      persistence:
        enabled: true
        existingClaim: loki
      resources:
        requests:
          cpu: 20m
          memory: 256Mi
        limits:
          cpu: 30m
          memory: 384Mi
    promtail:
      enabled: true
      resources:
        requests:
          cpu: 20m
          memory: 64Mi
        limits:
          cpu: 40m
          memory: 128Mi
    fluent-bit:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false
    filebeat:
      enabled: false
    logstash:
      enabled: false
```

<img width="1421" alt="Screenshot 2022-02-18 at 20 34 46" src="https://user-images.githubusercontent.com/4814684/154749901-30cf26f9-20d7-4c99-9077-2ad603a1af2b.png">
