### ISSUE TITLE
[tempo-distributed] Add custom grpc configuration for server

### ISSUE THREAD

**Issue by irizzant** [grafana/helm-charts#972]
Hello
at the moment it's not possible to add a custom server grpc configuration in the [values file](https://github.com/grafana/helm-charts/blob/cf2c3ea0a45b0ba627a95581fc43a509211a9f03/charts/tempo-distributed/values.yaml#L468) unless you redefine the config like this:

```yaml
server:
  grpc_server_max_recv_msg_size: 1.34217728e+08
  grpc_server_max_send_msg_size: 1.34217728e+08
...
config: |
  server:
     grpc_server_max_recv_msg_size: {{ .Values.server.grpc_server_max_recv_msg_size }}
     grpc_server_max_send_msg_size: {{ .Values.server.grpc_server_max_send_msg_size }}
```

It would be useful to allow this configuration in the values file directly, like for compactor [storage retention](https://github.com/grafana/helm-charts/blob/c490602c674b108b61ee4a4d2807e621f278bdf4/charts/tempo-distributed/values.yaml#L196)
