### ISSUE TITLE
how to rename existing datasource from the datasource configmap?

### ISSUE THREAD

**Issue by shay-berman** [grafana/helm-charts#98]
I tried to change the datasource name in my configmap and then reload grafana (using kube-prometheus-stack helm)
but then it just added another datasource with the new name.

Is it posible to rename datasource in grafana via the configmap?

```

kubectl get cm prom-kube-prometheus-stack-grafana-datasource -o yaml
apiVersion: v1
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - access: proxy
      editable: false
      name: prometheus1
      type: prometheus
      url: http://prometheus:9090
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prom
    meta.helm.sh/release-namespace: prometheus
  labels:
    app: kube-prometheus-stack-grafana
    app.kubernetes.io/managed-by: Helm
    chart: kube-prometheus-stack-11.1.1
    grafana_datasource: "1"
    heritage: Helm
    release: prom
  name: prom-kube-prometheus-stack-grafana-datasource
  namespace: prometheus

```

but if I kubectl edit this configmap and change the name from prometheus1 -> prometheusX, it will not actually rename the datasource on grafana, it will add another one.

is it posible to rename grafana datasource in k8s?  (reminder when using datasource as configmap its not posible to edit the datasource from the Grafana UI)

**Comment by shay-berman** [comment]
anyone?

also opened in kube-prometheus-stack https://github.com/prometheus-community/helm-charts/issues/443

**Comment by GMartinez-Sisti** [comment]
@shay-berman is this helpful: https://github.com/grafana/helm-charts/blob/main/charts/grafana/README.md#sidecar-for-datasources:

Adding this to your datasource definition could fix you problem:

```yaml
# list of datasources that should be deleted from the database
    deleteDatasources:
      - name: Prometheus
        orgId: 1
```
