### ISSUE TITLE
[grafana] CloudWatch Datasource using configmap provising

### ISSUE THREAD

**Issue by dotdc** [grafana/helm-charts#995]
Hi there 👋

I have an issue with the AWS "CloutWatch" datasource in Grafana 8.3.4.
I'm trying to create a cloudwatch datasource using configmap provisioning using Grafana on Kubernetes (EKS) with the official Helm Chart (latest, thru kube-prometheus-stack).

Here's my datasource configuration:

```
  - name: CloudWatch
    type: cloudwatch
    access: proxy
    editable: yes
    jsonData:
      authType: keys
      defaultRegion: us-east-1
    secureJsonData:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
```
(variables are correctly set/evaluated)

The datasource gets created but:

1. It doesn't contain the `accessKey` / `secretKey`
2. `Authentification Provider` is not set to `Access & secret key` like I would expect with `authType: keys`
( see screenshot of the UI below)

Documentation links :
- https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources
- https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/provision-cloudwatch/#using-accesskey-and-secretkey

Screenshots :

- Data in console : [2022-01-25-grafana-chrome-console.png](https://raw.githubusercontent.com/dotdc/media/main/github-issues/2022-01-25-grafana-chrome-console.png)
- Datasource in UI : [2022-01-25-grafana-cloudwatch-datasource.png](https://raw.githubusercontent.com/dotdc/media/main/github-issues/2022-01-25-grafana-cloudwatch-datasource.png)

Is this a bug or a configuration problem?

Thank you :slightly_smiling_face:
