### ISSUE TITLE
[loki] err="mkdir : no such file or directory

### ISSUE THREAD

**Issue by scybZhangliang** [grafana/helm-charts#997]
i've search the issues, there is no resolution for me.
with my values.yaml
```
image:
  repository: harbor.tk.com/iot.tk/loki
  tag: 2.4.2
  pullPolicy: IfNotPresent


## StatefulSet annotations
annotations: {}

# enable tracing for debug, need install jaeger and specify right jaeger_agent_host
tracing:
  jaegerAgentHost:

config:
  # existingSecret:
  auth_enabled: false
  ingester:
    chunk_idle_period: 3m
    chunk_block_size: 262144
    chunk_retain_period: 1m
    max_transfer_retries: 0
    wal:
      dir: /data/loki/wal
    lifecycler:
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1

  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
  schema_config:
    configs:
    - from: 2022-01-24
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: index_
        period: 24h
  server:
    http_listen_port: 3100
  storage_config:
    aws:
      endpoint: minio.default.svc.cluster.local
      insecure: true
      bucketnames: loki-data
      access_key_id: minioadmin
      secret_access_key: minioadmin
      s3forcepathstyle: true
  chunk_store_config:
    max_look_back_period: 0s
  table_manager:
    retention_deletes_enabled: false
    retention_period: 0s
  compactor:
    working_directory: /data/loki/boltdb-shipper-compactor
    shared_store: s3

## Additional Loki container arguments, e.g. log level (debug, info, warn, error)
extraArgs: {}
  # log.level: debug

livenessProbe:
  httpGet:
    path: /ready
    port: http-metrics
  initialDelaySeconds: 45

## ref: https://kubernetes.io/docs/concepts/services-networking/network-policies/
networkPolicy:
  enabled: false

## The app name of loki clients
client: {}
  # name:

## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
nodeSelector: {}

## ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
## If you set enabled as "True", you need :
## - create a pv which above 10Gi and has same namespace with loki
## - keep storageClassName same with below setting
persistence:
  enabled: false
  accessModes:
  - ReadWriteOnce
  size: 10Gi
  annotations: {}
  # selector:
  #   matchLabels:
  #     app.kubernetes.io/name: loki
  # subPath: ""
  # existingClaim:

#all default 
# ...
```
i got some error when deploy by `helm install loki $my_loki_helm_dir`
```level=info ts=2022-01-26T13:51:26.720858786Z caller=main.go:94 msg="Starting Loki" version="(version=2.4.2, branch=HEAD, revision=525040a32)"
level=info ts=2022-01-26T13:51:26.721160307Z caller=modules.go:573 msg="RulerStorage is not configured in single binary mode and will not be started."
level=info ts=2022-01-26T13:51:26.721919966Z caller=server.go:260 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=warn ts=2022-01-26T13:51:26.725899176Z caller=experimental.go:19 msg="experimental feature in use" feature="In-memory (FIFO) cache"
level=error ts=2022-01-26T13:51:26.727025964Z caller=log.go:106 msg="error running loki" err="mkdir : no such file or directory\nerror creating index client\ngithub.com/grafana/loki/pkg/storage/chunk/storage.NewStore\n\t/src/loki/pkg/storage/chunk/storage/factory.go:201\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:370\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:106\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:322\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nerror initialising module: store\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:322\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"
```

and i already mount the `/data` and `/data/loki` directories. need someone to help me.
pod volume config is below: 
<img width="436" alt="pod" src="https://user-images.githubusercontent.com/32383393/151176922-e0e9ba2a-a097-434f-91df-e636f98b2877.png">

**Comment by scybZhangliang** [comment]
wrong config

**Comment by king5211** [comment]
> 错误的配置
Can the correct configuration be posted

**Comment by KeHaohaoke** [comment]
> wrong config
Please provide the correct and complete configuration, I have a similar problem

**Comment by ninja9k1** [comment]
> 

This is seriously a useless reply.

**Comment by jankaifer** [comment]
If the issue is with `compactor` not starting, then doing [this](https://community.grafana.com/t/loki-mkdir-no-such-file-or-directory/111042/6) helped me.

**Comment by jankaifer** [comment]
After doing that I had the same error, but debug logs told me it's related to `index` files this time.
I fixed that error by adding this to my configuration:
```nix
storage_config = {
  filesystem.directory = "/var/log/loki/filesystem";
    boltdb_shipper = {
      active_index_directory = "/var/log/loki/boltdb_shipper/active_index_directory";
      shared_store = "/var/log/loki/boltdb_shipper/shared_store";
      cache_location = "/var/log/loki/boltdb_shipper/cache";
    };
  };
};
```
(I'm using nix syntax here, but it should be straight forward to port this to yaml syntax used by loki)

**Comment by aa-shalin** [comment]
Adding this fixed my issue:
```
loki:
  config: |
    common:
      path_prefix: /var/loki
```
